### ISSUE TITLE
GIMP icon is rendered incorrectly in the task bar

### ISSUE THREAD

**Issue by spronovo** [microsoft/wslg#1]
# Environment

```none
Windows build number: 21362
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17
```

# Steps to reproduce

```
sudo apt install gimp
gimp
```
**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

[pulseaudio.log](https://github.com/microsoft/wslg/files/6337943/pulseaudio.log)
[versions.txt](https://github.com/microsoft/wslg/files/6337944/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/6337945/weston.log)

#  Expected behavior

GIMP Icon rendered correctly in both start menu and task bar.

Icon in the start menu looks correct:
![image](https://user-images.githubusercontent.com/7545376/115277664-69f69280-a0f9-11eb-935f-6a81bde53cb4.png)

# Actual behavior

GIMP Icon incorrectly rendered in task bar.

![image](https://user-images.githubusercontent.com/7545376/115277525-3d427b00-a0f9-11eb-941d-ac5df0edf910.png)

**Comment by bl-ue** [comment]
@spronovo are you sure that that's a bug? I think the GIMP icon is supposed to look that way in thte task bar.  It dynmically updates to show the current image.  🤔

**Comment by spronovo** [comment]
@bl-ue you're right... the icon looked wrong to me but looks like it is what it is expected to look like in that case :-).

**Comment by hideyukn88** [comment]
Just for FYI: Icon image on Start menu is loaded from where .desktop file points. The Icon on taskbar is obtained from _NET_WM_ICON property.
