### ISSUE TITLE
Unable to install apps that required Snap store plugins or packages

### ISSUE THREAD

**Issue by kbdharun** [microsoft/wslg#102]
# Environment

```none
Windows build number: 21364
Your Distribution version: Ubuntu 20.04 LTS
Your WSLg version: 1.0.17.1 (WSLg Preview), 5.10.16 (WSL Update)
```

#  Expected behaviour
To install an application like Snap store or an application that has a plugin related to Snap store

# Actual behaviour
Snap store is not being installed also the packages/plugins dependent on the Snap store is not installing, It shows a message in a box  along with these three options to "Try Again", "Abort", "Exit/Stop-This I don't remember what was there in it" 

When will there be support for snap store and snap store supported applications in WSL in Ubuntu 20.04 LTS 

Regards, Dharun

**Comment by LinAGKar** [comment]
Related to this, it would be great if snaps and flatpaks were supported in WSL. Even better if the Snap Store and Flathub were to be integrated into the Microsoft Store, so you can just install flatpaks and snaps from the Microsoft Store and have them just work in WSL automatically. Which would let people publish an application in one place and have it available on any Linux distro and on Windows.

**Comment by rwilliams** [comment]
I think this should be moved to the WSL issue tracking as it's not specific to WSLg. That said, have you all tried using https://github.com/arkane-systems/genie It allows you to have a working systemd, and snaps work just fine.

**Comment by cerebrate** [comment]
snapd doesn't run by default under WSL because snapd requires systemd; you'll need to use one of the systemd hacks first to make snaps work. (Obligatory genie plug, inasmuch as I wrote that one.)

**Comment by kbdharun** [comment]
> snapd doesn't run by default under WSL because snapd requires systemd; you'll need to use one of the systemd hacks first to make snaps work. (Obligatory genie plug, inasmuch as I wrote that one.)
> 

Thanks I will try using Snapd using genie

**Comment by kbdharun** [comment]
> snapd doesn't run by default under WSL because snapd requires systemd; you'll need to use one of the systemd hacks first to make snaps work. (Obligatory genie plug, inasmuch as I wrote that one.)

Thanks can you guide me on how to use Genie in WSL 2 on Ubuntu 20.04 LTS Distribution in Build 21364, Sorry for asking separately but it would be great if you share the links or if possible to write it in here so that I could follow it to install genie.

**Comment by rwilliams** [comment]
https://github.com/arkane-systems/genie There is an installation section on the main readme. Packages for each distro are under the releases section.

**Comment by craigloewen-msft** [comment]
Snap support requires WSL to support systemd, as identified above in this thread this is something that is not yet correctly supported but we are tracking it here: https://github.com/microsoft/WSL/issues/994

**Comment by cerebrate** [comment]
@kbdharun What @rwilliams said, but also - since I know there are some units that cause issues on Ubuntu - don't miss the repo Wiki, which includes advice on fixing those issues.

@craigloewen-msft Although, to be fair, you've given us all the pieces to put together a pretty creditable imitation of it, of which I am most appreciative. 😁

**Comment by spronovo** [comment]
Hey folks, i'm going to close this thread on WSLg. As observed earlier in the thread the main blocker for snapd at the moment is the lack of support for systemd in WSL. If that is something you would like to see happen, please go over to https://github.com/microsoft/WSL/issues/994 and add your vote to it :-).

**Comment by rokejulianlockhart** [comment]
https://github.com/microsoft/WSL/issues/994 has been remediated. Can anyone verify that snap operates correctly consequently?

**Comment by cerebrate** [comment]
@rokejulianlockhart 

Assuming your distro includes versions of apparmor and snapd which include the relevant patches, yes, it does.
