### ISSUE TITLE
vmmem high CPU usage while idle

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/wslg#103]
As already reported here, after updating Windows and WSL, vmmem goes crazy with the CPU usage and the fan noise is unbeareable.

https://github.com/microsoft/WSL/issues/6837

The only solutions is to disable guiapplications in `.wslconfig`, but this prevents GUI apps from running.

Is there anything else?

**Comment by hideyukn88** [comment]
@ad-on-is , thanks for reporting. currently we are aware of one problem which prohibiting weston compositor to enter idle state, this is already fixed in our working branch, and will be in next update of WSLg.

**Comment by ad-on-is** [comment]
Ah great, thx for the info. will this be shipped with the next Windows update or will it be a `wsl --update`?

**Comment by hideyukn88** [comment]
It should be able to obtained by wsl --update, I believe there will be announcement once update is released, or I can post here as reminder, thanks!

**Comment by spronovo** [comment]
This should be fixed with v1.0.19 that we just released moments ago. To update your WSL install, make sure to save your work than type the following from an elevated command prompt in Windows:

```
wsl --shutdown
wsl --update
```

**Comment by framerate** [comment]
@spronovo - I'm not sure if my issue is different but:

- I'm running latest WSL2 (to get WSLg with my weird monitor setup)
- CPU idles at 21% with my full workload (sans X11 graphics)
- When I start my linux GUI app (electron based) I stay pegged 95% - 100% indefinitely
- If I close the GUI app, I'm back < 20%

Any ideas?

**Comment by ad-on-is** [comment]
For me the issue is solved with Windows 21370 and updated WSL.

@framerate Did you update WSL2 as suggested by spronovo

**Comment by framerate** [comment]
Yeah, I got the latest version yesterday. Weird. Maybe they pushed two? I'll make sure.

**Comment by framerate** [comment]
Follow up. Definitely latest version. I7-6700K processor. 

If I don't figure it out I will make a new bug. Thanks!

**Comment by ad-on-is** [comment]
The issue is happening again for me. Today, after I woke up my PC from hybernation, vmmem was using 40% of the CPU, and I didn't even had a GUI app open.

**Comment by hideyukn88** [comment]
@framerate , @ad-on-is , would you please use Feedback Hub report this ? please file report while it exhibit the issues and use "vmmem high CPU usage while idle" in feedback title and "Developer platform" as category and "Windows Subsystem for Linux" as sub-category, so we can locate the feedback internally, thanks!

**Comment by framerate** [comment]
Done! thanks!

----
*- justin *| @framerate <http://twitter.com/framerate> | framerate.io
