### ISSUE TITLE
GUI Applications will no longer launch in Wayland after updating

### ISSUE THREAD

**Issue by c4artisan** [microsoft/wslg#1032]
### Windows Version

Microsoft Windows [Versión 10.0.22624.1537]

### WSL Version

1.1.7.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 6.1.21.1-microsoft-standard-WSL2+ (root@40c8f3c2f8c6) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) microsoft/WSL#1 SMP Tue Mar 28 20:13:51 UTC 2023

### Distro Version

Ubuntu 22.04 (Jammy Jellyfish/jammy)

### Other Software

GNOME Files (nautilus)

### Repro Steps

Update to the latest version of WSL (and maybe have used CMake or GCC tools before?)
Launch Ubuntu
Type in "nautilus" (to launch Files)

### Expected Behavior

The application would load in the fancy Wayland window style.

### Actual Behavior

The window appears to load in X11?

### Diagnostic Logs

[appxpackage.txt](https://github.com/microsoft/WSL/files/11153545/appxpackage.txt)
[HKCU.txt](https://github.com/microsoft/WSL/files/11153546/HKCU.txt)
[HKLM.txt](https://github.com/microsoft/WSL/files/11153547/HKLM.txt)
[P9NP.txt](https://github.com/microsoft/WSL/files/11153548/P9NP.txt)
[Winsock2.txt](https://github.com/microsoft/WSL/files/11153549/Winsock2.txt)
[wsl.wprp.txt](https://github.com/microsoft/WSL/files/11153551/wsl.wprp.txt)

**Comment by hideyukn88** [comment]
@c4artisan, would you please share WSL version from `wsl --version` on Windows command prompt and share logs from /mnt/wslg/*.log, thanks!

**Comment by sarim** [comment]
Is it somehow related to #1030 ? Google-chrome and other electron apps failed to open with error 
```
[830:830:0411/002028.047290:ERROR:wayland_connection.cc(187)] Failed to connect to Wayland display: No such file or directory (2)
```
symlinking wayland-0 from /mnt/wslg/runtime-dir
```
ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/
```

Now chrome and electron based apps open. Also gedit / gnome apps also open instantly.

**Comment by c4artisan** [comment]
> @c4artisan, would you please share WSL version from `wsl --version` on Windows command prompt and share logs from /mnt/wslg/*.log, thanks!

[pulseaudio.log](https://github.com/microsoft/wslg/files/11194982/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/11194983/weston.log)
[wlog.log](https://github.com/microsoft/wslg/files/11194984/wlog.log)

wsl version 1.2.0.0
wslg version 1.0.51

**Comment by c4artisan** [comment]
> @c4artisan, would you please share WSL version from `wsl --version` on Windows command prompt and share logs from /mnt/wslg/*.log, thanks!



> Is it somehow related to #1030 ? Google-chrome and other electron apps failed to open with error
> 
> ```
> [830:830:0411/002028.047290:ERROR:wayland_connection.cc(187)] Failed to connect to Wayland display: No such file or directory (2)
> ```
> 
> symlinking wayland-0 from /mnt/wslg/runtime-dir
> 
> ```
> ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/
> ```
> 
> Now chrome and electron based apps open. Also gedit / gnome apps also open instantly.

chrome has no problems booting up for me at least

**Comment by fargiolas** [comment]
Same here, emacs (pure gtk) stopped working in wayland since this morning. The symlink trick seems to fix it.

**Comment by c4artisan** [comment]
the symlink trick did it. guess it's up to the developers to add in an official fix to it

**Comment by hideyukn88** [comment]
@c4artisan, thanks for info, but I do not observe this issue with the WSL version you have noted. But it's possible some of Ubuntu systemd unit might be deleting them. As a matter of fact, their gdm unit deletes X11 sockets, so WSL is monitoring that to restablish if that's happen, so it's possible that same is required for Wayland socket. Would you please share output from `systemctl -t service`? thanks!

>> wsl version 1.2.0.0
>> wslg version 1.0.51

**Comment by sarim** [comment]
systemctl -t service
```
  UNIT                                 LOAD   ACTIVE SUB     DESCRIPTION
  binfmt-support.service               loaded active exited  Enable support for additional executable binary formats
  blk-availability.service             loaded active exited  Availability of block devices
  dbus.service                         loaded active running D-Bus System Message Bus
  networkd-dispatcher.service          loaded active running Dispatcher daemon for systemd-networkd
  podman-restart.service               loaded active exited  Podman Start All Containers With Restart Policy Set To Always
  polkit.service                       loaded active running Authorization Manager
  qemu-kvm.service                     loaded active exited  QEMU KVM preparation - module, ksm, hugepages
  rtkit-daemon.service                 loaded active running RealtimeKit Scheduling Policy Service
  systemd-journal-flush.service        loaded active exited  Flush Journal to Persistent Storage
  systemd-journald.service             loaded active running Journal Service
  systemd-logind.service               loaded active running User Login Management
  systemd-network-generator.service    loaded active exited  Generate network units from Kernel command line
  systemd-networkd-wait-online.service loaded active exited  Wait for Network to be Configured
  systemd-networkd.service             loaded active running Network Configuration
  systemd-resolved.service             loaded active running Network Name Resolution
  systemd-sysctl.service               loaded active exited  Apply Kernel Variables
  systemd-sysusers.service             loaded active exited  Create System Users
  systemd-tmpfiles-setup-dev.service   loaded active exited  Create Static Device Nodes in /dev
  systemd-tmpfiles-setup.service       loaded active exited  Create Volatile Files and Directories
  systemd-udev-trigger.service         loaded active exited  Coldplug All udev Devices
  systemd-udevd.service                loaded active running Rule-based Manager for Device Events and Files
  systemd-update-utmp.service          loaded active exited  Record System Boot/Shutdown in UTMP
  systemd-user-sessions.service        loaded active exited  Permit User Sessions
  user-runtime-dir@1000.service        loaded active exited  User Runtime Directory /run/user/1000
  user@1000.service                    loaded active running User Manager for UID 1000

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
25 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```

ls -l /run/user/1000/
```
srw-rw-rw- 1 gittu gittu   0 Apr 12 15:07 bus
drwx------ 3 gittu gittu  60 Apr 12 15:07 dbus-1
drwx------ 2 gittu gittu 140 Apr 12 15:07 gnupg
srw-rw-rw- 1 gittu gittu   0 Apr 12 15:07 pipewire-0
-rw-rw---- 1 gittu gittu   0 Apr 12 15:07 pipewire-0.lock
srw-rw-rw- 1 gittu gittu   0 Apr 12 15:07 pk-debconf-socket
drwxr-xr-x 2 gittu gittu  60 Apr 12 15:07 podman
drwxr-xr-x 4 gittu gittu 120 Apr 12 15:07 systemd
```

Interesting thing is pipewire socket is present here. But not wayland. Ubuntu 22.04.2 LTS.

**Comment by harleylrn** [comment]
Same issue here.
Wayland socket not created.

**Comment by sarim** [comment]
> Thanks for all reporting the issue, would you please try if this still occurs if systemd is disabled? thanks!

@hideyukn88 without systemd, `XDG_RUNTIME_DIR` is set to `/mnt/wslg/runtime-dir`. And wayland-0 is present in `/mnt/wslg/runtime-dir` as expected. GUI apps in wayland also work.

With systemd enabled `XDG_RUNTIME_DIR` is set to `/run/user/1000/`. and There is no wayland-0 in `/run/user/1000/`.

**Comment by c4artisan** [comment]
> systemctl -t service
  UNIT                                                   LOAD   ACTIVE SUB     DESCRIPTION                                                           
  accounts-daemon.service                                loaded active running Accounts Service
  apport.service                                         loaded active exited  LSB: automatic crash report generation
  avahi-daemon.service                                   loaded active running Avahi mDNS/DNS-SD Stack
  binfmt-support.service                                 loaded active exited  Enable support for additional executable binary formats
  console-getty.service                                  loaded active running Console Getty
  console-setup.service                                  loaded active exited  Set console font and keymap
  cron.service                                           loaded active running Regular background program processing daemon
  cups-browsed.service                                   loaded active running Make remote CUPS printers available locally
  cups.service                                           loaded active running CUPS Scheduler
  dbus.service                                           loaded active running D-Bus System Message Bus
  gdm.service                                            loaded active running GNOME Display Manager
  kerneloops.service                                     loaded active running Tool to automatically collect and submit kernel crash signatures
  keyboard-setup.service                                 loaded active exited  Set the console keyboard layout
  lxc-monitord.service                                   loaded active running LXC Container Monitoring Daemon
  lxc-net.service                                        loaded active exited  LXC network bridge setup
  lxc.service                                            loaded active exited  LXC Container Initialization and Autoboot Code
  networkd-dispatcher.service                            loaded active running Dispatcher daemon for systemd-networkd
  NetworkManager-wait-online.service                     loaded active exited  Network Manager Wait Online
  NetworkManager.service                                 loaded active running Network Manager
  NetworkManager.service                                 loaded active running Network Manager
  nmbd.service                                           loaded active running Samba NMB Daemon
  openvpn.service                                        loaded active exited  OpenVPN service
  packagekit.service                                     loaded active running PackageKit Daemon
  plymouth-quit-wait.service                             loaded active exited  Hold until boot process finishes up
  plymouth-read-write.service                            loaded active exited  Tell Plymouth To Write Out Runtime Data
  polkit.service                                         loaded active running Authorization Manager
  power-profiles-daemon.service                          loaded active running Power Profiles daemon
  redis-server.service                                   loaded active running Advanced key-value store
  rsyslog.service                                        loaded active running System Logging Service
  rtkit-daemon.service                                   loaded active running RealtimeKit Scheduling Policy Service
  setvtrgb.service                                       loaded active exited  Set console scheme
  smbd.service                                           loaded active running Samba SMB Daemon
  snap.cups.cups-browsed.service                         loaded active running Service for snap application cups.cups-browsed
  snap.cups.cupsd.service                                loaded active running Service for snap application cups.cupsd
  snap.snap-store-proxy.memcached.service                loaded active running Service for snap application snap-store-proxy.memcached
  snap.snap-store-proxy.nginx.service                    loaded active running Service for snap application snap-store-proxy.nginx
  snap.snap-store-proxy.snapauth.service                 loaded active running Service for snap application snap-store-proxy.snapauth
  snap.snap-store-proxy.snapdevicegw.service             loaded active running Service for snap application snap-store-proxy.snapdevicegw
  snap.snap-store-proxy.snapproxy.service                loaded active running Service for snap application snap-store-proxy.snapproxy
  snap.snap-store-proxy.snaprevs.service                 loaded active running Service for snap application snap-store-proxy.snaprevs
  snap.ubuntu-desktop-installer.subiquity-server.service loaded active running Service for snap application ubuntu-desktop-installer.subiquity-server
  snapd.seeded.service                                   loaded active exited  Wait until snapd is fully seeded
  snapd.service                                          loaded active running Snap Daemon
  switcheroo-control.service                             loaded active running Switcheroo Control Proxy service
  systemd-journal-flush.service                          loaded active exited  Flush Journal to Persistent Storage
  systemd-journald.service                               loaded active running Journal Service
  systemd-logind.service                                 loaded active running User Login Management
  systemd-remount-fs.service                             loaded active exited  Remount Root and Kernel File Systems
  systemd-resolved.service                               loaded active running Network Name Resolution
  systemd-sysctl.service                                 loaded active exited  Apply Kernel Variables
  systemd-sysusers.service                               loaded active exited  Create System Users
  systemd-tmpfiles-setup-dev.service                     loaded active exited  Create Static Device Nodes in /dev
  systemd-tmpfiles-setup.service                         loaded active exited  Create Volatile Files and Directories
  systemd-udev-trigger.service                           loaded active exited  Coldplug All udev Devices
  systemd-udevd.service                                  loaded active running Rule-based Manager for Device Events and Files
  systemd-update-utmp.service                            loaded active exited  Record System Boot/Shutdown in UTMP
  systemd-user-sessions.service                          loaded active exited  Permit User Sessions
  udisks2.service                                        loaded active running Disk Manager
  ufw.service                                            loaded active exited  Uncomplicated firewall
  unattended-upgrades.service                            loaded active running Unattended Upgrades Shutdown
  upower.service                                         loaded active running Daemon for power management
  user-runtime-dir@1000.service                          loaded active exited  User Runtime Directory /run/user/1000
  user@1000.service                                      loaded active running User Manager for UID 1000
  waydroid-container.service                             loaded active running Waydroid Container
  wpa_supplicant.service                                 loaded active running WPA supplicant
  xrdp-sesman.service                                    loaded active running xrdp session manager
  xrdp.service                                           loaded active running xrdp daemon

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
66 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.


have no idea if the symlink thing changed anything so don't trust this log too much
i'll share a fresh log once i reboot wsl

**Comment by hideyukn88** [comment]
Thanks all for sharing the info, now we understood the issue and working on the fix, thanks!

**Comment by hideyukn88** [comment]
FYI: https://github.com/microsoft/WSL/releases/tag/1.2.2 will contain the fix.

**Comment by c4artisan** [comment]
yep after updating it's fixed
thank you all

**Comment by sarim** [comment]
After updating, wayland socket is created in correct /run/user/1000 and gedit starts instantly too. so Fixed. 

> WSLg: Revert change to use overlayfs for /run/user/ while a more complete fix is investigated

Hopefully in future more testing would be done before changing something as important as /run/user/ :) Many service and stuff has things in there.

**Comment by pkkid** [comment]
If I want the fix here, am I good to install Microsoft.WSL_1.2.2.0_x64_ARM64.msixbundle, or should I just wait for Windows Update to roll around with a fix?

**Comment by hideyukn88** [comment]
@pkkid, yes, you can manually download, or you can try `wsl --update --pre-release`, thanks!

**Comment by Parsifa1** [comment]
This problem seems to have reappeared in the latest version, I tried using ln to fix it
`ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/`
It works

**Comment by DominikM** [comment]
> This problem seems to have reappeared in the latest version, I tried using ln to fix it `ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/` It works

Also can confirm that I am dealing with this issue as well.

**Comment by da-moon** [comment]
this issue exists in the latest version of wsl. I dealt with it by adding the following to my `~/.bashrc` file

```bash
if grep -qEi "(Microsoft|WSL)" /proc/version &>/dev/null; then
  find "/mnt/wslg/runtime-dir/" -name 'wayland*' -exec basename {} \; | xargs -r -I {} ln -sf /mnt/wslg/runtime-dir/{} /run/user/$(id -u)/{}
fi
```

I also had issues with X11 mount which I fixed by updating my `/etc/tmpfiles.d/wslg.conf` file

```console
❯ cat /etc/tmpfiles.d/wslg.conf
# Type Path                          Mode UID  GID  Age Argument
L+     /tmp/.X11-unix/X0              -    -    -    -   /mnt/wslg/.X11-unix/X0
```

- WSL Version

```console
❯ wsl --version
WSL version: 2.3.17.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.64
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26120.1542
```

- WSLg version

```console
❯ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.64+Branch.main.Sha.8159bf9e5c474075665850afea5c60bdd34afd98
Built at: Mon Jul 29 22:52:44 UTC 2024
Mariner: VERSION="2.0.20240609"
DirectX-Headers:
mesa:
pulseaudio: 6f045ff0dca233a939a2aba815f84d177e294122
FreeRDP: c4030980b29322a9cb2190711a5fadeeeb8b6a33
weston: f227edd681479ec3cb2290a25d84d2d3462aebfa
```

**Comment by MustCodeAl** [comment]
> # WSL Symlink Fix
> ## Summary
> So , to sum up, it seems like there are two issues at least based on my experience:
> 
> * missing `/tmp/.X11-unix/X0` symlink : this has impacted my ability to run
>   application that rely on X11 in WSL, e.g Zed editor([zed hanging on startup because of 'unsupportedversion' zed-industries/zed#14126 (comment)](https://github.com/zed-industries/zed/issues/14126#issuecomment-2302645713))
> * missing `/run/user/1000/wayland-0*` symlink : on my machine, right after
>   starting wsl, the symlinks exists but they get deleted after a few second of
>   WSL start. This impacted clipboard syncing with `wl-copy` or running
>   applications such as Warp terminal([Support Warp for Linux on WSL (Windows Subsystem for Linux) warpdotdev/Warp#4240 (comment)](https://github.com/warpdotdev/Warp/issues/4240#issuecomment-2302686214))
> 
> ## X11 Symlink Fix
> use `systemd-tmpfiles` to create the symlinks by updating `/etc/tmpfiles.d/wslg.conf` file to contain the following:
> 
> ```
> # Type Path                          Mode UID  GID  Age Argument
> L+     /tmp/.X11-unix/X0              -    -    -    -   /mnt/wslg/.X11-unix/X0
> ```
> 
> ## Wayland Symlink Fix
> create a systemd oneshot user service that setsup the symlinks:
> 
> ```shell
> mkdir -p "${HOME}/.config/systemd/user"
> cat <<"EOF" > "${HOME}/.config/systemd/user/wsl-wayland-symlink.service"
> [Unit]
> Description=Create Wayland symlinks for WSL
> After=default.target
> 
> [Service]
> Type=oneshot
> ExecStart=/bin/sh -c 'USER_ID=$(id -u); find /mnt/wslg/runtime-dir -name "wayland-*" -type s -exec ln -sf {} /run/user/$USER_ID/ \;'
> 
> [Install]
> WantedBy=default.target
> EOF
> systemctl --user daemon-reload
> systemctl --user enable wsl-wayland-symlink.service
> systemctl --user start wsl-wayland-symlink.service
> ```
> 
> run `wsl --shutdown` and restart wsl to test the changes. The symlinks should be available a few seconds after wsl starts . try running a command like `echo 'foo' | wl-copy` just to test wayland socket creation as you should be able to have `foo` in your clipboard
> 
> ## additional context
> * Windows Version
> 
> ```
> ❯ Get-ComputerInfo | Select-Object OsName, OsVersion, WindowsVersion, OsBuildNumber
> 
> OsName                   OsVersion  WindowsVersion OsBuildNumber
> ------                   ---------  -------------- -------------
> Microsoft Windows 11 Pro 10.0.26120 2009           26120
> ```
> 
> * WSL Version
> 
> ```
> ❯ wsl --version
> WSL version: 2.3.17.0
> Kernel version: 5.15.153.1-2
> WSLg version: 1.0.64
> MSRDC version: 1.2.5326
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26100.1-240331-1435.ge-release
> Windows version: 10.0.26120.1542
> ```
> 
> * WSLg Version
> 
> ```
> ❯ wsl cat /mnt/wslg/versions.txt
> WSLg ( x86_64 ): 1.0.64+Branch.main.Sha.8159bf9e5c474075665850afea5c60bdd34afd98
> Built at: Mon Jul 29 22:52:44 UTC 2024
> Mariner: VERSION="2.0.20240609"
> DirectX-Headers:
> mesa:
> pulseaudio: 6f045ff0dca233a939a2aba815f84d177e294122
> FreeRDP: c4030980b29322a9cb2190711a5fadeeeb8b6a33
> weston: f227edd681479ec3cb2290a25d84d2d3462aebfa
> ```
> 
> * WSL Distro
> 
> ```
> ❯ wsl freshfetch
> 
> 
>                      -`                   damoon@zenbook-duo
>                     .o+`
>                    `ooo/                  OS: Arch Linux x86_64
>                   `+oooo:                 Kernel: Linux 5.15.153.1-microsoft-standard-WSL2
>                  `+oooooo:                Uptime: 16 minutes
>                  -+oooooo+:               Packages: 959 (pacman)
>                `/:-:++oooo+:              Shell: bash
>               `/++++/+++++++:             CPU: Intel Core Ultra 9 185H (22) @ 3.0719990730286MHz
>              `/++++++++++++++:            Memory: 737MB / 15675MB
>             `/+++ooooooooooooo/`
>            ./ooosssso++osssssso+`
>           .oossssso-````/ossssss+`
>          -osssssso.      :ssssssso.
>         :osssssss/        osssso+++.
>        /ossssssss/        +ssssooo/-
>      `/ossssso+/:-        -:/+osssso+-
>     `+sso+:-`                 `.-/+oso:
>    `++:.                           `-/+/
>    .`                                 `/
> ```

worked

**Comment by smac89** [comment]
I liked the tmpfiles approach, so I employed it for both.

`~/.config/user-tmpfiles.d/wslg.conf`

```
#Type Path                                     Mode User Group Age         Argument
L+    %t/wayland-0                             -    -    -     -           /mnt/wslg/runtime-dir/wayland-0
L+    %t/wayland-0.lock                        -    -    -     -           /mnt/wslg/runtime-dir/wayland-0.lock
L+    %t/pulse                                 -    -    -     -           /mnt/wslg/runtime-dir/pulse
```

**Comment by DovydasMackonis** [comment]
> > ```
> > ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/
> > ```
Fixed all my problems.

**Comment by aki-k** [comment]
I'm not sure if this issue has been fixed in the current WSL 2/Ubuntu 24.04 version that gets installed with "wsl --install". I had to create /etc/rc.local script that is
```
#!/bin/bash

su - username -c '/usr/bin/ln -s /mnt/wslg/runtime-dir/wayland-0* /run/user/1000/'
```

**Comment by Anutrix** [comment]
Issue still present on latest WSL and WSLg.

Above workarounds seem to work, though I wish there was an official fix.

**Comment by Souvlaki42** [comment]
Last few versions of WSL Ubuntu don't need the symbolic links workaround to work.
But still Arch needs it.
