### ISSUE TITLE
GUI Apps Refuse to Run

### ISSUE THREAD

**Issue by NickDeBeenSAE** [microsoft/wslg#1065]
### Windows build number:

22621.1702

### Your Distribution version:

Ubuntu 22.04 Jammy

### Your WSL versions:

WSL2

### Steps to reproduce:

<pre>sudo aptitude install x11-apps
The following NEW packages will be installed:
  x11-apps xbitmaps{a}
0 packages upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 743 kB of archives. After unpacking 2758 kB will be used.
Do you want to continue? [Y/n/?] y
Get: 1 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-apps amd64 7.7+8build2 [719 kB]
Get: 2 http://archive.ubuntu.com/ubuntu jammy/main amd64 xbitmaps all 1.1.1-2.1ubuntu1 [23.4 kB]
Fetched 743 kB in 3s (272 kB/s)
Selecting previously unselected package x11-apps.
(Reading database ... 200136 files and directories currently installed.)
Preparing to unpack .../x11-apps_7.7+8build2_amd64.deb ...
Unpacking x11-apps (7.7+8build2) ...
Selecting previously unselected package xbitmaps.
Preparing to unpack .../xbitmaps_1.1.1-2.1ubuntu1_all.deb ...
Unpacking xbitmaps (1.1.1-2.1ubuntu1) ...
Setting up x11-apps (7.7+8build2) ...
Setting up xbitmaps (1.1.1-2.1ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...

root@Crimson-8:/home/dbtsgds2023# export DISPLAY=192.168.1.103:0.0
root@Crimson-8:/home/dbtsgds2023# xeyes
Error: Can't open display: 192.168.1.103:0.0
root@Crimson-8:/home/dbtsgds2023# xeyes
Error: Can't open display: 192.168.1.103:0.0
root@Crimson-8:/home/dbtsgds2023# export DISPLAY=192.168.1.103:1.0
root@Crimson-8:/home/dbtsgds2023# xeyes
Error: Can't open display: 192.168.1.103:1.0
root@Crimson-8:/home/dbtsgds2023# apt install gedit -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  gedit-common gir1.2-gtksource-4 gir1.2-peas-1.0 gstreamer1.0-plugins-good gstreamer1.0-x libdv4 libgspell-1-2
  libgspell-1-common libgstreamer-plugins-good1.0-0 libgtksourceview-4-0 libgtksourceview-4-common libhandy-1-0
  libharfbuzz-icu0 libiec61883-0 libjavascriptcoregtk-4.0-18 libmanette-0.2-0 libpeas-1.0-0 libpeas-common libv4l-0
  libv4lconvert0 libwebkit2gtk-4.0-37 libyelp0 python3-gi-cairo xdg-dbus-proxy xdg-desktop-portal-gtk yelp yelp-xsl
  zenity zenity-common
Suggested packages:
  gedit-plugins libdv-bin oss-compat gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-alsa evince
  xdg-desktop-portal-gnome
The following NEW packages will be installed:
  gedit gedit-common gir1.2-gtksource-4 gir1.2-peas-1.0 gstreamer1.0-plugins-good gstreamer1.0-x libdv4 libgspell-1-2
  libgspell-1-common libgstreamer-plugins-good1.0-0 libgtksourceview-4-0 libgtksourceview-4-common libhandy-1-0
  libharfbuzz-icu0 libiec61883-0 libjavascriptcoregtk-4.0-18 libmanette-0.2-0 libpeas-1.0-0 libpeas-common libv4l-0
  libv4lconvert0 libwebkit2gtk-4.0-37 libyelp0 python3-gi-cairo xdg-dbus-proxy xdg-desktop-portal-gtk yelp yelp-xsl
  zenity zenity-common
0 upgraded, 30 newly installed, 0 to remove and 1 not upgraded.
Need to get 30.9 MB of archives.
After this operation, 116 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 gedit-common all 41.0-3 [101 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgtksourceview-4-common all 4.8.3-1 [262 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgtksourceview-4-0 amd64 4.8.3-1 [237 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gir1.2-gtksource-4 amd64 4.8.3-1 [20.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpeas-common all 1.32.0-1 [9760 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpeas-1.0-0 amd64 1.32.0-1 [66.1 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 gir1.2-peas-1.0 amd64 1.32.0-1 [5958 B]
Setting up libgstreamer-plugins-good1.0-0:amd64 (1.20.3-0ubuntu1) ...
Setting up zenity-common (3.42.1-0ubuntu1) ...
Setting up xdg-dbus-proxy (0.1.3-1) ...
Setting up libdv4:amd64 (1.0.0-14build1) ...
Setting up libpeas-1.0-0:amd64 (1.32.0-1) ...
Setting up libv4lconvert0:amd64 (1.22.1-2build1) ...
Setting up python3-gi-cairo (3.42.1-0ubuntu1) ...
Setting up libgtksourceview-4-common (4.8.3-1) ...
Setting up libgspell-1-2:amd64 (1.9.1-4) ...
Setting up yelp-xsl (42.0-1) ...
Setting up libhandy-1-0:amd64 (1.6.1-1) ...
Setting up libiec61883-0:amd64 (1.2.0-4build3) ...
Setting up gir1.2-peas-1.0:amd64 (1.32.0-1) ...
Setting up libv4l-0:amd64 (1.22.1-2build1) ...
Setting up libgtksourceview-4-0:amd64 (4.8.3-1) ...
Setting up gir1.2-gtksource-4:amd64 (4.8.3-1) ...
Setting up gstreamer1.0-plugins-good:amd64 (1.20.3-0ubuntu1) ...
Setting up libwebkit2gtk-4.0-37:amd64 (2.38.6-0ubuntu0.22.04.1) ...
Setting up libyelp0:amd64 (42.1-1) ...
Setting up zenity (3.42.1-0ubuntu1) ...
Setting up yelp (42.1-1) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up gedit (41.0-3) ...
update-alternatives: using /usr/bin/gedit to provide /usr/bin/gnome-text-editor (gnome-text-editor) in auto mode
root@Crimson-8:/home/dbtsgds2023# apt install gimp -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  gimp-data libamd2 libbabl-0.1-0 libcamd2 libccolamd2 libcholmod3 libcolamd2 libgail-common libgail18 libgegl-0.4-0
  libgegl-common libgexiv2-2 libgimp2.0 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libmetis5 libmypaint-1.5-1
  libmypaint-common libsuitesparseconfig5 libumfpack5 libwmf-0.2-7 libwmf0.2-7
Suggested packages:
  gimp-help-en | gimp-help gimp-data-extras gvfs-backends gvfs libwmf-0.2-7-gtk
The following NEW packages will be installed:
  gimp gimp-data libamd2 libbabl-0.1-0 libcamd2 libccolamd2 libcholmod3 libcolamd2 libgail-common libgail18
  libgegl-0.4-0 libgegl-common libgexiv2-2 libgimp2.0 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libmetis5
  libmypaint-1.5-1 libmypaint-common libsuitesparseconfig5 libumfpack5 libwmf-0.2-7 libwmf0.2-7
Setting up libmypaint-common (1.6.0-2) ...
Setting up libbabl-0.1-0:amd64 (1:0.1.92-1) ...
Setting up libmetis5:amd64 (5.1.0.dfsg-7build2) ...
Setting up libmypaint-1.5-1:amd64 (1.6.0-2) ...
Setting up libwmf-0.2-7:amd64 (0.2.12-5ubuntu1) ...
Setting up gimp-data (2.10.30-1build1) ...
Setting up libgegl-common (1:0.4.34-1build1) ...
Setting up libgtk2.0-common (2.24.33-2ubuntu2) ...
Setting up libgexiv2-2:amd64 (0.14.0-1build1) ...
Setting up libsuitesparseconfig5:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libcolamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libwmf0.2-7:amd64 (0.2.12-5ubuntu1) ...
Setting up libgtk2.0-0:amd64 (2.24.33-2ubuntu2) ...
Setting up libcamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libgail18:amd64 (2.24.33-2ubuntu2) ...
Setting up libgtk2.0-bin (2.24.33-2ubuntu2) ...
Setting up libccolamd2:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libcholmod3:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libgail-common:amd64 (2.24.33-2ubuntu2) ...
Setting up libumfpack5:amd64 (1:5.10.1+dfsg-4build1) ...
Setting up libgegl-0.4-0:amd64 (1:0.4.34-1build1) ...
Setting up libgimp2.0:amd64 (2.10.30-1build1) ...
Setting up gimp (2.10.30-1build1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Unpacking vlc-plugin-notify:amd64 (3.0.16-1build7) ...
Selecting previously unselected package vlc-plugin-samba:amd64.
Preparing to unpack .../07-vlc-plugin-samba_3.0.16-1build7_amd64.deb ...
Unpacking vlc-plugin-samba:amd64 (3.0.16-1build7) ...
Selecting previously unselected package vlc-plugin-skins2:amd64.
Preparing to unpack .../08-vlc-plugin-skins2_3.0.16-1build7_amd64.deb ...
Unpacking vlc-plugin-skins2:amd64 (3.0.16-1build7) ...
Selecting previously unselected package vlc-plugin-video-splitter:amd64.
Preparing to unpack .../09-vlc-plugin-video-splitter_3.0.16-1build7_amd64.deb ...
Unpacking vlc-plugin-video-splitter:amd64 (3.0.16-1build7) ...
Selecting previously unselected package vlc-plugin-visualization:amd64.
Preparing to unpack .../10-vlc-plugin-visualization_3.0.16-1build7_amd64.deb ...
Unpacking vlc-plugin-visualization:amd64 (3.0.16-1build7) ...
Setting up vlc-plugin-video-splitter:amd64 (3.0.16-1build7) ...
Setting up vlc-bin (3.0.16-1build7) ...
Setting up fonts-freefont-ttf (20120503-10build1) ...
Setting up vlc-l10n (3.0.16-1build7) ...
Setting up vlc-plugin-visualization:amd64 (3.0.16-1build7) ...
Setting up vlc-plugin-access-extra:amd64 (3.0.16-1build7) ...
Setting up vlc-plugin-qt:amd64 (3.0.16-1build7) ...
Setting up vlc (3.0.16-1build7) ...
Setting up vlc-plugin-notify:amd64 (3.0.16-1build7) ...
Setting up vlc-plugin-samba:amd64 (3.0.16-1build7) ...
Setting up vlc-plugin-skins2:amd64 (3.0.16-1build7) ...
Processing triggers for libvlc-bin:amd64 (3.0.16-1build7) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for man-db (2.10.2-1) ...
root@Crimson-8:/home/dbtsgds2023# apt install x11-apps -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
x11-apps is already the newest version (7.7+8build2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@Crimson-8:/home/dbtsgds2023# wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
--2023-05-31 12:49:10--  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
Resolving dl.google.com (dl.google.com)... 142.250.70.142, 2404:6800:4015:800::200e
Connecting to dl.google.com (dl.google.com)|142.250.70.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93841272 (89M) [application/x-debian-package]
Saving to: ‘google-chrome-stable_current_amd64.deb’

google-chrome-stable_current_ 100%[=================================================>]  89.49M  11.4MB/s    in 7.9s

2023-05-31 12:49:18 (11.3 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [93841272/93841272]

root@Crimson-8:/home/dbtsgds2023# dpkg -i google-chrome-stable_current_amd64.deb
Selecting previously unselected package google-chrome-stable.
(Reading database ... 208753 files and directories currently installed.)
root@Crimson-8:/home/dbtsgds2023# google-chrome
google-chrome: command not found
root@Crimson-8:/home/dbtsgds2023# apt install --fix-broken -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libu2f-udev
The following NEW packages will be installed:
  libu2f-udev
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
Need to get 4190 B of archives.
After this operation, 14.3 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libu2f-udev all 1.1.10-3build2 [4190 B]
Fetched 4190 B in 1s (4087 B/s)
Selecting previously unselected package libu2f-udev.
(Reading database ... 208868 files and directories currently installed.)
Preparing to unpack .../libu2f-udev_1.1.10-3build2_all.deb ...
Unpacking libu2f-udev (1.1.10-3build2) ...
Setting up libu2f-udev (1.1.10-3build2) ...
Setting up google-chrome-stable (114.0.5735.90-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
root@Crimson-8:/home/dbtsgds2023# dpkg -i google-chrome-stable_current_amd64.deb
(Reading database ... 208871 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (114.0.5735.90-1) over (114.0.5735.90-1) ...
Setting up google-chrome-stable (114.0.5735.90-1) ...
Processing triggers for man-db (2.10.2-1) ...
<pre>

According to this: https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps?source=docs

You could run GUI based Linux apps in an X11 server.

That's a lie.

Running any of the commands listed in the link when it comes to any of the installed apps results in this:

-bash: insert-app-name-here: command not found

Happens 24/7 with me.

You just cannot run ANY applications used on Linux distros with WSL2.

You must install Linux in order to use them.

Prove me wrong.

I'll fight back harder with log's and screenshots, because I am absolutely fed up with this ill explained instructions list from the link I have sent.

### WSL logs:

This directory is non-existent.

### WSL dumps:

Again, non-existent directory.

### Expected behavior:

The specified app opens without issue.

### Actual behavior:

Printed in "Steps to Produce".

**Comment by NickDeBeenSAE** [comment]
I don't know why it still printed in the grey box after editing the issue to correct it but I'll just add a much a much more visable version of the issue here:


According to this: https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps?source=docs

You could run GUI based Linux apps in an X11 server.

That's a lie.

Running any of the commands listed in the link when it comes to any of the installed apps results in this:

-bash: insert-app-name-here: command not found

Happens 24/7 with me.

You just cannot run ANY applications used on Linux distros with WSL2.

You must install Linux in order to use them.

Prove me wrong.

I'll fight back harder with log's and screenshots, because I am absolutely fed up with this ill explained instructions list from the link I have sent.

**Comment by shoffmeister** [comment]
```
export DISPLAY=192.168.1.103:1.0
```

May I suggest referring to the rather helpful architectural overview at https://github.com/microsoft/wslg to appreciate how WSLg works? This would highlight "XWayland" as one major building block.

Basically, running X11 GUI applications happens via XWayland; WSLg does not expose a native X11 (display) server anywhere, and at no stage are there any claims that this happens.

Leave out the explicit export of `DISPLAY` and everything will work just fine.

As a side note, language such as "is a lie", "prove me wrong", "fight back", "absolutely fed up" are all but inviting for anybody wishing to communicate with you.

**Comment by NickDeBeenSAE** [comment]
Well, those instruction were vague, because I followed them, but they didn't work.

**Comment by shoffmeister** [comment]
I just took the time to read the official Microsoft instructions you linked to.

I am unable to detect any vagueness in those instructions. When putting on my well-tuned "do not make me think" hat, I consider these instructions to be crystal clear, concise, and correct - and I expect that, once being followed, these instruction will lead to immediate success.

Even more, I am unable to notice anything suggesting that "export DISPLAY" or "runs an X11 display server" would in any way be relevant to WSLg.

**Comment by NickDeBeenSAE** [comment]
Well, it doesn't work on my system.

**Comment by NickDeBeenSAE** [comment]
I followed the same instructions you just read.

No Linux GUI apps run.

**Comment by NickDeBeenSAE** [comment]
I was finally able to open Linux Apps on Windows 11's WSL2 platform....

It required a reboot.
