### ISSUE TITLE
`make xconfig` for Linux kernel doesn't display under WSLg

### ISSUE THREAD

**Issue by cerebrate** [microsoft/wslg#107]
# Environment

```none
Windows build number: 21365
Your Distribution version: Debian 11 (bullseye/sid)
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

1. Clone the WSL Linux Kernel from the Microsoft/WSL2-Linux-Kernel repository, and switch to the linux-msft-wsl-5.10.y branch.
2. Run `make xconfig` in the top-level directory cloned repo.

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

[weston.log](https://github.com/microsoft/wslg/files/6379876/weston.log)
[versions.txt](https://github.com/microsoft/wslg/files/6379878/versions.txt)
[pulseaudio.log](https://github.com/microsoft/wslg/files/6379879/pulseaudio.log)

#  Expected behavior

The kernel configuration utility (i.e., this: https://en.wikipedia.org/wiki/Xconfig ) should be displayed, as per screenshot on right.

# Actual behavior

Instead, an empty black window is displayed. The window title appears to be correct, but no contents are visible. The window remains until the configuration utility process is forcibly killed.

**Comment by spronovo** [comment]
@cerebrate do you get some kind of error display? i got the following:

```
spronovo@OFFICE:~/src/kernel$ make xconfig
*
* Could not find Qt5 via pkg-config.
* Please install Qt5 and make sure it's in PKG_CONFIG_PATH
*
make[1]: *** [scripts/kconfig/Makefile:196: scripts/kconfig/qconf-cfg] Error 1
make: *** [Makefile:602: xconfig] Error 2
```
After intalling Qt5

```
sudo apt install qt5*
```

xconfig worked fine for me.

![image](https://user-images.githubusercontent.com/7545376/116345747-9cf5f180-a79d-11eb-9a6f-9dc3d49127cd.png)

**Comment by cerebrate** [comment]
No, no error message; it just reaches this point:

```
❯ make xconfig                                                                              2.54  ╱ 6.6G   at 12:40:07 AM  ─╯
  HOSTCC  scripts/kconfig/images.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTCXX scripts/kconfig/qconf.o
  MOC     scripts/kconfig/qconf-moc.cc
  HOSTCXX scripts/kconfig/qconf-moc.o
  HOSTLD  scripts/kconfig/qconf
```

and stops there indefinitely/until killed.

**Comment by cerebrate** [comment]
Hm. That didn't help, but on the other hand, running `sudo make xconfig` worked immediately. That's not something I've had to do before.

**Comment by cerebrate** [comment]
Closing this because it turns out to be a problem with linuxbrew silently breaking the PKG_CONFIG_PATH.
