### ISSUE TITLE
Octave exited with signal 11

### ISSUE THREAD

**Issue by Prabal1998** [microsoft/wslg#1071]
### Windows build number:

10.0.22621.0

### Your Distribution version:

 22.04

### Your WSL versions:

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1702

### Steps to reproduce:

1. Install octave
2. Open octave GUI
![image](https://github.com/microsoft/wslg/assets/40731891/cdb41da3-44da-4ac4-9eb0-4fcabf7d14de)
4. Use plot function in octave
5. Error discovery
![image](https://github.com/microsoft/wslg/assets/40731891/cc0e144b-9136-4aaf-bc03-21e87267521a)

### WSL logs:

1. kernel buffer log
![image](https://github.com/microsoft/wslg/assets/40731891/d3ce8156-d75e-4b2f-917c-baea15b24b2a)
2. WSL log 
![image](https://github.com/microsoft/wslg/assets/40731891/2117b275-c68a-4652-8b66-dedba3954b45)
3. Weston log 
![image](https://github.com/microsoft/wslg/assets/40731891/15e5b986-8ec0-4e02-a411-42110a0be243)

### WSL dumps:

None

### Expected behavior:

Expected  GUI plot
![image](https://github.com/microsoft/wslg/assets/40731891/eff8df5d-60b0-45d9-b8b0-806e2c629ef1)

### Actual behavior:

Octave uses OpenGL based qt for rendering graphics and terminates unexpectedly.

![image](https://github.com/microsoft/wslg/assets/40731891/571709bf-6d0b-4d5c-b8c4-530c9c1b42dd)

**Comment by alexander0042** [comment]
Also seeing this issue here- let me know if there's anything I can do to help debug

**Comment by Prabal1998** [comment]
**Work around solution**

- Kindly find the octaverc configuration file where octave environment and startup configuration exist.  Hint for file location @:

https://docs.octave.org/v8.2.0/Startup-Files.html

-Add the below line on octaverc configuration
`graphics_toolkit("gnuplot")`

![image](https://github.com/microsoft/wslg/assets/40731891/dd856f60-dad1-4752-8c53-787b7b7a0c09)



- Restart the app and verify the solution

![image](https://github.com/microsoft/wslg/assets/40731891/ddcea508-51ef-4ac8-8e54-9ebe6f97e69f)

**Here, Qt default rendering in octave is changed to gnuplot which works seamlessly in linux, Windows or Mac. Qt not being able to render using X11 interface is still to be resolved. **

**Comment by Prabal1998** [comment]
@alexander0042 Requesting for further support.

**Comment by alexander0042** [comment]
Perfect, this worked for me! Thank you for the suggestion, and feel free to close

**Comment by Prabal1998** [comment]
Octave source file pt-plot.cc doesn't include Qplot related headers or function call. It contains only gnuplot.
