### ISSUE TITLE
xterm geometry argument ignored

### ISSUE THREAD

**Issue by nweaver** [microsoft/wslg#108]
# Environment

Windows build number: Microsoft Windows [Version 10.0.21364.1000]
Your Distribution version: Debian installed with wsl
Your WSLg version: 1.0.17.1

# Steps to reproduce

xterm -fa 'Noto Mono' -fs 18 -sb -sl 1024 -geometry +1830+670

#  Expected behavior

Xterm should start up with relative geometry from the x-server so multiple invocations will always appear in the same space

# Actual behavior

Geometry on startup is ignored: repeated invocations have windows showing up in different locations.

**Comment by hideyukn88** [comment]
@nweaver , just for reference, can you try with xclock ? For me, xclock can be positioned as specified in geometry parameter, there is 32x32 window frame offset, thus its frame is positioned -32,-32 from requested position, and size of clock window also set correctly.

![image](https://user-images.githubusercontent.com/13857962/116159624-718fdb80-a6a5-11eb-8397-1a90a18b81b1.png)

**Comment by nweaver** [comment]
xclock does work, the geometry argument is respected.  So it seems to be xterm specific.

**Comment by hideyukn88** [comment]
Fixed in 1.0.23
