### ISSUE TITLE
Windows update error Windows Subsystem for Linux WSLg Preview - 1.0.27

### ISSUE THREAD

**Issue by CodeManMike** [microsoft/wslg#1083]
### Windows build number:

10.0.23493.1000

### Your Distribution version:

22.04.2

### Your WSL versions:

WSL version: 1.3.11.0
Kernel version: 5.15.90.2-3
WSLg version: 1.0.54
MSRDC version: 1.2.4240
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.23493.1000

### Steps to reproduce:

Windows update fails to install Windows Subsystem for Linux WSLg Preview - 1.0.27.
Uninstalled WSL updater, issue persists.
current version is higher than update version.
wsl --update works as expected
![image](https://github.com/microsoft/wslg/assets/125465986/bb7d0211-7de1-402c-a67b-c3d75eb73d6b)

### Actual behavior:

As stated above, it seems like the updater is trying to run, but updates are normally done through wsl --update or the ms store.

**Comment by PMPP** [comment]
I'm having the same issue. But, as you do, I also have a newer version than the version windows update is trying to install.

`wsl -v shows` shows `WSLg version: 1.0.55`, yet Windows Update is trying to install `1.0.27`, rather odd.
