### ISSUE TITLE
Evaluate user profile before starting GUI apps from windows start menu

### ISSUE THREAD

**Issue by mucki-at** [microsoft/wslg#11]
**Is your feature request related to a problem? Please describe.**
I am using kdevelop IDE and I need to set the environment variable KDEV_CLANG_BUILTIN_DIR for it to work properly (find the correct clang installation). The environment variable is set in system wide /etc/profile, but is ignored when launching the app from the start menu shortcut. When launching the app through WSL console manually it works fine (because shell evaluates /etc/profile).

Regular Linux desktops do not have this difference in behavior, starting apps from icons on the desktop or start menu has a proper environment (presumably because the parent process was launched by passing the command through "bash --login" or something similar.

**Describe the solution you'd like**
A linux application launched through the start menu should have the same initial environment as the one I get inside the shell I get when executing "wsl" in windows.

**Describe alternatives you've considered**
In my case I can change the location the environment is configure to make it so that init picks it up, but that requires superuser powers. Regular users will not always be able to do that, or will be confused because application installation/configuration documentation will not work as expected.

**Additional context**

**Comment by spronovo** [comment]
This has been addressed starting with Windows Insider Build 21387 which was released earlier this week. By default application from the start menu will now launch as if they had been launch from the user shell.
