### ISSUE TITLE
Illegal instruction error when  starting gnome-text-editor.

### ISSUE THREAD

**Issue by BenKey** [microsoft/wslg#1104]
### Windows build number:

10.0.22621.0

### Your Distribution version:

22.04

### Your WSL versions:

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2215

### Steps to reproduce:

Start gnome-text-editor.

### WSL logs:

I followed the instructions provided in the [Still having a problem?](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#still-having-a-problem) section of the [Diagnosing "cannot open display" type issues with WSLg](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg) page. The results are as follows.

```
benilda@BK-BEELINK:/mnt/c/Users/Benil$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.51+Branch.main.Sha.435b42ad093d8c9e785b57f2455098db2e3508c0
Mariner: VERSION="2.0.20230107"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: f09791f3314de7b414bf21a46940ff684d936eaf
benilda@BK-BEELINK:/mnt/c/Users/Benil$ echo $DISPLAY
:0
benilda@BK-BEELINK:/mnt/c/Users/Benil$ ls -la /tmp/.X11-unix
total 4
drwxrwxrwx 2 root root   40 Sep  2 04:28 .
drwxrwxrwt 6 root root 4096 Sep  2 04:28 ..
benilda@BK-BEELINK:/mnt/c/Users/Benil$ ls -la /tmp/.X11-unix/
total 4
drwxrwxrwx 2 root root   40 Sep  2 04:28 .
drwxrwxrwt 6 root root 4096 Sep  2 04:28 ..
```

I also followed the instructions found at [Collect WSL logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method). The log files can be found at [WslLogs-2023-09-02_04-51-46.zip](https://github.com/microsoft/wslg/files/12503703/WslLogs-2023-09-02_04-51-46.zip).

### Expected behavior:

gnome-text-editor starts.

### Actual behavior:

- gnome-text-editor does not start.
- The error "Illegal instruction" is displayed.
- It appears that the X server is not running.

**Comment by Masamune3210** [comment]
Something is wiggy about your install, because it works just fine for me
![image](https://github.com/microsoft/wslg/assets/1053504/80d7870f-f6ca-43a4-adc5-16fee3b64e3a)

**Comment by zcobol** [comment]
@BenKey you're correct, the display socket seems to be missing in your case.  Is `/mnt/wslg/.X11-unix/X0` present? It should look like:

```
zcobol@madrid:~$ file /mnt/wslg/.X11-unix/X0
/mnt/wslg/.X11-unix/X0: socket
```

and this should be preset also:

```
zcobol@madrid:~$ ls /tmp/.X11-unix/X0
srwxrwxrwx 1 zcobol zcobol 0 Sep  2 08:27 /tmp/.X11-unix/X0
```

Try running `wsl --shutdown` to restart the service. It might fix it.

**Comment by BenKey** [comment]
@zcobol 

The socket `/mnt/wslg/.X11-unix/X0` is present, as you can see below.

```
benilda@BK-BEELINK:/mnt/wslg/.X11-unix$ ls -la
total 0
drwxrwxrwx 2 root    root     60 Sep  7 02:49 .
drwxrwxrwt 7 root    root    300 Sep  7 02:49 ..
srwxrwxrwx 1 benilda benilda   0 Sep  7 02:49 X0
```

The socket /`tmp/.X11-unix/X0` is present as well, as you can see below.

```
benilda@BK-BEELINK:/mnt/wslg/.X11-unix$ ls /tmp/.X11-unix/X0
/tmp/.X11-unix/X0
```

I have run `wsl --shutdown` to restart the service multiple times. I also rebooted the computer afterward. I am still getting the same results. When I run gnome-text-editor the results are as follows.

```
benilda@BK-BEELINK:/mnt/wslg/.X11-unix$ gnome-text-editor
Illegal instruction
``` 

**Notes:**

* According to the [Diagnosing "cannot open display" type issues with WSLg](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg) page `/tmp/.X11-unix/X0` is supposed to be a symbolic link. It does not appear to a symbolic link on this system. Could this be the problem?
* I attempted to run the following commands to resolve the issue.

   ```
   sudo rm -r /tmp/.X11-unix
   ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
   ```
   Unfortunately this did not work. The first command failed, as follows.

   ```
   benilda@BK-BEELINK:/mnt/wslg/.X11-unix$ sudo rm -r /tmp/.X11-unix
   [sudo] password for benilda:
   rm: cannot remove '/tmp/.X11-unix/X0': Read-only file system
   ```

**Comment by BenKey** [comment]
Something was wrong with my setup. I reinstalled Windows 11 and WSL on my system and it is working correctly now.
