### ISSUE TITLE
Unable to snap WSLg window like native one

### ISSUE THREAD

**Issue by miloshavlicek** [microsoft/wslg#111]
**Is your feature request related to a problem? Please describe.**

Windows opened in WSLg could not be snapped as Windows native windows - see this post for more information about the native behavior: https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241

**Describe the solution you'd like**
I'd like to be able to:
- maximize the window by "move to the top screen border gesture"
- snap the window to the left/right half of the screen by "move to the left/right screen border gesture"
- unmaximize window by dragging it

**Describe alternatives you've considered**
At this time it's possible to resize the window or move it to one side of the screen manually.

**Comment by V-kremenlieva** [comment]
@

**Comment by totolook** [comment]
Same problem with [PowerToys - fancyzones ](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones) but the window is freeze. For unfreeze maxmize the window.

**Comment by spronovo** [comment]
Thanks for the suggestion, local window move and resize in the RDP client, which allows for more natural and performance window move and resize and enable such scenario such as snap/fanyzones, is high on our priority list of new feature to add in the future.

**Comment by spronovo** [comment]
This particular request is already tracked with #22, resolving as a duplicate.
