### ISSUE TITLE
WSL2 wrong OpenGL version

### ISSUE THREAD

**Issue by cyborck** [microsoft/wslg#1114]
### Windows Version

Microsoft Windows [Version 10.0.22621.2283]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

I ran the command `glxinfo -B` on Ubuntu, the results are shown below.

### Expected Behavior

The OpenGL extensions viewer shows the following information:
```
Renderer: Intel(R) Iris(R) Xe Graphics
Vendor: Intel
Version: 4.6.0 - Build 31.0.101.4824
Shading language version: 4.60 - Build 31.0.101.4824
```

### Actual Behavior

`glxinfo -B` prints the following result:

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (Intel(R) Iris(R) Xe Graphics) (0xffffffff)
    Version: 23.0.4
    Accelerated: yes
    Video memory: 8237MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.1
    Max compat profile version: 4.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (Intel(R) Iris(R) Xe Graphics)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.1 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL shading language version string: 4.10
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

As you can see, the renderer and vendor string is different from what it shows on Windows and the maximum OpenGL version is 4.1 instead of 4.6.

**Comment by hideyukn88** [comment]
@cyborck, thanks for reporting the issue. While I believe this is expected behavior with WSL implementation of OpenGL support **top on D3D12** based on its gallium driver. @jenatali, would you please verify? thanks!

**Comment by jenatali** [comment]
Yes, that's intentional. Higher versions will be supported in the future.

**Comment by isharma25** [comment]
Hi, is there any update on this?

**Comment by jenatali** [comment]
On up-to-date drivers, Mesa 24.0 will support GL4.6 in WSL.

**Comment by lesleyrs** [comment]
> On up-to-date drivers, Mesa 24.0 will support GL4.6 in WSL.

Yea it does, but the issue in question is that `glxinfo -B` reports a lower supported opengl version (4.1 on intel iris xe).

You have to use `MESA_GL_VERSION_OVERRIDE=4.6 MESA_GLSL_VERSION_OVERRIDE=460` before running a program to make it work, still up to this day.

**Comment by Trass3r** [comment]
Indeed. GL4.6 has been [supported since Mesa 24](https://gitlab.freedesktop.org/mesa/mesa/-/commit/cb019ff9266b5985dd8d467f724d3310acd03ab6) but it only offers 4.1 even in Mesa 25 offered by latest Ubuntu.
Context creation fails for a higher version.
`MESA_GL_VERSION_OVERRIDE` fixes it.
