### ISSUE TITLE
(1.0.59 pre-release) Graphic glitch with QT Installer and QT Creator

### ISSUE THREAD

**Issue by fscheuMoba** [microsoft/wslg#1128]
### Windows build number:

10.0.22621.0

### Your Distribution version:

22.04

### Your WSL versions:

WSL-Version: 2.0.6.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25880.1000-230602-1350.main
Windows-Version: 10.0.22621.2428

### Steps to reproduce:

**1. Download QT online installer:**
`wget https://d13lb3tujbc8s0.cloudfront.net/onlineinstallers/qt-unified-linux-x64-4.6.1-online.run`
**2. Make it executable:**
`chmod +x qt-unified-linux-x64-4.6.1-online.run`
**3. Start Installer:**
`./qt-unified-linux-x64-4.6.1-online.run`

### WSL logs:

[weston.log](https://github.com/microsoft/wslg/files/13166018/weston.log)
[stderr.log](https://github.com/microsoft/wslg/files/13166026/stderr.log)

### Expected behavior:

QT Installer and QT Creator should work without graphic glitch

### Actual behavior:

**If I start the QT Installer it looks like this**
![image](https://github.com/microsoft/wslg/assets/69569389/4062b436-cfe7-44e8-8d8d-8bd3df54d25e)

**Same with QT Creator**
![image](https://github.com/microsoft/wslg/assets/69569389/535d23e1-0552-4335-8ef4-86e9aaea0958)

If I move the window or move the mouse over the window the glitch disappears sometimes. The same happens if I make the window fullscreen.

**Comment by fscheuMoba** [comment]
**It seems like I fixed this by myself!**

I had compiled a custom kernel (version 5.15.74.2) with CAN bus support in the past and loaded this by the `.wslconfig`. If I do not load this kernel, it works without graphic glitches!

So if you have the same problem, check if you have loaded an old custom kernel. You can check if a custom kernel is loaded by comparing the kernel version from `wsl --version` (in powershell) and `uname -r` (in linux wsl shell). If the version in `uname -r` is lower, a old custom kernel is loaded.

_(I also activated the old kernel again and it continuous working without graphic glitches. I did a `wsl --shutdown`, maybe simply this fixed the glitch. I sadly cannot reproduce this anymore)_

**Comment by billyliuschill** [comment]
I took https://github.com/microsoft/wslg/issues/1130#issuecomment-1813058202 his advice and just updated my nvidia drivers. I then ran `wsl --shutdown` and rebooted wsl and everything operates fine now. No more application tearing (taring?).
