### ISSUE TITLE
Cannot launch app requires D-Bus

### ISSUE THREAD

**Issue by ZgblKylin** [microsoft/wslg#113]
# Environment

```none
Windows build number: 10.0.21364.0
Your Distribution version: 18.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

Start any app requires D-Bus from start menu, such as dolphin(file browser of kde plasma desktop).

The application exit immediately after window appears.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
```none
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.pulse-cookie': No such file or directory
E: [pulseaudio] module-console-kit.c: GetSessionsForUnixUser() call failed: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
E: [pulseaudio] module.c: Failed to load module "module-console-kit" (argument: ""): initialization failed.
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
E: [rdp-sink] module-rdp-sink.c: Connected failed
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Connected to fd 12
```
* `weston.log`
```none
[21:33:49.504] Spawned Xwayland server, pid 176
[21:33:52.703] xfixes version: 5.0
[21:33:52.712] created wm, root 586
[21:33:52.712] xfixes selection notify event: owner 2097153
[21:33:52.712] our window, skipping
[21:33:54.108] selection request, CLIPBOARD, target TARGETS, property _QT_SELECTION
[21:33:54.199] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[21:33:54.199] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[21:33:54.199] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[21:33:54.271] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[21:33:54.271] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[21:33:54.271] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[21:33:54.271] Client: ClientGetAppidReq: pid:130 appId:dolphin
```
* `versions.txt`
```none
WSLg ( x86_64 ): 1.0.17+3.Branch.master.Sha.a526dfd5ad03d126bb2d8c528f6c3563e86a40da
Mariner: VERSION="1.0.20210224"
FreeRDP: e4a2fc2053bd8c5f99455fcd08ffee7e5591567a
weston: fd961f5cd116c9358d82ce94d139c1578e21bd00
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

#  Expected behavior

There should be a /etc/wslg.conf.d folder, then we could put pre-start scripts into it, such as `export $(dbus-launch)`

# Actual behavior

Nothing useful happened.

**Comment by hideyukn88** [comment]
related to https://github.com/microsoft/wslg/issues/99.

**Comment by spronovo** [comment]
WSLg doesn't touch of configure your WSL distro. If you need to run an application which require dbus, you need to launch it manually or configure your distro to launch it automatically.

**Comment by stevebovy** [comment]
PARENT INIT PROCESS AND SHARED DBUS INSTANCE PROBLEM

The bigger problem here is dbus is designed to create  a "shared instance"  for all desktop apps launched from the desktop 
session which is the centralized parent of all subsequent  apps.  This is done with  environment variables that are created , these
variables are intended to be "inherited"  by  the child  processes.

If  you launch individual gnome apps without the proper pre-configured shared dbus instance via the variables,  then they 
will automatically create  there own private dbus instance .   Thus you could end up with many many dbus instances.   

> export $(dbus-launch)" <  IS USELESS UNLES IT RESIDES IN  the  single parent INIT script  from which ALL child processes
inherit their environment variables 

WSL  and/or WSL2  NEEDS  configuration support for a  PARENT INIT  process  that  can run  INIT scripts   from which all
subsequent child processes inherit their configuration variables.
