### ISSUE TITLE
Scrambled graphic after WSLg updates

### ISSUE THREAD

**Issue by rk0cc** [microsoft/wslg#1144]
### Windows build number:

10.0.22631.2715

### Your Distribution version:

Ubuntu 22.04

### Your WSL versions:

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715

### Steps to reproduce:

Simply open any GUI applications and hover somewhere of the app

### Expected behavior:

Normally displayed content.

### Actual behavior:

The graphic glitched out.

![Screenshot (8)](https://github.com/microsoft/wslg/assets/70585816/a1fe0110-0aeb-4c57-be8a-d58b23c2d538)
![Screenshot (9)](https://github.com/microsoft/wslg/assets/70585816/f2e7360c-e501-476d-8df5-f2e36ddd42e0)

It likely similar with #707 but this time it also affects Ubuntu application interface itself.

**Comment by rk0cc** [comment]
I revisited #1128 and #1130 and the problem resolved by performing update monitor driver update rather than graphic card one.

**Comment by uw13** [comment]
Had the same problem after an update of the WSLg component by a Windows update on two computers.
The `wsl --shutdown` command alone resolved the problem.

**Comment by awenborn** [comment]
I'm having the same sporadic issues with scrambled graphics forwarding via WSL on multiple client PCs
