### ISSUE TITLE
How to disable gui applications option for a particular distro on your pc if you have more than one

### ISSUE THREAD

**Issue by KavyanshJain** [microsoft/wslg#115]
hello I have installed two linux distros - ubuntu and kali linux.

and i want wslg to only enable on ubuntu not on kali linux.
for making a .wslconfig file disable the support for both but I want it enable for ubunut.

**Comment by spronovo** [comment]
Thanks for the feedback. That is not currently possible, but has been suggested and something we'll be looking into enabling (see #73)

**Comment by crramirez** [comment]
Unless WSLg is giving you serious problems (like the distro won't execute), you can as a workaround change the value of the DISPLAY environment variable at for example .bashrc. It will enable you to use your xserver or if you unset the variable to behave like WSLg is not installed.

Regards,
