### ISSUE TITLE
.wslconfig hyphen and underscore parsing / encoding issue

### ISSUE THREAD

**Issue by yumasheta** [microsoft/wslg#1173]
### Windows build number:

22621.2861 [Version 10.0.22621.2861]

### Your Distribution version:

22.04

### Your WSL versions:

```
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2861
```

### Steps to reproduce:

I tried configuring the wslg with options from: [the docs](https://github.com/microsoft/wslg/wiki/WSLg-Configuration-Options-for-Debugging). I attached the exact file I am using, renamed so it's accepted as an attachment.

[wslconfig.txt](https://github.com/microsoft/wslg/files/13818413/wslconfig.txt)

### WSL logs:

[weston.log](https://github.com/microsoft/wslg/files/13818528/weston.log)

[stderr.log](https://github.com/microsoft/wslg/files/13818511/stderr.log)

### Actual behavior:

When launching the WSL and checking in the event viewer, I get the following error logged:
```
Expected ']' in C:\Users\myuser\.wslconfig:3
Expected '=' in C:\Users\myuser\.wslconfig:4
Expected '=' in C:\Users\myuser\.wslconfig:5
Expected '=' in C:\Users\myuser\.wslconfig:6
```
and none of the settings from the system-distro-env section apply.

By playing around with the file, I was able pin it down to the hyphen in the section name and the underscores in the key names. Somehow they aren't parsed correctly. When removing the hyphens and underscores I get unknown key errors instead.
And when removing the system-distro-env section entirely, it works normally.
The file is UTF-8 with (CLRF).

**Comment by sl1pkn07** [comment]
same here with

```
[system-distro-env]
;disable GPU in system-distro
LIBGL_ALWAYS_SOFTWARE=1
```

leads:

```
PS C:\Users\sL1pKn07> wsl
wsl: Se esperaba ']' en C:\Users\sL1pKn07\.wslconfig:1
wsl: Nombre de clave no válido en C:\Users\sL1pKn07\.wslconfig:2
wsl: Se esperaba '=' en C:\Users\sL1pKn07\.wslconfig:3
```
(sorry, my LANG is es_ES)

greetings

**Comment by sl1pkn07** [comment]
ok, i found the error: `[system-distro-env]` is in the file `.wsl`**g**`config` instead of `.wslconfig`

**Comment by yumasheta** [comment]
ok, indeed this was the issue. The docs do have the correct name, though, it looks like reading is not my strength, huh...
Thank you @sl1pkn07
