### ISSUE TITLE
Scrambled UI when starting Emacs under WSLg. Clears when I `wsl --shutdown` and try again.

### ISSUE THREAD

**Issue by edburns** [microsoft/wslg#1195]
### Windows build number:

10.0.22631.3007

### Your Distribution version:

20.04

### Your WSL versions:

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3007

### Steps to reproduce:

1. Install Emacs.
2. Start Emacs.
3. Sometimes I see this scrambled UI
![20240212-eb-4993-scrambled-window](https://github.com/microsoft/wslg/assets/75821/dadd3274-4e90-404f-b78a-0747121a8116)
   - If I select in the window with the mouse, the scramble momentarily goes away and is replaced with the correct view, but quickly returns.
   - Emacs is responsive to keyboard input, but I can't see what I'm doing.
4. Stop WSL with `wsl --shutdown`
5. Start Emacs
![20240212-eb-4993-correct-window](https://github.com/microsoft/wslg/assets/75821/4bd8eafb-14c7-48d7-990e-9abfdc7c2e56)

### WSL logs:

[20240212-eb-4993-logs.zip](https://github.com/microsoft/wslg/files/14249342/20240212-eb-4993-logs.zip)

### Expected behavior:

Emacs shows

### Actual behavior:

Emacs is scrambled

**Comment by hideyukn88** [comment]
This is fixed by https://github.com/microsoft/WSL/releases/tag/2.1.1.
