### ISSUE TITLE
Installation of NVIDIA Graphics driver causes inability to use external monitor 

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/wslg#12]
# Environment

```none
Windows build number: ?
Your Distribution version: ?
Your WSLG version: 0.2.10
```

# Steps to reproduce

![image](https://user-images.githubusercontent.com/42221804/101933168-b3096980-3b90-11eb-8cee-c33b38a46a84.png)

This seems like a transient issue only affecting some users. We'd need to follow up with Elmo Todurov to get better logs if needed.

**Comment by spronovo** [comment]
Closing old issue
