### ISSUE TITLE
MSI title is shown incorrectly when uninstalling

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/wslg#13]
# Environment

0.2.7.2 (An older MSI) 

# Steps to reproduce

Uninstall the MSI and see an image like this:
![image](https://user-images.githubusercontent.com/42221804/100808523-2b319b80-33e9-11eb-942c-4a46e2a8f259.png)

This was reported by Paul Campbell but I was unable to exactly repro it on 0.2.10. Perhaps this is a no repro, but wanted to file it just to be sure.

**Comment by spronovo** [comment]
Closing old issue.
