### ISSUE TITLE
Can't install wslg: "wsl --update" returns "No updates are available."

### ISSUE THREAD

**Issue by soshishimada** [microsoft/wslg#133]
# Environment

 
Windows build number: Microsoft Windows [Version 10.0.21364.1011]
Your Distribution version:   18.04 
# Steps to reproduce
 
In Admin Command Prompt, run:
wsl --update 
 

#  Expected behavior
The system installs wslg on the existing wsl2.

# Actual behavior
Checking for updates...
No updates are available.
Kernel version: 5.10.16

**Comment by spronovo** [comment]
Hi @soshishimada, could you verify if WSLg was installed but maybe failed to start (as there are a few known issue at the moment). From your Ubuntu terminal, could you type the following:

```
ls /mnt/wslg
cat /mnt/wslg/versions.txt
```

**Comment by soshishimada** [comment]
Hi, I rebooted my computer and the issue was solved. Apparently, some Microsoft updates were pending. Now I can use wslg.
