### ISSUE TITLE
Snap package manager not working on wslg

### ISSUE THREAD

**Issue by Neizan93** [microsoft/wslg#135]
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.21370.1]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

Try to install a snap, example:
`sudo snap install teams`

#  Expected behavior

Successfully install

# Actual behavior

error: cannot communicate with server: Post http://localhost/v2/snaps/teams: dial unix /run/snapd.socket: connect: no such file or directory

**Comment by spronovo** [comment]
Thanks for the feedback. This is a known issue due to snap dependency on systemd and WSL not supporting systemd. Please see #102 and go over to https://github.com/microsoft/WSL/issues/994 to upvote this WSL feature request.
