### ISSUE TITLE
systemctl not working on wslg

### ISSUE THREAD

**Issue by JonSenpai** [microsoft/wslg#136]
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.21370.1]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

Try to run any systemctl command, example:
`systemctl` or `sudo systemctl --type=service`

#  Expected behavior

systemctl successfully working

# Actual behavior

Error:
_System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down_

**Comment by spronovo** [comment]
Thanks for the feedback. Unfortunately this is due to WSL not supporting systemd. Please visit https://github.com/microsoft/WSL/issues/994 to upvote the request for systemd support in WSL.
