### ISSUE TITLE
wsl --update invalid command line option

### ISSUE THREAD

**Issue by ehoahz** [microsoft/wslg#137]
![image](https://user-images.githubusercontent.com/40186705/116766745-7078f880-aa6f-11eb-8788-f16cef54a354.png)

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by spronovo** [comment]
I suspect you may be trying to do this from an older version of Windows. Could you type the following in a Windows command prompt

```
C:\WINDOWS\system32>ver

Microsoft Windows [Version 10.0.21367.1000]
```

You need to be on Windows insider build 21364+ for WSLg to be available. You can join Windows Insider program here: https://insider.windows.com/en-us/.

Steve

**Comment by ehoahz** [comment]
Windows build lower than 21364.
