### ISSUE TITLE
GUI feature not working in multiple user accounts

### ISSUE THREAD

**Issue by techie-explorer** [microsoft/wslg#138]
# Environment

Windows build number: 21370.1
Your Distribution version: Ubuntu 20.04.2 LTS
GUI app support: 1.0.17

# Steps to reproduce

1. Create a new user in wsl
2. Test gui app in default user, it will work fine
3. Then switch to the new user and try launching any gui app
4. An error will appear

**WSL logs**: 

> versions.txt
    WSLg ( x86_64 ): 1.0.17+3.Branch.master.Sha.a526dfd5ad03d126bb2d8c528f6c3563e86a40da
    Mariner: VERSION="1.0.20210224"
    FreeRDP: e4a2fc2053bd8c5f99455fcd08ffee7e5591567a
    weston: fd961f5cd116c9358d82ce94d139c1578e21bd00
    pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
    mesa:
> pulseaudio.log
    W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.config/pulse/cookie': No such file or directory
    W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.config/pulse/cookie': No such file or directory
    W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.pulse-cookie': No such file or directory
    W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.pulse-cookie': No such file or directory
    E: [pulseaudio] module-console-kit.c: GetSessionsForUnixUser() call failed: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
    E: [pulseaudio] module.c: Failed to load module "module-console-kit" (argument: ""): initialization failed.
    E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
    E: [rdp-sink] module-rdp-sink.c: Connected failed
    E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
    E: [rdp-sink] module-rdp-sink.c: RDP Sink - Connected to fd 12

#  Expected behavior

GUI apps should work fine without any issues no matter which user account we are using.

# Actual behavior

![image](https://user-images.githubusercontent.com/26202449/116772653-2e02ec00-aa6e-11eb-8dd1-0217a043c7c9.png)

**Comment by spronovo** [comment]
Can you try ```su trojanx``` without the ```-```, that works fine for me. The ```-``` resets the user environment variable for the new user... so DISPLAY that was setup in WSL INIT gets wiped and you won't be able to connect to the X server. 

You can restore functionality by restoring these environment variables:

```
export DISPLAY=:0
export XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
WAYLAND_DISPLAY=wayland-0
export PULSE_SERVER=/mnt/wslg/PulseServer
```

**Comment by techie-explorer** [comment]
Thanks a lot, your solution worked for me. This issue can be closed.
