### ISSUE TITLE
android studio: emulator window not moveable - stays in the way  - Crash when you minimize these windows

### ISSUE THREAD

**Issue by fflorey** [microsoft/wslg#139]
Examples of behavior: 
If your start Android Studio and Open the Configure Dialog OR
you start the Android Emulator you get the 
in both cases you get an XWindow without any "decorations" (window frames etc.) so it is not possibility to move this around. This can make the usage of some programms (like Emulator) nearly impossible.
Hint: If you MINIMIZE the windows by clicking on the "-" of the Emulator Settings Windows - the Emulator always crashes. Once i got the message, that the X-Server itself crashed. 
I used the xdotool to move the window - this also not possible. I tried:
xdotool windowmove --sync --relative $(xdotool selectwindow)
![Screenshot 2021-05-01 114926](https://user-images.githubusercontent.com/23704526/116778633-61944500-aa73-11eb-89ce-b4bb0950518c.png)

In the screenshot, i surrounded the mentioned xwindow with the red line.

Anyhow - thanks for your great work so far!!! Almost perfect!

**Comment by fflorey** [comment]
When you minimize the window, i see a crash and restart of the X-Server:

Waiting for data... (interrupt to abort)X connection to :0 broken (explicit kill or server shutdown).
Date: 2021-05-01 CEST
[12:00:54.106] weston 9.0.0

**Comment by fflorey** [comment]
> @fflorey , thanks for reporting this, and I am able to locally reproduce the issue using emulator window. Btw, I'm not able to find a way to "Open the Configure Dialog", would you please describe more this? I'm using android studio version 4.2.
> 
> ![image](https://user-images.githubusercontent.com/13857962/117735307-0ddbd700-b1aa-11eb-8d17-e3e2bd7dc8ec.png)
> 
> I do have a fix for crash with minimize locally and am still investigating it's not movable. it looks related to the window has "override_redirect" property, which is usually not movable. Thanks!

You can start it like that: 
Start Android Studio (here Version 4.1.3)
Then use the "configure" Button on the bottom. Use see a window, also not connected to the Android-Studio 4.1.3 window.

**Comment by hideyukn88** [comment]
Fixed in 1.0.23.
