### ISSUE TITLE
`wsl --update` command says "Invalid command --update" and lists out other allowed commands

### ISSUE THREAD

**Issue by skandaprasad** [microsoft/wslg#142]
*I am using Windows 10 Home with WSL 2 (Ubuntu 20.04)* 
I use Xorg for GUI support, but now I wanted to update to WSLg.

Any help would be appreciated.
Here is the command line output:

Invalid command line option: --update
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

Arguments for managing Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are currently
                being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --shutdown
        Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution.

    --help
        Display usage information.

**Comment by Biswa96** [comment]
Provide the Windows 10 version.

**Comment by skandaprasad** [comment]
Windows 10 Home Version 20H2

**Comment by onomatopellan** [comment]
You need at least build 21364 from insiders.  See [FAQ](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#verify-you-are-running-on-windows-build-21364).

**Comment by skandaprasad** [comment]
Ah yes, thanks! 
I did that.

**Comment by xE0F9** [comment]
Edition	Windows 10 Home
Version	21H1
Installed on	‎4/‎4/‎2021
OS build	19043.985
Experience	Windows Feature Experience Pack 120.2212.2020.0
Same issue...
