### ISSUE TITLE
Cuda Sample Aps not working

### ISSUE THREAD

**Issue by rpw138** [microsoft/wslg#147]
# Environment
Microsoft Windows [Version 10.0.21364.1011]
Release 20.04
WLS v5.10.16
WSLg 1.0.19

# Steps to reproduce
cd /usr/local/cuda/samples/2_Graphics/simpleGL
make
sudo make
./simpleGL

#  Expected behavior

Windows comes up showing simpleGL demo

# Actual behavior

Window pops up, disappears, and error message is returned:
GPU Device 0: "Turing" with compute capability 7.5

CUDA error at simpleGL.cu:421 code=999(cudaErrorUnknown) "cudaGraphicsGLRegisterBuffer(vbo_res, *vbo, vbo_res_flags)"
CUDA error at simpleGL.cu:433 code=400(cudaErrorInvalidResourceHandle) "cudaGraphicsUnregisterResource(vbo_res)"

**Comment by spronovo** [comment]
For CUDA did you follow NVIDIA's instruction on their website: https://developer.nvidia.com/cuda/wsl ? For support and report bugs with CUDA you should try NVIDIA's CUDA forum.
