### ISSUE TITLE
Windows Insider Build

### ISSUE THREAD

**Issue by skandaprasad** [microsoft/wslg#149]
Yesterday, I successfully installed WSLg (Ubuntu 20.04 Distro) by upgrading to the Windows Insider Build program.
Basic GUI applications worked. 

But today morning, after I booted my laptop, within 5 minutes, I encountered the GSOD (Green Screen of Death).
Stopcode was HYPERVISOR_ERROR, which I found out after some small research is related to virtualization.

The issue was that percentage of error information being collected by Windows never increased from 0%. 
I did a hard reset and very fortunately, I was able to boot up. I reverted back to my previous windows version.

WSLg could have had a lethal impact on the system. Windows Insider Build is pretty much unstable currently.

I'm just sharing my experience and I don't think we're just there yet with respect to WSLg. I'm sure others might have had more pleasant experiences than me. 
Anyone having good fixes for this is welcome to continue this thread.
![gsod](https://user-images.githubusercontent.com/54772857/116846687-7bb25c80-ac06-11eb-85ed-22b67e7855d6.jpeg)
![hypervisor_error](https://user-images.githubusercontent.com/54772857/116846692-7f45e380-ac06-11eb-91fa-05961b39913f.jpeg)

Images for refernce.

**Comment by hideyukn88** [comment]
@skandaprasad, please submit report using Feedback hub, thanks!

**Comment by spronovo** [comment]
Thanks for your report. As Hideyuki suggest this issue should be tracked through the Windows Feedback Hub as it isn't directly related to WSLg. Resolving this thread.
