### ISSUE TITLE
Forward GUI from SSH X11 Forwarding

### ISSUE THREAD

**Issue by Lorac** [microsoft/wslg#153]
**Is your feature request related to a problem? Please describe.**
I would like to be able to forward X11 from a remote Linux machine so that I can use my GUI application on my work machine while being remote on my Windows PC.

Remote Linux PC is using Ubuntu Wayland.

**Describe the solution you'd like**
When X11 forwarding is enabled with SSH, I would like to see GUI application locally without a 3rd party application like VcXsrv, X410, etc.

**Describe alternatives you've considered**
Using VcXsrv or X410.

X410 is not free.
VcXsrc setup is kind of annoying.

**Comment by Biswa96** [comment]
Then use RDP instead of X11 over SSH.

**Comment by Lorac** [comment]
> Then use RDP instead of X11 over SSH.

I don't want to use a full desktop experience, I just want some applications to be forwarded. Maybe I do not fully understand RDP is since I never used it.

I added the information that the remote PC is using Ubuntu Wayland.

**Comment by Lorac** [comment]
It seems that my setup was no correct because it already works: https://www.reddit.com/r/bashonubuntuonwindows/comments/n42arv/psa_with_wslg_you_do_not_need_another_x11_server/

**Comment by RichardYCJ** [comment]
Sorry to reopen this issue, I've tried @Lorac's post and this only works when **ssh within WSL**. I was wondering if it is possible to natively support X11 forwarding through XWayland in Windows or anything directly linked to Weston by ssh.

**Comment by nicola-lunghi** [comment]
That;s interesting for me as well

**Comment by sunlin7** [comment]
Call for the feature. 
Currently I use both WSLg and VcXsrv. The WSLg for local WSL, and VcXsrv for remote machine.
If WSLg can support X forwrding directly (without a running WSL), that will be perfect.
