### ISSUE TITLE
No icons to minimize/maximize application

### ISSUE THREAD

**Issue by bhardwajs** [microsoft/wslg#157]
# Environment

```none
Windows build number: 10.0.21370.1
Your Distribution version: Ubuntu 21.04
Your WSLg version: 1.0.19
```

# Steps to reproduce
- Install gnucash. In my case, I built it from git repo.
- Run gnucash. No icons to minimize, maximize, or close window.

**WSL logs**: 
```none
sumitb@sumitb-dsk-0:~$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.19+Branch.main.Sha.2a47bf20c239b523d7413f315cbc9ee60dfde831
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 16de531f00aa3dfd17e0de74c8f49e9fd7cec617
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
sumitb@sumitb-dsk-0:~$ echo $DISPLAY
:0
sumitb@sumitb-dsk-0:~$ ls -la /tmp/.X11-unix
lrwxrwxrwx 1 root root 19 May  3 13:17 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
sumitb@sumitb-dsk-0:~$ ls -la /tmp/.X11-unix/
total 0
drwxrwxrwx 2 root   root   60 May  3 13:17 .
drwxrwxrwt 5 root   root  220 May  3 13:17 ..
srwxrwxrwx 1 sumitb users   0 May  3 13:17 X0
```
* Attach WSLg logs from  `/mnt/wslg`
[weston.log](https://github.com/microsoft/wslg/files/6417455/weston.log)

#  Expected behavior
- Should see icons

# Actual behavior
- No icons to minimize, maximize, or close the application.
- Message on command prompt
WaylandCompositor requires eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL and eglQueryWaylandBuffer.
Nested Wayland compositor could not initialize EGL

**Comment by reanimus** [comment]
This isn't a WSL bug, it's normal behavior for gtk3 apps.

Install `gnome-tweaks` and open it, then enable the minimize/maximize buttons in there.

![image](https://user-images.githubusercontent.com/1053912/116932628-5da12800-ac17-11eb-9e35-d3b786ff6bad.png)

**Comment by reanimus** [comment]
Wait, I just noticed you said you don't see a close icon either. If that's the case, there's probably something wrong with the window manager. A screenshot of it might be helpful.

**Comment by bhardwajs** [comment]
@reanimus - I did see a close icon. Sorry for the confusion. And, using `gnome-tweaks` worked as a charm. Thanks!

Should these messages on the console be ignored?
```
WaylandCompositor requires eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL and eglQueryWaylandBuffer.
Nested Wayland compositor could not initialize EGL
```

**Comment by hideyukn88** [comment]
@bhardwajs , I also confirm close button is visible. so no more issue here. 

Regarding to those EGL messages, this is currently expected since our Wayland compositor is not yet supporting EGL based composition, currently it only works with Wayland SHM surface.

![image](https://user-images.githubusercontent.com/13857962/117216170-35026500-adb4-11eb-8885-b1738b2c1adb.png)

**Comment by MikeYeager** [comment]
I tried installing gnome-tweaks, but it fails with "Depends: gir1.2-handy-0.0 but it is not installable" I tried looking it up in the Ubuntu package search (I have 20.04 installed) and the package doesn't exist for Intel: 
```
Package gir1.2-handy-0.0
focal (20.04LTS) (introspection): GObject introspection files for libhandy
0.0.13-1: amd64 arm64 armhf ppc64el s390x
```
Am I stuck? Is there a work-around? Thanks in advance!

**Comment by reanimus** [comment]
amd64 is the one you want

> I tried installing gnome-tweaks, but it fails with "Depends: gir1.2-handy-0.0 but it is not installable" I tried looking it up in the Ubuntu package search (I have 20.04 installed) and the package doesn't exist for Intel:
> 
> ```
> Package gir1.2-handy-0.0
> focal (20.04LTS) (introspection): GObject introspection files for libhandy
> 0.0.13-1: amd64 arm64 armhf ppc64el s390x
> ```
> 
> Am I stuck? Is there a work-around? Thanks in advance!

amd64 is the one you want for intel

**Comment by MikeYeager** [comment]
Thanks for the quick reply. Any idea why it won't install then? The full error message is:
```
The following packages have unmet dependencies:
 gnome-tweaks : Depends: gir1.2-handy-0.0 but it is not installable
                Depends: gnome-shell-extension-prefs but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I have tried ```sudo dpkg --configure -a```, ```sudo apt-get install -f```, ```sudo apt-get clean && sudo apt-get update``` followed by ```sudo apt upgrade```

No luck. I just want to turn on the minimize and maximize buttons on the Linux windows. (not having them as a default seems odd, but it is what it is).

**Comment by reanimus** [comment]
> Thanks for the quick reply. Any idea why it won't install then? The full error message is:
> 
> ```
> The following packages have unmet dependencies:
>  gnome-tweaks : Depends: gir1.2-handy-0.0 but it is not installable
>                 Depends: gnome-shell-extension-prefs but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> I have tried `sudo dpkg --configure -a`, `sudo apt-get install -f`, `sudo apt-get clean && sudo apt-get update` followed by `sudo apt upgrade`
> 
> No luck. I just want to turn on the minimize and maximize buttons on the Linux windows. (not having them as a default seems odd, but it is what it is).

Gnome/GTK doesn't normally have a task bar or any equivalent of it so minimizing is less common, I think.

Have you tried looking through some of the solutions from [this thread](https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages)?

**Comment by MikeYeager** [comment]
@reanimus thank you for the help. I did go through most of those steps, but not all. I got some new info with this:
```
sudo apt install gnome-tweaks -o Debug::pkgProblemResolver=true -o Debug::Acquire::http=true
Reading package lists... Done
Building dependency tree
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) gnome-tweaks:amd64 < none -> 3.34.0-2ubuntu1 @un puN Ib >
Broken gnome-tweaks:amd64 Depends on gir1.2-handy-0.0:amd64 < none @un H >
Broken gnome-tweaks:amd64 Depends on gnome-shell-extension-prefs:amd64 < none | 3.36.1-5ubuntu1 @un uH >
  Considering gnome-shell-extension-prefs:amd64 1 as a solution to gnome-tweaks:amd64 9999
    Reinst Failed early because of gnome-shell:amd64
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gnome-tweaks : Depends: gir1.2-handy-0.0 but it is not installable
                Depends: gnome-shell-extension-prefs but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
That gave me a little more info. I installed and ran the Synaptic Package manager tool and found gnome-shell-extension-prefs and tried to install it and got this info:
![image](https://user-images.githubusercontent.com/7063813/124313739-874ed080-db2e-11eb-9cdf-b87f3cda18c3.png)
Which seems to indicate that the gnome-shell is too new? In any case, I'm too scared to mess with that for fear of breaking everything. Not sure why it says 'is to be installed'. 3.36.4-lumbutul~20.04.2 IS installed. 

I will just have to do that part of my testing on a real Linux box I guess.

**Comment by reanimus** [comment]
It sounds like that package (gnome-shell-extension-prefs) has a dependency on that specific (older) version of gnome-shell. Chances are they're bumping gnome versions right now and that's the source of the incompatibility.
