### ISSUE TITLE
Cursor disappearing on multi monitor configuration

### ISSUE THREAD

**Issue by joshward** [microsoft/wslg#160]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21370.1]
Your Distribution version: Ubuntu 18.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

* Open a gedit or another GUI application from WSL
* It opens on my primary monitor (see diagram below)
* Drag application to one of my monitors to the left
* Hover mouse over the application

**WSL logs**: 

[pulseaudio.log](https://github.com/microsoft/wslg/files/6422191/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/6422192/weston.log)
[versions.txt](https://github.com/microsoft/wslg/files/6422193/versions.txt)

#  Expected behavior

When I open a WSL GUI app and move the app to a different monitor I should be able see my mouse cursor and continue to interact with the app.

# Actual behavior

I have a monitor configuration like this:
![image](https://user-images.githubusercontent.com/11366954/117029734-cf2eb400-acb3-11eb-93e7-6d62366d6842.png)
where monitor 4 is my primary monitor.

When I open a WSL app (tested with gedit and others), it open as expected and I can interact and use it as expected. However, if I move the application (by dragging it) to either of my monitors on the left side (2 and 3), the mouse cursor no longer appears over the application. The mouse cursor still interacts with the application but I just can't see the cursor. If I move the application back to either of the monitors on the right side (4 and 1) the mouse cursor is visible again when over the top of the application.

**Comment by hideyukn88** [comment]
@joshward , thanks for reporting the issue. Unfortunately I don't have 4 monitors on hand, so I can't try on exact your condition, but relocating around 3 monitors in any way, it's working for me. Thus, I would like to ask a few questions to help narrow down the cause.

1: Keeping all 4 monitors enabled, but change the primary to the most upper-left monitor, 3 in your picture, so all coordinate (in Windows side) become positive space, does mouse disappear on any monitor ?

2: Keeping 4 as your primary monitor and you disabled monitors at negative Y space, which is 3 and 1, and keeping 2 and 4 enabled, then moving a window to 2, does mouse cursor disappears ? And same to negative X space, disabling 3 and 2, and moving a window to 1 makes cursor disappears ?

3: do you install any sort of mouse driver or tools (such as Logitech Options) in Windows side or have some accessibility software running ?

Thanks!

**Comment by joshward** [comment]
@hideyukn88 

Thanks for looking into this. Here's some the follow up to your tests:

1. Changing my primary monitor to the upper left (3) monitor corrects the issue.
Just to try more things, I made my lower left monitor (2) the primary and it also corrected the issue. However, making the upper right monitor (1) the primary does not correct the issue.

2. Disabling monitors 1 and 3 and only leaving 2 and 4 enabled with 4 being the primary also corrects the issue. Likewise, there is no issue when I only have 1 and 4 enabled with 4 being my primary.
Just to try more things, I disabled only 3 (4 still being primary) and still had the issue. However, oddly enough disabling only 2 with 4 still being primary solves the issue.

3. I don't have any specialty mouse drivers/tools or accessibility software running. The only thing that I can think of that might cause issues is Ultramon; just to be sure I closed the application but still had the issue.

Thanks for looking at this, I'm happy to help continue to diagnose anything else.

**Comment by hideyukn88** [comment]
@joshward , I'm still not able to reproduce this problem locally, so please do following

1: launch gedit.
2: move gedit to the monitor where has pointer visible issue.
3: while gedit has input focus, press L-CTRL then L-SHIFT (while holding L-CTRL) then SPACE (while holding L-CTRL and L-SHIFT) , then release all key, then press 'w' key.
4: please check /mnt/wslg/weston.log and it should have "rdp debug binding 'W' - dump all window from window hash_table." and all information about window. If you don't see this, please try key combo at 3 again.
5: please send entire that debug section to me.

Thanks!

**Comment by stefanrybacki** [comment]
I can confirm, this happens to me too on a 3 Monitor side by side configuration. Since I am going over usb-c for 2 of the monitors I suspect Displaylink to be the culprit, though. Will also try to get the logs.

**Comment by joshward** [comment]
@hideyukn88 

Here is the log file you requested.

[weston.log](https://github.com/microsoft/wslg/files/6533102/weston.log)

**Comment by stefanrybacki** [comment]
Here is my weston.log (I tested using google-chrome from within wsl).
Note the mouse works in chrome, but not on the surrounding container window, so once I move the window to one of the other screens, I can no longer move it, minimize, maximize or resize the window as the mouse disappears in those regions.

[weston.log](https://github.com/microsoft/wslg/files/6552074/weston.log)

**Comment by amivanoff** [comment]
The same issue on latest Ubuntu 20.04 with 3 monitors. Mouse pointer works on 1st (main) and 3rd monitors and disappears on 2nd monitor.
![image](https://user-images.githubusercontent.com/2325194/120084535-ba3e1880-c0d9-11eb-8f8c-ceca1b2ad3dc.png)

**Comment by hideyukn88** [comment]
Hi, all. Would you please try WSLg 1.0.23, https://github.com/microsoft/wslg/releases/tag/v1.0.23, to check if this issue is fixed? thanks!

**Comment by joshward** [comment]
@hideyukn88 Confirmed! 1.0.23 fixes the issue for me. Thank you!

**Comment by hideyukn88** [comment]
@joshward, thank you very much for confirming it. I think https://github.com/microsoft/weston-mirror/pull/16 addresses this, thanks!

**Comment by stefanrybacki** [comment]
It is not fixed for me. How can I confirm, I installed 1.0.23 correctly, to make sure the fix is actually running?

**Comment by hideyukn88** [comment]
@stefanrybacki , you can check /mnt/wslg/versions.txt. thanks!

WSLg ( aarch64 ): **1.0.23**+Branch.main

**Comment by stefanrybacki** [comment]
@hideyukn88 ok it shows 1.0.21, how to I update to 1.0.23 or higher, `wsl --update` throws an error.

**Comment by hideyukn88** [comment]
@stefanrybacki, we changed the way update works when "pre-release" builds are currently installed, 1.0.21 is the one of those "pre-release" build. (see https://github.com/microsoft/wslg/issues/302). At this point, you have two options, you can install 1.0.23 (or 1.0.24) from our release page by downloading MSI https://github.com/microsoft/wslg/releases, or wait 1.0.24 become official release, then wsl --update should work. thanks!.

**Comment by stefanrybacki** [comment]
@hideyukn88 thanks for the information, however I ran the 1.0.24 x64 msi, restarted but still see this in the versions.txt file:

```
WSLg ( x86_64 ): 1.0.22+Branch.main.Sha.d7102a7ff8a3bb04bbcd3483c3f7d7a7633686a1
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 9e402088aa2cd9316851ea20b9befbcf3b9c9564
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

And then I see this also under installed apps and features:
![image](https://user-images.githubusercontent.com/29799350/122816331-e151c980-d2d6-11eb-9ef2-a8284cb9a4f2.png)

So something is wrong. Any ideas what is going on?

**Comment by stefanrybacki** [comment]
I can now also confirm the mouse problem is gone for me too.
