### ISSUE TITLE
Taking screenshot of JetBrains rider causes hang and system to OOM

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/wslg#161]
# Environment

```none
Windows build number: 10.0.21370.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

1. Install Rider as detailed in #4 
2. If one wasn't created, create .desktop file for rider with contents from here: https://github.com/microsoft/wslg/issues/4#issuecomment-825118138
3. Take a screenshot of Rider using the snipping tool (Win+Shift+S). Ensure there is some Windows content behind the screenshot, like below: 
4. 
![image](https://user-images.githubusercontent.com/9649518/117072773-d2429800-ace5-11eb-91b3-eca97371e0ab.png)

**WSL logs**: 

[pulseaudio.log](https://github.com/microsoft/wslg/files/6424033/pulseaudio.log)
[weston.zip](https://github.com/microsoft/wslg/files/6424094/weston.zip)

#  Expected behavior

Rider works as expected after taking a screenshot

# Actual behavior

Rider stops working and vmmem memory usage grows until my system runs out of memory

# Other Information

If i do a `wsl --shutdown` the issue goes away and i can restart my app, but this only works 1-2 times. After that, GUI apps no longer start and I have to reboot.

Edit:

My machine eventually crashed shortly after it got into this bad state. Whenever I tried to launch a GUI app, the vmmem process would just continue to grow, but nothing would happen.

Here's a link to the memory.dmp created by the green screen: https://microsoft-my.sharepoint-df.com/:u:/p/stevenki/EQw2dp52S7VFtHtuuGzIn90Bi8fFvop8h0dVgHdrIOEwag?e=6c2XoD

**Comment by stevenbrix** [comment]
Thanks @hideyukn88, how do i update?

**Comment by hideyukn88** [comment]
@stevenbrix , for external insider, usually Windows Update automatically updates it, otherwise you can try "wsl --update". But it might depend on how you first installed WSL and WSLg for internal-MS user. If you happen to install msi package manually, you might need to uninstall it from control panel first.

**Comment by stevenbrix** [comment]
Ok, i uninstalled the MSI version, ran `wsl --update` and this issue seems to be fixed. Thanks @hideyukn88!
