### ISSUE TITLE
X11 Windows tunneled via "ssh -X" show blank

### ISSUE THREAD

**Issue by pmsjt** [microsoft/wslg#163]
# Environment

```none
Windows build number: 21375.1000.arm64fre.co_release_base.210430-1922
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

1. Open WSL2 prompt
2. xclock
3. Observe xclock renders nicely
4. ssh -X [some linux machine]
5. xclock
6. Observe the window shows up but the content of the window is blank

![image](https://user-images.githubusercontent.com/40605312/117095959-b0b0d300-ad1c-11eb-80c8-623a21ab7e78.png)

[weston.log](https://github.com/microsoft/wslg/files/6425017/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/6425019/pulseaudio.log)

**Comment by spronovo** [comment]
Hi @pmsjt,  To confirm, you are doing ssh -X from a WSL console into a native Linux box correct? I just tried on one of my Pi (32bits - raspbian) and it worked correctly in my configuration. I see your target is arm64 (pi running ubuntu?)... your WSL system is x64?

**Comment by pmsjt** [comment]
Hi @spronovo .

That is correct. I am running "ssh -X" in the SWL2 prompt. I tried this from both x64 and arm64 machines. Same result.

**Comment by pmsjt** [comment]
Hello there.

This no longer reproes. Things seem to be working quite well now, so I am going to close this.

Cheers.
