### ISSUE TITLE
With touchpad, I cannot scroll horizontally.

### ISSUE THREAD

**Issue by SmartPolarBear** [microsoft/wslg#164]
# Environment
[Environment]::OSVersion:
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.21370.0 Microsoft Windows NT 10.0.21370.0
```
lsb_release -r (debian):
```
Release:        11
```
[pulseaudio.log](https://github.com/microsoft/wslg/files/6425661/pulseaudio.log)

WSLg version: 1.0.19

# Steps to reproduce

1. install Clion
2. Open enough tabs for scrolling, or run commands in the terminal , which produce long-enough output for both vertical and horizontal scroll.
3. scroll up and down with touch pad
4. scroll left and right with touch pad

#  Expected behavior

swipe up and down for vertically scrolling and left and right for horizontal scrolling

# Actual behavior
In CLion and some other apps, I can only scroll horizontally in all windows and dialogs. For the tabs, I only can scroll it by swipe up and down, rather than left and right as normal

Logs : [https://aka.ms/AAcei9s](https://aka.ms/AAcei9s)

**Comment by hideyukn88** [comment]
At RDP backend, it needs to map RDP's PTR_FLAGS_HWHEEL message to WL_POINTER_AXIS_HORIZONTAL_SCROLL.
