### ISSUE TITLE
touchpad settings doesn't honor left and right swap at Window's settings

### ISSUE THREAD

**Issue by andrewacashner** [microsoft/wslg#167]
In Windows I swapped the mouse buttons (I mouse with my left hand), but the touchpad still functions normally (one finger tap = main mouse button; two fingers = secondary).

In WSLg it interprets clicks on the trackpad backwards, so a two-finger click is equivalent to the main mouse button.

**Comment by hideyukn88** [comment]
@andrewacashner , this is tracked by https://github.com/microsoft/wslg/issues/74.

**Comment by spronovo** [comment]
@andrewacashner thanks for your suggestion. As Hideyuki mentioned above, we're currently tracking this one with #74, so i'll resolve this thread. The good news is that this is on our list of enhancement in the near future, so stay tune :-).
