### ISSUE TITLE
windows server 22 compatibility

### ISSUE THREAD

**Issue by Shadowplays4k** [microsoft/wslg#169]
wslg wont install on windows server 22 20334.1 because of checks in the installer.

my solution to this would be to let windows server users use wslg on this version of windows

I have considered just booting up a hyperv instance of the latest insider version of windows 10 just to use it but that defeats the purpose of using wsl

**Additional context**
so some people might find this strange but I use windows server 22 as my desktop os, I wont use windows 10.
I'm on build: windows server 22 20334.1 21H2
I would upgrade to the latest version except one big issue, you have removed the keys that you used to provide. this means I cant activate windows server on any new versions. 
now this wouldn't have been a problem if wslg worked on this version.

thanks.

**Comment by spronovo** [comment]
Hi @Shadowplays4k, WSL and WSLg are not supported on Server SKU. Further, WSLg rely on functionality (such as the infrastructure to load the system distro) that is only available in Cobalt+. You would probably get a better desktop experience by running a client version of Windows :-).
