### ISSUE TITLE
Not seeing in Windows Update - on dev channel and 21376

### ISSUE THREAD

**Issue by pcause** [microsoft/wslg#175]
Is there some issue with these updates getting pushed to the Windows update.  I am not seeing 1.0.19 or 12.0.20.  CAn you add a procedure to manually install the release files

**Comment by pcause** [comment]
Yes, know all that and did both and got no updates.  I then installed the wsl_graphics_suupport msi and now it tries to update but gets a fatal error from wsl --update

**Comment by spronovo** [comment]
1.0.19 should be automatically delivered to you by running ```wsl --update`` from an elevated command prompt. If you have manually installed an msi, could search in the start menu for "add or remove programs" and then uninstall ```Windows Subsystem for Linux WSLg Preview", than try ```wsl --shutdown``` and ```wsl --update``` again.

if 1.0.19 doesn't get delivered to you after this, could you try ```settings -> Update & Security ->Windows Update``` are there any update pending?

When you launch WSL, could you type the following and share the output.

```
cat /mnt/wslg/versions.txt
```

1.0.20 isn't being pushed out externally yet, it's only being pushed to our internal ring while we selfhost it and make sure we haven't regressed anything. If all goes well, it it will released to the external ring in the next few days. The msi for 1.0.20 is already visible on the github project... but that's more of a use at your own risk kind of thing and not a recommended path unless you really like living on the edge :-).

Could you share the fatal error from ```wsl --update``` you are now getting?

**Comment by pcause** [comment]
I already had things set up for wsl updates and they were working fine.  I uninstalled the mis and did an update

**Comment by pcause** [comment]
As was said above, 1.20.20 isn't really released to the general public.

**Comment by astroboylrx** [comment]
I see. Thanks a lot. For future reference, is there any way to distinguish whether a release is for internal only or a user is not getting the updates?

**Comment by pcause** [comment]
perhaps you can tag them as pre-release, which other do, and only push release to windows update.  add a note in the README.md
