### ISSUE TITLE
Vulkan development support...

### ISSUE THREAD

**Issue by wmarti** [microsoft/wslg#191]
**Is your feature request related to a problem? Please describe.**
Vulkan appears to not currently be supported with wslg. I much prefer unix-style development on Windows using VsCode and WSL, and really dislike being forced to use Visual Studio or switch to a native linux environment.

**Describe the solution you'd like**
Full Vulkan support for native-like development in wslg.

**Describe alternatives you've considered**
Moving to Linux, which I've decided to do for Vulkan development, as I personally dislike the native windows development style through Visual Studio.

**Comment by hideyukn88** [comment]
@wmarti , thanks for suggestion, is your requirement covered by https://github.com/microsoft/wslg/issues/40 ? thanks!

**Comment by wmarti** [comment]
As long as Vulkan Development would be supported!

**Comment by spronovo** [comment]
Thanks for your report. Closing this one as a duplicate of #40.
