### ISSUE TITLE
Question: What distro and what desktop recommends to WSLG

### ISSUE THREAD

**Issue by ferkorol** [microsoft/wslg#195]
Hi friends!

I have 3 questions: 
 * 1 -What of the availibles distro you recommend to use with wslg (ubuntu, kali, debian, etc)
 *  2- What desktop Environment kind work better (gnome apps, kde, etc)
 *  3- Wich protocol work better x11 or wayland?

Regards and congratulations for the great work!

**Comment by Maks1116** [comment]
Are you sure that this needs bug label?

**Comment by ferkorol** [comment]
Hi, I try to remove the "bug" label, but with my permissions i cant or i don't find where. I you or some other can change it, please remove.

**Comment by ferkorol** [comment]
Thanks for sharing this @onomatopellan!!!
