### ISSUE TITLE
wsl --update, Invalid command line option: --update

### ISSUE THREAD

**Issue by freddiemacd** [microsoft/wslg#205]
I am currently using Ubuntu-20.04 on Version 2. I have Windows 10 Home version 2004 OS build 19041.985 with experience pack 120.2212.2020.0

I would like to update WSL 2 so that I can used gui apps.

In Administrator Command Prompt, wsl --update give me the invalid command line option.

Do I need to update something else to make this update work?

**Comment by raprocks** [comment]
You need the preview dev build fo Windows, which is available to insider's. You cannot use the --update flag on regular installations
