### ISSUE TITLE
Terminal apps opened with Windows shortcuts will open themselves, creating an infinite loop

### ISSUE THREAD

**Issue by AlexAegis** [microsoft/wslg#206]
# Environment

```none
Windows build number:  Win32NT             10.0.21382.0 Microsoft Windows NT 10.0.21382.0 
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

Install a terminal app like `Konsole` and open it with the autogenerated windows shortcut from the start menu
![image](https://user-images.githubusercontent.com/16900547/118413666-c5885180-b6a0-11eb-957f-8e3c33c65a4f.png)

#  Expected behavior

Open the app, once.

# Actual behavior

The app opens, it prints the stdout that the shell that opened it should recieve, then the app opens again, and this repeats over and over again until I do `wsl --shutdown` in an elevated powershell instance.

![image](https://user-images.githubusercontent.com/16900547/118413792-5ceda480-b6a1-11eb-936b-a35fbdd0e280.png)

# Workaround

I use the windows terminal to open my WSL instance and start the program from there. In this case I can see the same output in Windows Terminal that I saw printed in `konsole` when opened from the start menu, for example:

![image](https://user-images.githubusercontent.com/16900547/118413764-36c80480-b6a1-11eb-9f01-b7e89420fc4b.png)

**Comment by hideyukn88** [comment]
@AlexAegis , thanks for report the issue. this issue has been reported at https://github.com/microsoft/wslg/issues/64, and the fix is on the way.
