### ISSUE TITLE
Fresh install of WSL fails to install WSLg

### ISSUE THREAD

**Issue by muddybulldog** [microsoft/wslg#208]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21354.1
Your Distribution version: NONE
Your WSLg version: NONE
```

# Steps to reproduce
Fresh Windows install. No existing WSL.
Run wsl --install -d Ubuntu

#  Expected behavior
Install Ubuntu with WSLgsupport

# Actual behavior
Install of WSLg fails as follows with Error Code: 0x80070643

Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: WSL Kernel
Installing: WSL Kernel
WSL Kernel has been installed.
Downloading: GUI App Support
Installing: GUI App Support
A error was encountered during installation, but installation may continue. Component: 'GUI App Support' Error Code: 0x80070643
Downloading: Ubuntu
The requested operation is successful. Changes will not be effective until the system is rebooted.

**Comment by bpulliam** [comment]
This is by design.  WSLg requires at least build 21362.  Update to a newer Insider build and then run 'wsl --update'.
