### ISSUE TITLE
Render process is slow

### ISSUE THREAD

**Issue by zapplelove** [microsoft/wslg#211]
I use pybullet to load and simulate my robot, but the render process is too slow.
```bash
 python -m buildCheetah.py
```
```bash
pybullet build time: Apr 25 2021 07:44:46
startThreads creating 1 threads.
starting thread 0
started thread 0
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=VMware, Inc.
GL_RENDERER=llvmpipe (LLVM 10.0.0, 256 bits)
GL_VERSION=3.3 (Core Profile) Mesa 20.0.8
GL_SHADING_LANGUAGE_VERSION=3.30
pthread_getconcurrency()=0
Version = 3.3 (Core Profile) Mesa 20.0.8
Vendor = VMware, Inc.
Renderer = llvmpipe (LLVM 10.0.0, 256 bits)
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0
MotionThreadFunc thread started
ven = VMware, Inc.
ven = VMware, Inc.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 546 requests (546 known processed) with 0 events remaining.
```
and I find the usage rate of my intel 630 GPU is very low and the gtx1050 seems not working. 

Any solution that can improve the render process?

**Comment by onomatopellan** [comment]
You have Mesa version 20.0.8. For some GPU acceleration you need at least Mesa v21.0. On Ubuntu you can instal it like this:
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt-get update
```

**Comment by zapplelove** [comment]
> I suppose you are running a Dev channel Windows Insider build and you have already installed WDDM3.0 drivers for your GPU.
> 
> You have Mesa version 20.0.8. For some GPU acceleration you need at least Mesa v21.0. On Ubuntu you can install it like this:
> 
> ```
> sudo add-apt-repository ppa:kisak/kisak-mesa
> sudo apt-get update
> ```

After doing that, the window cannot show up anymore.
![image](https://user-images.githubusercontent.com/18183148/118633127-b8d03e80-b803-11eb-9b5f-b9a7e370daaf.png)

![image](https://user-images.githubusercontent.com/18183148/118633170-c4236a00-b803-11eb-8d1a-822043887a60.png)

**Comment by onomatopellan** [comment]
Do `wsl.exe --shutdown` and launch WSl2 again.

**Comment by zapplelove** [comment]
thanks.  after the reboot of the windows, this problem has been solved.
