### ISSUE TITLE
Support App Taskbar Pinning

### ISSUE THREAD

**Issue by DeadlySurgeon** [microsoft/wslg#229]
It would be cool if tiles could be pinned, so I don't have to go to the start menu every time I wanted to launch an application.

**Comment by crramirez** [comment]
But if you right-click the start menu shortcut, you can't add it to the taskbar?

**Comment by DeadlySurgeon** [comment]
@crramirez 

It's been quite a while since I've used Windows, but yeah it looks like I can pin it from the start menu. After it's pinned though, whenever I open it, it's under a new tile.

![image](https://user-images.githubusercontent.com/60354262/119494242-b485b300-bd26-11eb-8179-ae4d883a4457.png)

**Comment by DeadlySurgeon** [comment]
Closing since it's already a thing, and I'm just not used to Windows anymore.

**Comment by seflerZ** [comment]
Why is thread being closed?

**Comment by crramirez** [comment]
Because the app shortcuts created by wslg can be pinned to the taskbar. And this is exactly the requirement.

**Comment by seflerZ** [comment]
> Because the app shortcuts created by wslg can be pinned to the taskbar. And this is exactly the requirement.

I konw, but it behaves not as expected as @DeadlySurgeon suggested: whenever I open it, it's under a new tile. It's a bit weird and different from native Windows apps. We want same eperience.

**Comment by crramirez** [comment]
I suggest then creating a new issue with this behavior, with the right title. 

This happens also with Windows created by XServer. The thing is that there is no link between the tile and the created Window. I assume that this is very difficult to achieve and it will need a lot of votes.

Regards,
Carlos

**Comment by seflerZ** [comment]
> I suggest then creating a new issue with this behavior, with the right title.
> 
> This happens also with Windows created by XServer. The thing is that there is no link between the tile and the created Window. I assume that this is very difficult to achieve and it will need a lot of votes.
> 
> Regards, Carlos

Okay, thanks.
