### ISSUE TITLE
Can't copy/paste Chinese text

### ISSUE THREAD

**Issue by acooler15** [microsoft/wslg#233]
# Environment

```none
Windows build number: 10.0.21387.0
Your Distribution version: 20.04
Your WSLg version: 1.0.22
```

# Steps to reproduce
Paste Chinese text copied from WSL or paste Chinese text into WSL

[weston.log](https://github.com/microsoft/wslg/files/6532055/weston.log)

#  Expected behavior

# Actual behavior

![Snipaste_2021-05-24_19-48-45](https://user-images.githubusercontent.com/19186382/119343500-1ca5ac00-bcc9-11eb-83d5-e7d367ee0173.png)
Windows already uses UTF-8:
![windows](https://user-images.githubusercontent.com/19186382/119343856-8faf2280-bcc9-11eb-98c3-7a44d142fea7.png)
![cmd](https://user-images.githubusercontent.com/19186382/119344226-ff251200-bcc9-11eb-9c73-f0a81d336729.png)

wsl locale:
![wsl_lang](https://user-images.githubusercontent.com/19186382/119344111-d56beb00-bcc9-11eb-83e6-b42e407d3780.png)

**Comment by hideyukn88** [comment]
@acooler15 , thanks for reporting, this issue is tracked by https://github.com/microsoft/wslg/issues/20. thanks!
