### ISSUE TITLE
WSLG display just won't work

### ISSUE THREAD

**Issue by boehs** [microsoft/wslg#238]
# Environment

```none
Windows build number:  Win32NT 10.0.21387.0 Microsoft Windows NT 10.0.21387.0
Your Distribution version: Release: 20.04
Your WSLg version: 1.0.22
```

# Steps to reproduce

https://pastie.io/catxld.txt

I reinstalled ubuntu, and did everything in that command snippet 

* Attach WSLg logs from  `/mnt/wslg`

* [`puseaudio.log`](https://pastie.io/qnckjf.sql)
* [`weston.log`](https://pastie.io/kvkavr.txt)
* [`versions.txt`](https://pastie.io/wxbrdf.txt)

#  Expected behavior

I am expecting xcalc to open

# Actual behavior

Error: Can't open display:  :0

**Comment by boehs** [comment]
Oops, seems it added the bug label, not sure how to remove it from here. Its surely something I am doing wrong, but after 3 hours work on this I must go to bed

**Comment by discotroll65** [comment]
@boehs I've spent a lot of today trying to get things to work with wslg as well, and it could be that you're just not waiting long enough. Here's what I did:

1.) Upgraded to wslg by running running `>  wsl --update`  from an elevated windows prompt,  

2.) ran `$ time gedit .gitignore` in my 18.04 Ubuntu , immediately closing the window after it appeared to get the statistics from the bash `time`  command

it took me 6 minutes!  definitely too long to use practically. Not sure if it's because I usally use X410 as an xserver on this wsl2 ubuntu distro, hopefully this gets fixed to open faster soon!  Exciting progress but still a ways to go

**Comment by crramirez** [comment]
Hello @discotroll65 ,

If you use X410 with this distro it probably is overriding the DISPLAY variable. Be sure that the value of DISPLAY is :0

These 6 minutes looks like a firewall issue so check this variable.

Regards,
Carlos

**Comment by onomatopellan** [comment]
>Sleeping for 1 second to let systemd settle

If you want to see WSLg working you need first to get rid of any systemd trick you are using.

**Comment by boehs** [comment]
> > Sleeping for 1 second to let systemd settle
> 
> If you want to see WSLg working you need first to get rid of any systemd trick you are using.
> 
> Temporal solution is running this every time you want to use WSLg:
> 
> ```
> export DISPLAY=:0
> sudo rm -rf /tmp/.X11-unix
> ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
> ```

This is vanilla ubuntu to as far as I am aware, I ran `sudo apt update` and installed the x11 apps.

**Comment by boehs** [comment]
> whats your wddm version? you might need to update your graphics driver. pretty sure you need wddm 3.0.. oddly enough as it is, my wddm says its 2.7, but actually it is 3.0 compatible, i guess AMD was in a rush making the driver just work and didnt change version numbers properly.

Thank you, I will be checking for updates!

**Comment by onomatopellan** [comment]
> This is vanilla ubuntu to as far as I am aware, I ran `sudo apt update` and installed the x11 apps.

"Sleeping for 1 second to let systemd settle" is not a message from a vanilla ubuntu. That's something you see after installing a systemd script like https://github.com/DamionGans/ubuntu-wsl2-systemd-script.

> Edit: and what is a permanent solution?

If you are not interested in systemd then try to update the kernel with `wsl.exe --update` first.

**Comment by boehs** [comment]
> > This is vanilla ubuntu to as far as I am aware, I ran `sudo apt update` and installed the x11 apps.
> 
> "Sleeping for 1 second to let systemd settle" is not a message from a vanilla ubuntu. That's something you see after installing a systemd script like https://github.com/DamionGans/ubuntu-wsl2-systemd-script.
> 
> > Edit: and what is a permanent solution?
> 
> If you are not interested in systemd then try to update the kernel with `wsl.exe --update` first.

I have no idea then. I will try updating and reinstalling ubuntu

**Comment by boehs** [comment]
1. Pull up Spotify, gonna be a bit of work ahead of me
2. Update NVIDIA drivers to the latest (457.3 -> 466.47) using express settings
3. Uninstall ubuntu (right-click, uninstall)
4. Run `wsl --install -d Ubuntu`
5. Awesome! booted in
6. `sudo apt update`
7. `sudo apt install x11-apps`
8. Woah, it works!
9. I think it was the drivers because I tried 3 fresh installs, so thanks to @jamesfranklinnetsec and everyone else who helped. Hopefully, this thread can help people who also need to troubleshoot!

**Comment by discotroll65** [comment]
> Hello @discotroll65 ,
> 
> If you use X410 with this distro it probably is overriding the DISPLAY variable. Be sure that the value of DISPLAY is :0
> 
> These 6 minutes looks like a firewall issue so check this variable.
> 
> Regards,
> Carlos

@crramirez  , thanks so much for the tip! That was it -- setting the display variable to manually to `$ DISPLAY=:0` fixed the issue for me!
