### ISSUE TITLE
How to show ros rviz in docker

### ISSUE THREAD

**Issue by xixioba** [microsoft/wslg#239]
I can display apps in WSLg normally, but I want to use ros **rviz** in docker. 
It will prompt ```QXcbConnection: could not connect to display```, 
how should I set it

**Comment by onomatopellan** [comment]
You need to pass the env variables and volumes you need to Docker. If it uses X11 you would need something like this:

`docker run --gpus all -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ...etc`

**Comment by xixioba** [comment]
@onomatopellan 
I use the following command:
```nvidia-docker run  --gpus all -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  ...```
and run ```roscore & , rosrun rviz rviz``` in the container, It returns:
```
QXcbConnection: Could not connect to display
Aborted
```
then, I run
```nvidia-docker run  --gpus all -e DISPLAY -e WAYLAND_DISPLAY -e XDG_RUNTIME_DIR -e PULSE_SERVER -v /tmp/.X11-unix:/tmp/.X11-unix -v /mnt/wslg:/mnt/wslg ...```
But still get the above error, in my understanding, I seem to need to use xhost, but I don't know how to use it, do you have better suggestions
By the way, I can run rviz directly in WSL2, but my requirement is to run rviz in wsl2 + docker

**Comment by onomatopellan** [comment]
I tried and it works for me. xhost should show this from inside the container
```
$ xhost
access control disabled, clients can connect from any host
SI:localuser:wslg
```

I recommend to get into the container (`docker run -it ...`) and try something like glxgears first. Once you get that one running rviz will work too.

**Comment by xixioba** [comment]
Thank you very much. I just need to execute **xhost** in the container, and then I can run the software I need normally.
