### ISSUE TITLE
Firefox with Wayland does not work properly

### ISSUE THREAD

**Issue by letrhee** [microsoft/wslg#245]
# Environment

```none
Windows build number: 10.0.21387.0
Your Distribution version: 20.04
Your WSLg version: 1.0.22
```

# Steps to reproduce

- Install firefox
- Run firefox with wayland 
`MOZ_ENABLE_WAYLAND=1 firefox`

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`
  * [versions.txt](https://github.com/microsoft/wslg/files/6545390/versions.txt)
  * [weston.log](https://github.com/microsoft/wslg/files/6545391/weston.log)
  * [pulseaudio.log](https://github.com/microsoft/wslg/files/6545392/pulseaudio.log)

#  Expected behavior

Firefox that works normally

# Actual behavior

Firefox does not appear to freeze, but the screen does not appear normally

**Comment by onomatopellan** [comment]
If you are seeing artifacts that also happened to me with firefox installed via apt. Try a [nightly build](https://www.mozilla.org/en-US/firefox/channel/desktop/) and the experience will be much better.

**Comment by hideyukn88** [comment]
@letrhee , thanks for reporting, but I believe this is not WSLg issue, so I will close this at this point, thanks!

**Comment by letrhee** [comment]
I didn't know that firefox's wayland support was still in development. Thank you. 
https://bugzilla.mozilla.org/show_bug.cgi?id=wayland
