### ISSUE TITLE
Taking a screenshot of an app using 3D acceleration will cause the window to hang

### ISSUE THREAD

**Issue by diddledan** [microsoft/wslg#25]
# Environment

```none
Windows build number: 10.0.21364.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

1. Install Ubuntu
2. run `apt install -y mesa-utils`
2. execute `glxgears`
3. press <kbd>win</kbd>+<kbd>shift</kbd>+<kbd>s</kbd> to open the snipping tool overlay
4. choose "Window" from the toolbar at the top of your display
5. select the `glxgears` window (with the 3-dimensional view of rotating gears, **not** the terminal) to take a screenshot
6. Observe that the window hangs and cannot be closed and vmmem uses up all ram available to it (on my system with 32GB of ram vmmem balloons to using ~16GB)

**WSL logs**: 

* [`puseaudio.log`](https://github.com/microsoft/wslg/files/6354498/pulseaudio.log)
* [`weston.log`](https://github.com/microsoft/wslg/files/6354507/weston.log)
* [`versions.txt`](https://github.com/microsoft/wslg/files/6354500/versions.txt)

#  Expected behavior

The app should continue functioning and not hang the entire WSL GUI

# Actual behavior

The WSL GUI hangs and weston spins it's wheels with the following line added to `weston.log` repeatedly until out of tmpfs space:

```plain
[00:36:33.391] RDP clipboard_data_source_write: write failed (Resource temporarily unavailable)
```

**Comment by hideyukn88** [comment]
@diddledan , By looking at your build tag in weston.log and version.txt, it looks you are not using the latest release of WSLg, please update.

**Comment by diddledan** [comment]
Yes, you're quite right. Somehow I had an older version installed. I've manually uninstalled that and installed the 1.0.17.1 downloaded from the tag here on GitHub and everything is good :-) (closing the issue because it's invalid)
