### ISSUE TITLE
Qt program cannot run

### ISSUE THREAD

**Issue by neko-para** [microsoft/wslg#255]
# Environment

```none
Windows build number: 10.0.21390.0
Your Distribution version: Ubuntu 18.04 (Changed from WSL1)
Your WSLg version: 1.0.22
```

# Steps to reproduce

* launch `cmake-gui`

#  Expected behavior

* popup a window

# Actual behavior

* aborted
```none
 ✘ nekosu@LAPTOP-ID30VPC5  /mnt/c/Users/liaoh  cmake-gui
qt.qpa.xcb: could not connect to display 127.0.0.1:0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

[1]    161 abort      cmake-gui
```
* The output is almost the same as that when X server is closed

# Remarks

* The nautilus can open properly
```none
 nekosu@LAPTOP-ID30VPC5  /mnt/c/Users/liaoh  nautilus

(nautilus:133): dbind-WARNING **: 11:28:30.125: Could not open X display
```
* Although it says cannt open, it works fine.
```none
nekosu@LAPTOP-ID30VPC5  /mnt/c/Users/liaoh  echo $DISPLAY
127.0.0.1:0
```

**Comment by neko-para** [comment]
cmake version 3.20.3
build from sources, with `./bootstrap --prefix=/opt/cmake --qt-gui`
qt: 5.15.0 installed from binary
g++: 7.5.0 from http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu

I'm not sure if message above matters.

**Comment by neko-para** [comment]
The problem is that shell init DISPLAY to `127.0.0.1:0`(for old use). After changed to `:0`, everything works fine. That's all my fault.

**Comment by AddictArts** [comment]
> The problem is that shell init DISPLAY to `127.0.0.1:0`(for old use). After changed to `:0`, everything works fine. That's all my fault.

This exactly, change your exported DISPLAY to ":0". Check .bashrc and .profile if bash, zsh, fish, do similar.
