### ISSUE TITLE
Ubuntu won't start if Windows Terminal Preview is default terminal application

### ISSUE THREAD

**Issue by rye2020** [microsoft/wslg#256]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Platform ServicePack Version      VersionString                    
-------- ----------- -------      -------------                    
 Win32NT             10.0.21390.0 Microsoft Windows NT 10.0.21390.0

Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Ubuntu Release:        20.04
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
Windows Subsystem for Linux WSLg Preview 1.0.22

```

# Steps to reproduce
If Windows Terminal Preview is set as the default terminal application, Ubuntu will not start from Start Menu.  Ubuntu error message is invalid parameter.  However, Xfce Terminal will start.  

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by sabbyX** [comment]
possibly related to microsoft/terminal#10134

**Comment by hideyukn88** [comment]
@rye2020 , thanks for reporting the issue, I confirmed with Windows Terminal team this is tracked by https://github.com/microsoft/terminal/issues/10134. thanks!
