### ISSUE TITLE
WSLg

### ISSUE THREAD

**Issue by rye2020** [microsoft/wslg#26]
Apps start lightening fast Windows start menu, but from Ubuntu command line will only start intermittently:  gedit has only started for me a few times.

**Comment by spronovo** [comment]
@rye2020 Do you only see this with gedit or with other GUI applications as well? When gedit doesn't start, is there some error printed on the console? Or does it just hang?

**Comment by ethteck** [comment]
For me, I can't open any applications on the command line, but I can consistently open them from the start menu. Is there any debug information I can provide to assist with this?

**Comment by ethteck** [comment]
Actually, gedit did in fact open after multiple minutes of waiting, and I got this output on the command line
```
me@COMPUTER:~$ gedit

(gedit:34): dconf-WARNING **: 20:17:23.893: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=86154144798f4fb884bbbfe781c43f7f --binary-syntax --close-stderr”: Child process exited with code 1

(gedit:34): dconf-WARNING **: 20:17:23.898: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=86154144798f4fb884bbbfe781c43f7f --binary-syntax --close-stderr”: Child process exited with code 1

(gedit:34): dconf-WARNING **: 20:19:56.878: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=86154144798f4fb884bbbfe781c43f7f --binary-syntax --close-stderr”: Child process exited with code 1
```

**Comment by crramirez** [comment]
I think that something is changing you the DISPLAY environment variable, maybe a previous configuration for X Server? Issue an `echo $DISPLAY` it should output `:0`. If you see anything else look into your .bashrc or /etc/profile.d looking for a script that is setting the variable

**Comment by rye2020** [comment]
It just hangs.  No error message.  'ps aux' shows it is running.  same
result with xcalc and xfe.  xcalc and xfe eventually show an error
message: "Error: Can't open display: 172.24.144.1:0.0" and
"FXApp::openDisplay: unable to open display 172.24.144.1:0.0".

**Comment by rye2020** [comment]
with gedit, if I wait long enough, it will sometimes start, but even
though a window is opened, it may be unresponsive.  other times it will
actually work just fine. gedit seems to respond differently from xfe or
xcalc or xterm.

**Comment by rye2020** [comment]
with gedit, if I wait long enough, it will sometimes start, but even
though a window is opened, it may be unresponsive.  other times it will
actually work just fine. gedit seems to respond differently from xfe or
xcalc or xterm.

**Comment by rye2020** [comment]
When gedit does start, there will be many error messages on terminal:

**Comment by rye2020** [comment]
You are exactly right.  There was the following line in my .bashrc
file:
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print
$2}'):0.0
with removal of that line, gedit, xfe and xcalc start just fine.
Thank you.

**Comment by ethteck** [comment]
Thanks - I had the exact same issue! All set :)
