### ISSUE TITLE
I think install method is no working if you change the default command prompt to Windows Terminal Preview.

### ISSUE THREAD

**Issue by prabhumns** [microsoft/wslg#265]
# Environment

```none
Windows build number: Dev channel 21390.1
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.22 ---- This is the version of Windows Subsystem for Linux WSLg Preview
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by hideyukn88** [comment]
@prabhumns , thanks for reporting the issues, would you please describe the issue a bit more, what are you trying to install ? Btw, there is known issues with WSL and Windows Terminal Preview, which is tracked by https://github.com/microsoft/terminal/issues/10134. Could this be same issue ? thanks!

**Comment by hideyukn88** [comment]
Due to luck of response from user, and this is very likely dup of https://github.com/microsoft/terminal/issues/10134, closing this issue.
