### ISSUE TITLE
Unable to Unregister Ubuntu

### ISSUE THREAD

**Issue by XzeroR3** [microsoft/wslg#267]
# Environment

```none


PS C:\WINDOWS\system32> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.21390.0 Microsoft Windows NT 10.0.21390.0

Apps & Features:
Windows Subsystem for Linux WSLg Preview 1.0.22

```

# Steps to reproduce

```
PS C:\WINDOWS\system32> wsl --shutdown
PS C:\WINDOWS\system32> wsl --list -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
PS C:\WINDOWS\system32> wsl --unregister -d Ubuntu
Unregistering...
There is no distribution with the supplied name.


```
Notes: 
I shutdown this VM during the linux user creation process. 
This is a VM with the ExposeVirtualizationExtensions set to $true.  

**WSL logs**: 

* `puseaudio.log`
* `weston.log`
* `versions.txt`

Diagnostic logs and the above logs are attached to feedback hub issue. 

#  Expected behavior

Expecting to uninstall Ubuntu

# Actual behavior

Unable to uninstall Ubuntu

# Workaround

I was able to uninstall Ubuntu via Apps and Features and reinstall Ubuntu via:
wsl --install -d Ubuntu

**Comment by benhillis** [comment]
-d is not needed.  The command is wsl --unregister Ubuntu.

**Comment by XzeroR3** [comment]
🤦 Ugh, sorry, didn't see the -d is not needed
