### ISSUE TITLE
cairo-dock doesn't position correctly in Wayland mode (app bug?)

### ISSUE THREAD

**Issue by pcause** [microsoft/wslg#268]
# Environment

```none
Windows build number:21390
Your Distribution version: fedora 34
Your WSLg version:1.0.22
```

# Steps to reproduce

launch cairo dock from bash in windows terminal

#  Expected behavior

expect the dock tyo launch on the bottom of the screen.  Instead launched about 1/3 down from top.  Truied various cairo setting and no effect

**Comment by hideyukn88** [comment]
@pcause, thanks for reporting the issue. I think this is not WSLg issue but the issue in cairo-dock in Wayland mode. In WSLg, as Wayland compositor, cairo-dock run in Wayland mode. In order to force cairo-dock in X11 mode, please do "export GDK_BACKEND=x11" first, then launch cairo-dock. then it shows up at bottom of desktop screen. (you might need to hide or move to Windows's taskbar to other location as it's overlap with cairo-dock). thanks for trying out WSLg!

**Comment by pcause** [comment]
tried that an doesn't work.  also tried with plank and similar issues.

**Comment by hideyukn88** [comment]
@pcause, have you built WSLg from source code? otherwise please try again when WSLg 1.0.23 is released. This release has some fix for X11 application to position their window, thanks!

**Comment by pcause** [comment]
no, using insider dev builds.  will update when I get the 1.0.23 update.

**Comment by pcause** [comment]
now on 1.0.24 and no change.  i delete the .config/cairo-dock and the dock appears in different places on each launch. can' be moved.  if i run from a terminal I can see some messages about no parent window.

**Comment by hideyukn88** [comment]
@pcause, thanks for update, just to double check do you run cairo-dock in X11 mode?

**Comment by pcause** [comment]
i manually export XDG_SESSION_TYPE=wayland and same behavior.  Likely since no sddm and normal startup, lots of other stuff that is needed isn't set/there.

**Comment by hideyukn88** [comment]
@pcause, can you try export GDK_BACKEND=x11? thanks!

**Comment by pcause** [comment]
that fixed it.

**Comment by pcause** [comment]
on win11 / wslg and this happens again.  with the previous suggestions cairo-dock was at bottom of the screen.  in win11 more toward center of the screen.  same for latte-dock

**Comment by onomatopellan** [comment]
@pcause from elevated cmd run `wsl.exe --update` to make sure you have the latest version installed

**Comment by pcause** [comment]
I had done that before launching Windows Terminal/WSL2.  Just did again and no updates.  Also did right after the upgrade to Win11

**Comment by onomatopellan** [comment]
I'm in Windows11 and running `GDK_BACKEND=x11 cairo-dock` it appears at the bottom center. (I had to hide the window taskbar though)

If it doesn't work yet for you then look for Display Scale in Settings if it's the same as earlier. Maybe the Windows 11 upgrade did change something, even the video driver.

**Comment by pcause** [comment]
I have GTK_BACKEND=x11 set.  Monitor is 2k x 1k, scale is 100%.  I had no custom settings for the monitor in Win10.

**Comment by pcause** [comment]
I have both GTK_BACKEND and QT_QPA_PLATFORM set in my environment.  When I lauch with:

GTK_BACKEND=x11 cairo-dock

it works better but I have dock at top (to avoid the taksbar issue) and isn't flush to top of screen.

**Comment by onomatopellan** [comment]
Beware it's `GDK_BACKEND=x11` not GTK

**Comment by pcause** [comment]
I have both GTK_BACKEND and QT_QPA_PLATFORM set in my environment.  When I lauch with:

GTK_BACKEND=x11 cairo-dock

it works better but I have dock at top (to avoid the taksbar issue) and isn't flush to top of screen.

**Comment by pcause** [comment]
Fixed that and made it GDK_BACKEND and now aligned correctly and seems to be working
