### ISSUE TITLE
[not a bug] Star count?

### ISSUE THREAD

**Issue by bl-ue** [microsoft/wslg#28]
(This is not a bug—I just couldn't find a good issue template.)

Could anyone give me a hint as to why this repo is getting so many stars? Almost every time I reload the page, it has new stars.  It had only 100 stars about 4 or 5 hours ago when I starred it 🤔 

I can see that it's a cool product and lots of people like it.  But—that's all?

How do people know about it so soon?  This repo was created (or made public, or whatever) 2 days ago, and it's getting quite popular 🔥 

(Sorry if this is a dumb question, I'm just confused+curious :)

**Comment by spronovo** [comment]
@bl-ue this is a new WSL feature which we had disclosed a little while back, but is available publicly for the first time as part of the Windows Insider program. Today was launch day, and we made the source code available... i guess lots of folks wanted to take a peek which generated traffic through this project :-).

You can catch our announcement on the blog below:

https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/

**Comment by bl-ue** [comment]
Ah I see, that's what I was looking for. Well, it is definitely cool, and I can see why it popular.   I was just wondering if I missed something.  Thank you!
