### ISSUE TITLE
Set scaling for HiDPI screens

### ISSUE THREAD

**Issue by LoNicoM** [microsoft/wslg#284]
Currently the WSLg uses the scale factor set in windows, this causes blocky looking text.

I would rather have the graphics scaled on the linux side, so i can use HiDPI modes in linux apps.

It would be better if the scaling factor was set to 100% as default, but would be nice to be able to set it in .wslconfig

**Comment by hideyukn88** [comment]
@LoNicoM, thanks for trying out WSLg, that can be done by having below file (note: it's .wsl**g**config, not .wslconfig, and it's different location for now) with below contents, then scaling by Windows side will be disabled, thanks!

/mnt/c/ProgramData/Microsoft/WSL/.wslgconfig

[system-distro-env]
WESTON_RDP_DISABLE_HI_DPI_SCALING=true
