### ISSUE TITLE
Can't close window by Alt+F4

### ISSUE THREAD

**Issue by speller** [microsoft/wslg#293]
# Environment

```none
Windows build number: 21390.1010
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.22
```

I can't close WSL GUI apps by Alt + F4.

**Comment by hideyukn88** [comment]
@speller, thanks for reporting the issue, this is dup to https://github.com/microsoft/wslg/issues/187. Thanks for trying out WSLg.

**Comment by hideyukn88** [comment]
@wyjBot, thanks for inquiring the status. To enable this behavior is trivial change, but I wonder if this key combination is used for different purposes on Linux side applications, so hijacking the key combination might not be ideal, but it can be updated to only optionally enabled by .wslgconfig, thanks!

**Comment by homerobse** [comment]
Hi, I couldn't find the .wslgconfig. Could you tell me where it is and what changes should be made there? Thank you.
