### ISSUE TITLE
Add support for Windows clipboard shortcuts

### ISSUE THREAD

**Issue by speller** [microsoft/wslg#295]
As a Windows, user I want to have standard Windows clipboard shortcuts to work in WSL GUI apps.

**Comment by hideyukn88** [comment]
@speller, thanks for requesting a feature, but I don't think this is possible since clipboard functionality is implemented in Linux application itself and that's not where WSLg can control. Btw, isn't keyboard shortcut on many of Linux GUI application same as Windows? such as CTRL+C/V/X? Thanks!

**Comment by speller** [comment]
@hideyukn88 The default shortcuts are not working. I launched programs under VcXsrv under the same WSL distribution and they work well. So I assume the issue is in WSLg on the Linux or Windows side.

**Comment by hideyukn88** [comment]
@speller, would you please tell us what applications do you have this problem? thanks!

**Comment by akheron98** [comment]
Clipboard (Copy/Paste) was working when I used VcXsrv Windows X Server.  But now with WSLg, it doesn't work anymore.   

Copying text from a website in Chrome (Windows side), can't paste in a WSL Window like gedit.  It doesn't share the same clipboard.

**Comment by hideyukn88** [comment]
Closing this as dup of https://github.com/microsoft/wslg/issues/15.
