### ISSUE TITLE
[Help wanted] How to scale the apps?

### ISSUE THREAD

**Issue by PhyX-Meow** [microsoft/wslg#30]
I have an 2560x1440 screen, and have these in my .zshrc
```
export QT_SCALE_FACTOR=2
export GDK_SCALE=2
```
But some apps still look small. Eg. mousepad. How can I make them scale?

My distro is Manjaro, with xfce4 installed.

**Comment by PhyX-Meow** [comment]
By the way, is there any way to disable WSLg temporarily and so I can use back to x410.

**Comment by spronovo** [comment]
@PhyX-Meow you can use the following entry in your .wslconfig file (e.g. c:\Users\spronovo\.wslconfig) to disable guiApplications entirely. 

```
[wsl2]
guiApplications=false
```

You'll then need to restart WSL for the changes to take effect (wsl --shutdown from an elevated command prompt or powershell on Windows).

Did you try using scaling on the Windows side (settings -> System -> Display)... this will scale your Linux application as well, although at the moment WSLg only support integer scale (100%, 200%, fractional scaling like 150% is currently disabled by default.)

![image](https://user-images.githubusercontent.com/7545376/115674902-f9bb5d00-a302-11eb-8bd2-4e85882aed0b.png)

**Comment by PhyX-Meow** [comment]
Thanks, I set 150% in windows scale, so that's why my wsl app looks still small.
I would disable it at least for now, 200% is too big for my screen.

**Comment by hideyukn88** [comment]
@PhyX-Meow , if you want to try out fractional scaling (such as 150%), please refer https://github.com/microsoft/wslg/issues/23. And in case you don't want WSLg to auto scale, but prefer to let framework (such as Qt or GDK) to scale, then you can set WESTON_RDP_DISABLE_HI_DPI_SCALING=true in .wslgconfig.

**Comment by PhyX-Meow** [comment]
@hideyukn88 Thanks very much for your advise, I will try it.
