### ISSUE TITLE
Gnome GUI linux application are not registered to start menu due to "OnlyShowIn" in .desktop file

### ISSUE THREAD

**Issue by Elicetian** [microsoft/wslg#305]
### Windows Build Number

Microsoft Windows [version 10.0.21390.2025]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Nautilus 3.36.3-stable
gnome-terminal 3.36.2
gedit 3.36.2

### Repro Steps

Open any Linux app, right-click on it in the taskbar, the only option showing is "Close the window"

### Expected Behavior

When right clicking on a Linux GUI application I should be able to select options add to start menu or pin to taskbar

### Actual Behavior

When right clicking on a Linux GUI application no option is displayed but 'Close the window'

**Comment by hideyukn88** [comment]
@Elicetian, thanks for reporting the issue. Regarding to Pin to taskbar, does https://github.com/microsoft/wslg/issues/229 help ? thanks!

**Comment by Elicetian** [comment]
I can pin apps from the Start menu, but all the apps I have installed are not showing in the Ubuntu group.
Is there a way to make them appear there?

**Comment by hideyukn88** [comment]
Right, not every application will be registered in start menu, there is several cases ...
- .desktop file must be installed global location, /usr/share/applications, **not** ~/.local/share/applications.
- .desktop file must not have "Terminal" or "NoDisplay" set. https://github.com/microsoft/wslg/issues/4
- .desktop file must not have "OnlyShowIn" used. https://github.com/microsoft/wslg/issues/202
And many of gnome applications have "OnlyShowIn=GNOME", this is the reason it won't be registered to start menu by default. We plan to work with distro maintainer to come up with some solution for this. thanks!

**Comment by Elicetian** [comment]
Thank you, I will try that.
