### ISSUE TITLE
Connect MPD to the pulseaudio server running on WSLg

### ISSUE THREAD

**Issue by ertwro** [microsoft/wslg#306]
In the past I used to connect to the pulseaudio daemon running on windows by setting the bind adress in sound applications like MPD to ```localhost```. Now I can't find a way to connect to the pulse audio server already running on WSLg.

The pulse audio daemon I used to use had this option.
```
load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
```

**Comment by ertwro** [comment]
found that you can export ```/wslg/PulseAudioRDPSink``` as the audio output source

**Comment by dunn** [comment]
For anyone else coming to this, with WSLG running on Windows 11, the change to the `audio_output` block is `server "/mnt/wslg/PulseServer"`

**Comment by rokups** [comment]
Hey @dunn where is that setting supposed to be changed? I cant find anything like it in `/etc/pulse/default.pa`.

**Comment by dunn** [comment]
oh that was for the mpd configuration
