### ISSUE TITLE
accessibility for visualy impired users?

### ISSUE THREAD

**Issue by mjonsson1986** [microsoft/wslg#315]
**Is your feature request related to a problem? Please describe.**
what about accessibility? e.g screen readers
**Describe the solution you'd like**
maybe support for the orca screen reader?
**Describe alternatives you've considered**

**Additional context**

**Comment by hideyukn88** [comment]
@mjonsson1986, we verified Orca screen reader work with WSLg. I believe @craigloewen-msft had demo or blog for that. Thanks!

**Comment by mjonsson1986** [comment]
if orca works. can you tell me how to activate it?
i know how to do it in normal linux



Den 21 juni 2021 01:36:00 skrev Hideyuki Nagase ***@***.***>:

**Comment by hideyukn88** [comment]
@mjonsson1986, you might reference https://github.com/microsoft/wslg/issues/100. We are still looking that possible audio issues though. thanks!
