### ISSUE TITLE
wslg crashed when I want to take a screen shot and window flashed for a while

### ISSUE THREAD

**Issue by WhenMelancholy** [microsoft/wslg#319]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21390.2025]
Your Distribution version: Release:        20.04
Your WSLg version: 1.0.22
```

# Steps to reproduce

1. `display xxx.ppm`
2. take a screen shot by a third-party software (such as,QQ)
3. the imagemagick crashed, and the window flashed for a moment (I can see the background of windows terminal become transparent and not transparent, and I will lose the focus when I type if the window flashed)

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`
[pulseaudio.log](https://github.com/microsoft/wslg/files/6695370/pulseaudio.log)
[versions.txt](https://github.com/microsoft/wslg/files/6695371/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/6695372/weston.log)

#  Expected behavior

![image](https://user-images.githubusercontent.com/21274779/122948445-7fb05e80-d3ad-11eb-88b6-d0e3d8bd5f23.png)

I used imagemagick to display this window and I want to take a screenshot.
# Actual behavior

I took the screenshot and found wslg crashed.

**Comment by onomatopellan** [comment]
> Your WSLg version: 1.0.22

It could have been fixed already so try installing latest WSLg version 1.0.24 from https://github.com/microsoft/wslg/releases/download/v1.0.24/wsl_graphics_support_x64.msi

**Comment by WhenMelancholy** [comment]
I installed the latest version and it still crashed.

```
when@When:/mnt/e/project/C/opengl/smallpt$ display image.ppm
X connection to :0 broken (explicit kill or server shutdown).
```

**Comment by hideyukn88** [comment]
@WhenMelancholy, do you see any core dumps at /mnt/wslg/dumps? thanks!

**Comment by WhenMelancholy** [comment]
> @WhenMelancholy, do you see any core dumps at /mnt/wslg/dumps? thanks!

[core.weston.zip](https://github.com/microsoft/wslg/files/6724263/core.weston.zip)

**Comment by hideyukn88** [comment]
@WhenMelancholy, thank you for core dumps, but due to our side of issue, we haven't enabled debug info in past release of WSLg, would you please collect dump again with WSLg 1.0.26 at https://github.com/microsoft/wslg/releases/tag/v1.0.26 ? thanks you very much for trying out WSLg!

**Comment by WhenMelancholy** [comment]
> @WhenMelancholy, do you see any core dumps at /mnt/wslg/dumps? thanks!

[new-core-weston.zip](https://github.com/microsoft/wslg/files/6866232/new-core-weston.zip)

By the way, I found my issue was the same as #348 , since I was using QQ to take screenshot.
