### ISSUE TITLE
X-11 problem

### ISSUE THREAD

**Issue by bayvista170** [microsoft/wslg#320]
david@DESKTOP-U5S2IHE:~$ sudo apt install x-11 apps -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package x-11
E: Unable to locate package apps

**Comment by Ross-Dobson** [comment]
Typo in your command in the app name. It should be `sudo apt install x11-apps -y` not `sudo apt install x-11 apps -y`.

**Comment by bayvista170** [comment]
Tkx Ross,
"Next step:  Once these applications are installed, you'll find them in
your start menu under the distro name. For example Ubuntu -> Microsoft Edge.
You can also launch these from your terminal window using the commands:"

I assume you mean the W10 start menu. Well, they ain't there. It just says
'Ubuntu'. No apps.

**Comment by bayvista170** [comment]
david@DESKTOP-U5S2IHE:~$ xcalc
Error: Can't open display:
david@DESKTOP-U5S2IHE:~$ xclock
Error: Can't open display:
david@DESKTOP-U5S2IHE:~$

**Comment by onomatopellan** [comment]
Try running `export DISPLAY=:0` first before launching the apps.

More info here:
https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg

**Comment by bayvista170** [comment]
david@DESKTOP-U5S2IHE:~$ export DISPLAY=:0
david@DESKTOP-U5S2IHE:~$ xcalc
Error: Can't open display: :0
david@DESKTOP-U5S2IHE:~$

**Comment by onomatopellan** [comment]
Which Windows build are you running? (`winver.exe`)
Which Linux kernel? (`uname -a`)

**Comment by ntrp** [comment]
I have the same issue.. my system versions:
Windows: 21390.2025
WSL: Arch linux - Linux DESKTOP-2BD1RG8 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

I just verified that on Ubuntu works, anyway I can debug the reason and fix the problem?

**Comment by KeiichiroKOIWAI** [comment]
I also have the same trouble
Windows OS: 21390.2025
WSL: Linux KOIWAI-AH5 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by onomatopellan** [comment]
Please post the output of these:
```
cat /mnt/wslg/versions.txt

echo $DISPLAY

ls -la /tmp/.X11-unix

ls -la /tmp/.X11-unix/
```

**Comment by ntrp** [comment]
In my case this part from the troubleshooting guide fixed it:
```
sudo rm -r /tmp/.X11-unix
ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
```
I guess it's something that comes out of the box with the default distros..

**Comment by KeiichiroKOIWAI** [comment]
Thank you for replying,
these are the outputs.

I tried ntrp's suggestion, but not worked.

>>cat /mnt/wslg/versions.txt
No such file or directory

>>echo $DISPLAY
:0.0

>>ls -la /tmp/.X11-unix
lrwxrwxrwx 1 koiwai koiwai 19 Jun 23 21:55 /tmp/.X11-unix -> /mnt/wslg/.X11-unix

>>ls -la /tmp/.X11-unix/
ls: cannot access '/tmp/.X11-unix/': No such file or directory

**Comment by KeiichiroKOIWAI** [comment]
I'm not sure why "version.txt" was removed😢

**Comment by onomatopellan** [comment]
@KeiichiroKOIWAI only versions.txt? What's the output of `ls -la /mnt/wslg` ?

**Comment by KeiichiroKOIWAI** [comment]
@onomatopellan 
>>ls -la /mnt/wslg
total 8
drwxr-xr-x 2 root root 4096 Jun 11 17:17 .
drwxr-xr-x 9 root root 4096 Jun 11 17:17 ..

**Comment by ntrp** [comment]
did you run `wsl --update`? Also did you install WSL compatible drivers in Windows?

**Comment by KeiichiroKOIWAI** [comment]
@ntrp Yes, I did update. and also using the latest Nvidia's driver...

**Comment by onomatopellan** [comment]
@KeiichiroKOIWAI Right now it's like if you didn't have WSLg installed. So you can go to Add/Remove programs, uninstall the WSLg package and try wsl.exe --update again. If it still doesn't work you can install the latest version manually from https://github.com/microsoft/wslg/releases/download/v1.0.24/wsl_graphics_support_x64.msi

**Comment by ntrp** [comment]
The one from here? https://developer.nvidia.com/cuda/wsl

Last thing that comes to mind this you properly restart and/or ran `wsl --shutdown`?

**Comment by KeiichiroKOIWAI** [comment]
@onomatopellan 
I found Windows Subsystem for Linux WSLg Preview v1.0.22 on the Add/Remove Program.
Ok, I will remove it, then try wsl.exe --update again!

This is late due to the time difference, so I'll try tomorrow! Thank you very much.

**Comment by KeiichiroKOIWAI** [comment]
@ntrp Thx, I followed these completely! Even "nvidia-smi" is working.

@onomatopellan 
I tried re-installed using ```wsl --update"" but it installed v1.0.22 again...
I will manually install wslg tomorrow, thx.

**Comment by hideyukn88** [comment]
@KeiichiroKOIWAI, have you installed any other X server solution on this distro? given DISPLAY is set to what WSLg doesn't. thanks for trying out WSLg!

>> echo $DISPLAY
>> :0.0

**Comment by KeiichiroKOIWAI** [comment]
@hideyukn88 Thank you for your comments. I set DISPLAY manually. When I open WSL, echo $DISPLAY sows nothing.

**Comment by hideyukn88** [comment]
@KeiichiroKOIWAI, given you don't see versions.txt either, have you installed WSLg ? or it might be disabled by .wslconfig? thanks!

**Comment by KeiichiroKOIWAI** [comment]
@hideyukn88
Wao, accidentally .wslconfig's GUI option was set to false.....
When it turns true, everything goes well.

Thank you everyone, sorry for disturbing you with such an easy problem...

**Comment by hideyukn88** [comment]
@KeiichiroKOIWAI, no problem, thanks for trying out WSLg!

**Comment by bayvista170** [comment]
Thanks everyone. When I went back to the beginning, I found out that I had
missed a step - Now all is working fine. Congrats to the MS Team - a job
well done
