### ISSUE TITLE
X "Can't open display: :0"

### ISSUE THREAD

**Issue by ross-dobson** [microsoft/wslg#326]
# Environment

```
Windows build number: Win32NT 10.0.21390.0 Microsoft Windows NT 10.0.21390.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: Windows Subsystem for Linux WSLg Preview 1.0.22
```

# Steps to reproduce

Have completely removed distro, WSL and WSLg and reinstalled twice, still see the same errors as shown below.

```
rsd@DESKTOP-O9LC279:~$ sudo apt install x11-apps -y
[sudo] password for rsd:
Reading package lists... Done
Building dependency tree
Reading state information... Done
x11-apps is already the newest version (7.7+8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rsd@DESKTOP-O9LC279:~$ xclock
Error: Can't open display: :0
rsd@DESKTOP-O9LC279:~$ echo $DISPLAY
:0
rsd@DESKTOP-O9LC279:~$ ls -la /tmp/.X11-unix
lrwxrwxrwx 1 root root 19 Jun 24 19:16 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
rsd@DESKTOP-O9LC279:~$ ls /tmp/.X11-unix
rsd@DESKTOP-O9LC279:~$
```

As per [the wiki page on "cannot open display" type errors](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg), attaching weston.log and other log files as `ls /tmp/.X11-unix` did _not_ show an X0 socket.

**WSL logs**: 

* [pulseaudio.log](https://github.com/microsoft/wslg/files/6711787/pulseaudio.log)
* [weston.log](https://github.com/microsoft/wslg/files/6711789/weston.log)
* versions.txt is showing as empty in Explorer...

...but if I run `cat /mnt/wslg/versions.txt` in Ubuntu I get:
```
WSLg ( x86_64 ): 1.0.22+Branch.main.Sha.d7102a7ff8a3bb04bbcd3483c3f7d7a7633686a1
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 9e402088aa2cd9316851ea20b9befbcf3b9c9564
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

Furthermore, some other apps e.g. vlc and gedit _do_ appear to work but are printing console errors about dbus and interfaces. Not sure if related, can include if needed.

#  Expected behavior

X apps should work.

# Actual behavior

X does not appear to work.

**Comment by fanxing-6** [comment]
I'm in the same boat as you

**Comment by ross-dobson** [comment]
Issue now resolved after reinstall and recent updates.
