### ISSUE TITLE
Can not input chinese in JetBrains IDEA

### ISSUE THREAD

**Issue by lscgzwd** [microsoft/wslg#328]
# Environment

```none
Windows build number: Win32NT             10.0.21996.0 Microsoft Windows NT 10.0.21996.0
Your Distribution version:  ubuntu       20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

1.install ibus
2.setup ibus for default input method
3. exec idea.sh
4. use hotkey change the input method
5. the screen shows input method select
6. input some thing in the idea editor
7. still english words, can not input chinese

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

* [pulseaudio.log](https://github.com/microsoft/wslg/files/6720036/pulseaudio.log)
* [weston.log](https://github.com/microsoft/wslg/files/6720037/weston.log)
* [versions.txt](https://github.com/microsoft/wslg/files/6720042/versions.txt)

#  Expected behavior

idea can input chinese

# Actual behavior
![image](https://user-images.githubusercontent.com/7054255/123512257-0bc9cb00-d6b9-11eb-8746-35dafc759006.png)

can not input chinese

**Comment by lincanshu** [comment]
Can you tell me why you can see Chinese in IDEA? I try, but I failed.
![image](https://user-images.githubusercontent.com/63219194/128586056-4d94ae20-d06e-4956-921d-c9a9c3430a2b.png)

**Comment by lscgzwd** [comment]
> Can you tell me why you can see Chinese in IDEA? I try, but I failed.
> ![image](https://user-images.githubusercontent.com/63219194/128586056-4d94ae20-d06e-4956-921d-c9a9c3430a2b.png)

Change lang to zh_CN.UTF8 or en_US.UTF8 
Next: copy windows  fonts to wsl

```
   85  sudo locale-gen
   86  locale
   87  ls /usr/local/share/fonts/
   88  sudo apt install language-pack-gnome-zh-hans
   89  sudo dpkg-reconfigure locales
   90  sudo apt install fontconfig
   91  sudo apt-get install --reinstall ttf-mscorefonts-installer
   92  sudo vim /etc/fonts/local.conf
```
related to up commands

**Comment by lincanshu** [comment]
- 3Q, but I do one more thing:
- Copy this into /etc/fonts/local.conf

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>/mnt/c/Windows/Fonts</dir>
</fontconfig>
```

**Comment by fanxing-6** [comment]
someone can use sogou input method? How did you do it?

**Comment by lscgzwd** [comment]
> * 3Q, but I do one more thing:
> * paste below into /etc/fonts/local.conf
> 
> ```
> <?xml version="1.0"?>
> <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
> <fontconfig>
>     <dir>/mnt/c/Windows/Fonts</dir>
> </fontconfig>
> ```

same.

**Comment by lscgzwd** [comment]
> someone can use sogou input method? How did you do it?

I can not use , I have tried baidu, but the config panel for baidu is empty. 
I have installed many X11 packages, now I can input chinese use fcitx with default pinying and wubi input methods. 
Baidu still fail.

```

  465  fcitx-configtool
  466  sudo aptitude install fcitx-bin fcitx-table fcitx-config-gtk fcitx-config-gtk2 fcitx-frontend-all
  467  sudo aptitude install qt5-default qtcreator qml-module-qtquick-controls2
  468  sudo apt install fcitx-bin fcitx-table fcitx-config-gtk fcitx-config-gtk2 fcitx-frontend-all
  469  sudo apt install fcitx-bin fcitx-table fcitx-config-gtk fcitx-frontend-all
  470  sudo apt install qt5-default qtcreator qml-module-qtquick-controls2
  471  exit
  472  im-config
  473  ls -al /tmp/.X11-unix/
  474  sudo rm -rf /tmp/.X11-unix/
  475  sudo ln -s /mnt/wslg/.X11-unix /tmp/
  476  im-config
  477  fcitx-configtool
  478  pluma
  479  vim .bashrc
  480  vim /etc/bash.bashrc
  481  sudo vim /etc/environment
  482  ps axu |grep fcitx
  483  fcitx-autostart
  484  ps axu |grep fcitx
  485  fcitx-configtool
  486  ps axu |grep fcitx
  487  pluma
  488  source .bashrc
  489  fcitx-configtool
  490  pluma
  491  im-config
  492  fc-conflist
  493  fcitx4-config
  494  fcitx-configtool
  495  localectl
  496  localedef
  497  apt-cache search fcitx
  498  sudo apt-get install fcitx-baidupinyin fcitx5-table fcitx5-pinyin fcitx-googlepinyin sunpinyin-utils fcitx-tools fcitx-sunpinyin fcitx-ui-light fcitx-ui-classic  fcitx-table-all
  499  sudo apt-get install  i965-va-driver-shaders libbluray-bdj opencl-icd libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
  500  sudo apt-get install  i965-va-driver-shaders libbluray-bdj libnvidia-compute-465 libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
  501  sudo apt-get install  i965-va-driver-shaders libbluray-bdj libnvidia-compute-465 libvdpau-va-gl1
  502  fcitx-configtool
  503  pluma
  504  code workspace/jika/
  505  vim .config/fcitx/config
  506  vim .config/fcitx/profile
  507  vim .config/fcitx/conf/fcitx-baidupinyin.config
  508  vim .config/fcitx/conf/fcitx-pinyin
  509  vim .config/fcitx/conf/fcitx-pinyin.config
  510  vim .config/fcitx/baidupy/bdconf
  511  vim .config/fcitx/conf/fcitx-pinyin.config
  512  vim .config/fcitx/baidupy/bdconf
  513  vim .config/fcitx/conf/fcitx-baidupinyin.config
  514  sudo apt install qt5-default qtcreator qml-module-qtquick-controls2
  515  sudo fcitx-autostart
  516  ps axu |grep fcitx
  517  kill -9 1808
  518  kill -9 1814
  519  ps axu |grep fcitx
  520  fcitx-configtool
  521  ps axu |grep fcitx
  522  kill 4667
  523  kill -9 4667
  524  ps axu |grep fcitx
  525  sudo kill -9 4667
  526  ps axu |grep fcitx
  527  fcitx-autostart
  528  ps axu |grep fcitx
  529  sudo kill -9 4724
  530  sudo rm -rf /tmp/fcitx-socket-\:0
  531  fcitx-autostart
  532  fcitx-configtool
  533  sudo apt-get install clang clang-tidy clang-tidy-10 clang-tools-10 libclang1-8
  534  libkf5syntaxhighlighting-data libkf5syntaxhighlighting5 libllvm8
  535  libqbscore1.13 libqt5designer5 libqt5designercomponents5 libqt5help5
  536  libqt5positioning5 libqt5quicktest5 libqt5quickwidgets5 libqt5script5
  537  libqt5sensors5 libqt5serialport5 libqt5webchannel5 libqt5webkit5
  538  libqt5xmlpatterns5 qbs-common qdoc-qt5 qhelpgenerator-qt5
  539  qml-module-qtqml-models2 qmlscene qt3d5-doc qt5-assistant qt5-doc
  540  qtattributionsscanner-qt5 qtbase5-doc qtcharts5-doc qtconnectivity5-doc
  541  qtcreator-data qtcreator-doc qtdatavisualization5-doc
  542  qtdeclarative5-dev-tools qtdeclarative5-doc qtgraphicaleffects5-doc
  543  qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc
  544  qtquickcontrols5-doc qtscript5-doc qtscxml5-doc qtsensors5-doc
  545  qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-dev-tools
  546  qttools5-doc qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc
  547  qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc
  548  sudo apt-get install clang clang-tidy clang-tidy-10 clang-tools-10 libclang1-8 libkf5syntaxhighlighting-data libkf5syntaxhighlighting5 libllvm8 libqbscore1.13 libqt5designer5 libqt5designercomponents5 libqt5help5 libqt5positioning5 libqt5quicktest5 libqt5quickwidgets5 libqt5script5 libqt5sensors5 libqt5serialport5 libqt5webchannel5 libqt5webkit5 libqt5xmlpatterns5 qbs-common qdoc-qt5 qhelpgenerator-qt5 qml-module-qtqml-models2 qmlscene qt3d5-doc qt5-assistant qt5-doc qtattributionsscanner-qt5 qtbase5-doc qtcharts5-doc qtconnectivity5-doc qtcreator-data qtcreator-doc qtdatavisualization5-doc qtdeclarative5-dev-tools qtdeclarative5-doc qtgraphicaleffects5-doc qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc qtquickcontrols5-doc qtscript5-doc qtscxml5-doc qtsensors5-doc qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-dev-tools qttools5-doc qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc qtxmlpatterns5-dev-tools qtxmlpatterns5-doc
  549  sudo apt-get upgrade
  550  sudo apt remove fcitx-ui-qimpanel
  551  killall fcitx
  552  ps axu |grep fcitx
  553  fcitx-autostart
  554  fcitx-configtool
  555  fcitx-autostart
  556  history |grep X11
  557  echo
  558  vim fix-x11.sh
  559  chmod +x fix-x11.sh
```

**Comment by fanxing-6** [comment]
Thank you!

**Comment by fanxing-6** [comment]
> > someone can use sogou input method? How did you do it?
> 
> I can not use , I have tried baidu, but the config panel for baidu is empty.
> I have installed many X11 packages, now I can input chinese use fcitx with default pinying and wubi input methods.
> Baidu still fail.
> 
> ```
> 
>   465  fcitx-configtool
>   466  sudo aptitude install fcitx-bin fcitx-table fcitx-config-gtk fcitx-config-gtk2 fcitx-frontend-all
>   467  sudo aptitude install qt5-default qtcreator qml-module-qtquick-controls2
>   468  sudo apt install fcitx-bin fcitx-table fcitx-config-gtk fcitx-config-gtk2 fcitx-frontend-all
>   469  sudo apt install fcitx-bin fcitx-table fcitx-config-gtk fcitx-frontend-all
>   470  sudo apt install qt5-default qtcreator qml-module-qtquick-controls2
>   471  exit
>   472  im-config
>   473  ls -al /tmp/.X11-unix/
>   474  sudo rm -rf /tmp/.X11-unix/
>   475  sudo ln -s /mnt/wslg/.X11-unix /tmp/
>   476  im-config
>   477  fcitx-configtool
>   478  pluma
>   479  vim .bashrc
>   480  vim /etc/bash.bashrc
>   481  sudo vim /etc/environment
>   482  ps axu |grep fcitx
>   483  fcitx-autostart
>   484  ps axu |grep fcitx
>   485  fcitx-configtool
>   486  ps axu |grep fcitx
>   487  pluma
>   488  source .bashrc
>   489  fcitx-configtool
>   490  pluma
>   491  im-config
>   492  fc-conflist
>   493  fcitx4-config
>   494  fcitx-configtool
>   495  localectl
>   496  localedef
>   497  apt-cache search fcitx
>   498  sudo apt-get install fcitx-baidupinyin fcitx5-table fcitx5-pinyin fcitx-googlepinyin sunpinyin-utils fcitx-tools fcitx-sunpinyin fcitx-ui-light fcitx-ui-classic  fcitx-table-all
>   499  sudo apt-get install  i965-va-driver-shaders libbluray-bdj opencl-icd libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
>   500  sudo apt-get install  i965-va-driver-shaders libbluray-bdj libnvidia-compute-465 libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
>   501  sudo apt-get install  i965-va-driver-shaders libbluray-bdj libnvidia-compute-465 libvdpau-va-gl1
>   502  fcitx-configtool
>   503  pluma
>   504  code workspace/jika/
>   505  vim .config/fcitx/config
>   506  vim .config/fcitx/profile
>   507  vim .config/fcitx/conf/fcitx-baidupinyin.config
>   508  vim .config/fcitx/conf/fcitx-pinyin
>   509  vim .config/fcitx/conf/fcitx-pinyin.config
>   510  vim .config/fcitx/baidupy/bdconf
>   511  vim .config/fcitx/conf/fcitx-pinyin.config
>   512  vim .config/fcitx/baidupy/bdconf
>   513  vim .config/fcitx/conf/fcitx-baidupinyin.config
>   514  sudo apt install qt5-default qtcreator qml-module-qtquick-controls2
>   515  sudo fcitx-autostart
>   516  ps axu |grep fcitx
>   517  kill -9 1808
>   518  kill -9 1814
>   519  ps axu |grep fcitx
>   520  fcitx-configtool
>   521  ps axu |grep fcitx
>   522  kill 4667
>   523  kill -9 4667
>   524  ps axu |grep fcitx
>   525  sudo kill -9 4667
>   526  ps axu |grep fcitx
>   527  fcitx-autostart
>   528  ps axu |grep fcitx
>   529  sudo kill -9 4724
>   530  sudo rm -rf /tmp/fcitx-socket-\:0
>   531  fcitx-autostart
>   532  fcitx-configtool
>   533  sudo apt-get install clang clang-tidy clang-tidy-10 clang-tools-10 libclang1-8
>   534  libkf5syntaxhighlighting-data libkf5syntaxhighlighting5 libllvm8
>   535  libqbscore1.13 libqt5designer5 libqt5designercomponents5 libqt5help5
>   536  libqt5positioning5 libqt5quicktest5 libqt5quickwidgets5 libqt5script5
>   537  libqt5sensors5 libqt5serialport5 libqt5webchannel5 libqt5webkit5
>   538  libqt5xmlpatterns5 qbs-common qdoc-qt5 qhelpgenerator-qt5
>   539  qml-module-qtqml-models2 qmlscene qt3d5-doc qt5-assistant qt5-doc
>   540  qtattributionsscanner-qt5 qtbase5-doc qtcharts5-doc qtconnectivity5-doc
>   541  qtcreator-data qtcreator-doc qtdatavisualization5-doc
>   542  qtdeclarative5-dev-tools qtdeclarative5-doc qtgraphicaleffects5-doc
>   543  qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc
>   544  qtquickcontrols5-doc qtscript5-doc qtscxml5-doc qtsensors5-doc
>   545  qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-dev-tools
>   546  qttools5-doc qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc
>   547  qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc
>   548  sudo apt-get install clang clang-tidy clang-tidy-10 clang-tools-10 libclang1-8 libkf5syntaxhighlighting-data libkf5syntaxhighlighting5 libllvm8 libqbscore1.13 libqt5designer5 libqt5designercomponents5 libqt5help5 libqt5positioning5 libqt5quicktest5 libqt5quickwidgets5 libqt5script5 libqt5sensors5 libqt5serialport5 libqt5webchannel5 libqt5webkit5 libqt5xmlpatterns5 qbs-common qdoc-qt5 qhelpgenerator-qt5 qml-module-qtqml-models2 qmlscene qt3d5-doc qt5-assistant qt5-doc qtattributionsscanner-qt5 qtbase5-doc qtcharts5-doc qtconnectivity5-doc qtcreator-data qtcreator-doc qtdatavisualization5-doc qtdeclarative5-dev-tools qtdeclarative5-doc qtgraphicaleffects5-doc qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc qtquickcontrols5-doc qtscript5-doc qtscxml5-doc qtsensors5-doc qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-dev-tools qttools5-doc qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc qtxmlpatterns5-dev-tools qtxmlpatterns5-doc
>   549  sudo apt-get upgrade
>   550  sudo apt remove fcitx-ui-qimpanel
>   551  killall fcitx
>   552  ps axu |grep fcitx
>   553  fcitx-autostart
>   554  fcitx-configtool
>   555  fcitx-autostart
>   556  history |grep X11
>   557  echo
>   558  vim fix-x11.sh
>   559  chmod +x fix-x11.sh
> ```

I succeeded, but this input method is really hard to use,low

**Comment by fanxing-6** [comment]
After your tutorial, I looked up a lot of information and finally succeeded, and I found that the essence of it is to restart the system multiple times, otherwise, many Settings will not take effect.
![image](https://user-images.githubusercontent.com/73698197/128641277-727dd052-4821-4cbd-b466-90d7ca10656c.png)

**Comment by cyber-pixel** [comment]
> > someone can use sogou input method? How did you do it?
> 
> I can not use , I have tried baidu, but the config panel for baidu is empty. I have installed many X11 packages, now I can input chinese use fcitx with default pinying and wubi input methods. Baidu still fail.
> 
> ```
> 
>   465  fcitx-configtool
>   466  sudo aptitude install fcitx-bin fcitx-table fcitx-config-gtk fcitx-config-gtk2 fcitx-frontend-all
>   467  sudo aptitude install qt5-default qtcreator qml-module-qtquick-controls2
>   468  sudo apt install fcitx-bin fcitx-table fcitx-config-gtk fcitx-config-gtk2 fcitx-frontend-all
>   469  sudo apt install fcitx-bin fcitx-table fcitx-config-gtk fcitx-frontend-all
>   470  sudo apt install qt5-default qtcreator qml-module-qtquick-controls2
>   471  exit
>   472  im-config
>   473  ls -al /tmp/.X11-unix/
>   474  sudo rm -rf /tmp/.X11-unix/
>   475  sudo ln -s /mnt/wslg/.X11-unix /tmp/
>   476  im-config
>   477  fcitx-configtool
>   478  pluma
>   479  vim .bashrc
>   480  vim /etc/bash.bashrc
>   481  sudo vim /etc/environment
>   482  ps axu |grep fcitx
>   483  fcitx-autostart
>   484  ps axu |grep fcitx
>   485  fcitx-configtool
>   486  ps axu |grep fcitx
>   487  pluma
>   488  source .bashrc
>   489  fcitx-configtool
>   490  pluma
>   491  im-config
>   492  fc-conflist
>   493  fcitx4-config
>   494  fcitx-configtool
>   495  localectl
>   496  localedef
>   497  apt-cache search fcitx
>   498  sudo apt-get install fcitx-baidupinyin fcitx5-table fcitx5-pinyin fcitx-googlepinyin sunpinyin-utils fcitx-tools fcitx-sunpinyin fcitx-ui-light fcitx-ui-classic  fcitx-table-all
>   499  sudo apt-get install  i965-va-driver-shaders libbluray-bdj opencl-icd libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
>   500  sudo apt-get install  i965-va-driver-shaders libbluray-bdj libnvidia-compute-465 libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
>   501  sudo apt-get install  i965-va-driver-shaders libbluray-bdj libnvidia-compute-465 libvdpau-va-gl1
>   502  fcitx-configtool
>   503  pluma
>   504  code workspace/jika/
>   505  vim .config/fcitx/config
>   506  vim .config/fcitx/profile
>   507  vim .config/fcitx/conf/fcitx-baidupinyin.config
>   508  vim .config/fcitx/conf/fcitx-pinyin
>   509  vim .config/fcitx/conf/fcitx-pinyin.config
>   510  vim .config/fcitx/baidupy/bdconf
>   511  vim .config/fcitx/conf/fcitx-pinyin.config
>   512  vim .config/fcitx/baidupy/bdconf
>   513  vim .config/fcitx/conf/fcitx-baidupinyin.config
>   514  sudo apt install qt5-default qtcreator qml-module-qtquick-controls2
>   515  sudo fcitx-autostart
>   516  ps axu |grep fcitx
>   517  kill -9 1808
>   518  kill -9 1814
>   519  ps axu |grep fcitx
>   520  fcitx-configtool
>   521  ps axu |grep fcitx
>   522  kill 4667
>   523  kill -9 4667
>   524  ps axu |grep fcitx
>   525  sudo kill -9 4667
>   526  ps axu |grep fcitx
>   527  fcitx-autostart
>   528  ps axu |grep fcitx
>   529  sudo kill -9 4724
>   530  sudo rm -rf /tmp/fcitx-socket-\:0
>   531  fcitx-autostart
>   532  fcitx-configtool
>   533  sudo apt-get install clang clang-tidy clang-tidy-10 clang-tools-10 libclang1-8
>   534  libkf5syntaxhighlighting-data libkf5syntaxhighlighting5 libllvm8
>   535  libqbscore1.13 libqt5designer5 libqt5designercomponents5 libqt5help5
>   536  libqt5positioning5 libqt5quicktest5 libqt5quickwidgets5 libqt5script5
>   537  libqt5sensors5 libqt5serialport5 libqt5webchannel5 libqt5webkit5
>   538  libqt5xmlpatterns5 qbs-common qdoc-qt5 qhelpgenerator-qt5
>   539  qml-module-qtqml-models2 qmlscene qt3d5-doc qt5-assistant qt5-doc
>   540  qtattributionsscanner-qt5 qtbase5-doc qtcharts5-doc qtconnectivity5-doc
>   541  qtcreator-data qtcreator-doc qtdatavisualization5-doc
>   542  qtdeclarative5-dev-tools qtdeclarative5-doc qtgraphicaleffects5-doc
>   543  qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc
>   544  qtquickcontrols5-doc qtscript5-doc qtscxml5-doc qtsensors5-doc
>   545  qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-dev-tools
>   546  qttools5-doc qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc
>   547  qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc
>   548  sudo apt-get install clang clang-tidy clang-tidy-10 clang-tools-10 libclang1-8 libkf5syntaxhighlighting-data libkf5syntaxhighlighting5 libllvm8 libqbscore1.13 libqt5designer5 libqt5designercomponents5 libqt5help5 libqt5positioning5 libqt5quicktest5 libqt5quickwidgets5 libqt5script5 libqt5sensors5 libqt5serialport5 libqt5webchannel5 libqt5webkit5 libqt5xmlpatterns5 qbs-common qdoc-qt5 qhelpgenerator-qt5 qml-module-qtqml-models2 qmlscene qt3d5-doc qt5-assistant qt5-doc qtattributionsscanner-qt5 qtbase5-doc qtcharts5-doc qtconnectivity5-doc qtcreator-data qtcreator-doc qtdatavisualization5-doc qtdeclarative5-dev-tools qtdeclarative5-doc qtgraphicaleffects5-doc qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc qtquickcontrols5-doc qtscript5-doc qtscxml5-doc qtsensors5-doc qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-dev-tools qttools5-doc qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc qtxmlpatterns5-dev-tools qtxmlpatterns5-doc
>   549  sudo apt-get upgrade
>   550  sudo apt remove fcitx-ui-qimpanel
>   551  killall fcitx
>   552  ps axu |grep fcitx
>   553  fcitx-autostart
>   554  fcitx-configtool
>   555  fcitx-autostart
>   556  history |grep X11
>   557  echo
>   558  vim fix-x11.sh
>   559  chmod +x fix-x11.sh
> ```

vim的配置是什么呢
具体的方法能法一下吗，网上没有教程呢，现在能显示中文，不能输入。win11 wslg app

**Comment by mingyujiao** [comment]
参考这个博主的方法，可以输入中文了。 https://monkeywie.cn/2021/09/26/wsl2-gui-idea-config/

**Comment by linghengqian** [comment]
- I think this issue can be closed, all the issues surrounding this issue have been resolved, and ibus is available in intellij idea.

**Comment by lscgzwd** [comment]
if some users valid this, i'll close this issue. I do not have any time on this within half a year.

**Comment by linghengqian** [comment]
@lscgzwd 
- As a reminder, configuring ibus in WSL is linear and requires no special actions.
- 
![2022-11-17](https://user-images.githubusercontent.com/20187731/202235694-7b2e9946-2926-4e33-a597-d55dc3f53127.png)
- For IntelliJ IDEA's input method not following issue, people should pay attention to https://youtrack.jetbrains.com/issue/JBR-2460 instead of WSL, neither OpenJDK nor Jetbrains Runtime have been implemented correctly for AWT under X11 Input style for `below-the-spot`. **I must point out that X11 is definitely not the future.**
- This issue should be closed to avoid misleading others.

**Comment by lscgzwd** [comment]
Closed
