### ISSUE TITLE
Windows 11 dev preview broken WSLg

### ISSUE THREAD

**Issue by wormwang** [microsoft/wslg#335]
# Environment
Windows 11 build 22000.51, dev preview broken WSLg 
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce
click Ubuntu 20.04 icon, wait many mins, then it exit

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by maximo-draco** [comment]
Hi, I install first windows 10 Pro, install wsl, join to insider, update to windows 11, install nvidia recommended drivers, install wslg and all work fine (nautilus, gedit and all workfloow), for now.
Now a install IntellIdea in linux and and I'm going to test that.
Exuseme for mi English, spanish is my native language

**Comment by dpeterc** [comment]
I confirm that after update to Windows11 developers preview wslg stops working.
You need to update wsl and then it works again.
But all wsl entries are missing from the start menu.

**Comment by wormwang** [comment]
fixed it by follow steps
1, open a terminal as admin right
2, run 
wsl --update
update to 5.10.16
3, wsl --shutdown
4, wsl

**Comment by spronovo** [comment]
Sounds like everyone in this thread got their WSLg working again, closing the thread. Let us know if you are still experiencing issues.
