### ISSUE TITLE
windows11 can't install intel GPU driver

### ISSUE THREAD

**Issue by vicnoah** [microsoft/wslg#336]
# Environment

```none
Windows build number: 10.0.22000.51
Your Distribution version: 22000.51
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by framerate** [comment]
Same error. I'm on 11th gen Iris though, if it helps!

**Comment by mzaglia** [comment]
Working fine for me

CPU: Using AMD Ryzen R5 5600x
GPU: Nvidia GTX 1070
GPU Driver: 470.76
OS Build: 22000.51
WSL OS: Ubuntu 18.04
WSL Kernel: 5.10.16.3-microsoft-standard-WSL2

**Comment by spronovo** [comment]
Hi @vicnoah, @framerate, which Intel driver version/package are you trying to install? The one linked in our vGPU instructions?

Could you elaborate on the error you are hitting?

**Comment by framerate** [comment]
For sure! @spronovo 

If you go to Intel's page from the link in the readme and you try and install the driver, It will tell you your operating system is not supported (Windows 11)

**Comment by arielmoisis** [comment]
It appears the driver linked in the readme has not been updated since, 6/16/2020. Unsure if the latest drivers have all the correct pieces. https://downloadcenter.intel.com/download/30579/Intel-Graphics-Windows-DCH-Drivers.

**Comment by vicnoah** [comment]
> It appears the driver linked in the readme has not been updated since, 6/16/2020. Unsure if the latest drivers have all the correct pieces. https://downloadcenter.intel.com/download/30579/Intel-Graphics-Windows-DCH-Drivers.
> 

Thank you, the problem has been resolved.

**Comment by spronovo** [comment]
Thanks, i updated the link on our documentation to link to the new Win11 driver.
