### ISSUE TITLE
When "Automatically hide the taskbar in desktop mode" is enabled, taskbar will not appear for maximized WSLg windows

### ISSUE THREAD

**Issue by otocon** [microsoft/wslg#337]
# Environment

```none
Windows build number:10.0.21390.0
Your Distribution version: 20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

1. Enable "Automatically hide the taskbar in desktop mode"
2. Maximize WSLg app window (reproduced it with Intellij and gedit)
3. Move cursor to screen edge where taskbar should appear

#  Expected behavior

Taskbar should appear

# Actual behavior

Taskbar stays hidden

**Comment by hideyukn88** [comment]
@otocon, thanks for reporting the issue, yes, this is very interesting issue and I confirm I can repro locally, I will take a look, thanks!
