### ISSUE TITLE
Does WSLg will arrive in Windows 10 21H2?

### ISSUE THREAD

**Issue by KrisRadowski** [microsoft/wslg#338]
Hello,

Since Windows 11 was announced and the readme states:

> WSLg is going to be generally available alongside the upcoming release of Windows.

I'm not sure if WSLg will be included in Windows 10 21H2; my computer will not support Windows 11, so I hope that WSLg won't be exclusive for Windows 11..

**Comment by crramirez** [comment]
Maybe this question belongs to the Discussions tab
