### ISSUE TITLE
PHP Storm global search popup close immediately after being opened

### ISSUE THREAD

**Issue by bastoune** [microsoft/wslg#340]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.22000.51]
Your Distribution version: 20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

- open php storm (v2021.1.3) from wslg
- ctrl+shift+f 
- the popup appear and disapear
- do it between 3 and 10times really fast, and it will stay

**Comment by onomatopellan** [comment]
probably a duplicate of #331

**Comment by hideyukn88** [comment]
@bastoune, thanks you for reporting issue. this is most likely same root cause as https://github.com/microsoft/wslg/issues/96. thanks!
