### ISSUE TITLE
Emacs with wayland crashes when pasting from clipboard

### ISSUE THREAD

**Issue by untoreh** [microsoft/wslg#349]
# Environment

```none
Windows build number: Win32NT             10.0.22000.0 Microsoft Windows NT 10.0.22000.0
Your Distribution version: Arch linux
```

# Steps to reproduce
Installed emacs from aur:
```
aura -Ai emacs-gcc-wayland-devel-bin
Repository  : aur
Name        : emacs-gcc-wayland-devel-bin
Version     : 28.0.50.149085-1
AUR Status  : Up to Date
Maintainer  : mpsq
Project URL : https://github.com/mpsq/emacs-gcc-wayland-devel-builder
AUR URL     : https://aur.archlinux.org/packages/emacs-gcc-wayland-devel-binLicense     : GPL3
Depends On  : alsa-lib cairo gnutls gtk3 libxml2 jansson libotf harfbuzz gpm libgccjit webkit2gtk
Build Deps  :
Votes       : 16
Popularity  : 3.24
Description : GNU Emacs. Development native-comp branch and pgtk branch combined, served as a binary.
```
I run emacs making sure the use the wayland backend.
Because copy pasting doesn't work correctly I use these functions with emacs
```elisp
(progn
      (setq wl-copy-process nil)
      (defun wl-copy (text)
        (setq wl-copy-process (make-process :name "wl-copy"
                                            :buffer nil
                                            :command '("wl-copy" "-f" "-n")
                                            :connection-type 'pipe))
        (process-send-string wl-copy-process text)
        (process-send-eof wl-copy-process))
      (defun wl-paste ()
        (if (and wl-copy-process (process-live-p wl-copy-process))
            nil ; should return nil if we're the current paste owner
          (shell-command-to-string "wl-paste -n | tr -d '\r'")
          ))
      (setq interprogram-cut-function #'wl-copy)
      (setq interprogram-paste-function #'wl-paste))
```
This configuration works, but after a while, right after I issue a copy command from windows,
emacs crashes with log
```
Gdk-Message: 14:34:45.200: Error reading events from display: Broken pipe
```

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log` [pulseaudio.log](https://github.com/microsoft/wslg/files/6758375/pulseaudio.log)
* `weston.log` [weston.log](https://github.com/microsoft/wslg/files/6758376/weston.log)
* `versions.txt`
```
WSLg ( x86_64 ): 1.0.22+Branch.main.Sha.d7102a7ff8a3bb04bbcd3483c3f7d7a7633686a1
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 9e402088aa2cd9316851ea20b9befbcf3b9c9564
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

#  Expected behavior

no crash

# Actual behavior

When I issue a copy command from windows, emacs crashes with
```
Gdk-Message: 14:34:45.200: Error reading events from display: Broken pipe
```
from google looks like a problem with weston

**Comment by hideyukn88** [comment]
@untoreh, thanks for reporting the issues, by looking at weston.log, it hits the assertion and this is already fixed. Would you please update to the latest WSLg, and please try again. thanks!

>> weston: ../libweston/backend-rdp/rdpclip.c:1260: clipboard_client_format_data_response: Assertion `source->event_source == NULL' failed.
