### ISSUE TITLE
[Feature Request] Single Window Mode

### ISSUE THREAD

**Issue by SammCheese** [microsoft/wslg#352]
**Is your feature request related to a problem? Please describe.**
Sometimes its just nicer to have a Linux Desktop Environment. Using a VM or Dualbooting is a lot of effort and is rather inconvenient so why not integrate it into wsl?

**Describe the solution you'd like**
The Ability to run Multiple Programs (or DEs in this case) inside a single window, an example would be
```
wsl --single-window "kstart5 plasmashell"
```
Which would open a single weston window with all processes and subprocesses of plasmashell contained inside it

**Additional context**
As of Right now, KDE does start but all applets/widgets are separated and all over the place
![h1qLBAKY4m](https://user-images.githubusercontent.com/52699291/124685134-f16dc980-ded0-11eb-9cf4-33aa01c77a56.jpg)

**Comment by spronovo** [comment]
Thanks for the suggestion. There is already a request tracking support for full Linux environment, linking this back to #101.

**Comment by SammCheese** [comment]
Alright, Thanks for the Heads up!

**Comment by SonaliBendre** [comment]
have you installed arch using archwsl?
