### ISSUE TITLE
Wslg scaling of xterm, edit etc

### ISSUE THREAD

**Issue by mbalcerzyk** [microsoft/wslg#359]
# Environment
10.0.22000.65
Ubuntu 20.04
Wslg 1.0.24
*Surface Pro X with screen magnification of 150% instead of typical 200%*

# Steps to reproduce

Runing: xterm &,  or  gedit &

#  Expected behavior

Scaling parameter is not used. The letters are so small, that you cannot read them. Probably Intel systems have the same problem, like Surface Pro etc.

**Comment by hideyukn88** [comment]
Hi @mbalcerzyk, currently WSLg doesn't enable fractional scaling by default due to quality of scaling. Please refer https://github.com/microsoft/wslg/issues/23 in case you want try out. thanks for trying out WSLg!
