### ISSUE TITLE
Install help needed - wsl --update doesn't work, need more information on installing from repo

### ISSUE THREAD

**Issue by marcatredhat** [microsoft/wslg#363]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1621]
Your Distribution version: Generic release 34 (Generic)
Your WSLg version: not applicable
```

# Steps to reproduce
I have a fresh install of Fedora Remix, WSL v2
When I run 'wsl --update' I get a syntax error, looking at the wsl command there is no --update option
I cloned the wslg repo - but there is no makefile or compile instructions so I'm not sure what to do

#  Expected behavior

# Actual behavior

**Comment by mgateno** [comment]
Just to make sure, are you a part of the Insider program? I don't believe the preview is available outside the Insider builds, so you would not get the correct WSL otherwise AFAIK.

**Comment by benhillis** [comment]
Judging by your release number you are not part of the Insider Dev ring, which is currently required for WSLg.
