### ISSUE TITLE
Requirement of Windows 10 Insider Preview build 21362 not available

### ISSUE THREAD

**Issue by jax79sg** [microsoft/wslg#367]
Hi, the ISO listed on https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso?wa=wsignin1.0 is build 21354 for the Dev Channel. The requirement for WSLg is 21362, where can i get it?

**Comment by onomatopellan** [comment]
@jax79sg The next official ISO with WSLg will be Windows 11 build 22000 and is expected in the next weeks.

**Comment by Biswa96** [comment]
What? "official ISO with WSLg"? Isn't WSLg meant to be installed separately?

**Comment by Biswa96** [comment]
> official ISO with WSLg 

Isn't WSLg meant to be installed separately?

**Comment by onomatopellan** [comment]
I mean WSLg support. You can install the msi but it won't wotk if you are not at least in build 21362 .

**Comment by jax79sg** [comment]
Hi, I'm unable to transit to windows 11 due to some app incompatibility. Is it not possible to use an older preview build? When I start with 21354, it automatically upgrade to Windows 11 build and rendered my apps useless.

**Comment by Biswa96** [comment]
AFAIK, the latest Windows 10 insider is build 21390. Can't you updateto that version?

**Comment by jax79sg** [comment]
Hi

> AFAIK, the latest Windows 10 insider is build 21390. Can't you updateto that version?

Hi, when i move to Insider Dev Channel from Windows 10 build 19*** and perform Updates, it automatically download Windows 11 Build 22000.* and installs. It skips all the Windows 10 insider builds. Did i miss something?

**Comment by jax79sg** [comment]
I managed to build a 21390 from uupdump. updated the drivers and then disabled windows update before windows 11 creeped in.
