### ISSUE TITLE
Resizing window leads to not updating display any further

### ISSUE THREAD

**Issue by akuropka** [microsoft/wslg#372]
Windows 22000.71
Kernel 5.10.43.3
wslg 1.0.26
Official Ubuntu-Community Preview
NVidia v471,41 @ GeForce 930MX WDDM3.0

After resizing a window the display within doesn't get updated anymore.
(Entering anything is not shown, clicking anything doesn't change anything except mouse and title of top bar, making the window bigger leads to stripes)

MS Edge ist just a sample, happens with other applications as well:
![20210720_135248](https://user-images.githubusercontent.com/22570574/126320042-8e5b8c7f-b1a6-4044-87fc-d3bbfcec0ace.gif)

/mnt/wslg:
[weston.log](https://github.com/microsoft/wslg/files/6848070/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/6848071/pulseaudio.log)
[stderr.log](https://github.com/microsoft/wslg/files/6848072/stderr.log)
[versions.txt](https://github.com/microsoft/wslg/files/6848083/versions.txt)

**Comment by hideyukn88** [comment]
@akuropka, thanks for reporting the issue. this issue is reported at https://github.com/microsoft/wslg/issues/272, thanks!
