### ISSUE TITLE
OpenGL applications run faster with larger window sizes, and slower with smaller window sizes

### ISSUE THREAD

**Issue by SED4906** [microsoft/wslg#373]
### Windows Build Number

Microsoft Windows [Version 10.0.22000.71]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04

### Other Software

I was running a program I wrote.
[I was working on a WIP game engine](https://github.com/4906/engine)

### Repro Steps

Compile the program with make
Run the generated a.out file
Observe the speed of the demo with varying window sizes

### Expected Behavior

The program shows a window with a raymarching demo. Resizing the window should not affect the speed. [For reference, this is the demo in its original format.](https://www.shadertoy.com/view/ftlXzl)

### Actual Behavior

The program shows a window with a raymarching demo. Depending on the size of the window, the demo will change speed drastically. Smaller window sizes make the demo slower, and larger window sizes speed the demo up.

**Comment by lewisgdljr** [comment]
This could be due to display scaling. Weston can't resize your display, so it instead rescales applications to fill the screen. This takes a little time, so if you run it at your display's natural resolution where it doesn't need to scale it you might get a performance boost. (This is just the first thing that popped into my head, so it might not be the sole or even primary reason, but it probably contributes.)

**Comment by SED4906** [comment]
Well, my code uses the function clock() every frame to get the number of microseconds since the program was launched. This means that no matter the framerate, it should always run at the same speed.

**Comment by lewisgdljr** [comment]
I see. I thought you meant it was slow in rendering, but you meant that the simulation speed was slow. It's possible that the OpenGL driver is causing a lot of context switches into the hypervisor to run the display driver code, but it doesn't make sense that larger display areas would cause it to run faster (unless for some reason it can do more work per context switch with the larger drawing surface).

**Comment by SED4906** [comment]
I limited the framerate to 60fps and this doesn't happen anymore. The simulation speed was also never correct before this even on real hardware. Usually it would always run slower because real hardware is much faster*. The speed variance was only that drastic on WSL anyways.

*The reason smaller window sizes ran slower was because more frames were able to be rendered, and they were all being drawn one at a time.
