### ISSUE TITLE
Why i get a new user wslg after update KB5004300 in my win11

### ISSUE THREAD

**Issue by guorouda** [microsoft/wslg#379]
After update KB5004300 in my win11, I lost my user **ubuntu** and get a new user **wslg**. And My home directory is missing. I have my work in it. How to rescure it? I don't know how this happend. It seems Windows 11 does this himself -- set a new user whithout asking me the name and password. I lost my work. Why this happened?

# Environment

```none
Windows build number: Microsoft Windows NT 10.0.22000.0
Your Distribution version:  Ubuntu  20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by benhillis** [comment]
@guorouda - can you confirm what you mean by "you have a new user wslg"?

**Comment by guorouda** [comment]
> @guorouda - can you confirm what you mean by "you have a new user wslg"?
I try to  explain. When Installing  Ubuntu on Windows Subsystem for Linux (WSL), you must create a default unix account, to me is ubuntu, not wslg. I can only see user ubuntu in home directory . After I update windows 11 ,  user ubuntu and its directory disappears.  I have a new user wslg , I don't know how it appears.

**Comment by onomatopellan** [comment]
It looks like you are accessing the hidden System distro instead of your user distro.

What's the output for `wsl.exe -l -v` ?

**Comment by guorouda** [comment]
> It looks like you are accessing the hidden System distro instead of your user distro.
> 
> What's the output for `wsl.exe -l -v` ?
NAME        STATE          VERSION
* Ubuntu    Running       2

**Comment by guorouda** [comment]
I reboot my computer. I am GREAT GREAT glad  to find my ubuntu returns. The files in it is all fine and undamaged . @benhillis  @onomatopellanTHANKS  A LOT.

**Comment by RafaelZasas** [comment]
Hi, I see this has been closed but the same has happened to me.

![image](https://user-images.githubusercontent.com/42390827/159745148-ad7bcedf-5728-4a8f-901d-f7f88fc4391c.png)

**Comment by Bluebugs** [comment]
I can confirm that what happen to @RafaelZasas happened to me to and calling `wsl --shutdown` did also fix it. After `wsl --shutdown`, I can not find trace of that wslg user anymore.

**Comment by shripad-jyothinath** [comment]
Hi same happened to me, but if use `wsl --shutdown` it says that command doesn't exist
![image](https://user-images.githubusercontent.com/71135716/170902475-aa33719e-e1f0-4e48-b734-25b9d3875705.png)

**Comment by jonespm** [comment]
> Hi same happened to me, but if use `wsl --shutdown` it says that command doesn't exist ![image](https://user-images.githubusercontent.com/71135716/170902475-aa33719e-e1f0-4e48-b734-25b9d3875705.png)

@shripad-jyothinath You have to run the` wsl --shutdown`  and other `wsl` commands in a native Windows PowerShell or Command Prompt, it doesn't do anything in the WSL terminal. This also happened and fixed it for me today too.

**Comment by Devilshree123** [comment]
wsl --shutdown worked for me

**Comment by MMitsialis** [comment]
After the install of "January 19, 2023-KB5022478 Cumulative Update Preview for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 10 Version 22H2", and a system restart I experienced the same behavior.

My default WSL Distro is set to "Ubuntu-20.04", however a distro "wslg" is what starts. This distro is nor listed in `wsl --list` .
Running `wsl --shutdown` resolved the issue.

## My systeminfo:
``` 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
Hotfix(s):                 10 Hotfix(s) Installed.
                           [01]: KB5017308
                           [02]: KB5022405
                           [03]: KB5007401
                           [04]: KB5012170
                           [05]: KB5015684
                           [06]: KB5022282
                           [07]: KB5014032
                           [08]: KB5016705
                           [09]: KB5018506
                           [10]: KB5020372
``` 

## WSL --version:
```
wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2486
```

**Comment by tamtok111** [comment]
![image](https://user-images.githubusercontent.com/91633199/233855789-c807ea8c-1c44-4908-835d-a317ecadf3ed.png)
I am having the same problem. I left a VS Code window open connected to wsl remotely. Also I have Docker Desktop but i had no container running. I reboot my pc and it seems i get wslg instead of wsl. This is the third time that bug happens. It fixes after wsl --shutdown.

**Comment by mcDandy** [comment]
Exact same problem. I am on windows 10. It happened fwhen after few restarts I opened Ubuntu after updating to windows 10 22H2. I used docker on wsl2 multipe times before I noticed it.

**Comment by lonegunmanb** [comment]
Running `wsl --shutdown` worked for me, thanks @MMitsialis !
