### ISSUE TITLE
Removed user in wslg

### ISSUE THREAD

**Issue by Sreehariqwerty** [microsoft/wslg#406]
Wslg has removed all my info and user and created a new username called as wslg which doesnt contain any information.Thank you and please fix this bug

**Comment by onomatopellan** [comment]
Try rebooting your PC. See #379

**Comment by hideyukn88** [comment]
@Sreehariqwerty, does reboot fix your issue? I close the issue for now, if it doesn't resolve, feel free to reopen. Thanks!
