### ISSUE TITLE
Ctrl-Alt-[Left|Right] not working in IntelliJ

### ISSUE THREAD

**Issue by vlott** [microsoft/wslg#410]
# Environment

```none
Windows build number: 10.0.22000.132
Your Distribution version: Ubuntu 20.04
Your WSLg version: Windows Subsystem for Linux WSLg Preview 1.0.26
```

# Steps to reproduce

Can supply logs if desired

#  Expected behavior

Hotkey to jump back and forward to previous and next cursor positions in IntelliJ (same as Navigate > Back and Forward)

# Actual behavior

Keystrokes are ignored and Hotkeys do not work even though they work when using Vcxsrv (Intel Graphics competing hotkeys were previously disabled also)

**Comment by hideyukn88** [comment]
@vlott, this is reported at https://github.com/microsoft/wslg/issues/188, closing as dup. thanks!
