### ISSUE TITLE
Too aggressive downwards scrolling, and resists upwards scrolling

### ISSUE THREAD

**Issue by da2x** [microsoft/wslg#42]
# Environment

```none
Windows build number: 21364.1
Your Distribution version: Ubuntu 20.10
Your WSLg version: unknown
```

# Steps to reproduce

1. `apt install firefox -y` (or `epiphany-browser` or `nautilus`)
2. `firefox` (or `epiphany-browser` or `nautilus`)
3. Visit any tall webpage
4. Scroll downwards the smallest amount possible
5. Scroll upwards the smallest amount possible

#  Expected behavior

It should scroll down by about 40-50px, and up by about 40-50px.

# Actual behavior

It scrolls ~2000px downwards per tick. It resists scrolling upwards, and need to repeat it multiple times before it finally scrolls ~10px upwards.

# Hardware:

Synaptics Precision TouchPad (Lenovo)

**WSL logs**: 

https://aka.ms/AAc0u5v (feedbackid b6a23cbb-c7f7-4d6e-a2b1-66d85f95bc0c)

**Comment by hideyukn88** [comment]
@da2x , how do you scroll? is it by scroll bar, mouse wheel or something-else? I tried with top page of YouTube or news.yahoo.com (which scroll down almost forever as page move down), I do not notice any difference in amount of move for up or down direction. Thanks!

**Comment by da2x** [comment]
@hideyukn88 I hover the mouse cursor above the page contents and drag two fingers up and down on the touchpad. It happens with every page.

**Comment by da2x** [comment]
Here's a screen recording of me trying to scroll downwards using the tiniest scrolling motion. Next, I'm frantically trying to scroll upwards and almost nothing happens. The page just twitches a bit. Then I try to scroll downwards by the tiniest fraction again.
https://gateway.pinata.cloud/ipfs/bafybeicmbwha5ksgtifdncsoet66262uyns2f6euzhohtqfc4a4bcg5csa

As you can see, it goes way further down than expected and resists going up again.

It's the same in all WSLg apps, but scrolling in Windows native apps work fine.

**Comment by EndPositive** [comment]
I'm having the same issue while using my laptop's touchpad. Using a mouse works fine.

**Comment by hideyukn88** [comment]
Thanks, I confirmed the behavior using touchpad with Surface Pro as well.

**Comment by SciTechEnthusiast** [comment]
yes issue is with touchpad

**Comment by hideyukn88** [comment]
Issue understood. the unit value in "WheelRotationMask" in TS_POINTER_EVENT in RDP needs to be treat separately between mouse wheel and two finger scroll.

**Comment by fliespl** [comment]
Same happens one my end with Microsoft Wireless Mouse 5000. Not touchpad.

I can scroll down, but up goes only one line, need to wait a bit and then scroll up to get one more line up.

Not happening in windows apps.

**Comment by compulim** [comment]
Also bugged with Surface Dial with Edge Dev on Linux, connected to a Surface Book 3.

I can scroll down (super fast) but never scroll up.

**Comment by SmartPolarBear** [comment]
After the latest update, I find the problem that scrolling down is too fast is surely fixed, but now scrolling upwards and downwards are both too aggressive.

**Comment by hideyukn88** [comment]
@SmartPolarBear , thanks for report, would you please let us know which touchpad hardware do you have? thanks!

**Comment by fliespl** [comment]
@hideyukn88 in my case Microsoft Wireless Mouse 5000 still can't scroll upwards. Even on 1.0.20

**Comment by hideyukn88** [comment]
@fliespl , thanks for reporting, do you see any behavior change from previous version or same? and just in case, please double check version in version.txt at /mnt/wslg ? thanks!

**Comment by fliespl** [comment]
@hideyukn88 you were right - I had installed it, but didn't show up in WSL machine even after shutting it down. Windows restart helped, but now it's really sensitive. Any way to change it with xinput settings?

**Comment by hideyukn88** [comment]
@fliespl , thanks for checking. first for settings, we are hoping this to be set by Windows's setting just like other Windows app and that fulfill the needs. Regarding to sensitivity, yes, we are getting internal report some user are now seeing wheel rotation is too sensitive with certain mouse, while this doesn't occur to me with all mouse I personally have, but we are activity investigating this. thanks!

**Comment by SmartPolarBear** [comment]
> @SmartPolarBear , thanks for report, would you please let us know which touchpad hardware do you have? thanks!

I have an OMEN-15 2020 laptop, which has a precision touchpad.

**Comment by NyxCode** [comment]
Same issue on a ThinkPad T14s with the integrated touchpad

**Comment by hideyukn88** [comment]
@fliespl , @SmartPolarBear , @NyxCode , we have pushed the fix and it will be included in next release of WSLg, thanks all for reporting the issue!

**Comment by imReker** [comment]
Too sensitive with Logitech G604 (G Hub Driver).
No problem with my usb precision touchpad.
WSLg 1.20 pre

**Comment by NyxCode** [comment]
For me, it works flawlessly on 1.0.21

**Comment by spronovo** [comment]
1.0.22 with this fix has been officially released. Please run the following from an elevated command prompt to upgrade to 1.0.22.

```
wsl --shutdown
wsl --update
```

**Comment by speller** [comment]
I have this issue and a most-recent WSL version. How to check the WSLg version? I have no `/mnt/wslg` path on in my WSL2-based Ubuntu 20.04 distro. And how to update WSLg?

**Comment by speller** [comment]
Alright, the `versions.txt` file is in the `/wslg` folder (I've turned off the '/mnt' prefixes). The issue exists in PHPStorm when I'm scrolling by the touchpad on my Dell XPS 9310. When I scroll down very slowly, it hardly scrolls. When I scroll down normally, it eventually scrolls up a bit instead of scrolling down.

**Comment by speller** [comment]
It seems my issue is related to #575

**Comment by Cosss7** [comment]
More infomation: I meet same issue and I the mouse scroll works well on 1080P with 100% zoom screen but bad on 2.5K with 200% zoom screen.

I think it's related to HiDPI or scalling something.

Hope it can help.

**Comment by hideyukn88** [comment]
@Cosss7, thanks for info, would you please share the output from `wsl --version` ?, thanks!

**Comment by Cosss7** [comment]
> More infomation: I meet same issue and my mouse scroll works well on 1080P with 100% zoom screen but bad on 2.5K with 200% zoom screen.
> 
> I think it's related to HiDPI or scalling something.
> 
> Hope it can help.

Resolustion 3456 * 2160
Zoom 225% (recommand)

**Comment by hideyukn88** [comment]
@Cosss7,

>> Maybe I should install wsl from MS Store ? Can I just install from store without remove installed wsl first

Yes, please install from MS Store, aka.ms/wslstorepage, and you do not need to uninstall previous one first, thanks!

**Comment by Cosss7** [comment]
> @Cosss7,
> 
> > > Maybe I should install wsl from MS Store ? Can I just install from store without remove installed wsl first
> 
> Yes, please install from MS Store, aka.ms/wslstorepage, and you do not need to uninstall previous one first, thanks!

It's fixed, thank you.

On HiDPI and zoom screen it's a little bit slow but at least it works.

**Comment by CompeyDev** [comment]
> > @Cosss7,
> > > > Maybe I should install wsl from MS Store ? Can I just install from store without remove installed wsl first
> > 
> > 
> > Yes, please install from MS Store, aka.ms/wslstorepage, and you do not need to uninstall previous one first, thanks!
> 
> It's fixed, thank you.
> 
> On HiDPI and zoom screen it's a little bit slow but at least it works.

Yup, can confirm. Slow on HiDPI for me too.
