### ISSUE TITLE
XLookupString reports incorrect values.

### ISSUE THREAD

**Issue by jordansissel** [microsoft/wslg#441]
# Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: Windows Subsystem for Linux WSLg Preview v1.0.26 
```

# Steps to reproduce

Run `xev` and press letter keys. XLookupString output should report the text for the key/letter being pressed.
```
xev
```

**WSL logs**: I didn't see any relevant logs for this issue

#  Expected behavior

XLookupString should report the text for the string being pressed. For example, if I press the "a" key, XLookupString for the KeyPress event show by `xev` should report "a"

# Actual behavior

```
KeyPress event, serial 31, synthetic NO, window 0x400001,
    root 0x39b, subw 0x0, time 709009, (93,57), root:(407,703),
    state 0x4, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (01) ""
    XmbLookupString gives 1 bytes: (01) ""
    XFilterEvent returns: False
```

Notable, the XLookupString and XmbLookupString are wrong. They should report `"a"`

If I install Xephyr (a nested X server) and run `xev` there, the XLookupString is reported correctly.

**Comment by hideyukn88** [comment]
@jordansissel, thanks for reporting the issue, but I don't observe that issue, below is my output from xev. If you can share us /mnt/wslg/weston.log, we might be able to know more about your configuration. thanks!

KeyPress event, serial 34, synthetic NO, window 0x400001,
    root 0x3a7, subw 0x0, time 7460080, (1027,-660), root:(1830,495),
    state 0x0, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XmbLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False

**Comment by jordansissel** [comment]
I tried to reproduce and get some more data today, and I found one interesting clue -- 

```
state 0x4
```

This means the control key was active. At the time, I wasn't pressing the control key, so I'm thinking somehow the X server thought this key was active?

Today, I'm unable to reproduce this.  I'll report back if I'm able to reproduce it.

**Comment by jordansissel** [comment]
Ahh found a way to reproduce it.

I did:

1. Open Windows Terminal
2. Run `bash`
3. Run `xev`
4. Type a few things in the xev window
5. Focus the Windows Terminal, press Ctrl+C to terminate `xev` then release the keyboard
6. Run `xev` again
7. Press `a` in the xev window.

I haven't quite figured it what state (XWayland, Weston, etc) gets confused and believes the control key is pressed.

**Comment by hideyukn88** [comment]
@jordansissel, thanks for update. I think you are getting the combination two issues, because of the issue https://github.com/microsoft/wslg/issues/207, "ctrl" key remain pressed state after terminal is terminated, then because of the issue https://github.com/microsoft/wslg/issues/423#issuecomment-904230247, the Lookup locates the string with CTRL pressed, thus I can get below, too. https://github.com/microsoft/wslg/issues/207 is fixed (but not released yet), and I will look into latter issue, thanks!

KeyPress event, serial 34, synthetic NO, window 0x1000001,
    root 0x512, subw 0x0, time 105576247, (267,-843), root:(2522,538),
    state 0x14, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (01) ""
    XmbLookupString gives 1 bytes: (01) ""
    XFilterEvent returns: False

**Comment by jordansissel** [comment]
One small update, the input does indeed seem buffered per your other issue links (thanks!):

Running xev and pressing just the 'a' key results in a Control_L KeyPress event just before the "a" KeyPress.

```
KeyPress event, serial 31, synthetic NO, window 0x400001,
    root 0x39b, subw 0x0, time 1178819, (-250,-142), root:(891,445),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x400001,
    root 0x39b, subw 0x0, time 1179040, (-250,-142), root:(891,445),
    state 0x4, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (01) ""
    XmbLookupString gives 1 bytes: (01) ""
    XFilterEvent returns: False
```

**Comment by jordansissel** [comment]
In this case, XLookupString is correctly interpreting (state 0x4 keysym 0x61) as "control+a" and returning 0x01 byte value.

I think we can close as the same as #207. Thanks for the quick response :)
