### ISSUE TITLE
Window doesn't restore after disconnecting from docking station

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/wslg#444]
# Environment

```none
Windows build number: 10.0.22451.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.27
```

# Steps to reproduce

These steps are done on a SB3 - I'm unsure whether it happens for all devices or not.

1. Startup Linux GUI app while plugged into docking station
2. Unplug computer from docking station

**WSL logs**: 

[weston.log](https://github.com/microsoft/wslg/files/7136900/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/7136901/pulseaudio.log)
[versions.txt](https://github.com/microsoft/wslg/files/7136902/versions.txt)

Link to Feedback Hub issue: https://aka.ms/AAdsfdv

#  Expected behavior

My GUI app would still be in the foreground of my desktop, or at least I could restore it from the taskbar. 

# Actual behavior

The app is no longer in the foreground. It shows on my taskbar, but I can't restore it:

![image](https://user-images.githubusercontent.com/9649518/132695817-8eeef5fd-9e45-4ada-9bd4-a701c0bfe78d.png)

Edit: adding repro steps and link to feedback hub

**Comment by hideyukn88** [comment]
This is dup to https://github.com/microsoft/wslg/issues/1092.
