### ISSUE TITLE
GUI apps on Windows 11 does not follow primary mouse button settings

### ISSUE THREAD

**Issue by saschanaz** [microsoft/wslg#458]
### Windows Build Number

22000.184

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

Ubuntu 21.04

### Other Software

Firefox 92.0
Chrome 93.0
Gnome Web (Epiphany) 40.1

### Repro Steps

1. Set the primary mouse button as right
2. Run any of the above apps installed on Ubuntu
3. Click anything

### Expected Behavior

Right click should be a primary click on Ubuntu as it is on Windows

### Actual Behavior

It becomes a secondary click and opens a context menu

**Comment by hideyukn88** [comment]
@saschanaz, thanks for reporting the issue, this is reported at https://github.com/microsoft/wslg/issues/74, and is fixed in WSLg release 1.0.27 or newer. Please update and try again, thanks!

**Comment by saschanaz** [comment]
`wsl --update` says no update are available 👀 and how can I check WSLg version?

**Comment by hideyukn88** [comment]
@saschanaz, you can find WSLg version at /mnt/wslg/versions.txt. Thanks!

**Comment by saschanaz** [comment]
```
> wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 13/09/2021
WSL automatic updates are on.

Kernel version: 5.10.43

> ubuntu
$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

Seems it's not released yet, I'll wait then.

**Comment by hideyukn88** [comment]
@saschanaz, right, it's marked as pre-release at https://github.com/microsoft/wslg/releases, so it hasn't been distributed by Windows Update or 'wsl --update' yet. thanks!

**Comment by janpfeifer** [comment]
Is there any news on this issue ? I just updated (and rebooted) wsl.

**Comment by janpfeifer** [comment]
Answering my own question, the current default release of WSLg is still 1.0.26 from 2021-02-24. I'll try to figure out how to install the pre-release versions of WSLg.

**Comment by janpfeifer** [comment]
Thanks @hideyukn88 , I instead downloaded the pre-release 1.0.28 from WSLg from github, and it worked, fixing the issue.
