### ISSUE TITLE
Is it possible to start gui app in windows with scale factor

### ISSUE THREAD

**Issue by frankli998** [microsoft/wslg#46]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the I start linux gui applications from start menu in windows without scaling factor. In wsl, once
```
export QT_SCALE_FACTOR=2
export GDK_SCALE=2
```
are set, gui apps (for example gvim) can start with factor. But in windows, can't start with scaling factor.
![image](https://user-images.githubusercontent.com/16791452/115768113-72dab300-a3dc-11eb-9a2a-f5c22d9104e0.png)

**Describe the solution you'd like**

add an cmd line option to start app with scaling  factor so I can change the shortcut `C:\Windows\System32\wslg.exe ~ -d openSUSE-Tumbleweed gvim -f ` 

**Additional context**

**Comment by hideyukn88** [comment]
@frankli998 , just for clarification, how do you set below environment variables? Is it done from ~/.profile?

export QT_SCALE_FACTOR=2
export GDK_SCALE=2

**Comment by frankli998** [comment]
@hideyukn88 I set it in ~/.bashrc

**Comment by spronovo** [comment]
This has been addressed starting with Windows Insider Build 21387 which was released earlier this week. By default application from the start menu will now launch as if they had been launch from the user shell.
