### ISSUE TITLE
GUI apps hang up on start when `/etc/wsl.conf` has `root=/`

### ISSUE THREAD

**Issue by fsoikin** [microsoft/wslg#48]
# Environment

```none
Windows build number: 10.0.21364.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: I don't have 'Windows Subsystem for Linux GUI app support', but I do have this: 
```
![image](https://user-images.githubusercontent.com/4219105/115769811-f911dd80-a379-11eb-9bfd-7bd9a93dbf22.png)

# Steps to reproduce
0. Set host mount point to root: `/etc/wsl.conf` -> `[automount]` -> `root=/`
1. Enable WSLg:
    * Remove `guiApplications=false` from `.wslconfig`
    * `wsl --shutdown`
2. Run any GUI app. 
    * In my example I use `gnome-system-monitor` and `firefox`, but it also works with everything else I tried.

**WSL logs**: 
* Attach WSLg logs from  `/mnt/wslg`
    * I don't have a `/mnt/wslg` directory, which I'm assuming is because I changed the host mount point from `/mnt` to `/`.
    * I do indeed have a `/wslg` directory, but it's empty.

#  Expected behavior
The app should start normally and display a window. See below a recording of how that happens with VcXsrv.

# Actual behavior
1. The app doesn't print any errors.
2. But it also doesn't print any of its normal output, which would indicate that it's working, but invisible.
3. No new windows appear on the screen.
4. No second instance of `vmmem` in the process list (as reported by Windows Task Manager).
    * I'm assuming a second instance of `vmmem` should appear, because the docs say the whole thing works by starting a second WSL2 distro.
5. `DISPLAY` and `WAYLAND_DISPLAY` variables are present and look fine.

# Issue in WSLg
![doesnt](https://user-images.githubusercontent.com/4219105/115771594-25c6f480-a37c-11eb-9676-482f1e65d6d2.gif)

# Working normally via VcXsrv
![works](https://user-images.githubusercontent.com/4219105/115771559-1b0c5f80-a37c-11eb-8fcf-8943ee4f096d.gif)

**Comment by hideyukn88** [comment]
@fsoikin , thanks for reporting this, can you try "wsl --system" to check if system-distro has started ? and if it is, can you check log files under /mnt/wslg from system-distro ? thanks!

**Comment by fsoikin** [comment]
Indeed the system distro is running, and it has a bunch of stuff under `/mnt/wslg`:

```
root@DESKTOP-76URT0L [ /mnt/c/w ]# ls /mnt/wslg                                                                
PulseAudioRDPSink  PulseAudioRDPSource  PulseServer  doc  pulseaudio.log  runtime-dir  versions.txt  weston.log
```

I didn't know which one you needed, so here are `weston.log` and `versions.txt`, let me know if you need any others.

[versions.txt](https://github.com/microsoft/wslg/files/6361018/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/6361019/weston.log)

**Comment by fsoikin** [comment]
Update: 

* I was able to confirm that changing my host mount point from `/` back to `/mnt/` makes WSLg work as expected (though the windows don't respond to Alt+F4 for some reason, but that's minor).
* I also tried changing to to anything else, like `/bogus/` - and that also works. Which means that the problem is specifically with having it at root.

**Comment by spronovo** [comment]
@benhillis looks like an issue in init, can you take a peek when you have a chance.

**Comment by benhillis** [comment]
Yep I'll take a look.

**Comment by stehufntdev** [comment]
@fsoikin thanks for reporting the issue.  I tried to repro this locally on a recent internal build but I was unable to do so.  When you have a chance can you check the steps I took to see if there is anything different:

1.) Create /etc/wsl.conf with the following:
[automount]
enabled = true
root = /
options = "metadata,umask=22,fmask=11"
mountFsTab = false

2.) Restart WSL (e.g. sc stop lxssmanager, ...)

3.) Launch wsl and run xeyes

4.) Confirm that xeyes is running as a wslg application

There aren't a lot of differences between the internal build I am running and 10.0.21364.0 so I don't suspect that would make a difference.

**Comment by fsoikin** [comment]
Well, I don't know a lot about WSL inner workings, but one difference I can point out is that my `[automount]` section has only `root` and nothing else.

**Comment by stehufntdev** [comment]
Thanks for the quick reply!  For the [automount] section above I just copy\pasted from the documentation - https://docs.microsoft.com/en-us/windows/wsl/wsl-config.  Also, I updated wsl.conf to only have the root field under [automount] and everything still worked fine when running xeyes.

Since this is only hitting for you when setting the root field to the root filesystem, are you able to share the the contents of your root folder (e.g. `ls -lhA /`)?

**Comment by fsoikin** [comment]
Sure, here you go (I also included `/wsl` and `/wslg` just in case):

```
~
 λ ls -lhA /
total 2.2M
lrwxrwxrwx   1 root root    7 Aug  4  2020 bin -> usr/bin
drwxr-xr-x   5 root root 4.0K Apr 22 16:30 bogus
drwxr-xr-x   2 root root 4.0K Aug  4  2020 boot
drwxrwxrwx   1 name name 4.0K Apr 22 10:58 c
drwxr-xr-x   8 root root 2.8K Apr 22 16:37 dev
drwxr-xr-x 111 root root 4.0K Apr 22 16:37 etc
drwxr-xr-x   3 root root 4.0K Feb  2 14:52 home
-rwxr-xr-x   2 root root 1.4M Apr 17 09:06 init
lrwxrwxrwx   1 root root    7 Aug  4  2020 lib -> usr/lib
lrwxrwxrwx   1 root root    9 Aug  4  2020 lib32 -> usr/lib32
lrwxrwxrwx   1 root root    9 Aug  4  2020 lib64 -> usr/lib64
lrwxrwxrwx   1 root root   10 Aug  4  2020 libx32 -> usr/libx32
drwx------   2 root root  16K Apr 10  2019 lost+found
drwxr-xr-x   2 root root 4.0K Aug  4  2020 media
drwxr-xr-x   5 root root 4.0K Apr 22 16:27 mnt
drwxr-xr-x   5 root root 4.0K Apr 22 16:28 mntt
drwxr-xr-x   4 name root 4.0K Feb 27 23:10 nix
drwxr-xr-x   2 root root 4.0K Aug  4  2020 opt
dr-xr-xr-x 348 root root    0 Apr 22 16:37 proc
drwx------   5 root root 4.0K Apr 22 16:31 root
drwxr-xr-x   8 root root  220 Apr 22 16:38 run
lrwxrwxrwx   1 root root    8 Aug  4  2020 sbin -> usr/sbin
drwxr-xr-x   2 root root 4.0K Jul 10  2020 snap
drwxr-xr-x   2 root root 4.0K Aug  4  2020 srv
dr-xr-xr-x  11 root root    0 Apr 22 16:37 sys
drwxrwxrwt 159 root root 732K Apr 23 14:44 tmp
drwxr-xr-x  14 root root 4.0K Aug  4  2020 usr
drwxr-xr-x  13 root root 4.0K Aug  4  2020 var
drwxrwxrwt   5 root root  120 Apr 22 16:38 wsl
drwxr-xr-x   2 root root 4.0K Apr 22 10:59 wslg
~
 λ ls -lhA /wslg
total 0
~
 λ ls -lhA /wsl
total 4.0K
drwxr-xr-x 4 root root 100 Apr 22 16:38 docker-desktop
drwxr-xr-x 3 root root  60 Apr 22 16:38 docker-desktop-bind-mounts
drwxr-xr-x 6 root root 120 Apr 22 16:38 docker-desktop-data
-rw-r--r-- 1 root root 196 Apr 22 16:37 resolv.conf
~
 λ
```

**Comment by fsoikin** [comment]
Oh, I just noticed in that listing `/mnt`, `/mntt`, and `/bogus` - those are three places that I tried out as the host mount point, and WSLg worked with all three. Right now they contain empty mount points:

```
~                                            
 λ ls /bogus -lhA                            
total 12K                                    
drwxrwxrwx 2 root root 4.0K Apr 22 16:30 c   
drwxr-xr-x 2 root root 4.0K Apr 22 16:30 wsl 
drwxr-xr-x 2 root root 4.0K Apr 22 16:30 wslg
~                                            
 λ ls /bogus/c -lhA                          
total 0                                      
~                                            
 λ                                           
```

**Comment by stehufntdev** [comment]
Thanks for sharing the output.  It looks like the /wslg folder isn't being mounted correctly as it should be non empty, 'drwxrwxrwt' instead of 'drwxr-xr-x', ...

I'm going to ask around internally to see if anyone can get a repro, but in the meantime can you please share out the output from `mount` and `dmesg` so we can see if there are any breadcrumbs?

**Comment by fsoikin** [comment]
Sure, here you are.

[mount.log](https://github.com/microsoft/wslg/files/6377631/mount.log)
[dmesg.log](https://github.com/microsoft/wslg/files/6377632/dmesg.log)

**Comment by fsoikin** [comment]
And here's the output of `mount` when host is mounted at `/mnt`. As you can see it does contain `wslg` now.

[better-mount.log](https://github.com/microsoft/wslg/files/6377665/better-mount.log)

**Comment by benhillis** [comment]
@fsoikin - Are you positive that's the dmesg from the non working instance?  Looking through the wslg mount code I don't see how you could be in this state without an error message printed.

**Comment by benhillis** [comment]
@fsoikin - I tried this as well with both Alpine and Ubuntu and was unable to repro. Must be missing something specific to your environment.

**Comment by fsoikin** [comment]
Yes, those `mount.log` and `dmesg.log` have been produced one right after another, without anything at all happening in between.

The `better-mount.log` was produced after changing `root` to `/mnt` in `/etc/wsl.conf` and restarting WSL.

**Comment by benhillis** [comment]
Can you share the entire contents of /etc/wsl.conf and %userprofile%\.wslconfig?

**Comment by fsoikin** [comment]
Sure, here you go:

```
 λ cat /etc/wsl.conf                                                                                                                                                                                                 
[automount]                                                                                                                                                                                                          
root=/                                                                                                                                                                                                               
                                                                                                                                                                                                                     
[user]                                                                                                                                                                                                               
default=name                                                                                                                                                                                                         
                                                                                                                                                                                                                     
~                                                                                                                                                                                                                    
 λ cat /c/Users/name5/.wslconfig                                                                                                                                                                                     
[wsl2]                                                                                                                                                                                                               
memory=24GB                                                                                                                                                                                                          
swap=24GB                                                                                                                                                                                                            
```

Note that this is the state of `.wslconfig` specifically made for reporting this issue.
Normally, when I have to do actual work, I also add `guiApplications=false` at the end, so that I can use VcXsrv.

**Comment by benhillis** [comment]
@fsoikin - could you share the output of the following two commands?

```
wsl.exe -u root cat /proc/1/environ
wsl.exe --system cat /proc/1/environ
```

**Comment by fsoikin** [comment]
Here you go:

```
>  wsl.exe -u root cat /proc/1/environ
WSL2_CROSS_DISTRO=/wslpAHfHpWSL2_GUI_APPS_ENABLED=1WSL2_SYSTEM_DISTRO_SHARE=/wslDHbLPK
>  wsl.exe --system cat /proc/1/environ
WSL2_CROSS_DISTRO=/wslAmFFMfWSL2_GUI_APPS_ENABLED=1WSL2_SYSTEM_DISTRO_SHARE=/wsleJIociWSL2_VM_ID=27DA73EB-39A9-405F-AAF5-898C3B46BA40WSL2_DISTRO_NAME=Ubuntu-20.04WSL2_SHARED_MEMORY_OB_DIRECTORY=WSL\27DA73EB-39A9-405F-AAF5-898C3B46BA40\wslg
```

**Comment by benhillis** [comment]
Thanks for all the info, we're having a hard time reproducing here but I'll keep trying things.

**Comment by fsoikin** [comment]
Hi again guys!

I'm happy to report that issue has resolved itself: GUI apps are working as expected and all the logs are in place.
Closing the issue.
