### ISSUE TITLE
cannot launch any gui apps

### ISSUE THREAD

**Issue by w93163red** [microsoft/wslg#496]
# Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

Not sure if related to my previous GUI installation. I have tried to remove all of them.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

* `puseaudio.log`
* `weston.log`
* `versions.txt`
[stderr.log](https://github.com/microsoft/wslg/files/7314700/stderr.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/7314702/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/7314704/weston.log)

versions.txt

``` 
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

#  Expected behavior

Should launch the GUI apps like gedit
# Actual behavior

did not launch any GUI apps

**Comment by bhardwajs** [comment]
I am not able to open gui apps too. Seeing an error like
```
gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed
```
Search tells me this might be related to `wayland` https://github.com/swaywm/wlroots/issues/103
I don't see that in your logs though.

**Comment by w93163red** [comment]
I also have this error on the terminal but not in the wslg log

**Comment by w93163red** [comment]
I used wsl --update to update my ubuntu but previously I had installed xbuntu ( i have removed it), not sure if it caused problems.

**Comment by w93163red** [comment]
Oh, you are right... After I removed the file, it works. I also removed the gdm and xorgrdp to make it work. Hope it helps people who found this issue

**Comment by bhardwajs** [comment]
Maybe, we should have a different bug that points to the options for debugging providing a config that makes WSLg inoperational. Let me do that.
