### ISSUE TITLE
non-Latin characters can't be displayed correctly in window title 

### ISSUE THREAD

**Issue by hideyukn88** [microsoft/wslg#5]
# Environment

```none
Windows build number: 21340
Your Distribution version: Ubuntu
Your WSLg version: 0.2.13
```

# Steps to reproduce

Install any application can display non-Latin characters to window title, such as Spotify.
(In this repro step, Spotify is used)
Install Spotify
Launch Spotify
Select song/artist which include non-Latin characters.
Window title should show song/artist name, but when those contains non-Latin characters, it shows as "box".

![image](https://user-images.githubusercontent.com/13857962/112341834-fe96dd80-8c7e-11eb-9d93-a01df8ef2d6d.png)

#  Expected behavior

non-Latin characters should be shown correctly.

**Comment by PhyX-Meow** [comment]
Same issue here.
But actually I have non-Latin fonts:
```
❯ fc-list | ag sourcehansans-normal
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: 思源黑體 香港,Source Han Sans HC,Source Han Sans HC Normal,思源黑體 香港 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: 思源黑体,Source Han Sans SC,Source Han Sans SC Normal,思源黑体 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans,源ノ角ゴシック,Source Han Sans Normal,源ノ角ゴシック Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: Source Han Sans K,본고딕,Source Han Sans K Normal,본고딕 Normal:style=Normal,Regular
/usr/share/fonts/adobe-source-han-sans/SourceHanSans-Normal.ttc: 思源黑體,Source Han Sans TC,Source Han Sans TC Normal,思源黑體 Normal:style=Normal,Regular
```

**Comment by hideyukn88** [comment]
@PhyX-Meow , the window title bar is rendered by system-distro, thus fonts needs to be installed inside system-distro but currently system-distro is not user configurable (such as installing other international fonts).

**Comment by lwldcr** [comment]
Same issue. 
Is this problem going to be fixed in any later releases?

**Comment by hideyukn88** [comment]
@PhyX-Meow, @lwldcr, FYI: we made a change to system-distro to load from Windows by https://github.com/microsoft/wslg/pull/266, thus as long as fonts for required language are installed at Windows side, it will be used. (note: system-distro does not load fonts from user-distro). Also, by https://github.com/microsoft/weston-mirror/pull/22, pango will fallback for international text. Thanks for trying out WSLg!
