### ISSUE TITLE
wsl does not run in a windows command window (in admin mode).

### ISSUE THREAD

**Issue by jimrome** [microsoft/wslg#50]
wsl does not run in a windows command window (in admin mode). One must run wsl.exe

**Comment by spronovo** [comment]
@jimrome could you clarify what you mean?

**Comment by jimrome** [comment]
you must type wsl.exe or nothing happens. wsl alone is not found.

James A. Rome

***@***.***
https://blogs.jamesrome.net

**Comment by spronovo** [comment]
you mean if you type something like below you get an error file not found error unless you type wsl.exe instead of wsl?

```
C:\WINDOWS\system32>wsl --list --online
The following is a list of valid distributions that can be installed.
Install using 'wsl --install -d <Distro>'.

NAME            FRIENDLY NAME
Ubuntu          Ubuntu
Debian          Debian GNU/Linux
kali-linux      Kali Linux Rolling
openSUSE-42     openSUSE Leap 42
SLES-12         SUSE Linux Enterprise Server v12
Ubuntu-16.04    Ubuntu 16.04 LTS
Ubuntu-18.04    Ubuntu 18.04 LTS
Ubuntu-20.04    Ubuntu 20.04 LTS
```

Could you try running

```
where wsl
```
Does it display "C:\Windows\System32\wsl.exe", or does it pick up a wsl.cmd script somewhere on your path maybe?
