### ISSUE TITLE
Does not work with Open SUSE LEAP 15.2

### ISSUE THREAD

**Issue by jimrome** [microsoft/wslg#51]
**Is your feature request related to a problem? Please describe.**
C:\WINDOWS\system32>wsl.exe --list --online
The following is a list of valid distributions that can be installed.
Install using 'wsl --install -d <Distro>'.

NAME            FRIENDLY NAME
Ubuntu          Ubuntu
Debian          Debian GNU/Linux
kali-linux      Kali Linux Rolling
openSUSE-42     openSUSE Leap 42
SLES-12         SUSE Linux Enterprise Server v12
Ubuntu-16.04    Ubuntu 16.04 LTS
Ubuntu-18.04    Ubuntu 18.04 LTS
Ubuntu-20.04    Ubuntu 20.04 LTS

**Describe the solution you'd like**
The SUSE Leap 42 listed is ancient and unsupported for security patches
**Describe alternatives you've considered**
I hate Ubuntu distros!
**Additional context**

**Comment by rwilliams** [comment]
Here's some resources for troubleshooting opensuse as well as installing tumbleweed if that's of interest to you.

https://boxofcables.dev/why-do-apps-look-weird-on-wslg-on-opensuse/

https://boxofcables.dev/install-opensuse-tumbleweed-on-wsl/

**Comment by spronovo** [comment]
@jimrome thanks for your interest in WSLg. For generic wsl question such as wsl --list --online, it is best to take those up on the core WSL project at http://github.com/microsoft/wsl. Please note that the various Linux distro publisher decide which of their distro they want to target and package for WSL... wsl --list --online gives you a list of distro that publisher have decided to package using a new package technology. You can also find additional WSL distro in the Microsoft App Store. It looks like OpenSUSE Leap 15.2 isn't available as a --install target, but it is available for install through the Microsoft App Store.
