### ISSUE TITLE
The key input keeps being entered when I launch tool in WSLg.

### ISSUE THREAD

**Issue by GrapeJuicer** [microsoft/wslg#512]
# Environment

```none
Windows build number: 10.0.22000.258
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
Emacs version: 26.3
```

# Steps to reproduce

- Launch GUI tools. ex: emacs
- Creating a Window with OpenCV in C++. ex: cv::imshow()

**WSL logs**: 

- [pulseaudio.log](https://github.com/microsoft/wslg/files/7355628/pulseaudio.log)
- [weston.log](https://github.com/microsoft/wslg/files/7355618/weston.log)
- versions.txt
```
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```
- [stderr.log](https://github.com/microsoft/wslg/files/7355748/stderr.log)

#  Expected behavior

Be like:
![image](https://user-images.githubusercontent.com/57088986/137545818-bb8439f1-804f-406c-857c-6d40f10e419e.png)

# Actual behavior

Be like:
![image](https://user-images.githubusercontent.com/57088986/137545614-c6bbce1f-1a41-4f21-8f57-affa14f5aa3c.png)

When a file is specified as an argument, it often looks like this:
![image](https://user-images.githubusercontent.com/57088986/137547009-a331296d-30c6-43e7-9f99-4c9f47ad3e40.png)

Look at the bottom of the window. It says, `"C-c C-c is undefined"`. Sometimes `"c is undefined"`, `"x is undefined"`, etc ...
After trying several times, it seems that the key that was entered just before closing the previous window is entered the next time the window is launched. 
In the `stderr.log`, there is also a log showing that the key is being typed at high speed.
If you type any key other than Ctrl or Shift, it stops.
When launched with `emacs -nw`, this problem does not occur.

**Comment by hideyukn88** [comment]
@GrapeJuicer, thanks for reporting the issue, this is reported at https://github.com/microsoft/wslg/issues/207, and partially fixed already except key modifier which is described at https://github.com/microsoft/wslg/issues/207#issuecomment-938757008. Thanks!
