### ISSUE TITLE
cut and paste does not work

### ISSUE THREAD

**Issue by jimrome** [microsoft/wslg#52]
# Environment
 [Version 10.0.21364.1]  Ubuntu 20.4
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce
Opened these wsl instructions in Windows EdgeDev. marked and copied command.
Went to Ubunto shell. 
command V just prints out ^V
But the top-left menu edit paste works. It say

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl\<Distro-Name>\mnt\wslg` (eg: `\\wsl\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by hideyukn88** [comment]
@jimrome, just for clarification, so cut & paste does work using menu, but it does not by Windows shortcut, Ctrl+V ? If that's case, this can be by design since Windows short cut key combination might not be understood by Ubuntu shell.

**Comment by BSalita** [comment]
Try ctrl-shift-v

**Comment by jimrome** [comment]
I did. It did not work

James A. Rome

***@***.***
https://blogs.jamesrome.net

**Comment by spronovo** [comment]
There are known limitation with the old command prompt. Give **Windows Terminal** a try, ctrl+V should work right up and overall you'll have a much better experience. Scott has some pretty good video on how to customize it and make it your own as well. Check-out https://www.youtube.com/watch?v=oHhiMf_6exY.

**Comment by crramirez** [comment]
Be sure that this is checked
![image](https://user-images.githubusercontent.com/8397379/115857220-b578ab80-a42d-11eb-8c3a-a77c010e6c77.png)

**Comment by jimrome** [comment]
I was doing the paste into the Ubuntu window, not command.exe

James A. Rome

***@***.***
https://blogs.jamesrome.net

**Comment by crramirez** [comment]
![image](https://user-images.githubusercontent.com/8397379/115876797-09dc5500-a447-11eb-9f92-2912f8ed9581.png)

**Comment by jimrome** [comment]
Yes, this worked

James A. Rome

https://blogs.jamesrome.net
