### ISSUE TITLE
Unable to init server: Could not connect: Connection refused (gedit:1859): Gtk-WARNING :  cannot open display:)

### ISSUE THREAD

**Issue by neuberfran** [microsoft/wslg#522]
Can anyone help-me with this issue:
**Unable to init server: Could not connect: Connection refused
(gedit:1859): Gtk-WARNING : 18:14:00.048: cannot open display:

**wsl --update**
Checking for updates...
There are no updates available.
Versão do kernel: 5.10.60.1

**wsl -l -v**
```
NAME                            STATE           VERSION
* Ubuntu                        Running          2
 docker-desktop            Running          2
 docker-desktop-data    Running          2
```

**in PowerShell 7 I have this result When I try found CBL Mariner**
PS C:\Users\neuberfran> wsl --system
**There is no distribution with the given name.**

![wslG-ubuntu2004-ISSUE](https://user-images.githubusercontent.com/38701397/137767905-728f94f7-2bec-414c-8cf5-8c14d3a0e4b9.jpg)

**I tried this:**

https://stackoverflow.com/questions/60284542/wsl-gedit-unable-to-init-server-could-not-connect-connection-refused

But not solved

**Comment by meyayl** [comment]
Hav you checked https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg?

Most likely either /tmp/.x11-daemon is a directory instead of a symlink to /mnt/wslg/.X11-unix and/or the required environment variables are missing.

**Comment by meyayl** [comment]
The output of `ls -la /tmp` would've been helpful. In all my wslg instances it is always x0, not x10. 
The non existing /tmp/wslg folder is odd?
You performed `wsl --update` and `wsl --shutdown` to actualy replace the updated system distro?

**Comment by meyayl** [comment]
Can't realy help you. You installation looks way different then mine. 

I spend a good share of the weekend to understand how to make wslg work in my custom wsl distro. Though, what was the solution there, seem not to be the solution for you.

**Comment by neuberfran** [comment]
@meyayl  What are you trying to say with my custom wsl distro?

Unfortunately the real solution here might be to reinstall wsl2/ubuntu. But I have several things in it that will need to be reinstalled.

**Comment by meyayl** [comment]
> @meyayl What are you trying to say with my custom wsl distro?

Nothing. Just that I spend a lot of time to research how the wsgl integration is done - and your case looks completly different.

I am not sure if reinstalling ubuntu will heal the problems with the system distribution. With wslg each user distribution has a sibling system distribution (see https://www.youtube.com/watch?v=EkNBsBx501Q&t=2105s in case of questions) - in you case the system distribution doesn't seem to work as it should, otherwise /mnt/wslg would exist.

Good luck!

**Comment by neuberfran** [comment]
@onomatopellan 
![issuewsl2store](https://user-images.githubusercontent.com/38701397/137961534-7c395b7c-f0f3-4b48-bca0-09feb550ce0f.png)


I found the  XServer - GWSL(Opticos Studios)
app in MS Store
I just tried it and I liked it. But I prefer use app directly from the command line of wsl2/ubuntu

**Comment by neuberfran** [comment]
I Solved with XLaunch: https://faithcov.org/images/ubuntu/WSL-2-Run-Graphical-Linux-Desktop-Applications-from-Windows-10-Bash-Shell-Error-E233-cannot-open-display.png

XLaunch/VcXsrv
1) Multiple screen
2) Start a program
3) Start program on remote computer
4)  export DISPLAY_NUMBER='0.0' export DISPLAY=$(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):$DISPLAY_NUMBER export LIBGL_ALWAYS_INDIRECT=1 # OPTIONAL Set the keyboard layout to US setxkbmap -layout us setsid emacs exit

in wsl2/ubuntu 20.04

**Comment by neuberfran** [comment]
@onomatopellan 

PS C:\Users\neuberfran> wsl --status
Default Distribution: docker-desktop-data
Default Version: 2
Versão do WSL: 0.48.2.0
Versão do kernel: 5.10.60.1
Versão do WSLg: 1.0.29
Versão do Windows: 10.0.22478.1012
PS C:\Users\neuberfran> wsl --version
Versão do WSL: 0.48.2.0
Versão do kernel: 5.10.60.1
Versão do WSLg: 1.0.29
Versão do Windows: 10.0.22478.1012
PS C:\Users\neuberfran> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  docker-desktop         Running         2
  Debian                 Stopped         2
  Ubuntu-20.04           Stopped         2
PS C:\Users\neuberfran> wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  docker-desktop         Running         2
  Debian                 Stopped         2
  Ubuntu-20.04           Running         2

![issueanswers](https://user-images.githubusercontent.com/38701397/138299415-39163bad-e8d1-49a9-a40d-688d48c5b039.png)

**Comment by neuberfran** [comment]
@onomatopellan notepad $env:USERPROFILE/.wslconfig In PowerShell show ok.

**Comment by onomatopellan** [comment]
@neuberfran Then that's the problem. Put a # in front of the last line like this
```
[wsl2]
#guiApplications=false
```
and save the file. After running `wsl.exe --shutdown` and running wsl again then `gedit` should work.

**Comment by afcruzs** [comment]
@spronovo thanks for that wiki link! that worked for me to realize the symlink of the socket wasn't created. I think is worth to put it on the main README.
