### ISSUE TITLE
Constant high CPU load after (dis)connecting an external display

### ISSUE THREAD

**Issue by galiovsky** [microsoft/wslg#528]
# Environment

Windows build number: 10.0.22000.282
Your Distribution version: not distro specific (reproduced both on Fedora 34 and Ubuntu 20.04)
Your WSLg version: 1.0.26 (the issue has been hitting me on previous versions too)

Ryzen 4650U with integrated graphics. Issue persists across multiple driver versions.
Both screens 1920x1080, one scaled at 100 %, the other 125 %, vertically arranged.

# Steps to reproduce

1. Run a distro, can be freshly booted. No need to run any apps.
2. While the distro is running, connect an external display. (Or if you have one attached already, disconnect it.)

**WSL logs**: 

* [weston.log](https://github.com/microsoft/wslg/files/7386583/weston.log)
* [versions.txt](https://github.com/microsoft/wslg/files/7386588/versions.txt)
* [wsl.etl.zip](https://github.com/microsoft/wslg/files/7386627/wsl.etl.zip)

#  Expected behavior

Nothing unusual happens.

# Actual behavior

Vmmem starts to load one CPU core 100% constantly until Ctrl+Shift+Win+B is pressed or WSL is shut down altogether.

For more reports, see https://github.com/microsoft/WSL/issues/6982.

**Comment by hideyukn88** [comment]
@galiovsky, thanks for trying out WSLg, It looks your versions.txt shows you are on WSLg ( x86_64 ): 1.0.24, which is very old version, would you please update to the latest version? You can install from https://github.com/microsoft/wslg/releases, or even better, install from Store, please refer https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/. Thanks!
