### ISSUE TITLE
Using WSLg vGPU in docker desktop - no gpu acceleration

### ISSUE THREAD

**Issue by jnewb1** [microsoft/wslg#531]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.282]
Your Distribution version: Ubuntu 20.04, Docker Desktop V4.1.1
Your WSLg version: 1.0.26
```

# Steps to reproduce

Create a simple ubuntu docker container (which contains mesa 21 drivers), and attempt to run glxinfo -B.
This repo contains the scripts and dockerfile for this container: https://github.com/jnewberry0502/vgpu-docker-wslg-testing

#  Expected behavior

The docker container can use the vGPU for acceleration using the D3D12 mesa driver, as can be seen in my local ubuntu

# Actual behavior

/dev/dxg seems to be mounted to the container correctly
GUI apps show up in windows as they should
No gpu acceleration is happening
Attempting to manually force the d3d12 gallium driver crashes glxinfo

```
+ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 12.0.0, 256 bits) (0xffffffff)
    Version: 21.0.3
    Accelerated: no
    Video memory: 15966MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.0.3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

+ GALLIUM_DRIVER=d3d12
+ glxinfo -B
name of display: :0
libGL error: failed to create dri screen
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  148 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  58
  Current serial number in output stream:  59
```

[DxDiag.txt](https://github.com/microsoft/wslg/files/7392982/DxDiag.txt)

Container running glxgears, connected via wslg to windows:
![image](https://user-images.githubusercontent.com/9648890/138360817-4d245cad-6527-4240-b076-4250cfb81c78.png)

dxg shows up in /dev in the container
![image](https://user-images.githubusercontent.com/9648890/138360970-5a4fc5ab-419c-4013-acc8-8f91bf8016f8.png)

D3D acceleration seems to work properly in normal WSL:
![image](https://user-images.githubusercontent.com/9648890/138361049-3b0235fd-0c8f-47b6-9fd2-a7d3eee29a03.png)

**Comment by 171930433** [comment]
it does not work, 
root@f917d7019c0c:/# ./diagnostics.sh
+ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 10.0.0, 256 bits) (0xffffffff)
    Version: 20.0.8
    Accelerated: no
    Video memory: 15994MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 10.0.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 20.0.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

+ GALLIUM_DRIVER=d3d12
+ glxinfo -B
name of display: :0
libGL error: failed to create dri screen
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  148 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  52
  Current serial number in output stream:  51
+ ls /dev/
console  core  dxg  fd  full  mqueue  null  ptmx  pts  random  shm  stderr  stdin  stdout  tty  urandom  zero
+ glxgears
6567 frames in 5.0 seconds = 1313.270 FPS
6536 frames in 5.0 seconds = 1307.134 FPS
