### ISSUE TITLE
Gui application shows only close button; not minimize and maximize

### ISSUE THREAD

**Issue by gjevardat** [microsoft/wslg#538]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.22000.0 Microsoft Windows NT 10.0.22000.0

Your Distribution version: Release:        20.04
Your WSLg version: 2
```

# Steps to reproduce

Install last eclipse version on Ubuntu. 
Launch it. Works well.

#  Expected behavior

Close button plus minimize and maximize. Dispatch in any Tile of the windows manager would be a must !

# Actual behavior
Only close window options available

**Comment by enigma131** [comment]
I've solved the issue by installing gnome-tweaks. Then launch gnome-tweak, and enable minimize and maximize buttons
