### ISSUE TITLE
Firefox Support Multibyte Font.

### ISSUE THREAD

**Issue by KeitoTobi1** [microsoft/wslg#549]
**Is your feature request related to a problem? Please describe.**
I'm a person in a Japanese environment, and Firefox doesn't support Japanese or multi-byte characters when using WSLg, so this should be addressed as soon as possible.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZhanhuaJin** [comment]
Install asian font not working?

**Comment by KeitoTobi1** [comment]
thx. fixed.
