### ISSUE TITLE
Slic3r GUI doesn't load without GDK_BACKEND=x11

### ISSUE THREAD

**Issue by dxgldotorg** [microsoft/wslg#55]
# Environment

```none
Windows build number: 10.0.21364.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce
Start Slic3r in GUI mode with command line slic3r --gui

**WSL logs**: 
[pulseaudio.log](https://github.com/microsoft/wslg/files/6361969/pulseaudio.log)
[versions.txt](https://github.com/microsoft/wslg/files/6361971/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/6361972/weston.log)

#  Expected behavior

Slic3r opens up its GUI

# Actual behavior

Slic3r gives the error:
```
Fatal Error: wxGLCanvas is only supported on X11 currently.  You may be able to
work around this by setting environment variable GDK_BACKEND=x11 before starting
your program.
Segmentation fault
```

Adding GDK_BACKEND=x11 before the slic3r command allows Slic3r to load.

**Comment by spronovo** [comment]
It appears that wxGLCanvas is not currently supported on Wayland, at least in the version of the component currently packaged with Ubuntu 20.04. WSLg is one of the first Linux desktop environment exposed Wayland by default. If you unset XDG_RUNTIME_DIR & WAYLAND_DISPLAY and run slic3r, it will automatically fallback to X11... or by forcing GDK to use X11 per the error message. You'll need to force the X11 backend until GDK is updated and the update package for Ubuntu 20.04.

**Comment by dxgldotorg** [comment]
I'm guessing if I want wxGLCanvas to support Wayland once merged I probably want to update the distro to 21.04 as a LTS release is unlikely to push newer major versions of software.
