### ISSUE TITLE
Installing WSLg offline

### ISSUE THREAD

**Issue by jax79sg** [microsoft/wslg#559]
# Environment

```none
Disconnected, no internet.
Windows build number: 22000.194
Your Distribution version: Ubuntu 18.04
Your WSLg version: *Missing*
```

# Steps to reproduce
```
wsl --shutdown
./wsl_update_x64.msi
add-appxpackage ubuntu_1804.2020.424.0_x64.appx
wsl
sudo apt update
sudo apt install gedit
gedit
```

**WSL logs**: 
`/mnt/wslg` is empty.

#  Expected behavior

Runs gedit and opens up gedit.

# Actual behavior
```
Unable to init server: Could not connect: Connection refused
(gedit:25): Gtk-WARNING **: 21:42:20.761: cannot open display:
```

**Comment by jax79sg** [comment]
The issue seems to be that i need to connect to windows update in order to install WSLg. Is there an offline package?

**Comment by Biswa96** [comment]
* Preview releases here https://github.com/microsoft/wslg/releases
* Official releases here https://wslstorestorage.blob.core.windows.net/wslblob/wsl_graphics_support_x64.msi

**Comment by jax79sg** [comment]
> * Preview releases here https://github.com/microsoft/wslg/releases
> * Official releases here https://wslstorestorage.blob.core.windows.net/wslblob/wsl_graphics_support_x64.msi

Thanks! this works.
