### ISSUE TITLE
cannot open display

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/wslg#56]
root@correy:/home/correy# gedit
Unable to init server: Could not connect: Connection refused

(gedit:20032): Gtk-WARNING **: 15:19:18.610: cannot open display:
root@correy:/home/correy#

**Comment by crramirez** [comment]
Hello,

Check with `echo $DISPLAY` if the variable is set. You are in root. How did you become root? Did you use sudo -d? Or launched the distro directly in root. Remember that sudo won't pass the environment unless you use sudo -E

Regards,

**Comment by kouzhudong** [comment]
correy@correy:~$ su
Password:
root@correy:/home/correy# echo $DISPLAY

root@correy:/home/correy#

**Comment by gustalima** [comment]
Check if this helps 

https://github.com/microsoft/wslg/issues/57#issuecomment-825545682

**Comment by crramirez** [comment]
Use `sudo -s -E` to become root instead of `su`. It will pass the environment variable

**Comment by spronovo** [comment]
Could you take a peek at to help diagnosing your issue.

https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues

In particular, the DISPLAY environment variable must be set to :0, see wiki for details

**Comment by franciscocandido** [comment]
`Error: Can't open display: :0`

**Comment by SciTechEnthusiast** [comment]
are you using wsl 2 ? https://i.stack.imgur.com/MiBVd.png

**Comment by kouzhudong** [comment]
C:\Users\Administrator>wsl --list -v
  NAME            STATE           VERSION
* Debian          Stopped         1
  SLES-15         Stopped         1
  kali-linux      Stopped         1
  CentOS          Stopped         1
  Ubuntu-18.04    Stopped         1

C:\Users\Administrator>wsl --set-version debian 2
正在进行转换，这可能需要几分钟时间...
有关与 WSL 2 的主要区别的信息，请访问 https://aka.ms/wsl2
由于虚拟磁盘系统限制，无法完成请求的操作。虚拟硬盘文件必须是未压缩和未加密的文件，并且不能是稀疏文件。

**Comment by SciTechEnthusiast** [comment]
yes you are using wsl v1. after set version you have to restart wsl using wsl --shutdown. then start again.

**Comment by kouzhudong** [comment]
C:\Users\Administrator>wsl --list  -v
  NAME          STATE           VERSION
* Debian        Running         2
  kali-linux    Stopped         2

C:\Users\Administrator>



correy@correy:~$ gedit
Unable to init server: Could not connect: Connection refused

(gedit:15): Gtk-WARNING **: 16:34:00.235: cannot open display:
correy@correy:~$

**Comment by kouzhudong** [comment]
correy@correy:~$ echo $DISPLAY

correy@correy:~$ echo $WAYLAND_DISPLAY

correy@correy:~$ echo $PULSE_AUDIO

correy@correy:~$

**Comment by spronovo** [comment]
@kouzhudong what version of Windows are you running? Could you run **winver** on Windows. You need to be on insider build 21364+ for WSLg to be deployed and install on your machine.

Given the above output, i suspect WSLg isn't installed. From your WSL distro could you type

cat /mnt/wslg/version.txt

**Comment by kouzhudong** [comment]
C:\Users\Administrator>ver

Microsoft Windows [版本 10.0.19042.928]

C:\Users\Administrator>

correy@correy:~$ cat /mnt/wslg/version.txt
cat: /mnt/wslg/version.txt: No such file or directory
correy@correy:~$

**Comment by spronovo** [comment]
Thanks @kouzhudong, build 19042.928 is not supported with WSLg. To use WSLg you need to join the [Windows Insider](https://insider.windows.com/en-us/) program and install build 21364+.

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/116239290-0fae9f00-a795-11eb-848a-f1bbb6472a13.png)
