### ISSUE TITLE
wslg is delaying time to load user accounts

### ISSUE THREAD

**Issue by mukeshgurpude** [microsoft/wslg#560]
# Environment

```none
Windows build number: Version 10.0.22000.160
Your Distribution version: 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

- Restart windows, and open Ubuntu console...
- Console opens with `wslg` user
- All other users are missing...
  ![image](https://user-images.githubusercontent.com/55982424/140630942-b9949b73-abf3-466d-9b19-f6a6b95c7aa0.png)
- This problem continues for around 7-10 minutes, and thereafter all wsl is initialized to the normal state with all users and files.
- After full initialization of WSL, `wslg` user disappears
  <img width="588" alt="image" src="https://user-images.githubusercontent.com/55982424/140631046-c85556f3-691b-404c-9a0e-85a43c26185c.png">

#  Expected behavior
WSL should load with all files at start, and wslg should be working in background(If it's taking time to load some stuff)

# Actual behavior
Probably wslg is doing some stuff, delaying loading of files in wsl

**Comment by hideyukn88** [comment]
@benhillis, any clue on this? could this be waiting system-distro to start up, then wslg disappear? but 7-10mins sounds too long.

**Comment by benhillis** [comment]
Something funky definitely going on, I'd have to look at a trace: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually

**Comment by mukeshgurpude** [comment]
I'm trying to recreate this issue, but instead I'm getting another error
Here's the link to feedback: https://aka.ms/AAet3z0

**Comment by mukeshgurpude** [comment]
Yesterday, I upgraded to Build version `10.0.22000.258`.
There's no longer a delay in WSL loading.
It appears that the problem has been resolved.
