### ISSUE TITLE
weston starts crashing once a second when WSLg is started through Windows task scheduler

### ISSUE THREAD

**Issue by aki-k** [microsoft/wslg#564]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.22000.282]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

My target is to run Docker and Nvidia container toolkit in WSL 2.
I enabled systemd in WSL 2 with https://github.com/DamionGans/ubuntu-wsl2-systemd-script (changed the systemd target from basic.target to multi-user.target). At some point weston starts crashing once per second seen in the user distro's "dmesg -Tw"

**WSL logs**: 

* [pulseaudio.log](https://github.com/microsoft/wslg/files/7520871/pulseaudio.log)
* I'll upload the log elsewhere because it's 45 megabytes. [weston.log](https://akik.kapsi.fi/wslg/weston.log)
* [versions.txt](https://github.com/microsoft/wslg/files/7520876/versions.txt)
* [dmesg.txt](https://github.com/microsoft/wslg/files/7520911/dmesg.txt)

#  Expected behavior

weston shouldn't be crashing.

# Actual behavior

I see weston crashing in the user distro but I don't see the process as it's probably running in the system distro and the system load goes up.
dmesg gets filled up with weston stack dumps seen in dmesg.txt above.

**Comment by aki-k** [comment]
The problem was not about that systemd enablement. I'll close this one and try to find the reason.

**Comment by aki-k** [comment]
The problem looks to be coming from Windows task scheduler where from I start WSL 2 at startup of this machine.
If I don't use the task scheduler to start WSL 2, I don't get weston crashing.

I configure the task to run as the same user in Windows than I configured it and select it to run with highest privileges.

**Comment by cyklee** [comment]
@aki-k I am experincing similar problems, with files starting with `RdClientAutoTrace-WppAutoTrace` in `AppData/Local/Temp/DiagOutputDir/RdClientAutoTrace`.

**Comment by aki-k** [comment]
@jamesianberry mentioned that same directory in https://github.com/nullpo-head/wsl-distrod/issues/21 . I wonder why I don't get that directory created on my setup.

**Comment by aki-k** [comment]
@cyklee jamesianberry mentioned that same directory in nullpo-head/wsl-distrod#21 . I wonder why I don't get that directory created on my setup.

**Comment by cyklee** [comment]
@aki-k I ended up writing a bash loop constantly deleting the content of that directory and then moved on to native Linux installation, which IMO is currently more suited for long term deployment than WSL2. I hope this issue goes away as MS updates WSL2.

**Comment by aki-k** [comment]
A kludge to stop weston from running in the wsl system distro:

    C:\>wsl --system
    # chmod 000 /usr/bin/weston

The load doesn't drop too much below 1.00 but maybe this bug will be fixed one day.

**Comment by aki-k** [comment]
weston is not crashing any more
