### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by strarsis** [microsoft/wslg#567]
WSL 2 CUDA support should now also be in Windows 10 non-Insider releases.
Does the same apply for `wslg`? How can I find out whether my Windows 10 (not 11) system supports it?

**Comment by aki-k** [comment]
Microsoft writes on the WSLg github page that you need Windows 11 for WSLg.

https://github.com/microsoft/wslg

Pre-requisites
Windows 11 (build 22000.*) or Windows 11 Insider Preview (builds 21362+)

**Comment by strarsis** [comment]
@aki-k: That's honestly surprising for me as `wslg` existed already for some time and a Windows 10 insider release was mentioned.
Now everything changed to Windows 11...

**Comment by peliz** [comment]
> @aki-k: That's honestly surprising for me as `wslg` existed already for some time and I remember that Windows 10 Insider releases were mentioned as prerequisite.

And for me. they have lied, and they have lost everything they gained

**Comment by AlexAegis** [comment]
I just rolled back from W11 to a fresh W10  after months(!) because W11 is so unbearable. Sad that WSLg is not available even though it was during that insider period.

**Comment by MichaelTrip** [comment]
This is also a very needful thing in WSL2. I am currently limited to a Windows laptop for work. I am a Linux desktop user by default and i use a wide variety of Linux GUI based programs. At this moment i am limited to a Windows 10 laptop fro my company and i can't install Windows 11.

**Comment by hoagsie** [comment]
+1 On the work laptop situation. If this can't be added officially to Windows 10 then I probably won't be able to use this for at least a year before they'll clear a Windows 11 upgrade.

**Comment by IQIUM** [comment]
I think that windows11 isn't useful for me to work and some unbearable problems is crazy for me,but I always look forward to using wslg in win10, why not push a new way to make a support for win10?

**Comment by tkonsta** [comment]
For everyone who is interested in some facts: In the issue #347 there is a broad explanation about why WSLg is currently not working on Windows 10 (deep link: https://github.com/microsoft/wslg/issues/347#issuecomment-971126353)

So maybe the best thing for now would be to have a lot of votes on a feature request for the possibility to use the Windows Store version of WSL in Windows 10, since this seems the only realistic option to get WSLg working on a real Windows 10

**Comment by a-stana** [comment]
To me it would be a huge benefit to use WSLg on my work computer. Iam not allowed to install a dual boot, which would also be frustrating to reboot into the different systems. And the company won't upgrade to Win 11 for at least one more year. I was waiting and hoping that this was pushed to the 21H2 release of Win10 since they announced and showed it in the development process. I'm also disappointed it didn't happen.

**Comment by IQIUM** [comment]
> To me it would be a huge benefit to use WSLg on my work computer. Iam not allowed to install a dual boot, which would also be frustrating to reboot into the different systems. And the company won't upgrade to Win 11 for at least one more year. I was waiting and hoping that this was pushed to the 21H2 release of Win10 since they announced and showed it in the development process. I'm also disappointed it didn't happen.

I think too,a few months ago,I heard that wslg was supported for 21H2,and  I have been waiting for it.However, i updated my win10 to 21H2 yesterday, i can't install wslg !! I am so disappinted too!

**Comment by spronovo** [comment]
Hey folks, we realize folks would really like to see WSLg supported on Windows 10. We're using #347 as the primary thread tracking this. In particular see the following update/comment.

https://github.com/microsoft/wslg/issues/347#issuecomment-971126353

**Comment by strarsis** [comment]
Just some hours ago a new update of **Windows Subsystem for Linux** became available on the Microsoft Store for Windows **10** and I installed it - and now Linux applications can be started straight from the start menu without any configuration, including from command line! 😄

**Comment by fushinari** [comment]
I still get the error:

> Windows version 10.0.19044.2251 does not support the packaged version of Windows Subsystem for Linux.
> For information please visit https://aka.ms/wslinstall
> Press any key to continue... 

@strarsis How did you get it to work?

**Comment by Biswa96** [comment]
@fushinari The WSL from Windows Store now supports latest Windows 10. Please make sure that your machine is fully up to date. The Windows Update required is KB5020030.

**Comment by fushinari** [comment]
@Biswa96 Oh thanks for letting me know. Looks like it's a an update preview. Maybe corporate policy is restricting it, idk for sure, but I haven't received it, neither as an optional update nor as a regular update.

**Comment by fushinari** [comment]
I manually installed KB5020030 and yes, it works! I can now run Linux GUI apps on Windows 10 through WSLg.

**Comment by MrLinDowsMac** [comment]
I was able to run xeyes, and the WSL from the Store, it also ships gedit!

**Comment by xax** [comment]
**Notabene:** *WSL* from *Store* not only supports *WSLg*, but also uses **`systemd`** as PID=1, which makes using several Linux daemons and services a lot easier (thinking e.g. of `podman`/`docker`).

**Comment by spronovo** [comment]
Hey folks, it is indeed official and WSLg is now available for Windows 10. Please make sure that your Windows 10 installation is fully up to date and then update to the latest version of WSL in the Microsoft Store.

For more details, please see our official blog on this.

https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/
