### ISSUE TITLE
Dedicated GPU is never used and remains at 0% usage. Everything is done only by integrated GPU.

### ISSUE THREAD

**Issue by siferati** [microsoft/wslg#570]
# Environment

```none
Windows build number: 22000.318
Your Distribution version: Ubuntu 18.04
Your WSLg version: 1.0.26
```

I have a laptop with a Ryzen 7 5800HS and an RTX 3050 Ti.
I installed the WSL NVIDIA drivers correctly, and the dedicated GPU is properly detected inside linux (`nvidia-smi` shows expected output).
But when running applications, the NVIDIA GPU is never used.

# Steps to reproduce

Run gazebo.

#  Expected behavior

Dedicated gpu is used.

# Actual behavior

Dedicated GPU remains at 0% usage. Only the integrated GPU is used.

**Comment by onomatopellan** [comment]
You need Mesa 21.x for GPU acceleration inside WSL2 and the Ubuntu 18.04 version is probably older.
You can install latest Mesa libs like this:
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update && sudo apt upgrade -y
```

**Comment by siferati** [comment]
Thank you, that fixed it! :D

I tested on Ubuntu 20 and it works out of the box, so I guess that's needed only for 18 and lower. Perhaps those instructions should be added to the docs somewhere? Or better yet, add the correct version of Mesa to the Ubuntu image, so that it works out of the box!
