### ISSUE TITLE
rviz panel is frozen

### ISSUE THREAD

**Issue by kuzen** [microsoft/wslg#588]
# Environment

```none
Windows build number: 10.0.22494.1000
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.28+Branch.main.Sha.8b5993a2190de8954de59fbca93ff8b4ed5f8330
```

# Steps to reproduce

1. install ros-noetic-desktop, according to the tutorial https://wiki.ros.org/noetic/Installation/Ubuntu
2. run `roscore`
3. run `rviz`
4. Drag the panel in rviz out of the window
![image](https://user-images.githubusercontent.com/16202160/143524781-1abd93a2-92bd-4e0d-ba0d-d3ca8c451746.png)

**WSL logs**: 
[wsl_log.zip](https://github.com/microsoft/wslg/files/7612671/wsl_log.zip)

#  Expected behavior

The panel floats normally.

# Actual behavior

The panel is frozen, and cannot be operated.

**Comment by hideyukn88** [comment]
@kuzen, thank you very much for reporting the issue. I'm able to confirm the issue locally. To be sure we are seeing same issue, when you reproduce this issue, would you please run "xwininfo -root -tree", then see how it shows for non-movable panel window (this case, "Displays" panel), especially I'm interested in what's shown in below where double asterisks. Thanks!

     0x200013 (has no name): ()  408x581+**-32768+-32768  +-32768+-32768**
        1 child:
        0x40001c "Displays": ("rviz" "rviz")  344x517+32+32  +-32736+-32736

**Comment by kuzen** [comment]
> @kuzen, thank you very much for reporting the issue. I'm able to confirm the issue locally. To be sure we are seeing same issue, when you reproduce this issue, would you please run "xwininfo -root -tree", then see how it shows for non-movable panel window (this case, "Displays" panel), especially I'm interested in what's shown in below where double asterisks. Thanks!
> 
> ```
>  0x200013 (has no name): ()  408x581+**-32768+-32768  +-32768+-32768**
>     1 child:
>     0x40001c "Displays": ("rviz" "rviz")  344x517+32+32  +-32736+-32736
> ```

Great job! This is the output of `xwininfo -root -tree` ("Display" panel).
```
     0x20003d (has no name): ()  408x909+-32768+-32768  +-32768+-32768
        1 child:
        0x40001c "Displays": ("rviz" "rviz")  344x845+32+32  +-32736+-32736
```"panel).
