### ISSUE TITLE
Enable Discussions tab in this repo

### ISSUE THREAD

**Issue by crramirez** [microsoft/wslg#59]
Hello,

The Issue list is filling very fast, and I am really impressed with how much feedback we are giving. Sure, when this feature is released, WSLg will be well tested.

But some issues are more discussions than problems or feature requests. This is why I suggest that the Discussions tab be enabled in this repo.

Regards,
Carlos

**Comment by spronovo** [comment]
@crramirez that's a great suggestion, i just enabled the Discussions tab.
