### ISSUE TITLE
[Help wanted] Jetbrains IDEs feature ‘find in files’ window disappeared very quickly

### ISSUE THREAD

**Issue by JYInMyHeart** [microsoft/wslg#60]
I often find some words by Jetbrains IDEs feature 'find in files'. But this feature's window disappears so quickly when i start an ide by wslg. So i can't type anything to find i want. 
![idea](https://user-images.githubusercontent.com/26308552/115855639-10c29200-a45e-11eb-9553-de9e7ccfdbec.gif)

**Comment by itspers** [comment]
Seems like wslg has bad problems with focus. Im considering to switch back to xserver for now. But its also jetbrains issue 
https://youtrack.jetbrains.com/issue/IDEA-265390, looks like they sometimes have problems with z-index, cause in such moments you can notice windows is still here, by cursor behaviour, just invisible.

But i was managed to 'fix' that yesterday - sometimes after restart it works, and i clicked Pin icon on top-right corner - was working for whole day, until broke again.

**Comment by JYInMyHeart** [comment]
> Seems like wslg has bad problems with focus. Im considering to switch back to xserver for now. But its also jetbrains issue
> https://youtrack.jetbrains.com/issue/IDEA-265390, looks like they sometimes have problems with z-index, cause in such moments you can notice windows is still here, by cursor behaviour, just invisible.
> 
> But i was managed to 'fix' that yesterday - sometimes after restart it works, and i clicked Pin icon on top-right corner - was working for whole day, until broke again.

I uninstalled xserver software in the morning. Now I try to click Pin icon to 'fix' this problem😂.

**Comment by spronovo** [comment]
This is a known issue #10, z-order is sometime messed up due to the way Weston handle pop up window. We need make to do a pretty big change to Weston to address that, we'll be reaching out to folks on the project to discuss how best to address these problem in a way that folks would be happy to see upstream.

**Comment by spronovo** [comment]
Closing this one for now as we'll track this with #10. We'll prioritize getting this one address as we realize this is quite frustrating when trying to use an application and having window popup under the one you're currently interacting with :-).

**Comment by davidsmith-accesso** [comment]
I'm still seeing this issue in Jetbrains. When I launched the app it worked once where the window stayed, but every subsequent time (even upon restarting the app) the `find in files` search window would appear for 1 frame and then disappear. As of 4/11/2022 I have updated to the latest wsl version:

```
$wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 3/28/2022
Kernel version: 5.10.102.1
```
