### ISSUE TITLE
WSLg prevents computer from entering sleep or low-power mode

### ISSUE THREAD

**Issue by pervognsen** [microsoft/wslg#603]
I noticed my computer was failing to enter sleep mode at night. After running powercfg -energy duration 5 as administrator, the resulting energy report noted that WSL's msrdc.exe was preventing the computer from entering sleep:

![image](https://user-images.githubusercontent.com/123173/144728645-3d343431-f028-41b7-a7b9-3d4d83d215a2.png)

Here is the command line from that msrdc.exe process:

msrdc.exe /v:1EE901CB-28F6-4D47-9443-1A1B12F192A1 /hvsocketserviceid:A816F674-FACB-11E6-BD58-64006A7986D3 /silent /wslg /plugin:WSLDVC /wslgsharedmemorypath:WSL\1EE901CB-28F6-4D47-9443-1A1B12F192A1\wslg "C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemforLinux_0.50.2.0_x64__8wekyb3d8bbwe\wslg.rdp"

This happens right after a fresh boot, even though I am not running any WSLg apps, nor have I run any WSLg apps this boot cycle. If I kill the msrdc.exe process it gets restarted by its wslhost.exe parent process. If I kill that wslhost.exe parent process and re-run powercfg -energy duration 5, I get a clean report.

# Environment

Windows version: 10.0.22000.318
Distribution version: Ubuntu 20.04.3 LTS
WSL version: 0.50.2.0
Kernel version: 5.10.74.3
WSLg version: 1.0.29

# Steps to reproduce

1. Run powercfg -energy duration 5 with admin rights.
2. Open energy-report.html.
3. Note in the report that WSLg's msrdc.exe is preventing Windows from entering sleep and low-power mode:

#  Expected behavior

WSLg should allow computer to go to sleep.

# Actual behavior

WSLg blocks computer from going to sleep.

**Comment by hideyukn88** [comment]
Closing dup to https://github.com/microsoft/wslg/issues/380.
