### ISSUE TITLE
Stuck key input at window launch

### ISSUE THREAD

**Issue by amzon-ex** [microsoft/wslg#606]
# Environment

```none
Windows build number: 22000.348
Your Distribution version: Ubuntu-21.10
Your WSLg version: 1.0.26
```

# Steps to reproduce

On certain windows when launched via the command line, it seems like a key has been held down - and the window continuously keeps taking input, leading to weird behaviour such as this:

https://user-images.githubusercontent.com/45428344/144973706-4c7d4983-e0fa-4e52-bf22-81ad20ccbe64.mp4

Until I press another key (Ctrl+C in this case), otherwise it keeps on running. This particular example is with **st**, but it happens with **gedit**, **firefox** and so on.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

[pulseaudio.log](https://github.com/microsoft/wslg/files/7665806/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/7665807/weston.log)

versions.txt (since I could not drop the file here for some unknown reason):
```none
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

**Comment by codeofdusk** [comment]
I can also repro this with [Emacspeak](https://github.com/tvraman/emacspeak). Cc @craigloewen-msft

**Comment by edburns** [comment]
I see this as well.  I press Ctrl-G, but it's still terribly annoying an unprofessional.

**Comment by hideyukn88** [comment]
Closing dup to https://github.com/microsoft/wslg/issues/207. Please refer https://github.com/microsoft/wslg/issues/207#issuecomment-938757008, thanks!
