### ISSUE TITLE
Runaway process when copying bitmap to clipboard

### ISSUE THREAD

**Issue by edburns** [microsoft/wslg#609]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.318
Your Distribution version: Ubuntu 20 (from Store)
Your WSLg version: 1.0.26
```

# Steps to reproduce

* Start WSL2.
* Tail `weston.log`.
* Using Edge, do Ctrl-Shift-S to capture a region of the browser window to the clipboard. FWIW, I use exactly this:
![image](https://user-images.githubusercontent.com/75821/147009829-ab8ac428-e9f9-44d4-9de4-908cf63338f1.png)
* Notice that the `weston.log` tail starts going into runaway mode.

I also observed that if I have the bitmap in the clipboard before starting WSL2, I also get into runaway mode.

**WSL logs**: 

[20211213-wslg-runaway-process.txt](https://github.com/microsoft/wslg/files/7707736/20211213-wslg-runaway-process.txt)

#  Expected behavior

I can use GNU emacs under WSLg without the system going into an unusable state.

# Actual behavior

Something I am doing is triggering the system going into an unusable state where the keyboard and mouse focus keeps getting stolen several times a second, lots of content is written to the `weston.log` (attached), and this keeps happening until I somehow managed to get Task Manager opened, find the process "Virtual machine worker" and end it. All the while I must fight with the focus stealing.

**Comment by edburns** [comment]
Even after killing the process, I find I must reboot the machine.

**Comment by edburns** [comment]
Happened again. That's twice today.
[20211213-wslg-runaway-process-609-02.txt](https://github.com/microsoft/wslg/files/7707984/20211213-wslg-runaway-process-609-02.txt)
.

**Comment by jonhoward** [comment]
I am having the same issue.  Process Explorer shows that mstsc.exe is stuck launching and terminating repeatedly and I have the same problem as @edburns with the computer becoming nearly unusable because focus keeps leaving the application I'm trying to work with.  I have found that the problem starts when I use Greenshot to copy some image data into the clipboard of my PC and I can get it to stop if I can manage to copy some text into the clipboard, although that is easier said than done due to the unfocusing issue.

**Comment by edburns** [comment]
Actually, using `wsl --shutdown` doesn't prevent it from happening again. Soon after next time I started WSL it happened again. This time I was able to fight with the focus stealer to execute `cp /mnt/wslg/weston.log <some other place>` so that it would survive the reboot.  Here it is.

[20211221-wslg-runaway-process-609-01.txt.gz](https://github.com/microsoft/wslg/files/7757995/20211221-wslg-runaway-process-609-01.txt.gz)

**Comment by edburns** [comment]
I suspect my use of [Ditto Clipboard](https://www.microsoft.com/store/productId/9NBLGGH3ZBJQ) may be related. Today I quit Ditto and have not re-started it since I started using WSL2 for the day and I have not been able to reproduce the runaway process by following the steps that worked in the description.

**Comment by jonhoward** [comment]
While waiting on a fix to be available, is anyone able to advise on how I could continue using WSL but without the GUI part so I can use my PC without being affected by this issue?  Running Linux GUI apps is not a day-to-day need I have, but using the clipboard for image data is.

**Comment by Masamune3210** [comment]
could just disable wsl if you dont need linux apps for now until the issue is fixed?

**Comment by jonhoward** [comment]
No, I believe disabling WSL entirely would prevent me from running Docker containers.

**Comment by Masamune3210** [comment]
Ah, yeah, you are probably right , was just throwing the idea out
