### ISSUE TITLE
Qt applications with Wayland backend do not have shadows

### ISSUE THREAD

**Issue by std4453** [microsoft/wslg#618]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.376]
Your Distribution version: Actually I'm running ArchWSL with all packages newest
Your WSLg version: 1.0.26
```

# Steps to reproduce

Install [`konsole`](https://archlinux.org/packages/extra/x86_64/konsole/).

Run `konsole` with:

```bash
QT_QPA_PLATFORM=wayland konsole
```

#  Expected behavior

There should be shadow around windows.

# Actual behavior

No shadow around windows with wayland, the other one is started without the environment variable.

![image](https://user-images.githubusercontent.com/13191718/147686975-dd8430e5-2826-4a55-a913-50952ef53b49.png)

**Comment by hideyukn88** [comment]
@std4453, thanks for trying out WSLg, I think this is currently expected behavior since WSLg doesn't add window shadow for Wayland native application. And for Wayland application by its nature, application is responsible to render all window decoration. thanks!
