### ISSUE TITLE
Left-handed mouse ignoredver

### ISSUE THREAD

**Issue by Pantarheon** [microsoft/wslg#625]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `pulseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

**Comment by Pantarheon** [comment]
Microsoft Windows [Version 10.0.22000.376], my mouse is configured to swap left and right buttons. But in Debian, when running a WLSg application (gedit specifically, but true overall), this is ignored. This is frustrating to me (and undoubtedly other left-handed users), as I am constantly pressing the "wrong" mouse button, just to be reminded WLSg is ignoring my mouse configuration.

Please fix it. Thanks.

**Comment by hideyukn88** [comment]
@Pantarheon, thanks for reporting the issue. How do you swap mouse button in Windows? If it does via Settings app, then it should be fixed by https://github.com/microsoft/weston-mirror/pull/31. Please share /mnt/wslg/versions.txt, this tells us which version you have, thanks!

**Comment by Pantarheon** [comment]
@hideyukn88 , thanks for the reply. I swap the mouse button in the Settings app. I am enclosing the file you have requested.
[versions.txt](https://github.com/microsoft/wslg/files/7830079/versions.txt)
.

**Comment by hideyukn88** [comment]
@Pantarheon, thanks. Please update WSL by installing from Store app, https://www.microsoft.com/en-us/p/windows-subsystem-for-linux-preview/9p9tqf7mrm4r?activetab=pivot:overviewtab, this should address your issue, thanks!

**Comment by Pantarheon** [comment]
@hideyukn88, thank you. That fixed the problem. I can now use my left-hand mouse the same way in native Windows and WSLg applications. :)
