### ISSUE TITLE
Only first wslg window launched receives mouse events (per wsl boot)

### ISSUE THREAD

**Issue by crispinb** [microsoft/wslg#631]
# Environment

```
Win:   10.0.22000.0 Microsoft Windows NT 10.0.22000.0
Linux: Ubuntu 20.04

Your WSLg version: 1.0.26
```

# Steps to reproduce

* launch xeyes or xev
* point / click with mouse - all works as expected
* close the launched app
* launch again - keyboard input is fine, but no input from mouse (for either the app's or window decoration controls)

# Logs

[versions.txt](https://github.com/microsoft/wslg/files/7837939/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/7837945/weston.log)

#  Expected behavior

Clicking app or window controls should work as expected

# Actual behavior

- any windows launched after the 1st one receive no mouse input 
- eg. `xev` - nothing is displayed when the xev window is clicked with the mouse
- even 'close/max/restore' window decorations don't work, and the window can't be dragged with the title bar
- keyboard input works as normal

This behaviour resets after a `wsl --shutdown` in powershell/cmd` - 1 more wslg window can be launched from a new linux shell.

**Comment by hideyukn88** [comment]
@crispinb, thanks for reporting the issue. It looks you are on older version of WSLg (1.0.26). Would you please update from Store and try again? Here is the link to updated WSL: https://www.microsoft.com/en-us/p/windows-subsystem-for-linux-preview/9p9tqf7mrm4r?activetab=pivot:overviewtab. Thanks!

**Comment by crispinb** [comment]
@hideyukn88 - many thanks, the Store build fixed the issue. I'm not aware of ever having installed WSLg - I thought it had arrived as part of the Win 11 upgrade - but in any case, it's all working now. Appreciate it.
