### ISSUE TITLE
Scrolling up of mouse wheel invokes scroll-down events in Windows Subsystem for Linux (Windows on ARM)

### ISSUE THREAD

**Issue by ybjang** [microsoft/wslg#636]
# Environment

```none
Windows build number: 22000.376 (Windows on ARM) * Windows Subsystem for Linux on x64 devices has no problem.
Your Distribution version: Ubuntu 18.04 & 20.04
Your WSLg version: Windows Subsystem for Linux WSLg Preview 1.0.26
```

# Steps to reproduce

1. Install "Windows Subsystem for Linux preview" in Microsoft Store.
2. Install "Ubuntu-18.04 LTS" or "Ubuntu-20.04 LTS" in Microsoft Store.
3. Launch Ubuntu in Start.
4. Install firefox as "sudo apt install firefox."
5. Launch firefox in WSL.
6. Check if scroll-up/down of mouse wheel is working properly on the site of https://fractalglider.github.io/fun/2018/02/13/testing-mouse-scroll-wheel.html.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `pulseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

Both scroll up and down should work.

# Actual behavior

Scrolling up invokes scroll-down events.

**Comment by ybjang** [comment]
Link to Feedback Hub logs: https://aka.ms/AAfhb2w

**Comment by hideyukn88** [comment]
@ybjang, thanks for reporting the issue, this should be fixed by this PR, https://github.com/microsoft/weston-mirror/pull/46, which should be included in next update, WSLg version 1.0.30, thanks!

**Comment by ybjang** [comment]
@hideyukn88 Thank you for your reply. Could you let me know when v1.030 is released?

**Comment by onomatopellan** [comment]
@ybjang WSLg 1.0.30 is included in WSL 0.51.2 from the store. Running `wsl.exe --update` should work too.

**Comment by ybjang** [comment]
I've confirmed it is resolved. Thanks!

**Comment by alex-startengine** [comment]
I have the opposite problem. Whether I move mouse wheel up or down, it always scrolls up.

**Comment by hideyukn88** [comment]
@alex-startengine, would you please check if you have installed WSL from aka.ms/wslstorepage? thanks!

**Comment by alex-startengine** [comment]
I am stunned -- it works now! Thank you :)
