### ISSUE TITLE
Firefox fails to start with Intel GPU driver 30.0.101.1191

### ISSUE THREAD

**Issue by thedelog** [microsoft/wslg#638]
# Environment

Microsoft Windows [Version 10.0.22000.434]

# Steps to reproduce

![image](https://user-images.githubusercontent.com/60874085/149728718-6deafd38-bf40-42f3-b566-357112e60f32.png)

![image](https://user-images.githubusercontent.com/60874085/149728009-6c31b892-1b50-4883-9582-5520272af20b.png)

**Comment by hideyukn88** [comment]
@thedelog, thanks for reporting the issue. Did this generate core dump from firefox? If so, please share with us, if core file, the log with strace might help too, thanks!

**Comment by thedelog** [comment]
[dump.tar.gz](https://github.com/microsoft/wslg/files/7941563/dump.tar.gz)
please find it attached

**Comment by thedelog** [comment]
When I force the software rendering by adding environment variable LIBGL_ALWAYS_SOFTWARE = 1 ,  both firefox and glxgears works  but without hardware acceleration.  Otherwise firefox reports above issue and glxgears appears as  black window without gears..
I am using latest version of Intel DHC graphic driver.

**Comment by hideyukn88** [comment]
@thedelog, thanks for info, we understood the bug causes the black window issue with glxgears with Intel GPU driver, they have an issue with depth buffer. Intel is currently working on the fix. For firefox issue, we are not be able to root cause yet, since mainly we are not able to reproduce locally here, even using same Intel UHD 620 hardware and the latest driver, but just in case would you please point us which exact driver did you install? thanks!

**Comment by thedelog** [comment]
@hideyukn88 , Thank you for information. 
I downloaded driver from : https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html
the latest one, igfx_win_101.1191.exe ,

**Comment by hideyukn88** [comment]
@thedelog, thanks, now I'm able to reproduce.

```
Thread 1 "GeckoMain" received signal SIGSEGV, Segmentation fault.
0x00007fffe39f3f11 in ?? () from /usr/lib/wsl/drivers/iigd_dch.inf_amd64_a6f2bd19df3d42e0/libigd12umd64.so
(gdb) bt
#0  0x00007fffe39f3f11 in  () at /usr/lib/wsl/drivers/iigd_dch.inf_amd64_a6f2bd19df3d42e0/libigd12umd64.so
#1  0x00007fffe39e0ae9 in OpenAdapter12 () at /usr/lib/wsl/drivers/iigd_dch.inf_amd64_a6f2bd19df3d42e0/libigd12umd64.so
#2  0x00007fffe43e1391 in  () at /usr/lib/wsl/lib/libd3d12core.so
#3  0x00007fffe43d0052 in  () at /usr/lib/wsl/lib/libd3d12core.so
#4  0x00007fffe42cb52c in  () at /usr/lib/wsl/lib/libd3d12core.so
#5  0x00007fffe42cb20f in  () at /usr/lib/wsl/lib/libd3d12core.so
#6  0x00007fffe42cbc62 in  () at /usr/lib/wsl/lib/libd3d12core.so
#7  0x00007fffe42ccf56 in  () at /usr/lib/wsl/lib/libd3d12core.so
#8  0x00007fffe4686950 in D3D12CreateDevice () at /usr/lib/wsl/lib/libd3d12.so
#9  0x00007fffead45cb2 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#10 0x00007fffead45270 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#11 0x00007fffea212d11 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#12 0x00007fffea8d02f8 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#13 0x00007fffea8d027c in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#14 0x00007fffea2135c4 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#15 0x00007fffea7e1c7a in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#16 0x00007fffebc7da12 in  () at /lib/x86_64-linux-gnu/libGLX_mesa.so.0
#17 0x00007fffebc83243 in  () at /lib/x86_64-linux-gnu/libGLX_mesa.so.0
#18 0x00007fffebc7ec54 in  () at /lib/x86_64-linux-gnu/libGLX_mesa.so.0
#19 0x00007fffebc7f116 in  () at /lib/x86_64-linux-gnu/libGLX_mesa.so.0
#20 0x00007ffff60d3efd in epoxy_glx_version () at /lib/x86_64-linux-gnu/libepoxy.so.0
#21 0x00007ffff64dbe05 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#22 0x00007ffff64dc1a0 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#23 0x00007ffff64e5193 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#24 0x00007ffff64e2147 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#25 0x00007ffff64d1ed4 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007ffff64a4378 in gdk_display_manager_open_display () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#27 0x00007ffff0af804d in  () at /usr/lib/firefox/libxul.so
#28 0x00007ffff0afc3fe in  () at /usr/lib/firefox/libxul.so
#29 0x00007ffff0afc800 in  () at /usr/lib/firefox/libxul.so
#30 0x0000555555561180 in  ()
#31 0x00007ffff7a750b3 in __libc_start_main (main=
    0x555555560d30, argc=1, argv=0x7fffffffe298, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe288) at ../csu/libc-start.c:308
#32 0x0000555555560bde in _start ()
(gdb)
```

**Comment by hideyukn88** [comment]
@thedelog, this will be fixed in next Intel GPU driver update, thanks!

**Comment by thedelog** [comment]
Many thanks for the information, I am closing this issue and waiting for Intel's update.

**Comment by anilzeybek** [comment]
It looks like there is a new driver (https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) but problem still persists. Firefox uses software rendering automatically and glxgears gives black output:


![glxgears](https://user-images.githubusercontent.com/33326624/153403518-bd54da4e-66c7-4fee-8ecf-8b5ae6518b0d.png)
![firefox](https://user-images.githubusercontent.com/33326624/153403520-dc3c751e-a72e-4890-b457-62a888b751d3.png)

**Comment by thedelog** [comment]
> It looks like there is a new driver (https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html) but problem still persists. Firefox uses software rendering automatically and glxgears gives black output:
> 
> ![glxgears](https://user-images.githubusercontent.com/33326624/153403518-bd54da4e-66c7-4fee-8ecf-8b5ae6518b0d.png) ![firefox](https://user-images.githubusercontent.com/33326624/153403520-dc3c751e-a72e-4890-b457-62a888b751d3.png)

Yes, confirmed. Same problem is continue but firefox running without error by using software rendering. @hideyukn88  Can we hope that next DHC intel driver will support hardware acceleration?

**Comment by thedelog** [comment]
It seems the driver version igfx_win_101.1404  solves the issue for 3d hardware acceleration support. 
https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

I had to set firefox config "gfx.webrender.all"  as true. 
![image](https://user-images.githubusercontent.com/60874085/157559394-d829aab1-864b-4254-b4ab-96601a8bb448.png)


$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (Intel(R) HD Graphics 620) (0xffffffff)
    Version: 21.2.6
    Accelerated: yes
    Video memory: 8239MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (Intel(R) HD Graphics 620)
------------------------------------------------------------------------------------------------------------------------------------------
$ glxgears -info
GL_RENDERER   = D3D12 (Intel(R) HD Graphics 620)
GL_VERSION    = 3.1 Mesa 21.2.6
GL_VENDOR     = Microsoft Corporation
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_EXT_texture_buffer_object GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_timer_query GL_EXT_direct_state_access GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_shading_language_include GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_KHR_context_flush_control GL_ARB_parallel_shader_compile GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_MESA_shader_integer_functions GL_ARB_texture_filter_anisotropic GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_EGL_sync
VisualID 444, 0x1bc
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
