### ISSUE TITLE
Cannot display in singularity shell

### ISSUE THREAD

**Issue by smoggy-P** [microsoft/wslg#648]
# Environment

```none
Windows build number: [10.0.22543.1000]
Your Distribution version: [20.04]
Your WSLg version: [1.0.27]
```

# Steps to reproduce

Launch a singularity shell and try to run any application with GUI

#  Expected behavior

Display the GUI interface (like it's in root shell)

# Actual behavior

```
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted

```

**Comment by PeterNjeim** [comment]
The first line in your log makes it seem like your `DISPLAY` variable isn't set, try running `export DISPLAY=:0` and try it again

**Comment by smoggy-P** [comment]
> The first line in your log makes it seem like your `DISPLAY` variable isn't set, try running `export DISPLAY=:0` and try it again

Thank you for your reply! I have tried your method but unfortunately it doesn't work. I also check by `echo $DISPLAY` and the result is exactly `:0`

**Comment by PeterNjeim** [comment]
Please do `export QT_DEBUG_PLUGINS=1` and try it again, this should show more detailed logs

**Comment by PeterNjeim** [comment]
Try running `sudo apt-get install libxcb-xinerama0`, it seems to have worked for some people

**Comment by smoggy-P** [comment]
> Try running `sudo apt install libxcb-xinerama0`, it seems to have worked for some people

I have installed this. After running with debug mode I got this:
```
Singularity HRWROS:~> rviz
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330752
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/ros/noetic/bin/platforms" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
```

**Comment by PeterNjeim** [comment]
Can you share what `echo $GDK_BACKEND` says?

**Comment by omozopia** [comment]
I have the same problem as well even with setting GDK_BACKEND=x11. Please, find below the debug output. Is there anyway of fixing this problem with singularity?

Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 329986
}


Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 329986
}


Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 329986
}


Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 329986
}


Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 329986
}


Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 329986
}


Found metadata in lib /usr/lib64/qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329986
}


qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
QLibraryPrivate::unload succeeded on "/usr/lib64/qt5/plugins/platforms/libqxcb.so"

**Comment by omozopia** [comment]
@smoggy-P did you ever resolve this problem?

**Comment by smoggy-P** [comment]
> @smoggy-P did you ever resolve this problem?

Unfortunately no. Turning to dual boot now

**Comment by omozopia** [comment]
@smoggy-P and @PeterNjeim, I have solved the problem. Find below the steps that I used. There might be a more elegant solution than mine. 
Essentially singularity needs to read a ~/.Xauthority to determine the credentials used by xauth for authentication of an XServer. This .Xauthority file is not found when you install your Linux distro in WSL2. Here are the steps that to over this problem:

1. Install OpenSSH server inside the Linux distro in WSL: sudo apt install openssh-server

2. Edit /etc/ssh/sshd_config. Ensure that "X11Forwarding yes" is enabled (or uncommented)

3. Determine the IP address of your Linux distro in WSL2 (ifconfig (might need to install this with: sudo apt install net-tools)

4. ssh into Linux distro in WSL2 with MobaxTerm on the same computer or with another computer. This will generate a ~/.Xauthority file.

5. In the login "echo $DISPLAY" to determine the environmental variable.

6. Back to WSL2, export these two variables in your terminal (perhaps, it can be added to .bashrc)
    - export LIBGL_ALWAYS_INDIRECT=1
    - export DISPLAY=localhost:10.0
    
7. The variable for DISPLAY is based on the result of step 5.

8. The display of singularity should work now

Steps 4 and 5 are very crude. There should be a more elegant way of creating the ~/.Xauthority file within WSL2 without having to use ssh. Perhaps, you have suggestions for this.

**Comment by vinay-hebb** [comment]
> Try running `sudo apt install libxcb-xinerama0`, it seems to have worked for some people

This worked for me 👍

**Comment by UgurKap** [comment]
> @smoggy-P and @PeterNjeim, I have solved the problem. Find below the steps that I used. There might be a more elegant solution than mine. Essentially singularity needs to read a ~/.Xauthority file to determine the credentials used by xauth for authentication of an XServer. This .Xauthority file is not found when you install your Linux distro in WSL2. Here are the steps that help solve this problem:
> 
>     1. Install OpenSSH server inside the Linux distro in WSL: sudo apt install openssh-server
> 
>     2. Edit /etc/ssh/sshd_config. Ensure that "X11Forwarding yes" is enabled (or uncommented)
> 
>     3. Determine the IP address of your Linux distro in WSL2 (ifconfig (might need to install this with: sudo apt install net-tools)
> 
>     4. ssh into Linux distro in WSL2 with MobaXterm(a separate software) on the same computer. This will generate a ~/.Xauthority file.
> 
>     5. In the MobaXterm login "echo $DISPLAY" to determine the environmental variable.
> 
>     6. Back to WSL2, export these two variables in your terminal (perhaps, they can be added to a wrapper script)
>        
>        * export LIBGL_ALWAYS_INDIRECT=1
>        * export DISPLAY=localhost:10.0
> 
>     7. The variable for DISPLAY is based on the result of step 5.
> 
>     8. The display of singularity should work now.
> 
> 
> Steps 4 and 5 are very crude. There should be a more elegant way of creating the ~/.Xauthority file within WSL2 without having to use ssh. Perhaps, you have suggestions for this.

This worked for me. One possible change is instead of using EXPORT, I added those variables to my bashrc file.

**Comment by PeterNjeim** [comment]
Make sure to remove `@` from quotes or else you'll end up pinging people. I don't use singularity shell and so would like to not hear about this issue, thanks
