### ISSUE TITLE
How do I get VcXsrv to work with wayland-0

### ISSUE THREAD

**Issue by lewisdonofrio** [microsoft/wslg#650]
would like to get my full xfce4 desktop like I have with windows 10 and https://www.tinyurl.com/donofrioworkremmina2020 shows WSL1 working great.  In windows 11 I've yet to get WSL2 to work even when I do the display mod's for the env setup, but that was trying x11, now in Insider w11 dev channel I guess we now get Wayland native but how to get a full DE like xfce4 so far all I get is:

(xfwm4:3779): Gtk-WARNING **: 05:58:38.765: cannot open display: wayland-0

**Comment by aadvanraamt** [comment]
Works for me!

**Comment by crramirez** [comment]
> would like to get my full xfce4 desktop like I have with windows 10 and https://www.tinyurl.com/donofrioworkremmina2020 shows WSL1 working great. In windows 11 I've yet to get WSL2 to work even when I do the display mod's for the env setup, but that was trying x11, now in Insider w11 dev channel I guess we now get Wayland native but how to get a full DE like xfce4 so far all I get is:
> 
> (xfwm4:3779): Gtk-WARNING **: 05:58:38.765: cannot open display: wayland-0

If you want a full desktop I recommend you this project: https://github.com/DesktopECHO/xWSL

**Comment by lewisdonofrio** [comment]
yah works for me when I do not use VcXsrv but built-in Wayland support - https://github.com/microsoft/wslg/issues/843 - well almost perfect, cannot close Wayland once opened lol
