### ISSUE TITLE
Using wslg.exe in a shortcut regens /etc/resolv.conf

### ISSUE THREAD

**Issue by tyingq** [microsoft/wslg#668]
# Environment

```none
Windows build number:  Win32NT    10.0.22543.0 Microsoft Windows NT 10.0.22543.0
Your Distribution version: Ubuntu 20.04
Your WSLg version:  Instructions to find this don't make sense
```

# Steps to reproduce

Create a shortcut on the windows desktop used to launch some Linux utility, with the target being something like:

C:\Windows\System32\wslg.exe --  xterm

And "Start In" being: \\wsl$\Ubuntu\home\myhomedir

Then, when you use it to launch the xterm, the /etc/resolv.conf is re-generated, overwriting any changes you've made.  

I expect /etc/resolv.conf to be generated ONLY when the WSL instance is first started, not every time I use wslg.exe to launch something in an already running WSL instance.

To be clear, I do have generateResolvConf=true so I'm expecting it to be generated once...when the WSL instance is started.  Just not every time I launch an xterm in an already running WSL instance.

**Edit:** I'd also be interested in:

- Any info on how, exactly generateResolvConf works.   What process (windows process? linux process?) is actually generating the contents?
- Any workarounds I can implement to stop it from regenerating when launching an xterm with wslg.exe in an already running instance.

**Comment by benhillis** [comment]
Yep you'll need to disable generateResolvConf  in /etc/wsl.conf.
