### ISSUE TITLE
Clear the list of WSLg apps after removing/reinstalling WSL distro

### ISSUE THREAD

**Issue by alexushkagz** [microsoft/wslg#669]
I've noticed a bug on my machine. I'm on Windows 11 21H2. After completely removing the wsl Ubuntu distro and even wsl and wslg updates from "Install and remove software" I have a list of wslg apps in a start menu that can't be removed, even though there is no more Ubuntu system installed or any gui app as well. I haven't completely uninstalled wsl cause I'm using also docker. How can I clear the list of gui apps in a start menu?

**Comment by Masamune3210** [comment]
They are just shortcuts, they would be cleaned up if you uninstalled the apps first, but you can just delete them manually if they werent

**Comment by stevemagruder** [comment]
I've run into this as well. The expectation is that the shortcuts would be removed when the distro is removed. Instead, I have to manually drill down to where the shortcuts are and remove them. It makes test-driving the various distros more cumbersome than it should be.

**Comment by hideyukn88** [comment]
This is dup of https://github.com/microsoft/wslg/issues/24. Thanks!
