### ISSUE TITLE
Zsh is not "interactive"

### ISSUE THREAD

**Issue by zstg** [microsoft/wslg#674]
Bash seems to work fine on WSL (Windows Terminal) ( tested on Kali, Debian , Ubuntu , Void, Arch and Manjaro )

But on Arch, Kali and Manjaro , `zsh` seems to be having some problems - for example the `delete`, `home` and `end` keys don't seem to be working as intended (even though they work perfectly on `bash`.

Is this a problem with ZSH or with WSL?

**Comment by elsaco** [comment]
@ZeRealStig inside `zsh` type `bindkey` to show your current line editor's setting. `bindkey -l` will show all maps available and `bindkey -M emacs` will show a specific map, emacs like in this case.

**Comment by zstg** [comment]
This is a problem with Oh-my-zsh not being set up properly. After Oh-my-zsh has been installed correctly, the keys work just fine. Closing this issue.
