### ISSUE TITLE
mstsc.exe which under wslhost.exe keep crashing and causes every window refreshing

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/wslg#676]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.527]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

Not always can reproducing this problem.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

I've checked these logs, the really interesting parts listed here:

stderr.log:

```
weston: ../libweston/backend-rdp/rdpclip.c:525: clipboard_process_bmp: Assertion `bits == (DWORD*)(&bmi->bmiColors[color_table_size/sizeof(RGBQUAD)])' failed.
<4>WSLGd: /usr/bin/weston terminated with signal 6.
<4>WSLGd: /mnt/c/Windows/System32/mstsc.exe exited with status 5.
```

[weston.log](https://github.com/microsoft/wslg/files/8211412/weston.log)

[pulseaudio.log](https://github.com/microsoft/wslg/files/8211413/pulseaudio.log)

and one more important thing here which from Windows Logs:

```
Faulting application name: mstsc.exe, version: 10.0.22000.282, time stamp: 0x4f2ad43b
Faulting module name: WSLDVCPlugin.dll_unloaded, version: 1.0.26.0, time stamp: 0x60f0bddd
Exception code: 0xc0000005
Fault offset: 0x000000000000239d
Faulting process id: 0x424c
Faulting application start time: 0x01d83363eaa62081
Faulting application path: C:\Windows\System32\mstsc.exe
Faulting module path: WSLDVCPlugin.dll
Report Id: eee57cbf-9db5-4abf-b6fc-5617a3d07429
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 2230987108122348732, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: mstsc.exe
P2: 10.0.22000.282
P3: 4f2ad43b
P4: WSLDVCPlugin.dll_unloaded
P5: 1.0.26.0
P6: 60f0bddd
P7: 000000000000239d
P8: c0000005
P9: 0000000000000008
P10: 

Attached files:
<omitted>

These files may be available here:
<omitted>

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4f31498d-3aa1-4a03-9edc-8bb6c7513fe0
Report Status: 268435456
Hashed bucket: b56f467c88760cb78ef60ef45e1bccbc
Cab Guid: 0
```

#  Expected behavior

don't crash

# Actual behavior

Today I noticed my whole Windows keep refreshing everything per second, including almost every window, especially for the "Notification Area", which previously Windows 11 keeps buggy refreshing and flickering。

So, I'm trying to figure out which naughty process causes this and with `procexp.exe` which from `Windows SysInternal Suite`, I've noticed this:

![1](https://user-images.githubusercontent.com/1884240/157367630-ebac1dc2-242d-4612-a08c-9b233b011200.png)

The rdp client process keeps crashing, and WerFault.exe came out. This happens every second.

Tried shutting down WSL by `wsl --shutdown`, they calm down. but once WSL restarted, turns to that situation again.

but minutes after, it's fine and stable again, and during that time, I have not making any noticeable action.

**Comment by epiciskandar** [comment]
> would you please update to the latest WSL from aka.ms/wslstorepage
OK, I've done that now, I will see if this would happen again.

**Comment by hello-smile6** [comment]
> [Version 10.0.22000.527]

Maybe try updating to Windows 11?

**Comment by epiciskandar** [comment]
> Maybe try updating to Windows 11?

That is Windows 11, [see wiki here](https://en.wikipedia.org/wiki/Windows_11_version_history#:~:text=It%20carries%20the%20build%20number)

**Comment by hideyukn88** [comment]
@epiciskandar, thanks for trying out the latest WSL, and let us know if this happens again. Just to be clear for the crash in mstsc.exe, which is known and reported at https://github.com/microsoft/wslg/issues/287 and this issue still exists, but since this crash is secondary which only happens when it's forcibly disconnected by weston crash, thus given the latest WSL has the fix for that weston crash, the secondary crash from mstsc.exe should not happen either. Thanks!

**Comment by epiciskandar** [comment]
The latest WSL kernel(5.10.93.2-microsoft-standard-WSL2) works stable for days, so I'm going to close this issue for now.

**Comment by ryanhinton** [comment]
I am currently experiencing this exact issue.

This is my wsl version
`wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.102.1`

This is my Windows version
Version 21H2 (OS Build 22000.556)

**Comment by hideyukn88** [comment]
@ryanhinton, have you updated WSL from aka.ms/wslstorepage?

**Comment by ryanhinton** [comment]
No. I intentionally and originally did not install WSL through the Microsoft store and I prefer not to use the store to install, if it is not necessary.  The CLI command `wsl --update` should offer the same update, is that not correct?

**Comment by hideyukn88** [comment]
@ryanhinton, may I ask you share the output from `wsl --version`?

**Comment by ryanhinton** [comment]
Hi @hideyukn88, you are correct.  it is not available.  I have to use `wsl -l -v` to retrieve the version.  OK, I will have to wait for the release to older Windows 11 release.  What version of Windows 11 currently allows for the newest wsl release that does not require the using the store installation?

`$ wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Stopped         2`

**Comment by ryanhinton** [comment]
Is there any reason why wsl is not yet updatable using `wsl --update` command?

**Comment by hideyukn88** [comment]
As I noted above comments, current wsl.exe in Windows 11 does not support updating WSL from Store. The newer version of wsl.exe will be available from Windows Update for public release soon. While I can't not say when that will be but it's already insider version of Windows 11, so it should be within a month or two. Thanks!

**Comment by RimuruChan** [comment]
Linux NOPE 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

still crash

**Comment by hideyukn88** [comment]
@RimuruChan, would you please share the output of `wsl --version` on Windows's command prompt? thanks!

**Comment by RimuruChan** [comment]
> @RimuruChan, would you please share the output of `wsl --version` on Windows's command prompt? thanks!

Thanks for your reply, I have solved the problem by updating the latest version

**Comment by Thadir** [comment]
Hi seem to have this problem with my:

WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2604
