### ISSUE TITLE
Error maximize the window to full screen

### ISSUE THREAD

**Issue by CN-traveler** [microsoft/wslg#688]
# Environment

```none
Windows build number: Windows 11 22000.556
Your Distribution version: Ubuntu 20.04
Your WSLg version: 
```

#  Expected behavior

1. Open a GUI program and maximize.
2. Close this program and open it.
3. Click maximize.

There window will overflow screen, and can not cliclk maximize.

**Comment by CN-traveler** [comment]
![image](https://user-images.githubusercontent.com/55753029/159122366-be7fb38e-f4b5-4824-87a2-a3292a428a8f.png)
![image](https://user-images.githubusercontent.com/55753029/159122373-130ae3a3-a9c6-4dee-8ebe-d7691948a67f.png)
![image](https://user-images.githubusercontent.com/55753029/159122402-b94b0e72-cd8f-4a24-9f1b-6e0c2b0734b2.png)
![image](https://user-images.githubusercontent.com/55753029/159122418-a1da5e4a-217e-4025-854f-7f16dce73c2c.png)

**Comment by CN-traveler** [comment]
![image](https://user-images.githubusercontent.com/55753029/159122481-98ae26d8-8a04-48d7-8729-c47e555aaec4.png)

**Comment by wrprice** [comment]
Already reported in #619

**Comment by CN-traveler** [comment]
> Already reported in #619

OK , thank you !
