### ISSUE TITLE
Why wslg is running GUIs with a poor resolution on a 4K monitor?

### ISSUE THREAD

**Issue by XushanLu** [microsoft/wslg#699]
### Discussed in https://github.com/microsoft/wslg/discussions/698

<div type='discussions-op-text'>

<sup>Originally posted by **XushanLu** March 27, 2022</sup>
Hello, 

I have recently started to use wslg and after I installed the newest Nvidia Game Ready driver my computer was able to run Linux GUI apps in 4K on my 4K monitor. However, after the most recent update (Cumulative Update for Windows 11, version 22H2 Insider Preview (10.0.22581.100) (KB5013283)), I observed that wslg could not recognize the 4K monitor anymore. It is only running GUI apps with a reduced resolution (seems to be just 1080P).

Here is the output of 'gxlinfo -B':
```shell
❯ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA GeForce GTX 1650) (0xffffffff)
    Version: 22.0.0
    Accelerated: yes
    Video memory: 20238MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce GTX 1650)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 22.0.0 - kisak-mesa PPA
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.3 (Compatibility Profile) Mesa 22.0.0 - kisak-mesa PPA
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.0.0 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

[1]    658 segmentation fault  glxinfo -B
```

I don't know why there is a segmentation fault message and whether this is related to the issue. I'd be happy to post any further information if needed. I would really appreciate any suggestions since this issue makes having a 4K monitor almost meaningless as I am intending to use the Emacs app under Ubuntu extensively for writing my code.

I am suspecting that the Nvidia driver is not effective at all since I am noticing an obvious lag in the low-resolution Emacs GUI as I type. Is there a way to check whether the Nvidia driver is really being used apart from the 'glxinfo -B' option?

Here are the log files under /mnt/wslg:

[pulseaudio.log](https://github.com/microsoft/wslg/files/8365165/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/8365167/weston.log)
[versions.txt](https://github.com/microsoft/wslg/files/8365168/versions.txt)

Note that I still have this stderr.log file which was discussed in https://github.com/microsoft/wslg/issues/689
[stderr.log](https://github.com/microsoft/wslg/files/8365169/stderr.log)

I noticed that gedit is working perfectly with a 4K resolution but anything else is just having a very poor resolution (e.g., Firefox, Emacs, VS code). Don't know whether this is helpful.

Thanks very much.
</div>

**Comment by hideyukn88** [comment]
@XushanLu, thanks for reporting the issue, first, the segmentation fault is now known issue and it is reported at https://github.com/microsoft/WSL/issues/8145#issuecomment-1071460813, we are working with NVIDIA to get driver fixed. Regarding to resolution, the difference is whether application is wayland native or X11 application. For wayland application, with HI-DPI monitor, WSLg let application to render on higher-resolution, while for X11 application, WSLg scale it. In WSLg, gedit runs in Wayland native mode, thus it has crisp image, but firefox and other has blur image. We are working on some idea for better X11 with HI-DPI, which is tracked by https://github.com/microsoft/wslg/issues/3. Thanks!

**Comment by facboy** [comment]
is there any update on the segfault issue?

**Comment by liuyapeng1996** [comment]
I encountered the same problem, using a laptop with a resolution of 2880X1800. When using WSL2 to open the GUI of Ubuntu's VS code, the GUI of code appears blurry, like a mosaic, which is very uncomfortable to look at. I use the WSL2+X-server solution (https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3), which can change the resolution to normal. But the font of VS code's GUI becomes very small. So I did the following: export GDK_SCALE=0.5, export GDK_DPI_SCALE=2, export XCURSOR_SIZE=64. In this way, VS code will display normally. But you need to enter these every time you enter, which is very troublesome. So I want to add these to ~/.bashrc. Although this solves the problem of VS code, it is still very inconvenient. Moreover, for some other software (such as PyCharm), there will be errors that cannot be opened. So isn't there a better solution to support high-resolution screen display?
