### ISSUE TITLE
Windows Subsystem for Linux WSLg Preview - 1.0.26 fails to install

### ISSUE THREAD

**Issue by blowdart** [microsoft/wslg#701]
# Environment

Microsoft Windows [Version 10.0.22000.556]
Ubuntu Microsoft Windows [Version 10.0.22000.556]

WSLg Version 

Windows build number: Microsoft Windows [Version 10.0.22000.556]
Your Distribution version:  Release:        20.04
Your WSLg version: 1.0.26

# Steps to reproduce

Check for Microsoft Updates
Get told an update awaits for WSLg
Attempt to install Windows Subsystem for Linux WSLg Preview - 1.0.26

#  Expected behavior

Update installs from Microsoft Update

# Actual behavior

Wait until it fails with `Install error - 0x80070643`

Running the update manually from the latest MSI on releases gives

Could not write value GraphicsSupport to key \Software\Microsoft\Windows\CurrentVersion\Lxss\Capabilities

![Screenshot 2022-03-29 101616](https://user-images.githubusercontent.com/796298/160669528-3e32b6c3-9599-4ac2-8098-29c2a5a4fcfe.png)

Checking the registry in regedit no Capabilities node or key exists. I cannot create a key in \Software\Microsoft\Windows\CurrentVersion\Lxss despite being an administrator and permissions showing Administrators having Full Control (and read)

Have tried uninstalling WSL graphics, then all distros as well as docker, then wsl itself, then starting over, and it happens again. If I manually ignore the error in the manual install the update is no longer available over MU

Attempting to run xclock

`Error: Can't open display:`

If I configure display via `export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0` that error goes away but xclock doesn't start, nor do I get returned to the shell prompt

Possible dupe of https://github.com/microsoft/wslg/issues/509?

**Comment by elsaco** [comment]
@blowdart to manually add the key you need to specify which hive to use, in this case it's HKLM.

The `GraphicsSupport` key is at:
`HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Lxss\Capabilities\`

**Comment by Johnsiras** [comment]
> Doesn't work. As I said I'm told I don't have permissions.
> 
> ![Screenshot 2022-03-29 125947](https://user-images.githubusercontent.com/796298/160696961-62c3104a-93c0-4f88-b72f-51ccf98843be.png)
> 
> ![Screenshot 2022-03-29 130014](https://user-images.githubusercontent.com/796298/160696989-6c440a4d-a29b-4a88-9037-504424c67551.png)

Are you login as an administrator?

**Comment by blowdart** [comment]
Yes I'm logged in as an administrator

**Comment by hideyukn88** [comment]
@blowdart, thanks for reporting the issue. Have you tried to install the latest WSLg from aka.ms/wslstorepage? Or do you have any specific needs to install 1.0.26, thanks!

**Comment by blowdart** [comment]
This was the version that microsoft update was offering, I didn't have a choice :)

I fixed it this morning by uninstalling everything, including WSL itself, then starting again from scratch from the command line, rather than going through Add/Remove features. Going that route, and running update from the command line has removed detection of updates in MU.

**Comment by hideyukn88** [comment]
>> Possible dupe of https://github.com/microsoft/wslg/issues/509?

Yes, it looks it is, but that didn't root cause any issue unfortunately. Going forward, I recommend installing Store version of WSLg, and let it keep updated by Store app, not by Windows Update. Thanks!
