### ISSUE TITLE
Occasional crash when GUI applications run: X connection to :0 broken (explicit kill or server shutdown). 

### ISSUE THREAD

**Issue by juliaschatz** [microsoft/wslg#714]
# Environment

```none
Windows build number: 10.0.22543.1000
Your Distribution version: 20.04
Your WSLg version: 1.0.27
```

# Steps to reproduce

Be running a GUI application (usually happens on startup of application, but occasionally after the program has been running for a while). Randomly the application will crash with the message "X connection to :0 broken (explicit kill or server shutdown)."

Specifically it happens the most often on my own custom GUI applications, but that might just be because I'm in them more often. I've also had it happen with matplotlib windows. Probably happens once every 12 hours or so?

**WSL logs**: 

[weston.log](https://github.com/microsoft/wslg/files/8504287/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/8504285/pulseaudio.log)
[versions.txt](https://github.com/microsoft/wslg/files/8504286/versions.txt)

#  Expected behavior

Not crashing.

# Actual behavior

Crashing.

# Notes

Alternate to this problem being fixed, is there some way to restart the X server when this does happen? The only way I've been able to work around this is shutting down WSL and restarting it.

**Comment by hideyukn88** [comment]
@juliaschatz, thanks for reporting the issue, it looks you are on older WSLg, 1.0.27, please update from aka.ms/wslstorepage, thanks!

**Comment by juliaschatz** [comment]
So that MS store page only gives me the option to "Open" which makes me think that I have the most recent version. Additionally "versions.txt" lists WSLg as `WSLg ( x86_64 ): 1.0.33+Branch.main.Sha.d57addbe6309d0a453123c91e6117fc21871496c`. Not sure why the version listed in Apps and Features is 1.0.27 or whether they correspond to different things. I also have a pending Windows update I've been putting off for a while (but not as old as this issue) so that might bring it in line.

I recently finished the project that caused me to have most of the issues with this and haven't hit it again on my other computer, and the intermittent nature makes it difficult to diagnose or reproduce anyway, so I might just let it go and add back onto this if I chance across it again. Appreciate the response.

**Comment by hideyukn88** [comment]
@juliaschatz, there is 2 version of WSL (including WSLg), one shows up in "App & Features" which is considered as a part of Windows OS, and other one from Store, and we made a change on how to release WSL, and the latest one is released from Store, and once Store version is installed, the Windows's version is disabled (until Store gets uninstalled). Thus, in your case, you do have the latest release (and will get auto updated). Please feel free to reopen this issue if you see it again, thanks!
