### ISSUE TITLE
WSLg (weston) crash with nautilus in X11 mode

### ISSUE THREAD

**Issue by hideyukn88** [microsoft/wslg#72]
# Environment

Your Distribution version:20.04
Your WSLg version: 1.0.17.1

# Steps to reproduce

First, copy simple text to Windows system clipboard in Windows side
Second, launch WSLg, then
$ export GDK_BACKEND=x11
$ nautilus &
Then weston compositor crash and restart.

"read error from data source: Bad address" is logged in weston.log

Crash is due to freeing invalid address.

libc.so.6!__GI___libc_free(void * mem) (\build\glibc-eX1tMB\glibc-2.31\malloc\malloc.c:3102)
libwayland-client.so.0!wl_array_release(struct wl_array * array) (...\wayland\src\wayland-util.c:104)
xwayland.so!weston_wm_read_data_source(int fd, uint32_t mask, void * data) (...\weston\xwayland\selection.c:413)
libwayland-server.so.0!wl_event_loop_dispatch(struct wl_event_loop * loop, int timeout) (...\wayland\src\event-loop.c:1055)
libwayland-server.so.0!wl_display_run(struct wl_display * display) (...\wayland\src\wayland-server.c:1351)
libexec_weston.so.0!wet_main(int argc, char ** argv) (...\weston\compositor\main.c:3429)
main(int argc, char ** argv) (...\weston\compositor\executable.c:33)

**Comment by hideyukn88** [comment]
The fix for this should address https://github.com/microsoft/wslg/issues/2 as well.

**Comment by UGatgithub** [comment]
Not 100% sure if it is the same issue?! When I launch Nautilus, it starts with 8 icons (Desktop. Documents, Downloads, Music, Pictures, Public, Templates, Videos) but in the shell there is this error: Called "net usershare info" but it failed: Failed to execute child process "net" (No such file or directory) and the "Ubuntu on Community Preview" shell crashes (does not return to :~$). 

Also could not copy the error message from that shell into Edge browser running on Ubuntu, so I had to type above text in here, while Copy & Paste into the shell itself still works and also Copy & Paste within the Write section here in Edge.

 Finally have to close and reopen the  "Ubuntu on Community Preview" shell to be able to start other Ubuntu apps.

**Comment by spronovo** [comment]
This should be fixed with v1.0.19 that we just released moments ago. To update your WSL install, make sure to save your work than type the following from an elevated command prompt in Windows:

```
wsl --shutdown
wsl --update
```
