### ISSUE TITLE
Cant open X applications anymore

### ISSUE THREAD

**Issue by dcoolArne** [microsoft/wslg#720]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.613]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `pulseaudio.log`
* [pulseaudio.log](https://github.com/microsoft/wslg/files/8541908/pulseaudio.log)
* `weston.log`
* [weston.log](https://github.com/microsoft/wslg/files/8541904/weston.log)
* `versions.txt`
* [version.txt](https://github.com/microsoft/wslg/files/8541903/version.txt)

#  Expected behavior
open X Server applications like Firefox

# Actual behavior

getting an X Server error when openning new applications, but not when i open gedit

Firefox error: Gdk-Message: 16:50:33.780: firefox: Fatal IO error 2 (No such file or directory) on X server :0.

The error also only appared in the last few days, i could use gui apps like firefox even a week ago(same gpu driver). Already removed wslg and wsl updates from the system and reinstalled them, also tried debian.

[debug.txt](https://github.com/microsoft/wslg/files/8541924/debug.txt)

**Comment by hideyukn88** [comment]
@dcoolArne, your debug.txt file shows weston is crashed, so there should be dump files created at /mnt/wslg/dumps, would you please share with us? thanks!

**Comment by dcoolArne** [comment]
Hope this helps, had to zip it for upload.
[core.zip](https://github.com/microsoft/wslg/files/8542744/core.zip)

**Comment by hideyukn88** [comment]
@dcoolArne, thanks for dump, so when X11 application is opened, the WSLg's compositor draw window frame and its title bar. In order to support various international fonts, it loads from windows side, and your dump shows the freetype library failed to read from memory mapped I/O of Windows's font, c:\Windows\Fonts\l_10646.ttf. There is a few possibilities, 1) the font file is corrupted, can you use this font file from Windows? 2) WSL access Windows's volume over network, so network is disconnected/interrupted. Can you access that files from Linux after this error occurs? Thanks!

**Comment by dcoolArne** [comment]
The file is in the folder but it seams to be broken, it wont show in Explorer but its showing in cmd and wsl. I also cant open it using cat or notepad. 
cat: /mnt/c/Windows/Fonts/l_10646.ttf: Input/output error
Notepad says something about checking if a have inserted a correct drive. If i just try to copy a new l_10646.ttf file into the fonts folder nothing happends and when deleting to old file i get a access denied error.

**Comment by hideyukn88** [comment]
@dcoolArne, do you see "Lucida Sans Unicode" font is available from Windows applications? thanks!

**Comment by dcoolArne** [comment]
Not under Apps and Features and also not in Windows Search or Font Manager.

**Comment by dcoolArne** [comment]
I just did an inplace system upgrade and now it works again.
