### ISSUE TITLE
Disable WSLg system distro on a per-distro basis

### ISSUE THREAD

**Issue by cerebrate** [microsoft/wslg#73]
**Is your feature request related to a problem? Please describe.**
I have several WSL distributions installed, but only one of them is my "main" distro in which I expect to be running GUI apps; of the others, I have one for system recovery and several for devtest, none of which require GUI capability. Starting up WSLg system distros for them merely wastes resources.

**Describe the solution you'd like**
As well as/instead of the global .wslconfig setting to disable WSLg entirely, allow the WSLg system distro to be enabled/disabled on a per-distribution basis, perhaps using the existing wsl.conf or another mechanism.

**Comment by onomatopellan** [comment]
I think the same. This is specially a problem in Docker Desktop since it launches 3 distros (docker-desktop, docker-desktop-data and the user distro). Only the user distro should have created a SystemDistro so a wsl.conf setting should help the Docker developers to avoid this.

I know everything runs under the same VM but it stills seems to be wasting memory.

**Comment by cerebrate** [comment]
...urgh. I didn't even think of the implications for Docker. 😱

**Comment by spronovo** [comment]
@benhillis i think this is a great idea, i'm assigning to you. We should keep the "turn system distro off" globally flags... but then have an overwrite where user can specify the exact name of distro(s) they want GUI on for and reenable just for those... so more advance user can control precisely where this gets enabled without it being an all or nothing that waste resources (docker for Windows leveraging WSL to run Linux container is indeed a great example).

**Comment by onomatopellan** [comment]
This issue can be closed since it was fixed in the WSL from the store.
https://github.com/microsoft/WSL/releases/tag/0.48.2

```
[general]
guiApplications=false
```

**Comment by Hugo1043** [comment]
> 可以关闭此问题，因为它已在存储的 WSL 中修复。 https://github.com/microsoft/WSL/releases/tag/0.48.2
> 
> ```
> [general]
> guiApplications=false
> ```

it doesnt work in my centos7 wsl ，i have add this to /etc/wsl.conf, but wslg still work
 5.10.102.1-microsoft-standard-WSL2
