### ISSUE TITLE
Incompatibility with remote credential guard/restricted admin

### ISSUE THREAD

**Issue by conatsera** [microsoft/wslg#734]
# Environment

```none
Windows build number: 10.0.22616.0
Your Distribution version: Ubuntu 20.04.4 LTS
Your WSLg version: 1.0.33
```

# Steps to reproduce

1. Have remote credential guard required by group policy.
`Software\Policies\Microsoft\Windows\CredentialsDelegation\RestrictedRemoteAdministration=1`
`Software\Policies\Microsoft\Windows\CredentialsDelegation\RestrictedRemoteAdministrationType=2`
Administrative Templates->System->Credentials Delegation->Restrict delegation of credentials to remote computer = Require Remote Credential Guard

2. Launch WSL

**WSL logs**: 

* `versions.txt`:
```none
WSLg ( x86_64 ): 1.0.33+Branch.main.Sha.d57addbe6309d0a453123c91e6117fc21871496c
Mariner: VERSION="1.0.20220226"
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 651d33374f9b9e93e1cf1210faff13bcd339f132
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

#  Expected behavior

For WSLg to not need user credentials to be delegated to it and to launch with this policy set.

# Actual behavior

The RDP client gets stuck in a reconnect loop until `wsl --shutdown`.
In Windows logs TerminalServices-ClientActiveXCore/Microsoft-Windows-TerminalServices-RDPClient/Operational, event ID 1033 repeatedly reports "Component name:OnDisconnected, :: SL::OnDisconnected, Error code:0xE09". I found the text for 0xE09 to be "The remote PC doesn't support Restricted Administration mode."

**Comment by hideyukn88** [comment]
This is fixed in MSRDC version: 1.2.3401.
