### ISSUE TITLE
Strange artefact in fyne GL application when using wslg

### ISSUE THREAD

**Issue by Bluebugs** [microsoft/wslg#735]
# Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version: Ubuntu 22.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

```
sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
go install fyne.io/fyne/v2/cmd/fyne_demo@develop
~/go/bin/fyne_demo
```

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

[versions.txt](https://github.com/microsoft/wslg/files/8653815/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/8653816/weston.log)

#  Expected behavior

When running fyne_demo or any fyne application on Windows natively we would get the following visual result:

![fyne_demo-windows](https://user-images.githubusercontent.com/1481576/167462601-7fc093d9-c512-4853-a0ef-0e89f13e8c55.jpg)

This is the result we get on every platform where fyne is running (Windows, Linux, BSD, MacOS, Android and iOS).

# Actual behavior

When running in wslg environment, we instead get this stripe artefacts on screen:
![fyne_demo-wslg](https://user-images.githubusercontent.com/1481576/167462784-74645df2-0d32-465b-bf3c-ed73bb0ce8fa.jpeg)

It might be something at the shader level in OpenGL, as it looks like maybe something going on with one of the triangle used for rendering each primitive on screen. It does happen in wslg with both wayland and X (but fyne X support is more mature than its Wayland support, so the bug report steps to reproduce trigger the X code path). On exactly the same machine, the windows binary would just work as expected.

Other users have reported the same issue, I don't know what GPU they were using, but I am using an AMD Radeon Vega 3 with latest drivers.

**Comment by elsaco** [comment]
@Bluebugs are you using display scaling?

Sample run with WSLg 1.0.33, slightly newer compared to your setup:

![fyne_demo](https://user-images.githubusercontent.com/3933920/167526503-e01d7664-9a3d-4a4b-9046-b74f38852150.png)


```
PS C:\Users\elsaco> wsl --status
Default Distribution: fedoraremix
Default Version: 2
WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.652
```

**Comment by Bluebugs** [comment]
@elsaco thanks! I finally got the time today to update and test. This is working correctly now with latest wsl.
