### ISSUE TITLE
WSLg not updated

### ISSUE THREAD

**Issue by c0ffeec0der** [microsoft/wslg#745]
Hello,

I ran wsl --update. However the WSLg does not update to latest version (1.0.34)

I am kinda worried if installing from the [store ](https://www.microsoft.com/store/productId/9P9TQF7MRM4R) would wipe out current wsl and linux distro

Is there another way to update? 

Thanks

# Environment

Windows build number: 10.0.22000.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26

# Steps to reproduce

1. Delete WSLg from Settings > Apps > Apps & features
2. Run wsl --update

#  Expected behavior

WSLg updated to latest version

# Actual behavior

WSLg remain in 1.0.26

**Comment by c0ffeec0der** [comment]
@hideyukn88 by installing manually from aka.ms/wslstorepage. Do you mean to go to that page and click install? Wouldn't that wipe out the linux already installed?

**Comment by c0ffeec0der** [comment]
@hideyukn88 So I tried,

1. Install from aka.ms/wslstorepage -> run ok
2. run wsl --update -> no update, wsl already latest version

The WSLg version is updated to 1.0.33 (after installing from store); but still far from latest 1.0.35. Is this intended difference from github release version? Thanks

Notes:

WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.675

**Comment by hideyukn88** [comment]
@c0ffeec0der, WSLg 1.0.33 is the latest version currently available for non-insider users. Thanks!

**Comment by c0ffeec0der** [comment]
@hideyukn88 Ah, okay! Thank you very much for the help!
