### ISSUE TITLE
WSL from the Store: Tooltips in GUI apps appear "behind" the window

### ISSUE THREAD

**Issue by ophers** [microsoft/wslg#747]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-20.04

### Other Software

Eclipse 2022-03
Installed, but not relate (probably)
Docker Desktop 3.6.0(67351)

### Repro Steps

Running Windows 11 Enterprise - fully updated, plus WSL built-in from Windows OS.

1. Install WSL Preview from Microsoft Store: https://www.microsoft.com/store/productId/9P9TQF7MRM4R
2. Open terminal on Ubuntu-20.04, and install Eclipse CDT 2022-03 or "gedit".
3. Run the GUI app - either `eclipse` or `gedit`.
4. Hover over a button on the toolbar, that normally shows a tooltip.

### Expected Behavior

![image](https://user-images.githubusercontent.com/11839190/170266642-e433d571-4f89-4c2b-b483-9574c914ec2f.png)
the tooltip is shown on top of the window

### Actual Behavior

I don't have a screenshot, but the tooltip is shown behind the window.

### Diagnostic Logs

This also affects in the same way other external X11 servers like `VcXsrv`.
I mainly was excited about the WSL Preview feature of mounting a `vhdx`, but I had to go back because it broke the Eclipse IDE too badly (function preview on hover, for instance).

**Comment by ophers** [comment]
Thank you @elsaco for checking it out.
After I uninstalled WSL Preview from the Store - so that WSL/WSLg from Windows11 was activated again - the tooltips pop-ups are once again sown above the window.
![image](https://user-images.githubusercontent.com/11839190/170574421-6c9d9464-d73d-460b-9d22-16b9ae42c430.png)

Could you check whether you're seeing the tooltip from the `Save` button? As it's shown "behind" the window you shouldn't see it.

**Comment by ophers** [comment]
Is there a way to "deactivate" WSLg from the Microsoft Store WSL Preview -- so that the native Windows 11 WSLg becomes active?
I'd like to benefit from new WSL functionality - e.g. `wsl --mount --vhd` - but still have a functioning GUI (i.e. with this bug, I can't use Eclipse).
Thanks.

**Comment by onomatopellan** [comment]
@ophers You can safely uninstall Microsoft Store WSL Preview app from the Apps & Features settings and the WSL from the system will take preference.

BTW I just [compiled latest WSLg](https://github.com/microsoft/wslg/blob/main/CONTRIBUTING.md) with latest weston changes and I can confirm this issue has been fixed and next release for the Store WSL should contain the fix.

**Comment by mKIRArasif** [comment]
Epiphany (GNOME Web) is facing a similar kind of issue both in the native and flatpak apps!

<img width="1151" height="796" alt="Image" src="https://github.com/user-attachments/assets/e91ff8d6-53a3-4d22-9697-54659c643b2d" />

<img width="1920" height="1020" alt="Image" src="https://github.com/user-attachments/assets/6cd3db0a-583b-42ec-8191-17dc89174bcd" />
