### ISSUE TITLE
Dead keys not working

### ISSUE THREAD

**Issue by nomike** [microsoft/wslg#748]
# Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: Windows Subsystem for Linux WLSg Preview 1.0.26
```

# Steps to reproduce

Set the keyboard layout in Windows to "English (United States) - United States International".
You have now support for dead keys. E.g. in notepad you can type <">, <a> to get the letter ä.

If you usethe same key combination in a Linux graphical application (e.g. gedit) you will end up with "a.

#  Expected behavior

I expect the same key-presses to produce the same letters regardless of whether you are in a native Windows application or in a Linux application.

# Actual behavior

The same key presses produce different results depending on what type of application you are in.

**Comment by hideyukn88** [comment]
@nomike, please update WSL from aka.ms/wslstorepage, then it should work, thanks!

![image](https://user-images.githubusercontent.com/13857962/171743872-82bd9a84-e779-47ab-99e5-fcee4f321dad.png)

**Comment by elsaco** [comment]
Is this bug about `dead keys` or the modifier `AltGr`, the `Alt` key at the right of `space` key? They are not the same.

**Comment by hideyukn88** [comment]
Closing this as the issue reported does not reproduce, if this is not the case, please reopen with output from `wsl --version`, thanks!
