### ISSUE TITLE
Windows Start menu shortcuts are not created if 'Ubuntu' folder is missing

### ISSUE THREAD

**Issue by SyntevoAlex** [microsoft/wslg#750]
# Environment

```none
Windows build number: 10.0.22000.675
Your Distribution version: 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce
1) Delete folder `%AppData%\Microsoft\Windows\Start Menu\Programs\Ubuntu`
2) Install a shortcut in `/usr/share/applications`
Shortcut is not created in `%AppData%\Microsoft\Windows\Start Menu\Programs\Ubuntu`.

3) Create empty folder `%AppData%\Microsoft\Windows\Start Menu\Programs\Ubuntu`
4) Install a shortcut in `/usr/share/applications`
Now it works.

**WSL logs**: 
[pulseaudio.log](https://github.com/microsoft/wslg/files/8790133/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/8790135/weston.log)
[versions.txt](https://github.com/microsoft/wslg/files/8790141/versions.txt)

#  Expected behavior
Shortcuts should be created together with the missing folder.

# Actual behavior
Shortcuts are not created.

# Notes
I deleted folder manually (and discovered this bug) when troubleshooting a problem reported by customer.

**Comment by hideyukn88** [comment]
Fixed in WSLg 1.0.39
