### ISSUE TITLE
Not all releases are published under https://github.com/microsoft/wslg/releases

### ISSUE THREAD

**Issue by ohault** [microsoft/wslg#753]
e.g. https://github.com/microsoft/wslg/commit/4bf6401cb759fb5d5c857319b8a37d72711a6347

**Comment by hideyukn88** [comment]
@ohault, we don't release WSLg independently anymore, all public releases are from aka.ms/wslstorepage with WSL. Thanks!

**Comment by ohault** [comment]
It's very sad for an Open Source project and the worse is that wie have also lost the release notes. Can you please continue to deliver releases via Github with release notes ?

**Comment by stackia** [comment]
It's better to leave a note on https://github.com/microsoft/wslg/releases to point to the WSL releases page, otherwise, ppl will think wslg as an abandoned project due to inactive changelogs.

**Comment by ohault** [comment]
Great, thank you. I can see it's back on track since https://github.com/microsoft/wslg/releases/tag/v1.0.45

**Comment by hideyukn88** [comment]
FYI: Link to WSLg release is added to WSL release page as suggested.

**Comment by ohault** [comment]
Thx
