### ISSUE TITLE
When WSLg is installed, copying a PNG to the clipboard will cause all system UI constantly refreshed.

### ISSUE THREAD

**Issue by ixuan789** [microsoft/wslg#758]
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

In WSL: gedit and its dependencies

### Repro Steps

Just install a GUI application in WSL, and try to run it once.
And then copy a PNG image on Windows, all the Windows UI will constantly refreshed until you copy some plain text, or shutdown the wsl.

I first encountered this problem at least 3 months ago.
I thought it was an issue with the WSLg preview.
Thanks to the issue microsoft/WSL#8166 , I known the issue clearly. But that issue was cloesed, so I try to submit a new one.

### Expected Behavior

Nothing happend.

### Actual Behavior

It will cause any window to lose focus frequently.
I even can't use my devices.

In this GIF, you will see the issue. 
Once I copy a PNG Image(GIF, JPG is OK) to the clipboard, soon all the windows start to blink, and CPU usage increases.
Copy some text or shut down the wsl can stop this madness.

![bug](https://user-images.githubusercontent.com/23429395/172544257-8d04b11f-8592-48cf-9014-ece5cc3e8498.gif)

### Diagnostic Logs

[WslLogs-2022-06-08_14-00-11.zip](https://github.com/microsoft/WSL/files/8858705/WslLogs-2022-06-08_14-00-11.zip)

I use [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) to collect this logs.

After the logcat started, I boot the wsl, copy a PNG Image to the clipboard, and keep the UI blink for 10s, copy some text to stop the madness. Finally, exit the shell and save the log.

**Comment by hideyukn88** [comment]
@ixuan789, please make sure you are using WSLg version 1.0.33 or newer, you can find WSLg version by `wsl --version` from Window's command prompt. If you are using the latest version, but still hitting this issue, please check if any core files are created under /mnt/wslg/dumps, and share them with us, thanks!

**Comment by markKscode** [comment]
我这儿的是输入法在中文和英文之间自动快速切换，根本打不了字。

**Comment by ixuan789** [comment]
> @ixuan789, please make sure you are using WSLg version 1.0.33 or newer, you can find WSLg version by `wsl --version` from Window's command prompt. If you are using the latest version, but still hitting this issue, please check if any core files are created under /mnt/wslg/dumps, and share them with us, thanks!

Thanks for the reply. Seems the issue has been resolved in the latest version!
I get it from aka.ms/wslstorepage.

My version info now:
```
WSL 版本： 0.60.0.0
内核版本： 5.10.102.1
WSLg 版本： 1.0.34
MSRDC 版本： 1.2.2924
Direct3D 版本： 1.601.0
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22000.675
```

p.s.
I just found out I need to download the preview version from MSstore. Before this, the `wsl --version` command has no effect. And `wsl --update` and the WSLg Github releases only up to 1.0.26.
So just download it from store, and the issue will be solved.

**Comment by cherrol** [comment]
The problem was solved after I updated windows and wsl.

**Comment by MitchTalmadge** [comment]
Mentioning #443 for visibility.
