### ISSUE TITLE
Copying bitmap to clipboard causes unexpected Windows behavior

### ISSUE THREAD

**Issue by appel1** [microsoft/wslg#768]
### Version

Microsoft Windows [Version 10.0.22000.708]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Make sure wsl is running by opening a terminal window. 
Open Task Manager. 
In Windows open Microsoft Edge and navigate to a page. 
Press Ctrl+Shift+C, select an area and press Copy. 

### Expected Behavior

I'd expect it to behave like if I copy regular text. That is no unexpected blinking and window deactivation/activation or wmmem cpu usage. 

### Actual Behavior

The Task Manager window and others start to blink and redraw. Same thing with the systray icons. 
Vmmem process continuously uses about 10% CPU. 
It is difficult to interact with applications that blink. 

If I copy regular text the blinking stops and Windows goes back to normal. Another option is to shutdown wsl with `wsl --shutdown`.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/973314/172813796-d50b054c-66fa-4040-923d-8aa23e7283e6.png">

### Diagnostic Logs

[WslLogs-2022-06-09_11-28-00.zip](https://github.com/microsoft/WSL/files/8869035/WslLogs-2022-06-09_11-28-00.zip)

**Comment by MitchTalmadge** [comment]
See https://github.com/microsoft/wslg/issues/443

**Comment by MitchTalmadge** [comment]
Good question. The releases page only shows 1.0.28 as the latest pre-release, and 1.0.26 as the latest release. I do have the preview version installed according to the Microsoft Store: https://aka.ms/wslstorepage

I don't know where any information on 1.0.34 is.

**Comment by hideyukn88** [comment]
@MitchTalmadge, now WSLg is always released as a part of WSL release, you can find release notes at https://github.com/microsoft/WSL/releases.

**Comment by hideyukn88** [comment]
@appel1, I think this is dup of https://github.com/microsoft/wslg/issues/348, please update WSL from aka.ms/wslstorepage, unfortunately there is no automatic update from WSLg 1.2x to 1.3x, thus one time manual update from Store is currently required, thanks!

**Comment by dsmithkeyloop** [comment]
If you don't have access to the store (say due to GPO restrictions), just install with the .msixbundle file from the releases link above.  Appears to have fixed the issue for me, thanks everyone.
