### ISSUE TITLE
Some WSLg applications can't interact with Windows 11 browser

### ISSUE THREAD

**Issue by delucca** [microsoft/wslg#770]
# Environment

**Windows Build Number**
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.22000.0 Microsoft Windows NT 10.0.22000.0
```

**Distro:** Fedora Linux 35

**WSLg version:** 1.0.26

# Steps to reproduce

- Install Gitkraken
- Login into an account
- Go to settings
- Go to "Integrations"
- Go to "Github"
- Click "Connect to Github"

#  Expected behavior

I was expecting the browser to open (I've already have a `$BROWSER` env variable pointing to my Windows browser)

# Actual behavior

Nothing happens

**Comment by hideyukn88** [comment]
Hi @delucca, have you installed any browser in Linux? For me, the Linux version of Firefox starts up and process login. Btw, you are on very old version of WSLg, please update it from aka.ms/wslstorepage, thanks!

>> WSLg version: 1.0.26

**Comment by delucca** [comment]
@hideyukn88 thanks!

i don't have any browser installed on Linux, can't I link it to open the Windows browser?

Regarding the WSLg version, actually the installed app is `Windows Subsystem for Linux WSLg Preview` (which has the 1.0.26 version)

My WSL installation is custom (Fedora), I've searched for WSLg in the Microsoft Store but was not able to find anything. Also, if I run `wsl --update` from an elevated shell it says that is already up to date

**Comment by hideyukn88** [comment]
@delucca, I think you will need a browser installed in Linux side. For WSLg update, please type `aka.ms/wslstorepage` to your Windows's browser, then Store app will start up with WSL page, thanks!

**Comment by hideyukn88** [comment]
@delucca,

>> (I've already have a $BROWSER env variable pointing to my Windows browser)

May I ask what do you set in $BROWSER env ? thanks!

**Comment by delucca** [comment]
@hideyukn88 sure, here it is:
```
~
❯ echo $BROWSER
/mnt/c/Program Files/Mozilla Firefox/firefox.exe
```

It is the path to Firefox on my Windows machine.

BTW, I've just updated WSLg using your URL

**Comment by hideyukn88** [comment]
@delucca, sorry for late response, I was able to observe same issue with GitHub CLI, and it looks it appears they don't handle space in path such as "Program Files" well, please see below error message. And if firefox is copied to the folder with no space in path, such as /mnt/c/tmp/firefox.exe, then Github CLI is able to launch Windows version of Firefox properly. Could gitkarken be same? Please let us know, thanks!


```
hideyukn@HIDEYUKN-SX2:~$ echo $BROWSER
/mnt/c/Program Files/Mozilla Firefox/firefox.exe

hideyukn@HIDEYUKN-SX2:~$ gh auth login
? What account do you want to log into? GitHub.com
? You're already logged into github.com. Do you want to re-authenticate? Yes
? What is your preferred protocol for Git operations? HTTPS
? How would you like to authenticate GitHub CLI? Login with a web browser

! First copy your one-time code: XXXX-XXXX
Press Enter to open github.com in your browser...
! Failed opening a web browser at https://github.com/login/device
exec: "/mnt/c/Program": stat /mnt/c/Program: no such file or directory
Please try entering the URL in your browser manually
```

**Comment by hideyukn88** [comment]
For GitHub CLI case, by looking at https://github.com/cli/cli/blob/b9c1605c411167f1cb38e5323f038149c32a9a9f/pkg/cmdutil/web_browser.go#L28, it splits by space and first token is considered as executable, thus it doesn't work if path contains space.

**Comment by hideyukn88** [comment]
Closing the issue as this is not actionable from WSLg.
