### ISSUE TITLE
FXApp::openDisplay: unable to open display :0

### ISSUE THREAD

**Issue by rye2020** [microsoft/wslg#773]
# Environment

```none
**Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]**
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.25145.0 Microsoft Windows NT 10.0.25145.0

jrm@OPX3050:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

PS C:\Users\jrmar> wsl --version
WSL version: 0.60.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.34
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25145.1011

Your Distribution version: [On Debian or Ubuntu run `Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.25145.0 Microsoft Windows NT 10.0.25145.0` in WSL]
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `pulseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

# Actual behavior

unable to run any graphical apps -- XFE gives "FXApp::openDisplay: unable to open display :0"

**Comment by rye2020** [comment]
the problem seems to be only with some graphical apps started from the command line.  Thunar File Manager, Text Editor, and System Monitor started from Windows Start execute properly.  However, xfe started from Windows Start gives the same error message.  thunar from command line gives  cannot open display: :0 error.  

https://forum.snapcraft.io/t/wsl-wslg-and-systemd-hacks/24022 does not seem to cure problem this time

**Comment by hideyukn88** [comment]
@rye2020, thanks for reporting the issue, would you please provide a bit more details step to reproduce and the error message? thanks!
