### ISSUE TITLE
Outdated documentation: No longer need for nvidia drivers (?)

### ISSUE THREAD

**Issue by Ueland** [microsoft/wslg#776]
The pre-requresites recommend installing a specific Nvidia driver. The driver's page now states:

```
Developers can now leverage the NVIDIA software stack on Microsoft Windows WSL environment using the NVIDIA drivers available today.
```

This guide from Nvidia: https://docs.nvidia.com/cuda/wsl-user-guide/index.html states: 
```
(driver version) R495 and later windows will have CUDA support for WSL 2.
```

So it seems to me that there is no longer a need for a preview driver from Nvidia to get WSLg up and running

**Comment by zulc22** [comment]
I believe this applies to the AMD driver as well, as I could run `glxgears` in Debian without installing the specific AMD driver the page tells me to use.

**Comment by hideyukn88** [comment]
@Ueland, @zulc22, thanks for pointing out this. When WSLg was just released years ago, the GPU drivers support WSL were only available by manually updating driver, thus the URL from each GPU manufactures website is listed for convenience, but now all major GPU manufacturers is releasing the WSL capable drivers in standard release including Windows Update, thus no longer requiring installing specific drivers. And also, software renderer is always available, thanks!

**Comment by Dwuuds** [comment]
I get the feeling that currently this project is essentially on life support...

**Comment by Masamune3210** [comment]
It just got a release in July, what are you on about lol
Just because you don't see large jumps in progress doesn't mean that work isn't being done

**Comment by Dwuuds** [comment]
> 

I realize that I came across as a total D in that last post, apologies. I just really want to see this project succeed, but Microsoft is spinning 10000 plates at a time and sometimes good projects go un-noticed by the community at large. Hell, I work in the IT world and a good chunk of people don't even know _what_ powertoys is let alone wsl.

**Comment by Masamune3210** [comment]
Lots of stuff are held up in other parts of the system. If it involves any OS changes, it has to go through a lot of teams, a lot of validation and would likely have to wait for a feature update. Slow and steady is just how big projects move, companies included. They have a lot of things spinning, but given the amount of people who work there, I would honestly be surprised if that wasn't the case
