### ISSUE TITLE
not updating to wslg from wsl2

### ISSUE THREAD

**Issue by iKausik** [microsoft/wslg#779]
# Environment

```none
Windows build number: 22000.739
Your Distribution version: Ubuntu 22.04 LTS
Your WSL version: WSL2
```

# How to update to WSLg ??

![Screenshot 2022-07-02 141505](https://user-images.githubusercontent.com/32932853/176993541-2006af71-311f-4562-ba6c-4592dbf38fe1.png)

**Comment by benhillis** [comment]
Install the version of WSL from the store.

**Comment by iKausik** [comment]
wsl2 already install with ubuntu 22.04 from the store. but I want to install WSLg!!

**Comment by Rauxon** [comment]
WSLg is not a different release,

I am running that version of WSL and have the GUI applications running perfectly well.

**Comment by elsaco** [comment]
@iKausik you already have the latest `WSLg`. It is part of WSL2. It's also known as the `system` distro, the container that provides `weston` for graphics, `PulseAudio` for sound, the `kernel`, and more. Look for details under `/mnt/c/wslg` folder. To boot the system distro use `wsl --system`, however no changes will survive. This is a read-only distro.

**Comment by tusharsnn** [comment]
> wsl2 already installed with ubuntu 22.04 from the store. but I want to install WSLg!!

wslg does not come separately from the wsl2 package. To use wslg you need to install wsl2 preview version from the store. If wsl2 (store version) is correctly installed, the output for `wsl --version` should be something like:
```sh
WSL version: 0.61.8.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.795
```
note the wslg version info.
