### ISSUE TITLE
Bug of WSL Preview - Empty /mnt/wslg/.X11-unix & /tmp/.X11-unix Directory

### ISSUE THREAD

**Issue by yqs112358** [microsoft/wslg#782]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.778]
Distribution version: Ubuntu 20.04
WSL version: 0.61.8.0
WSL kernel version: 5.10.102.1
WSLg version: 1.0.39
```

# Steps to reproduce
1. Install `WSL Preview` in Microsoft Store to upgrade WSL to the newest
2. Open Ubuntu, try `xterm` but get `xterm: Xt error: Can't open display: :0`
3. Check solutions in wiki [Diagnosing "cannot open display" type issues with WSLg](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg), then find that there is nothing in `/tmp/.X11-unix` and `/mnt/wslg/.X11-unix`. X11 socket was not created and linked correctly
<img width="299" alt="image" src="https://user-images.githubusercontent.com/37969157/177687953-50633403-4ab9-4287-827c-1db5aab91618.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/37969157/177688655-2c53d1b8-c60b-4161-80ad-2d170a510d1c.png">

4. "Display" environment variable is correct:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/37969157/177688995-39e9f360-0eba-406d-9efc-7b59e4303fbe.png">

### versions.txt
```
WSLg ( x86_64 ): 1.0.39+Branch.main.Sha.cdbed82a21d382b5c74367c48a32ef4736cc8735
Mariner: VERSION="2.0.20220426"
mesa:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 4e99bb16dd44fc6daf4a45c46ba3e053c0637afa
```
### weston.log
[weston.log](https://github.com/microsoft/wslg/files/9060270/weston.log)
### pulseaudio.log
[pulseaudio.log](https://github.com/microsoft/wslg/files/9060289/pulseaudio.log)

#  Expected behavior
Everything works well, and GUI applications run normally.

# Actual behavior
X11 socket was not created and linked correctly

**Comment by yqs112358** [comment]
More: 
I installed synaptic package manager and it works well after I fix environment variable manually:
```
export DISPLAY=:0
export WAYLAND_DISPLAY=wayland-0
export XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
export PULSE_SERVER=/mnt/wslg/PulseServer
```
but X11 programs (like xeyes, xterm,...) still cannot work. Maybe the wayland part works well and the X11 proxy had some problem during install process.

**Comment by yqs112358** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/37969157/177808325-82aaa20e-5f52-4166-b2b0-bc3f33e24b3d.png">
the wayland-0 socket is OK. I think the problem is only about XWayland

**Comment by yqs112358** [comment]
After uninstall WSL Preview in Microsoft Store and restart WSL, X0 socket appears again in `/mnt/wslg/.X11-unix`.
It seems that the problem is solved so I close this issue. But I think there maybe some problem in WSL Preview, anyway.

**Comment by win98se** [comment]
IMO, this issue needs to be kept open. It is a bug in WSL Preview, and it is not the solution for users to uninstall WSL Preview and use the stock WSL instead.

Additional information: I can't even remove the `/tmp/.X11-unix` directory as the error message says "Device or resource busy" -
![image](https://user-images.githubusercontent.com/11819816/179380906-bc58856c-f553-4976-a0d6-07e68a8cb8eb.png)

**Comment by yqs112358** [comment]
> IMO, this issue needs to be kept open. It is a bug in WSL Preview, and it is not the solution for users to uninstall WSL Preview and use the stock WSL instead.
> 
> Additional information: I can't even remove the `/tmp/.X11-unix` directory as the error message says "Device or resource busy" - ![image](https://user-images.githubusercontent.com/11819816/179380906-bc58856c-f553-4976-a0d6-07e68a8cb8eb.png)

Oh I had the same problem, actually.

**Comment by alparslanozturk** [comment]
there is no solution already linked by tmpfile.d setup. 
```
java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at org.netbeans.core.startup.Main.start(Main.java:228)
        at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
        at java.base/java.lang.Thread.run(Thread.java:834)

/usr/local/jdk/bin$ ls -alh /tmp/.X11-unix/
total 24K
drwxrwxrwx  2 root root  60 Jul 27 12:47 .
drwxrwxrwt 11 root root 20K Jul 27 12:49 ..
lrwxrwxrwx  1 root root  19 Jul 27 12:47 .X11-unix -> /mnt/wslg/.X11-unix

```

**Comment by lisander-lopez** [comment]
> I changed with these commands:
> 
> ```
>  sudo umount /tmp/.X11-unix
>  sudo rm -rf /tmp/.X11-unix
>  sudo ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
> ```

Did not work for me, still got `Error: Can't open display: :0` after a `xcalc`

**Comment by pfeerick** [comment]
I have the same issue, but for me, this only started in the last few weeks.

**Comment by ShaneCarr** [comment]
> I changed with these commands:
> 
> ```
>  sudo umount /tmp/.X11-unix
>  sudo rm -rf /tmp/.X11-unix
>  sudo ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
> ```

This does work. Lordie, i have a lot of trouble with wslg. maybe wsl can just do this on every start. yes i know but i mean it' s just really annoying. Even a hack would be appreciated.

**Comment by hakanserce** [comment]
Having the exact same issue. Started noticing after the 1.0.0.0 update.

**Comment by hakanserce** [comment]
The following (thanks to @alparslanozturk), followed by a `wsl --shutdown` worked for me:

```
 sudo umount /tmp/.X11-unix
 sudo rm -rf /tmp/.X11-unix
 sudo ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
```

**Comment by edmondium** [comment]
To make it work, create ``/etc/tmpfiles.d/wslg.conf`` file with the following content:
```
#  This file is part of the debianisation of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.

# See tmpfiles.d(5) for details

# Type Path           Mode UID  GID  Age Argument
L+     /tmp/.X11-unix -    -    -    -   /mnt/wslg/.X11-unix
```
then restart WSL.

**Comment by Andrew-J-Larson** [comment]
> I changed with these commands:
> 
> ```
>  sudo umount /tmp/.X11-unix
>  sudo rm -rf /tmp/.X11-unix
>  sudo ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
> ```

Thanks! I had to remove the WSLg preview from my computer first, shutdown WSL, and then run these commands in my distro, and it got GUI working again.

> To make it work, create `/etc/tmpfiles.d/wslg.conf` file with the following content:
> 
> ```
> #  This file is part of the debianisation of systemd.
> #
> #  systemd is free software; you can redistribute it and/or modify it
> #  under the terms of the GNU General Public License as published by
> #  the Free Software Foundation; either version 2 of the License, or
> #  (at your option) any later version.
> 
> # See tmpfiles.d(5) for details
> 
> # Type Path           Mode UID  GID  Age Argument
> L+     /tmp/.X11-unix -    -    -    -   /mnt/wslg/.X11-unix
> ```
> 
> then restart WSL.

And this fixes the issue for subsequent restarts of WSL.

**Comment by brookman1** [comment]
**Andrew-J-Larson** summary likely works.  Follow the directions, my X11 works now on WSL2 Windows 11!
