### ISSUE TITLE
WESTON_RDP_DEBUG_DESKTOP_SCALING_FACTOR is ignored

### ISSUE THREAD

**Issue by ChGen** [microsoft/wslg#787]
WESTON_RDP_DEBUG_DESKTOP_SCALING_FACTOR parameter is ignored, so I cannot force e.g. 200 dpi when having 150% scale in the MS Windows itself.

# Environment

```none
wsl -v
Версия WSL: 0.61.8.0
Версия ядра: 5.10.102.1
Версия WSLg: 1.0.39
Версия MSRDC: 1.2.3213
Версия Direct3D: 1.601.0
Версия DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows версии: 10.0.22000.795
```
WSL2g, Ubuntu 22.04 LTS Linux distribution, from the MS Store.

# Steps to reproduce

I put `.wslconfig` to my Windows home drectory and restart WSL with `wsl --shutdown`:
```
[system-distro-env]
WESTON_RDP_DEBUG_DESKTOP_SCALING_FACTOR=200
[wsl2]
kernelCommandLine=mitigations=off
```

Kernel command line options do get added to `/proc/cmdline`,  but simple `gedit` runs with 100% scale under WSLg.
This is reproduceable is different systems.

Expected behavior: native 200% scale for `gedit` in WSLg environment.

WSLg logs are attached.

[wslg.tar.gz](https://github.com/microsoft/wslg/files/9127510/wslg.tar.gz)

**Comment by tusharsnn** [comment]
wslg related config should be kept in `.wslgconfig` instead of .wslconfig.

**Comment by ChGen** [comment]
Oh, my bad. Bit thanks!
It works now. I think this could be closed now.
