### ISSUE TITLE
WSLGd: Please make `mstsc` and `msrdc` locations configurable

### ISSUE THREAD

**Issue by cky** [microsoft/wslg#794]
WSLGd contains numerous hardcoded file references, which are not configurable via environment variables, such as the location of `C:\Windows\System32\mstsc.exe`, `C:\ProgramData\Microsoft\WSL\msrdc.exe`, etc. (You can configure the `C:\ProgramData\Microsoft\WSL` part via `$WSL2_INSTALL_PATH`, but it's still hardcoded to expect `msrdc.exe` to be inside that directory, rather than in `\Program Files\Remote Desktop`, which is the default install location for `msrdc`.)

This means that for people who have [Windows installed in a different drive](https://twitter.com/cky944/status/1342374700165586945), it takes jumping through a lot of hoops to have a working WSLg setup. Please make the location of `mstsc` and `msrdc` configurable (and independent of `$WSL2_INSTALL_PATH`).

(Ideally, I'd like to see the location of `.wslgconfig` be configurable too, but I'm not sure if that's actually possible, since there's a chicken-and-egg problem going on there. Also, I still have to log into the system instance every boot and edit `/etc/fonts/local.conf`, but that's a small inconvenience in comparison to the above.)

**Comment by elsaco** [comment]
`I still have to log into the system instance every boot` ...why not edit on the client side to avoid the system distro. The font rendering is done by `FreeType` not `X`.

**Comment by hideyukn88** [comment]
@cky, thanks for reporting the issue. Yes, currently there is hardcoded C drive dependency when mstsc is used by specifying "WSLG_USE _MSTSC" option in .wslgconfig. https://github.com/microsoft/wslg/blob/f3f7f81bf876a320fbbdc29dc398cd3af0597add/WSLGd/main.cpp#L38 https://github.com/microsoft/wslg/blob/f3f7f81bf876a320fbbdc29dc398cd3af0597add/WSLGd/main.cpp#L374 But by default, msrdc.exe is used and the WSLg released from Store includes msrdc and $WSL2_INSTALL_PATH should point the path contains msrdc regardless of where Windows is installed. Would you please update WSL from aka.ms/wslstorepage and try again? 

And regarding to font path, yes, this has to be dynamically configured to point correct Windows path.

https://github.com/microsoft/wslg/blob/f3f7f81bf876a320fbbdc29dc398cd3af0597add/config/local.conf#L5

Thanks!

**Comment by cky** [comment]
> But by default, msrdc.exe is used and the WSLg released from Store includes msrdc and $WSL2_INSTALL_PATH should point the path contains msrdc regardless of where Windows is installed. Would you please update WSL from aka.ms/wslstorepage and try again?

Ah, very nice, thank you! I did install the Windows Store version of WSL, but didn't know that it set `$WSL2_INSTALL_PATH` automatically; I had, instead, been using its `$WSL2_USER_PROFILE` feature to use my own `.wslgconfig` file that sets up `$WSL2_INSTALL_PATH` directly. Glad to know I don't need even that!

Would you like me to leave this issue open, in regard to `/etc/fonts/local.conf`? Or create a new issue for it?

**Comment by hideyukn88** [comment]
@cky, yes please go ahead to open one, and there is another C drive dependency here.

https://github.com/microsoft/wslg/blob/8d4696b44106e0a76157aa73cb6814cd094359ba/config/default_wslg.pa#L4

But unfortunately, these issues could be lower priority for us as it is not common to install Windows other than `C:\WINDOWS`, but we will revisit depending on how many upvote will the issue get, thanks!

**Comment by cky** [comment]
@hideyukn88 Thanks for identifying more places to fix! I totally understand that it's not a priority for the WSLg team—I'm more than happy to file a pull request when I implement it myself, since this is my own itch to scratch. :smiley:

Since the original issue seems adequately addressed by the Windows Store version of WSLg, I'll close this issue. Thanks again!
