### ISSUE TITLE
Android emulator could not work

### ISSUE THREAD

**Issue by c0ffeec0der** [microsoft/wslg#796]
# Environment

Windows build number: Microsoft Windows NT 10.0.22000.0
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.40 (Note does not show in Apps but from wsl --version)

# Steps to reproduce

run android emulator (i.e emulator -avd [avd name])

#  Expected behavior

Emulator to run in x11 window

# Actual behavior

not running with error:

The Android emulator exited with code -11 during startup
Android emulator stderr:
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the
emulator.
WARNING | cannot add library /home/felix/sdk/android/emulator/qemu/linux-x86_64/lib64/vulkan/libvulkan.so: failed
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Address these issues and try again.
[pulseaudio.log](https://github.com/microsoft/wslg/files/9210061/pulseaudio.log)
[versions.txt](https://github.com/microsoft/wslg/files/9210062/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/9210063/weston.log)
[WslLogs-2022-07-28_20-23-33.zip](https://github.com/microsoft/wslg/files/9210067/WslLogs-2022-07-28_20-23-33.zip)

**Comment by c0ffeec0der** [comment]
Question, is there a way to revert to old version? It works with

WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22000.675

**Comment by hideyukn88** [comment]
@c0ffeec0der, thanks for reporting the issue. Android emulator is the one of applications we used for WSLg verification, and I confirmed that it is working on the same build version as yours. You can install order WSLg version from https://github.com/microsoft/WSL/releases, in your case, https://github.com/microsoft/WSL/releases/tag/0.58.3, and download the .msixbundle, and double click the file will start the installation. You might want to uninstall previous version first. Please let us know if it works on older WSLg version, thanks!

**Comment by c0ffeec0der** [comment]
@hideyukn88 Thank you so much! I just installed WSL version: 0.58.3.0 and its working !!

Just for my curiosity, could you try to retest running android emulator with WSLg version 1.0.40 on WSL 0.64.0? I am worried if future updates of WSL will continuously break running android emulator. Many Thanks

**Comment by hideyukn88** [comment]
@c0ffeec0der, I did with below version, which is next release candidate, thanks!

```
C:\Windows\System32>wsl --version
WSL version: 0.64.2.0
Kernel version: 5.10.102.1
WSLg version: 1.0.40
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25171.1000
```

<img width="675" alt="image" src="https://user-images.githubusercontent.com/13857962/181833327-9988a6d5-690c-42c3-b520-de0f2d55b733.png">

**Comment by c0ffeec0der** [comment]
Thanks @hideyukn88 , I will try when WSL : 0.64.2.0 is GA. Many Thanks!
