### ISSUE TITLE
Preview build being forced on me via Windows Update

### ISSUE THREAD

**Issue by gary-desroches** [microsoft/wslg#800]
# Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version:  22.04
Your WSLg version: 1.0.26
```

# Steps to reproduce
Upgrade to Windows 11
Go to Windows Update

#  Expected behavior
I don't expect Windows Update to be forcing preview builds on me.  It should be under "Optional Updates."

# Actual behavior
Windows Subsystem for Linux WSLg Preview 1.0.26 is listed as "Download Pending."  It will be forced to install when quality and security updates are installed.

**Comment by hideyukn88** [comment]
@gary-desroches, if you have installed WSLg, then its update will be automatically installed, thanks!

**Comment by gary-desroches** [comment]
I don't have it installed.  Windows is telling me it will be installed if I want any updates from Windows Update.

**Comment by hideyukn88** [comment]
@gary-desroches, basically WSLg has been always in "Preview" state, thus thank you very much for trying out WSLg!

![image](https://user-images.githubusercontent.com/13857962/185473224-4028e970-10e6-48da-bda7-cc513ee966fc.png)
