### ISSUE TITLE
Add the new issue forms instead of templates

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/wslg#804]
I would like to suggest to use the new issue forms instead of the templates in this repository.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

I would also like to work on this if you like the idea.

**Comment by hideyukn88** [comment]
@Aaron-Junker, yes, it sounds good, if you can help us, please! thanks!

**Comment by hideyukn88** [comment]
@Aaron-Junker, thank you very much for your contribution. I approve the PR, so whenever you feel good about, please complete it, thanks!

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker, thank you very much for your contribution. I approve the PR, so whenever you feel good about, please complete it, thanks!

What's missing? I thinknit's finished.

**Comment by hideyukn88** [comment]
@Aaron-Junker, nothing is missing, I just wanted to double check. I've merged the PR, thanks for your contribution!
