### ISSUE TITLE
exessive startup time (14s) for first xterm window (MS SQ2 arm64 processor & GPU)

### ISSUE THREAD

**Issue by hwine** [microsoft/wslg#806]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Release:        20.04
Your WSL versions: [run `wsl --version` on Windows command prompt]
WSL version: 0.65.3.0
Kernel version: 5.15.57.1
WSLg version: 1.0.41
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.856
Device Specs: [from Settings => System => About]
Device name	TABLET-935H4GMO
Processor	Microsoft SQ2 @ 3.15 GHz   3.15 GHz
Installed RAM	16.0 GB (15.6 GB usable)
Device ID	<removed>
Product ID	<removed>
System type	64-bit operating system, ARM-based processor
Pen and touch	Pen and touch support with 10 touch points
```

# Steps to reproduce

1. Cold boot (or warm or after `wsl --shutdown`)
2. let all startup activity complete (i.e. CPU, etc, idling)
3. start MS app `Terminal`
4. start `xterm`
5. time duration before window is drawn on screen

* Attach WSLg logs from  `/mnt/wslg`

_No files or directories under this mountpoint._

#  Expected behavior

First time startup should be, at most, a few seconds. No other display output anomalies should occur.

Please let me know if these are unreasonable expectations for the current state of WSLg on a Microsoft SQ2 processor & gpu. I can't quite tell from other issues what my expectations should be for this combination.

Things worked much better on this machine with traditional X. I don't do video or audio from wsl -- just text. (I use native Win11 apps for a/v.) Happy to help, as when Xwayland does work, it's very nice. But the current stability isn't practical.

# Actual behavior

It takes about 14 seconds for the window to appear. After that, windows appear "instantly". 

The above part is repeatable, I also experience occasional ongoing "display stalls", even in `Terminal`. `dmesg` output from around those times sometimes shows `rcu: INFO: rcu_sched self-detected stall on CPU`, followed by a task dump, where the task is WSLg related (`weston`, `weston-rdprail-`, `Xwayland`). I've observed these "text stalls" using `Terminal`, `Terminal Preview`, and `VScode` (win 11, wsl as remote).

**Comment by WSLUser** [comment]
If you use a normal Powershell prompt (no WT involved), do you still experience the latency?

**Comment by hwine** [comment]
Please clarify - for win 11 "normal Powershell" uses "WT" -- how do you want me to start it?

**Comment by WSLUser** [comment]
From Start, Run: type pwsh.exe, or failing that, powershell.exe. If you've configured WT as your default term though, might be difficult to get it to run outside of it.

**Comment by WSLUser** [comment]
If you have issues running a shell through conhost on Win11, I suggest opening a discussion thread on the wt discussion page: https://github.com/microsoft/terminal/discussions

**Comment by hwine** [comment]
Ah "`conhost`" was the magic I needed -- I'll have to wait until after work to do the test.

**Comment by hwine** [comment]
Starting wsl from `conhost` still took ~13 seconds for first `xterm`
<details>

I press ^D as soon as the xterm displays.
```none
Microsoft Windows [Version 10.0.22000.856]
(c) Microsoft Corporation. All rights reserved.

C:\Users\hwine>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

Loading personal and system profiles took 2951ms.
C:\Users\hwine> wsl -d work

/c/Users/hwine
❯ date
Mon Aug 15 14:47:56 PDT 2022

/c/Users/hwine
❯ declare -p DISPLAY WAYLAND_DISPLAY
declare -x DISPLAY=":0"
declare -x WAYLAND_DISPLAY="wayland-0"

/c/Users/hwine
❯ date ; xterm ; date
Mon Aug 15 14:48:27 PDT 2022
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
Mon Aug 15 14:48:40 PDT 2022

/c/Users/hwine took 13s
❯ date ; xterm ; date
Mon Aug 15 14:49:14 PDT 2022
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
Mon Aug 15 14:49:15 PDT 2022

/c/Users/hwine
```

**Comment by Biswa96** [comment]
The delay for wslg startup depends on internal implementation of actual WSL feature. It does not matter which terminal program is being used. There are delay in x86_64 systems also. But the delay should be perceivable for first time only.

**Comment by hwine** [comment]
@Biswa96 thanks - since this appears to be a known issue, I'll close it. I assume the WSLg team has been able to provide the WSL team with far more precise information than I could.

I'll see if I can better isolate the stability issues - I was hoping they were linked.

Thanks, all!

**Comment by hideyukn88** [comment]
@hwine, currently this delay at X11 application startup is due to fontconfig initialization with Windows's side font, from /mnt/c/Windows/Fonts, accessing Windows volume from Linux is much slower than local ext4 filesystem, we are seeking some solution on this, thanks!
