### ISSUE TITLE
Error: Can't Open Display: :0

### ISSUE THREAD

**Issue by awlc** [microsoft/wslg#815]
### Windows build number:

22621.575

### Your Distribution version:

22.04.1

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.575

### Steps to reproduce:

any x apps such as xcalc, xeyes

### WSL logs:

[weston.log](https://github.com/microsoft/wslg/files/9403113/weston.log)
[versions.txt](https://github.com/microsoft/wslg/files/9403115/versions.txt)

### Actual behavior:

Error: Can't Open Display: :0

**Comment by awlc** [comment]
[Solved]

Problem was that ls /mnt/wslg/.X11-unix/ gives X3 instead of X0.

Solution was simple:
1. go to Windows Settings->Apps->Installed apps and remove "Windows Subsystem for Linux WSLg Preview"
2. download it from github, and install it again.  I got the Preview version:[https://github.com/microsoft/wslg/releases/download/v1.0.28/wsl_graphics_support_x64.msi](url)
3. restart wsl by wsl --shutdown

Done, ls /mnt/wslg/.X11-unix/ gives X0 again.

**Comment by awlc** [comment]
[Solved]

Problem was that ls /mnt/wslg/.X11-unix/ gives X3 instead of X0.

Solution was simple:

go to Windows Settings->Apps->Installed apps and remove "Windows Subsystem for Linux WSLg Preview"
download it from github, and install it again. I got the Preview version:[https://github.com/microsoft/wslg/releases/download/v1.0.28/wsl_graphics_support_x64.msi](https://github.com/microsoft/wslg/issues/url)
restart wsl by wsl --shutdown
Done, ls /mnt/wslg/.X11-unix/ gives X0 again.

**Comment by awlc** [comment]
[Solved]

Problem was that ls /mnt/wslg/.X11-unix/ gives X3 instead of X0.

Solution was simple:

go to Windows Settings->Apps->Installed apps and remove "Windows Subsystem for Linux WSLg Preview"
download it from github, and install it again. I got the Preview version:[https://github.com/microsoft/wslg/releases/download/v1.0.28/wsl_graphics_support_x64.msi](https://github.com/microsoft/wslg/issues/url)
restart wsl by wsl --shutdown
Done, ls /mnt/wslg/.X11-unix/ gives X0 again.

**Comment by LBates2000** [comment]
I have the same issue with WSLG version 1.0.42, which was released 5 days ago. What you're suggesting is a downgrade to a much older version from Sep 15, 2021. WSLg is now included with WSL and I suspect that as soon as you run `wsl --update` you'll get bumped back up to WSL 0.66.2/WSLg 1.0.42

You may want to look here instead: https://github.com/microsoft/WSL/releases

**Comment by awlc** [comment]
> I have the same issue with WSLg version 1.0.42, which was released 5 days ago. What you're suggesting is a downgrade to a much older version of WSLg from Sep 15, 2021. I suspect that as soon as you run `wsl --update` you'll get bumped back up to WSL 0.66.2/WSLg 1.0.42
> 
> You may want to look here instead: https://github.com/microsoft/WSL/releases Filed a bug report here: [microsoft/WSL#8759](https://github.com/microsoft/WSL/issues/8759)

I downloaded the latest "Windows Subsystem for Linux WSLg Preview" from github with v1.0.28, but then when I do wsl --version and it shows
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.586

And the funny thing is...  I had another PC having the same issue, I did the same process by reinstalling "Windows Subsystem for Linux WSLg Preview" so things seemed good.  I rebooted the PC and the socket changed from X0 to X3.  I reinstalled WSLg again then went back to X0.

This raises my interest on how this xserver and weston actually work on WSL.

**Comment by awlc** [comment]
Problem still persists, went back to X2, X3... etc after PC rebooted.

Temp solution:
https://github.com/microsoft/wslg/issues/818#issuecomment-1227756256

**Comment by rye2020** [comment]
the solution mentioned in [(https://github.com/microsoft/wslg/issues/818)] works for my non systemd system, but not for a systemd system, at least for me.

**Comment by nicoandmee** [comment]
I am experiencing this same issue.

**Comment by pbecotte** [comment]
Seems pretty clear they stopped doing releases from this repo- is there a documented way to download/install a specific release anymore?

**Comment by codeart1st** [comment]
Experienced the same issue

```
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.586

plange@ws20211107:~$ ls /mnt/wslg/.X11-unix -al
total 0
drwxrwxrwx 2 root   root    60 Sep 25 08:06 .
drwxrwxrwt 7 root   root   280 Sep 25 08:06 ..
srwxrwxrwx 1 foo    foo0 Sep 25 08:06 X3
```

**Comment by hideyukn88** [comment]
Hi all, regarding to X server connection issue, WSL 0.70.0 is just released, and this should address the issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

**Comment by awlc** [comment]
> Hi all, regarding to X server connection issue, WSL 0.70.0 is just released, and this should address the issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

Yup confirmed all good now!
