### ISSUE TITLE
No GUI (x11 errors) after Windows Subsystem for Linux Preview update today

### ISSUE THREAD

**Issue by chincheta** [microsoft/wslg#816]
### Windows build number:

22000.856

### Your Distribution version:

22.04

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.856

### Steps to reproduce:

1. Open the terminal.
2. Try to open any app with a GUI, for instance google-chrome.
3. It complains about x11 not running and does not run.

### WSL logs:

[stderr.log](https://github.com/microsoft/wslg/files/9418376/stderr.log)
[weston.log](https://github.com/microsoft/wslg/files/9418377/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/9418378/pulseaudio.log)

### WSL dumps:

No dumps.

### Expected behavior:

I expect apps using the GUI would work.

### Actual behavior:

Error messages on the terminal:

[1864:1864:0824/195920.130803:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[1864:1864:0824/195920.130844:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.

**Comment by chincheta** [comment]
This workaround works:

https://github.com/microsoft/wslg/issues/815#issuecomment-1225174620

**Comment by carylewis** [comment]
I am experiencing the same issue, but the work around posted does not work.

I traced the problem to the point of where the /mnt/wslg/.X11-unix/X0 file gets deleted or overwritten, and it is happening in:

`/usr/sbin/enter-systemd-namespace`

This script launches systemd, and at some point after that, the X0 file is deleted.

**Comment by hideyukn88** [comment]
Hi all, regarding to X server connection issue, WSL 0.70.0 is just released, and this should address the issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!
