### ISSUE TITLE
X server display socket is being set incorrectly after upgrade to WSL 0.66.2.0/WSLg 1.0.42

### ISSUE THREAD

**Issue by LBates2000** [microsoft/wslg#818]
### Version

Microsoft Windows [Version 10.0.22622.575]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Pengwin WLinux (Debian 11)

### Other Software

Docker Desktop (Windows), version 4.11.1 (84025)/Docker engine version 20.10.17, build 100c701
also seems to have sporadic issues spinning up, but I think that is because of the issue with WSLg

### Repro Steps

Launch distro and observe the following at boot:

```
xdpyinfo:  unable to open display ":0".
xprop:  unable to open display ':0'
xprop:  unable to open display ':0'
xprop:  unable to open display ':0'
xprop:  unable to open display ':0'
```
Check the DISPLAY environment variable:
```
$ echo $DISPLAY
:0
```
Launch a GUI program. i.e. if xeyes is installed, use it to verify:
```
$ xeyes
Error: Can't open display: :0
```
View the socket:
```
$ ls -la /tmp/.X11-unix/
total 44
drwxrwxrwx 2 root   root      60 Aug 23 20:21 .
drwxrwxrwt 5 root   root   40960 Aug 23 21:15 ..
srwxrwxrwx 1 lbates lbates     0 Aug 23 20:21 X3
```
Change the DISPLAY environment variable to match the socket:
`DISPLAY=:3`
Test again:
`$ xeyes`
GUI program displays correctly

### Expected Behavior

Socket should be set to `/tmp/.X11-unix/X0` every time.

### Actual Behavior

Socket is set to  `/tmp/.X11-unix/X1, X2, X3, etc.`

### Diagnostic Logs

```
Default Distribution: WLinux
Default Version: 2
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.575
```

**Comment by benhillis** [comment]
@hideyukn88 - I think I've seen this as well, it seems intermittent and like a new regression with WSLg. Can you think of anything that would have caused this?

**Comment by keai4le** [comment]
OMG, workinging for me!

**Comment by soerenhenkel** [comment]
I see the same issue when I auto-start Docker Desktop for Windows at login. When I disable that option, and start my WSL distro (Ubuntu-20.04) first (before Docker), the issue does not seem to pop up.
Maybe the two distros that Docker starts (docker-desktop, docker-desktop-data) somehow block the X0 and X1 socket, so that for Ubuntu, only X2 is left usuable?

**Comment by acarrillo** [comment]
I experience this frequently on my machine, and it definitely seems related to the order in which the `docker-desktop` container starts. I often seem to be able to fix this by shutting both wsl and docker down, then starting wsl first, then starting docker.

In this screenshot, the top terminal is shelled into `docker-desktop`, and the bottom terminal is shelled into my `Ubuntu-20.04` container. In this example, `docker-desktop` has taken `X1`, and my Ubuntu container has taken `X0` (this is a working config):

![image](https://user-images.githubusercontent.com/442213/192875765-d5b4b374-43a6-4609-be24-5645823860e2.png)


After reading through a few of these related open GH issues, I have figured out that I can hotfix a running session by running `cd /tmp/.X11-unix && mv X1 X0`, where `X1=` is what showed when I `ls /tmp/.X11-unix`. Pretty interesting!

**Comment by hideyukn88** [comment]
This should be fixed by WSL [0.67.6](https://github.com/microsoft/WSL/releases/tag/0.67.6) or newer, thanks!

**Comment by matthewpersico** [comment]
> This should be fixed by WSL [0.67.6](https://github.com/microsoft/WSL/releases/tag/0.67.6) or newer, thanks!

I just installed WSL fresh on a Windows 11 upgrade:
```
C:\Users\matth>wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2
WSL version: 0.66.2.0
...
WSLg version: 1.0.42
...
```
When will 0.67.6 hit the Microsoft Store?

**Comment by hideyukn88** [comment]
Hi all, WSL 0.70.0 is just released from Store, and this should address the issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

**Comment by acarrillo** [comment]
Thank you @hideykn88! Appreciate the fix turnaround. I shut all WSL instances down, started Docker first, then my WSL distro, and `/tmp/.X11/X0` was set correctly for my distro 🎉

**Comment by matthewpersico** [comment]
> Hi all, WSL 0.70.0 is just released from Store, and this should address the issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

```
PS C:\Users\matth> wsl --shutdown
PS C:\Users\matth> wsl --update
Checking for updates.
Error: 0x80244022
Error code: Wsl/UpdatePackage/0x80244022
PS C:\Users\matth>
```
Can you advise?
