### ISSUE TITLE
Running a wslg program will generate a host to mstsc

### ISSUE THREAD

**Issue by Jw9394** [microsoft/wslg#826]
### Windows build number:

10.0.22000.856

### Your Distribution version:

22.04

### Your WSL versions:

Ubuntu-22.04 WSL2

### Steps to reproduce:

1. enabled all wsl features.
2. upgrade wsl to wsl2.
3. install a ubuntu-22.04 from Microsoft Store.
4. install a gui program like gedit(apt install gedit).
5. open start menu and run the gedit
6. gedit run successfully and at the same time, windows remote desktop will regularly generate a host automatically.

### Expected behavior:

do not generate a host to my mstsc program.

### Actual behavior:

i have 3 wslg program so it generate 3 different hosts.
![20220913103824](https://user-images.githubusercontent.com/65437870/189795339-ad08f0ea-d354-4197-a097-fb9d4053bd4a.png)

**Comment by hideyukn88** [comment]
@Jw9394, this issue should be resolved already, please update WSL from aka.ms/wslstorepage, thanks!
