### ISSUE TITLE
After restarting wsl, GUI: Error: Can't open display:: 0 cannot be displayed

### ISSUE THREAD

**Issue by qinshuze** [microsoft/wslg#834]
### Windows build number:

22621.382

### Your Distribution version:

Debian 11

### Your WSL versions:

WSL 版本： 0.66.2.0
内核版本： 5.15.57.1
WSLg 版本： 1.0.42
MSRDC 版本： 1.2.3401
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.382

### Steps to reproduce:

1. Open WSL, enter `xeyes`, and the GUI program can be displayed normally
![image](https://user-images.githubusercontent.com/22045080/191697824-200732ba-6dae-4216-a41e-649555843375.png)

2. Enter `wsl - t Debian` on the console to close the distribution
![image](https://user-images.githubusercontent.com/22045080/191697974-bc4ff111-4689-4a70-93e5-51227019c09d.png)

3. Enter the distribution again, enter `xeyes`, and get the output: Error: Can't open display:: 0
![image](https://user-images.githubusercontent.com/22045080/191698076-53850c5f-f9ad-4f3a-846f-7b3e8129bf14.png)

### WSL logs:

[pulseaudio.log](https://github.com/microsoft/wslg/files/9623721/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/9623722/weston.log)
[stderr.log](https://github.com/microsoft/wslg/files/9623723/stderr.log)

### Expected behavior:

GUI program can be displayed normally
![image](https://user-images.githubusercontent.com/22045080/191694057-93d24c6a-2882-4ca4-83e2-1ac456bb3691.png)

### Actual behavior:

Error: Can't open display: :0
![image](https://user-images.githubusercontent.com/22045080/191694211-4d5ec440-16a1-477f-a8ad-09936dc8f8f2.png)

**Comment by tusharsnn** [comment]
Take a look at #820.

**Comment by qinshuze** [comment]
> 看看#820。

this doesn't work for me https://github.com/microsoft/wslg/issues/820#issuecomment-1229467157
I can't tell if it's the same problem, as I restarted the computer and the problem was fixed, but if I shut down the distribution again with `wsl -t Debian` the problem reappears

**Comment by tusharsnn** [comment]
just to cross-check, please share the contents of `/tmp/.X11-unix` when this problem occurs.

**Comment by qinshuze** [comment]
> just to cross-check, please share the contents of `/tmp/.X11-unix` when this problem occurs.
Changes when an error occurs
![image](https://user-images.githubusercontent.com/22045080/191813508-af6c3b28-227f-42df-8e15-441751840802.png)
Changes after restarting the computer
![image](https://user-images.githubusercontent.com/22045080/191813852-3e009a1a-3f1f-46b4-9a8c-78bba41513fc.png)
Funny thing happened, after I restarted my computer
The solution given at https://github.com/microsoft/wslg/issues/820#issuecomment-1229467157 worked for me! Now the GUI program works fine after restarting the distribution
![image](https://user-images.githubusercontent.com/22045080/191814694-58c1fb80-099b-477e-8e17-5bf88ba8f550.png)

**Comment by tusharsnn** [comment]
You may close this issue now, as it is already being tracked there.
