### ISSUE TITLE
start Systemd and cannot start firefox

### ISSUE THREAD

**Issue by qyw233** [microsoft/wslg#838]
### Windows build number:

22622.0

### Your Distribution version:

20.04

### Your WSL versions:

WSL 版本： 0.67.6.0
内核版本： 5.15.62.1
WSLg 版本： 1.0.44
MSRDC 版本： 1.2.3401
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22622.601

### Steps to reproduce:

1.start Systemd [https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/](url)
2.start firefox then show unable to init server: could not connect: connection refused error cannot open display: :0

### Actual behavior:

as I start Systemd following [https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/](url)，then I can not start firefox and other application with sudo such as sudo geany
it says unable to init server: could not connect: connection refused error cannot open display: :0

**Comment by tusharsnn** [comment]
I am guessing it might be related to permissions, does it work without sudo?

**Comment by Yuzi0201** [comment]
same！！

**Comment by qyw233** [comment]
> I am guessing it might be related to permissions, does it work without sudo?

firefox without sudo did not work,the same as sudo  .Other program work without sudo but can not run with sudo

**Comment by elsaco** [comment]
@qyw233 what is the output of `systemctl status user.slice`? Here's output of Firefox on Ubuntu, Firefox was installed as a snap:

![wsl_ubuntu_snap_firefox](https://user-images.githubusercontent.com/3933920/192079174-b3a11072-7cb8-49d8-894a-34418592be30.png)

**Comment by tusharsnn** [comment]
> firefox without sudo did not work,the same as sudo .Other program work without sudo but can not run with sudo

@qyw233  By default sudo does not preserve user env vars set by wsl. In order to preserve env while running the command with sudo you need to add -E flag:

> -E, --preserve-env
> Indicates to the security policy that the user wishes to preserve their existing environment variables. The security policy may return an error if the user does not have permission to preserve the environment.

try running apps with:
```sh
$ sudo -E <comm>
```

**Comment by qyw233** [comment]
> @qyw233输出是什么？以下是火狐在Ubuntu上的输出，火狐是作为快照安装的：`systemctl status user.slice`
> 
> ![wsl_ubuntu_snap_firefox](https://user-images.githubusercontent.com/3933920/192079174-b3a11072-7cb8-49d8-894a-34418592be30.png)

     Loaded: loaded (/lib/systemd/system/user.slice; static; vendor preset: enabled)
     Active: active since Sat 2022-09-24 12:54:33 CST; 2min 54s ago
       Docs: man:systemd.special(7)
      Tasks: 57
     Memory: 109.4M
     CGroup: /user.slice
             └─user-1000.slice
               ├─session-c1.scope
               │ ├─723 /bin/login -f
               │ └─898 -bash
               └─user@1000.service
                 ├─at-spi-dbus-bus.service
                 │ ├─1078 /usr/libexec/at-spi-bus-launcher
                 │ ├─1083 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
                 │ └─1086 /usr/libexec/at-spi2-registryd --use-gnome-session
                 ├─dbus.service
                 │ ├─904 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
                 │ ├─961 /usr/libexec/goa-daemon
                 │ └─984 /usr/libexec/goa-identity-service
                 ├─gvfs-afc-volume-monitor.service
                 │ └─993 /usr/libexec/gvfs-afc-volume-monitor
                 ├─gvfs-daemon.service
                 │ ├─924 /usr/libexec/gvfsd
                 │ └─939 /usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
                 ├─gvfs-goa-volume-monitor.service
                 │ └─957 /usr/libexec/gvfs-goa-volume-monitor
                 ├─gvfs-gphoto2-volume-monitor.service
                 │ └─1006 /usr/libexec/gvfs-gphoto2-volume-monitor
                 ├─gvfs-metadata.service
                 │ └─1043 /usr/libexec/gvfsd-metadata
                 ├─gvfs-mtp-volume-monitor.service
                 │ └─999 /usr/libexec/gvfs-mtp-volume-monitor
                 ├─gvfs-udisks2-volume-monitor.service
                 │ └─945 /usr/libexec/gvfs-udisks2-volume-monitor
                 ├─init.scope
                 │ ├─887 /lib/systemd/systemd --user
                 │ └─888 (sd-pam)
                 ├─pulseaudio.service
                 │ └─895 /usr/bin/pulseaudio --daemonize=no --log-target=journal
                 └─tracker-miner-fs.service
                   └─897 /usr/libexec/tracker-miner-fs

Warning: journal has been rotated since unit was started, output may be incomplete.
~

**Comment by qyw233** [comment]
@tusharsnn  Oh！I can use sudo -E geany to open geany.But firefox cannot open with or without sudo.

john@ThinkPad-E480:~$ firefox
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0
john@ThinkPad-E480:~$ sudo -E firefox
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/john which is owned by john.)


firefox cannot use sudo

**Comment by hideyukn88** [comment]
Currently we are aware of systemd and WSLg is not working along on Ubuntu 20.04. You can try Ubuntu 22.04 or 18.04, or Debian as workaround, we will look into the root cause with 20.04, thanks!

**Comment by roblatham00** [comment]
systemd and WSLg does not work on my Ubuntu 22.04 installation ..  Could be related to #844

**Comment by hideyukn88** [comment]
Hi all, WSL 0.70.0 is just released and it addresses various issues with systemd, including the problem like this, please update by `wsl --update`, and if it still doesn't address, please let us know by reopening this issue, thanks!
