### ISSUE TITLE
Installing an application in snap doesn't create a start menu icon

### ISSUE THREAD

**Issue by kbdharun** [microsoft/wslg#842]
### Windows build number:

 10.0.22622.0

### Your Distribution version:

Ubuntu 22.04

### Your WSL versions:

```powershell
PS C:\Users\kbdha> wsl --version
WSL version: 0.67.6.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.601
```

### Steps to reproduce:

1. `wsl --update` or update through Store.
2. Enable systemd support as mentioned [here](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl).
3. `sudo apt install snapd` (Note: This step isn't required as the `snap` is part of the core Ubuntu Package, this command is for installing `snapd` if you have removed it in past).
4. Now, We install a `snap` package, for example, ` sudo snap install shortwave`. 

This is the output

```bash
[user@user]:~$ sudo snap install shortwave
shortwave 3.0.0 from Alex Murray (alexmurray✪) installed
```
6. Check the Start menu for icons.

### Expected behaviour:

The icon of the default snap package (if exists) must be displayed in the Start menu just like how icons are displayed for applications installed using package managers like `apt`; if the icon doesn't exist for an application, you could use the generic one used currently.

### Actual behaviour:

No icons are created for applications installed through `snap` in the start menu.

### Extra information:

Since icons aren't created in the start menu for snap packages unlike other package managers, I need to use the terminal to directly open the application, so it effectively blocks my terminal. I could open multiple terminal sessions, but it increases memory usage. Also, having multiple terminal windows/tabs open would mean that it would be hard to keep a note on the ones that I am working on.

### Reference Issues/Discussions

https://github.com/microsoft/wslg/discussions/829

**Comment by Sos-Zachary** [comment]
i have the same problem.[https://github.com/microsoft/wslg/discussions/829](url)

**Comment by hideyukn88** [comment]
When applications are installed using snap, the desktop file will be placed at `/var/lib/snapd/desktop/applications`, currently this folder is not monitored by WSLg, we will work on the fix, thanks for reporting the issue!

**Comment by hideyukn88** [comment]
Please update to WSL 0.70.0 which contains the fix for this issue, by `wsl --update`, and if this still occurs, please let is know, thanks!

**Comment by kbdharun** [comment]
> Please update to WSL 0.70.0 which contains the fix for this issue, by `wsl --update`, and if this still occurs, please let is know, thanks!

Thanks
