### ISSUE TITLE
Ubuntu Programs don't appear in Windows start menu

### ISSUE THREAD

**Issue by AndyArty** [microsoft/wslg#846]
### Windows build number:

22000.0

### Your Distribution version:

22.04

### Your WSL versions:

WSL-Version: 0.66.2.0
Kernelversion: 5.15.57.1
WSLg-Version: 1.0.42
MSRDC-Version: 1.2.3401
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22000.978

### Steps to reproduce:

Install a program - Mine is shotwell
Search it on Windows Start menu

### Expected behavior:

The shotwell icon should be visible in Windows start menu

### Actual behavior:

it's not

**Comment by hideyukn88** [comment]
Dup of https://github.com/microsoft/wslg/issues/823, fixed in WSLg 1.0.44, thanks!
