### ISSUE TITLE
Cannot open GUI for any application on WSL (Kali Linux)

### ISSUE THREAD

**Issue by dvdmtw98** [microsoft/wslg#847]
### Windows build number:

10.0.22000.1042

### Your Distribution version:

2022.3

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1042

### Steps to reproduce:

Try to launch any application from terminal

### Versions.txt
```bash
cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.42+Branch.main.Sha.78fa15d6ffd8fad62343b194d39c142e57cc1869
Mariner: VERSION="2.0.20220426"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: d57e0de202fd049f6cc0ce8c25b7120feea3468f
```

### Display Variable
Note: This variable was set to blank and was manually created
```bash
echo $DISPLAY
:0
```

### Socket File
Note: This link did not exist and was manually created using [Error Guide](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg)
```bash
ls -la /tmp/.X11-unix
lrwxrwxrwx 1 david david 19 Sep 29 11:12 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
```

### Folder Content
Note: Error Guide says X0 should exist but my system shows X1
```bash
ls -la /tmp/.X11-unix/
total 0
drwxrwxrwx 2 root  root   80 Sep 29 11:13 .
drwxrwxrwt 7 root  root  280 Sep 29 11:08 ..
srwxrwxrwx 1 david david   0 Sep 29 11:08 X1
lrwxrwxrwx 1 david david  19 Sep 29 11:13 .X11-unix -> /mnt/wslg/.X11-unix
```

### Log Files
[weston.log](https://github.com/microsoft/wslg/files/9671462/weston.log)
[stderr.log](https://github.com/microsoft/wslg/files/9671464/stderr.log)

### Expected behavior:

GUI for the application should open

### Launching Gedit
```bash
gedit

(gedit:106): Gtk-WARNING **: 11:14:28.643: cannot open display: :0
```

### Launching Wireshark
```bash
wireshark
 ** (wireshark:159) 11:23:03.708119 [GUI WARNING] -- could not connect to display :0
 ** (wireshark:159) 11:23:03.708291 [GUI ERROR] -- This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

zsh: IOT instruction  wireshark
```

### Cherrytree
```bash
cherrytree

(cherrytree:282): Gtk-WARNING **: 11:33:21.645: cannot open display: :0
```

**Comment by dvdmtw98** [comment]
### Additional Note
- Using WSL Preview (The one that can be downloaded from the Microsoft Store)
- I do have Ubuntu and Docker installed on the system as well

```bash
wsl --list

Windows Subsystem for Linux Distributions:
Ubuntu (Default)
kali-linux
docker-desktop-data
docker-desktop
```

**Comment by NotTheDr01ds** [comment]
I could be wrong, but the fact that you have an `X1` makes me believe you are experiencing the regression that happened in 0.66.2 described in #825.  According to [this comment](https://github.com/microsoft/wslg/issues/825#issuecomment-1261464445), the WSLg team believes that they have this fixed in WSL 0.67.6 and later (currently 0.68.2 is the latest).  This release is not currently available in the Store, but has to be manually downloaded from the [WSL releases page](https://github.com/microsoft/WSL/releases).

Can you try updating and see if the problem persists or is resolved?

**Comment by dvdmtw98** [comment]
@NotTheDr01ds I updated to the current latest version (0.68.2) and it seems to have solved the problem. Thanks

**Comment by NotTheDr01ds** [comment]
@dvdmtw98 Great to hear!  When you get a chance, remember to close this one out.  Thanks!
