### ISSUE TITLE
Some GUI Applications Are Unresponsive (Arch Linux)

### ISSUE THREAD

**Issue by cdunford** [microsoft/wslg#848]
### Windows build number:

10.0.22621.521

### Your Distribution version:

Arch (https://github.com/yuk7/ArchWSL) - 22.3.18.0

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521

### Steps to reproduce:

Launch one of the following applications:

- GIMP
- Reaper

### WSL logs:

[pulseaudio.log](https://github.com/microsoft/wslg/files/9690397/pulseaudio.log)
[stderr.log](https://github.com/microsoft/wslg/files/9690398/stderr.log)
[versions.txt](https://github.com/microsoft/wslg/files/9690399/versions.txt)
[weston.log](https://github.com/microsoft/wslg/files/9690400/weston.log)

### WSL dumps:

There are none.

### Expected behavior:

The applications should be functional and respond to both mouse and keyboard input

### Actual behavior:

Bother GIMP and Reaper are nearly completely unresponsive. Neither respond to mouse input at at all; I cannot move the window or minimize/maximize it. The menus seem to respond to keyboard shortcuts however the sub-menus do not render.

I have just updated to WIndows 11 22H2; these applications were working (mostly) correctly on the prior version of Windows 11 with WSL/WSLg

Kdenlive does not seem to suffer from this issue and functions correctly.

**Comment by hideyukn88** [comment]
@cdunford, thanks for reporting the issue. I have tried out gimp and reaper, I didn't see any issue with gimp and it works normally. reaper was not able to start up due to below error, I haven't looked into further, but it looks no relation to WSL/WSLg, thanks!

`reaper: symbol lookup error: /usr/lib/REAPER/libSwell.so: undefined symbol: gdk_init_check`

**Comment by cdunford** [comment]
@hideyukn88 - where do we go from here? this was working prior to the 22H2 update in Windows 11. Would a capture showing the behavior help?

**Comment by hideyukn88** [comment]
@cdunford, while gimp is unresponsive, what would happen if other application, such as xterm is launched, does xterm window can be moved/maximized by mouse, and does it work with keyboard input? thanks!

**Comment by cdunford** [comment]
@hideyukn88  - yes other applications work while unresponsive applications are open; it mostly seems like the applications are just not responsive mouse input.

**Comment by hideyukn88** [comment]
@cdunford, is the unresponsive application's window at maximized state? thanks!

**Comment by cdunford** [comment]
Here's a recording showing the behavior in GIMP. No response to mouse at all. You can see I can somewhat navigate with the keyboard; the menus at the top sometimes show, but usually don't.

![gimp](https://user-images.githubusercontent.com/1405868/194706211-340b339f-f14f-43ba-a4c2-12b4f038f06f.gif)

**Comment by hideyukn88** [comment]
@cdunford, thanks for screen recording, I think this is same issue as https://github.com/microsoft/wslg/issues/801, the fix will be released in next WSL update release, thanks!

**Comment by cdunford** [comment]
@hideyukn88 - awesome! do you know what that is due to be released?

**Comment by hideyukn88** [comment]
@cdunford, the fix is included in WSL 0.70.0 which is already released, please update by `wsl --update` and help us to verify the fix. I will close this issue, but if it's still not addressed, please let us know by reopening it, thanks!
