### ISSUE TITLE
App doesn't start GUI or put Entries in Start Menu

### ISSUE THREAD

**Issue by avlec** [microsoft/wslg#849]
### Windows build number:

22621.521

### Your Distribution version:

22.04

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.521

### Steps to reproduce:

1. Install Ubuntu from Microsoft Store
2. Try to run emacs from Ubuntu WSL

### WSL logs:

```
$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.42+Branch.main.Sha.78fa15d6ffd8fad62343b194d39c142e57cc1869
Mariner: VERSION="2.0.20220426"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: d57e0de202fd049f6cc0ce8c25b7120feea3468f
```
```
$ echo $DISPLAY
:0
```
```
$ ls -la /tmp/.X11-unix
total 4
drwxrwxrwx  2 root  root    60 Oct  5 00:10 .
drwxrwxrwt 13 root  root  4096 Oct  5 00:10 ..
srwxrwxrwx  1 avlec avlec    0 Oct  5 00:10 X0
```
[weston.log](https://github.com/microsoft/wslg/files/9713528/weston.log)

### Expected behavior:

Expecting to be able to run emacs from WSL by invoking `emacs` from WSL terminal or from entry displayed in the start menu under a "Ubuntu" folder.

### Actual behavior:

Invoking `emacs` from WSL terminal causes process to not do anything further. No more console output, the only way to regain control is to `Ctrl+Z` the process and force it dead.

There is no "Ubuntu" folder and subsequently no entry to run emacs.

**Comment by VenelinU** [comment]
I got the same problem. I have managed to create the shortcuts manually.
Create the shortcut here:
C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Ubuntu(distro name)\
VLC.lnk
C:\Windows\System32\wsl.exe ~ -d Ubuntu /usr/bin/vlc

It is working like a charm :-)

**Comment by avlec** [comment]
The problem is not simply the missing link, running `C:\Windows\System32\wsl.exe ~ -d Ubuntu /usr/bin/emacs` from cmd generates no console output and no GUI is displayed.

**Comment by hideyukn88** [comment]
@avlec, this is dup of https://github.com/microsoft/wslg/issues/823 for missing start menu item, and your last comments is dup of https://github.com/microsoft/wslg/issues/820, thanks for reporting the issue.
