### ISSUE TITLE
WSL2 does not use discrete graphics

### ISSUE THREAD

**Issue by archee8** [microsoft/wslg#86]
I have ASUS G14 with spec:
1) CPU : R5-4600HS
2) GPU : NVIDIA GTX 1650
3) WSL2
When I run GUI applications, they run using integrated graphics. How can i run GUI apps on NVIDIA graphics?

**Comment by KarasevPavel** [comment]
Have same problem on Acer Aspire 7 with spec:

  1. CPU:  i7-9750H
  2. GPU : NVIDIA GTX 1650
  
  Nvidia driver was installed from the [link](https://developer.nvidia.com/cuda/wsl)
  Ubuntu 20.04
  Mesa drivers were built manually using this [link](https://gitlab.freedesktop.org/mesa/mesa)

**Comment by willparsons** [comment]
I have the same issue. Running a ortbk GUI app and seeing "No available video device".

**Comment by simonernst** [comment]
I would say that your OpenGL renderer is still on software (llvm).
You can check by using this command and read the "OpenGL renderer string"
```bash
glxinfo | grep OpenGL
```
To install glxinfo : `sudo apt install mesa-utils`

On my system, I upgraded mesa using this ppa (both on Ubuntu 18.04 & 20.04) : https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

```bash
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt-get update && sudo apt dist-upgrade
``` 

Then when running `glxinfo | grep OpenGL`, I got OpenGL rendered on my GPU: 
```bash
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce GTX 1660 Ti)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.0.3 - kisak-mesa PPA
```

Hope this helps !

**Comment by spronovo** [comment]
At the moment if you have multiple GPU all supporting vGPU in WSL, the mesa d3d12 gallium driver will pick which ever GPU happens to be enumerated first on your system. We're currently looking at changes that will let user control which GPU is picked, stay tune.

**Comment by willparsons** [comment]
@spronovo Weird thing is I am on a ryzen processor so I only have the discrete card that provides graphics. Unless I am understanding that wrong.

**Comment by spronovo** [comment]
Could you share the output of glxinfo-B

**Comment by willparsons** [comment]
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 11.0.0, 256 bits) (0xffffffff)
    Version: 20.2.6
    Accelerated: no
    Video memory: 7927MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 11.0.0, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 20.2.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20


```

**Comment by spronovo** [comment]
Thanks, you are running on Mesa's software renderer (LLVM 11.0.0, 256 bits). This is because you are running Mesa 20.2.6. As the blog and project main page describes, you need to be on Mesa 21.x in order to light up GPU acceleration. Mesa is a component that ships along with your user distro, so not something that WSLg itself can update for you.

From: https://devblogs.microsoft.com/commandline/wslg-architecture/

```
Depending on when you read this, accelerated OpenGL in WSLg may or may not immediately light up on your system as you may still be running an older version of Mesa. If you don’t want to wait on your distro to pick up those changes and want to try this out immediately, you can visit Mesa official home and build a private version of Mesa with this support. Alternatively, you can try out Canonical recently announced Ubuntu on Windows Community Preview for WSL 2. This new distribution of Ubuntu is built from bleeding edge components an includes support for Mesa 21.0, enabling seamless hardware accelerated OpenGL with WSLg out of the box. This distribution is meant for advanced WSL users to help test and debug upcoming features and not meant as a “daily driver” but is a great way of getting an early glimpse at those features.
```

Alternatively, you can try something like the package repo that Kisak maintains so you can easily install bleeding build of Mesa without having to build them yourselves or having to switch to a bleeding edge distro. 

https://itsfoss.com/install-mesa-ubuntu/

Eventually these changes will flow through the system and will be available in your distro without taking additional steps, but that is still some ways away.

Steve

**Comment by wmarti** [comment]
I have  the 470.14 NVIDIA Driver installed, as well as  The Canonical Release of Ubuntu on Windows Community Preview for WSL 2 (Mesa Version is 21.0.1). Still getting the same issue as these other people.

**Comment by wmarti** [comment]
Make sure to update to the latest WSL kernel version.

**Comment by archee8** [comment]
> Thanks, you are running on Mesa's software renderer (LLVM 11.0.0, 256 bits). This is because you are running Mesa 20.2.6. As the blog and project main page describes, you need to be on Mesa 21.x in order to light up GPU acceleration. Mesa is a component that ships along with your user distro, so not something that WSLg itself can update for you.
> 
> From: https://devblogs.microsoft.com/commandline/wslg-architecture/
> 
> _Depending on when you read this, accelerated OpenGL in WSLg may or may not immediately light up on your system as you may still be running an older version of Mesa. If you don’t want to wait on your distro to pick up those changes and want to try this out immediately, you can visit Mesa official home and build a private version of Mesa with this support. Alternatively, you can try out Canonical recently announced Ubuntu on Windows Community Preview for WSL 2. This new distribution of Ubuntu is built from bleeding edge components an includes support for Mesa 21.0, enabling seamless hardware accelerated OpenGL with WSLg out of the box. This distribution is meant for advanced WSL users to help test and debug upcoming features and not meant as a “daily driver” but is a great way of getting an early glimpse at those features._
> 
> Alternatively, you can try something like the package repo that Kisak maintains so you can easily install bleeding build of Mesa without having to build them yourselves or having to switch to a bleeding edge distro.
> 
> https://itsfoss.com/install-mesa-ubuntu/
> 
> Eventually these changes will flow through the system and will be available in your distro without taking additional steps, but that is still some ways away.
> 
> Steve

I installed Mesa 21.0, but the GUIs still don't use the NVIDIA card.

> ```
> OpenGL vendor string: Mesa/X.org
> OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits) 
> OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3 - kisak-mesa PPA                 
> OpenGL core profile shading language version string: 4.50           
> OpenGL core profile context flags: (none)              
> OpenGL core profile profile mask: core profile                                                                                                                                                                                                                                                                                                                        
> OpenGL core profile extensions: 
> OpenGL version string: 3.1 Mesa 21.0.3 - kisak-mesa PPA
> OpenGL shading language version string: 1.40    
> OpenGL context flags: (none)  
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3 - kisak-mesa PPA
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20  
> OpenGL ES profile extensions:  
> ```

**Comment by spronovo** [comment]
@archee8 do you see ```/dev/dxg``` listed? If not you need to update your NVIDIA driver to one supporting WSL: https://developer.nvidia.com/cuda/wsl. 

I see that you are using kisak's repo. In addition to be on Mesa 21.x, you need to have compile Mesa with the d3d12 gallium driver included. kisak had a chat with our d3d folks over the weekend and he updated his repo to include those binaries, so you may need to ```sudo apt-get update && sudo apt dist-upgrade``` to pick up the latest. List the content of the directory below and verify if d3d12_dri.so is present.

```
spronovo@OFFICE:~$ ls /usr/lib/x86_64-linux-gnu/dri
d3d12_dri.so       iHD_drv_video.so   nouveau_drv_video.so  r600_dri.so        radeonsi_drv_video.so  zink_dri.so
i915_dri.so        iris_dri.so        nouveau_vieux_dri.so  r600_drv_video.so  swrast_dri.so
i965_dri.so        kms_swrast_dri.so  r200_dri.so           radeon_dri.so      virtio_gpu_dri.so
i965_drv_video.so  nouveau_dri.so     r300_dri.so           radeonsi_dri.so    vmwgfx_dri.so
```

Could you verify which kernel you are running as well

```
spronovo@OFFICE:~$ uname -a
Linux OFFICE 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

If you are not on 5.10.16, you'll want to ```wsl --shutdown``` and ```wsl --update``` from an elevated command prompt in Windows.

**Comment by archee8** [comment]
> @archee8 do you see `/dev/dxg` listed? If not you need to update your NVIDIA driver to one supporting WSL: https://developer.nvidia.com/cuda/wsl.
> 
> I see that you are using kisak's repo. In addition to be on Mesa 21.x, you need to have compile Mesa with the d3d12 gallium driver included. kisak had a chat with our d3d folks over the weekend and he updated his repo to include those binaries, so you may need to `sudo apt-get update && sudo apt dist-upgrade` to pick up the latest. List the content of the directory below and verify if d3d12_dri.so is present.
> 
> ```
> spronovo@OFFICE:~$ ls /usr/lib/x86_64-linux-gnu/dri
> d3d12_dri.so       iHD_drv_video.so   nouveau_drv_video.so  r600_dri.so        radeonsi_drv_video.so  zink_dri.so
> i915_dri.so        iris_dri.so        nouveau_vieux_dri.so  r600_drv_video.so  swrast_dri.so
> i965_dri.so        kms_swrast_dri.so  r200_dri.so           radeon_dri.so      virtio_gpu_dri.so
> i965_drv_video.so  nouveau_dri.so     r300_dri.so           radeonsi_dri.so    vmwgfx_dri.so
> ```
> 
> Could you verify which kernel you are running as well
> 
> ```
> spronovo@OFFICE:~$ uname -a
> Linux OFFICE 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> If you are not on 5.10.16, you'll want to `wsl --shutdown` and `wsl --update` from an elevated command prompt in Windows.

I see  `/dev/dxg` 

```
archee8@DESKTOP-KJHVQ36:~$ ls /usr/lib/x86_64-linux-gnu/dri
d3d12_dri.so  iris_dri.so        nouveau_vieux_dri.so  r600_dri.so      swrast_dri.so      zink_dri.so
i915_dri.so   kms_swrast_dri.so  r200_dri.so           radeon_dri.so    virtio_gpu_dri.so
i965_dri.so   nouveau_dri.so     r300_dri.so           radeonsi_dri.so  vmwgfx_dri.so
```
```
archee8@DESKTOP-KJHVQ36:~$ uname -a
Linux DESKTOP-KJHVQ36 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by spronovo** [comment]
You're on the older kernel... The 5.4 kernel was creating ```/dev/dxg``` even if no actual GPU devices enumerated over vPCI.

Could you update your kernel (```wsl --shutdown``` and ```wsl --update```).

On Windows, could you launch dxdiag.exe, click "Save All Information" and attach the resulting txt file to this thread.

**Comment by archee8** [comment]
> You're on the older kernel... The 5.4 kernel was creating `/dev/dxg` even if no actual GPU devices enumerated over vPCI.
> 
> Could you update your kernel (`wsl --shutdown` and `wsl --update`).
> 
> On Windows, could you launch dxdiag.exe, click "Save All Information" and attach the resulting txt file to this thread.

I have updated kernel to 5.10 but nothing has changed.
[DxDiag.txt](https://github.com/microsoft/wslg/files/6401386/DxDiag.txt)

**Comment by archee8** [comment]
> Your GeForce GTX 1650 is currently running on a WDDM2.7 driver (466.27).
> 
> Could you update to 470.14. You need to download from this link specifically:
> 
> https://developer.nvidia.com/cuda/wsl/download

I updated the driver and it worked! Thank you!

**Comment by spronovo** [comment]
You're welcome, once this hit retails the driver situation will get easier :-).

Have fun!

**Comment by spronovo** [comment]
@willparsons did you get yours working as well?

**Comment by willparsons** [comment]
@spronovo Sorry I never get a chance to and I'm on a different machine now

**Comment by FarisR99** [comment]
Is there a perfect solution to this?

I'm running both an iGPU and a discrete graphics card. `glxinfo` keeps reporting my iGPU, and I've tried setting the Graphics settings of wsl to "High performance mode" but that doesn't work (maybe I'm selecting the wrong executable).

When I disable my iGPU, WSL immediately picks up my NVIDIA 3090 and works as expected, but I need my iGPU enabled.

**Comment by spronovo** [comment]
@FarisR99, please see the following article on how to select which GPU WSLg will use

https://github.com/microsoft/wslg/wiki/GPU-selection-in-WSLg

**Comment by SJ2050cn** [comment]
> @FarisR99, please see the following article on how to select which GPU WSLg will use
> 
> https://github.com/microsoft/wslg/wiki/GPU-selection-in-WSLg

Nice solution! Now I can change to the GPU driver which I want to use.

**Comment by hellototoro** [comment]
The situation has changed now. On Ubuntu 20.04, using apt update && apt upgrade can directly update Mesa to version 21.2.6. Conversely, if you use the PPA, the d3d12 driver will not be available.

**Comment by onomatopellan** [comment]
> The situation has changed now. On Ubuntu 20.04, using apt update && apt upgrade can directly update Mesa to version 21.2.6. Conversely, if you use the PPA, the d3d12 driver will not be available.

It should work with the kisak PPA. Just make sure you `export GALLIUM_DRIVER=d3d12` before.
