### ISSUE TITLE
Cannot start GUI apps (e.g. xeyes) after official setup instructions

### ISSUE THREAD

**Issue by neurorepro** [microsoft/wslg#867]
### Windows build number:

22000.0

### Your Distribution version:

20.04

### Your WSL versions:

```
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```

### Steps to reproduce:

1. Update current WSL version as per [official instructions](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#existing-wsl-install).
2. Update Nvidia drivers (NVIDIA GeForce RTX 3080 Laptop GPU, veresion 522.25)
3. Install gedit (`sudo apt install gedit`)
4. Run gedit (`gedit`) and see nothing happening
5. Run xeyes (`xeyes`) and see nothing happening

However i could narrow down the bug.

I noticed this is more likely due to the fact the value of the `DISPLAY` variable is not `:0` but `W.X.Y.Z:0` where `W.X.Y.Z` is the IP as specified by `nameserver` in `/etc/resolv.conf`

I could have both `gedit` and `xeyes`  work by setting the `DISPLAY` variable in the spawn shell:
```console
DISPLAY=:0 gedit
```

```console
DISPLAY=:0 xeyes
```

**IMPORTANT**: on the same laptop, a fresh install of Ubuntu 22.04 from the Microsoft Store (not Ubuntu 20.04 which is the version to which the current issue applies to), **both `gedit` and `xeyes` are working fine**. In that case, the value of `DISPLAY` is already `:0` at OS startup.

**The main question to solve this issue** is then likely to be: **how to set the DISPLAY variable back to :0 at startup**, instead of W.X.Y.Z (where W.X.Y.Z is the value of nameserver in /etc/resolv.conf)

### WSL logs:

Before running `gedit` and `xeyes` with `DISPLAY` manually set to `:0`

[pulseaudio.log](https://github.com/microsoft/wslg/files/9809753/pulseaudio.log)
[stderr.log](https://github.com/microsoft/wslg/files/9809754/stderr.log)
[weston.log](https://github.com/microsoft/wslg/files/9809755/weston.log)
[WslLogs-2022-10-18_13-15-04.zip](https://github.com/microsoft/wslg/files/9809756/WslLogs-2022-10-18_13-15-04.zip)

After running `gedit` and `xeyes` with `DISPLAY` manually set to `:0`
[pulseaudio.log](https://github.com/microsoft/wslg/files/9809985/pulseaudio.log)
[stderr.log](https://github.com/microsoft/wslg/files/9809986/stderr.log)
[weston.log](https://github.com/microsoft/wslg/files/9809987/weston.log)

### Expected behavior:

To work as in the Ubuntu 22.04 WSL release tested on the same laptop

### Actual behavior:

Terminal hangs when running `gedit` or `xeyes`.

**Comment by crramirez** [comment]
Check this: https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#display-environment-variable

**Comment by crramirez** [comment]
"The main question to solve this issue is then likely to be: how to set the DISPLAY variable back to :0 at startup, instead of W.X.Y.Z (where W.X.Y.Z is the value of nameserver in /etc/resolv.conf)" check your `~/.bashrc` or a file in `/etc/profile.d` that is setting the variable
