### ISSUE TITLE
Unable to open up x11 apps shows error cant open display ::0

### ISSUE THREAD

**Issue by leocoolmitra** [microsoft/wslg#868]
### Windows build number:

10.0.22621.674

### Your Distribution version:

11

### Your WSL versions:

![wsl version](https://user-images.githubusercontent.com/47373248/196498562-f077a974-93b1-4f54-9c6d-74b5aa644dbb.jpg)

### Steps to reproduce:

Trying to open X11 app gives error
![image](https://user-images.githubusercontent.com/47373248/196498860-5a09bbce-ef99-4c3b-846a-13d879ab24e6.png)
If we set the display variable .zshrc explicitly to vsock then it overrides WSLG and it works fine but if we comment it out the issue hapens.
![image](https://user-images.githubusercontent.com/47373248/196499361-811fd546-7d12-410c-84d1-4a8ded7627a6.png)
It all happened after a couple of windows 11 update.
![image](https://user-images.githubusercontent.com/47373248/196499535-a50eb311-f60b-4fbd-97d3-b1c7e63de088.png)
If we do ls -la /tmp/.X11-Unix it shows the below screen.
![image](https://user-images.githubusercontent.com/47373248/196499830-eb1a6c7b-89d3-40de-844f-16d9ee4c5c25.png)
even after recreating the link manuall it still shows the above error.
checked the value of display variable
![image](https://user-images.githubusercontent.com/47373248/196500029-3343b870-a172-4f5f-99ee-a3d2796babb4.png)
still get the same error.
![image](https://user-images.githubusercontent.com/47373248/196500123-28aaa746-8562-43df-a238-4c06c7107f65.png)

Gedit works fine and all wayland applications work fine

### WSL logs:

[pulseaudio.log](https://github.com/microsoft/wslg/files/9813627/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/9813630/weston.log)
[stderr.log](https://github.com/microsoft/wslg/files/9813631/stderr.log)

### Expected behavior:

x11 apps should open

### Actual behavior:

it fails with cant open display : : 0
![image](https://user-images.githubusercontent.com/47373248/196500697-a266b5b7-675d-4322-85e3-895875f6935a.png)

**Comment by hushanjushi** [comment]
But how to solved it? I met the same situation...
