### ISSUE TITLE
cannot open display: :0 with "Illegal instruction at address 0x7f26b2a00c5c" at Intel GPU driver

### ISSUE THREAD

**Issue by twoplan** [microsoft/wslg#877]
### Windows build number:

10.0.22621.675

### Your Distribution version:

Ubuntu-22.04

### Your WSL versions:

WSL-Version: 0.70.4.0
Kernelversion: 5.15.68.1
WSLg-Version: 1.0.45
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.22621.675

### Steps to reproduce:

- system: Acer Swift 1 laptop with Intel Pentium Silver N6000 cpu
**Note: the N6000 doesn't support avx or bmi2 instructions**
- no X11 app is starting
- from the end of  /mnt/wslg/stderr.log:

```
(EE) 39: /usr/bin/Xwayland (_start+0x25) [0x556f52a74265]
(EE)
(EE) Illegal instruction at address 0x7f26b2a00c5c
(EE)
Fatal server error:
(EE) Caught signal 4 (Illegal instruction). Server aborting
(EE)
[11:51:56:429] [10:10] [ERROR][com.freerdp.core.gcc] - Unknown GCC client data block: 0xC00C
```

### WSL logs:

[weston.log](https://github.com/microsoft/wslg/files/9859674/weston.log)
[stderr.log](https://github.com/microsoft/wslg/files/9859676/stderr.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/9859679/pulseaudio.log)

### Expected behavior:

X11 apps should start

### Actual behavior:

Message ".. cannot open display: :0" in terminal
and **Illegal instruction** logged to /mnt/wslg/stderr.log:

```
(EE) Illegal instruction at address 0x7f26b2a00c5c
(EE)
Fatal server error:
(EE) Caught signal 4 (Illegal instruction). Server aborting
```

**Comment by hideyukn88** [comment]
@twoplan, thanks for reporting the issue. Most likely you are hitting the issue same as https://github.com/microsoft/wslg/issues/853#issuecomment-1284904454. To confirm, would you please share the core dump file from /mnt/wslg/dumps? Also would you please let us know what is your CPU model, thanks!

**Comment by twoplan** [comment]
As mentioned in **Steps to reproduce** the cpu is Intel Pentium Silver N6000. 

Btw: the issue happens with Intel graphics driver **30.0.101.1994** as well as with latest **31.0.101.3729/31.0.101.2114** from 10/20/2022
[core.zip](https://github.com/microsoft/wslg/files/9860124/core.zip)

**Comment by hideyukn88** [comment]
@twoplan, thanks for sharing the dump, it is exhibiting the same issue as https://github.com/microsoft/wslg/issues/853#issuecomment-1284755913, thanks!

**Comment by twoplan** [comment]
@hideyukn88, thanks for looking into!

To the "Illegal instruction" issue should be noted, that the N6000 cpu supports only **popcnt** and no new **avx** or **bmi2** instructions. Maybe Intel forgot about this, while compiling the drivers?

**Comment by twoplan** [comment]
Reported the issue to the [Intel forum](https://community.intel.com/t5/Graphics/Illegal-instruction-with-Intel-GPU-driver/m-p/1424831#M110682) too. Let's hope for the best.

**Comment by gmsh** [comment]
Thanks @twoplan . I'm experiencing the same issue. I also commented on your thread on the Intel forum. My CPU is N6005 whose instruction set is the same as your model, except the device is manufactured by Intel. Hopefully, they could fix the driver.

**Comment by twoplan** [comment]
Thanks @gmsh for commenting at the Intel forum, shows them the issue is more common to the N600x.

@Microsoft: is there any conversation between developers at Microsoft and Intel about this issue?

**Comment by KDBalashevich** [comment]
I am not sure if it is helpful, but I have the same issue with Pentium G4620.

**Comment by twoplan** [comment]
The old Intel GPU driver **27.20.100.9466** works for X11 apps with WSLg on my laptop.

Unfortunately this driver has a black screen issue after returing from powersave (after opening the laptop lid) .

But maybe usefull for people with desktop systems?!

**Comment by twoplan** [comment]
@gmsh: could you please comment about your **Intel NUC** on the [Intel thread](https://community.intel.com/t5/Graphics/Illegal-instruction-with-Intel-GPU-driver/m-p/1424831) again.

Intel support tries to shift the issue to the manufactor (Acer in my case). Lab tested on **Core-i** cpu and didn't get, that the problem is related to **N600x**.

**Comment by gmsh** [comment]
> @gmsh: could you please comment about your **Intel NUC** on the [Intel thread](https://community.intel.com/t5/Graphics/Illegal-instruction-with-Intel-GPU-driver/m-p/1424831) again.
> 
> Intel support tries to shift the issue to the manufactor (Acer in my case). Lab tested on **Core-i** cpu and didn't get, that the problem is related to **N600x**.

Thanks for letting me know, @twoplan  . Sure. Have added my comments there.

**Comment by tianlongJ** [comment]
@hideyukn88 I have the same problem.The X11-uninx file is empty.ls /tmp/.X11-unix has no output

**Comment by twoplan** [comment]
Looks like [Intel will not investigate](community.intel.com/t5/Graphics/Illegal-instruction-with-Intel-GPU-driver/m-p/1432636#M111345). They set the N600x iGPU (released in 2021!) to legacy support. Whatever caused the issue will not get fixed, only critical security bugs.

I posted a summary of the situation on Intels community at Reddit: [https://www.reddit.com/r/intel/comments/z5cjsl/intel_does_not_fix_grafic_driver_issues_for/](https://www.reddit.com/r/intel/comments/z5cjsl/intel_does_not_fix_grafic_driver_issues_for/)

**You are very welcome to comment there.** 

If we can't get **help from Microsoft**, who is able to escalate our problem inside Intel, then we are done IMO.

**Comment by tyeth** [comment]
Just come upon this, now see there is hope as of yesterday: 
https://community.intel.com/t5/Graphics/Illegal-instruction-with-Intel-GPU-driver/m-p/1439002/highlight/true#M112026
<img width="554" alt="image" src="https://user-images.githubusercontent.com/6692083/208113018-46cc247c-0e6c-4c34-8dcc-5e8c62ba12ba.png">

**Comment by twoplan** [comment]
Noticed this too .. almost didn't expect it anymore. 
Good news, just right for Christmas time.

**Comment by cwt** [comment]
Latest driver update fix this!

**Comment by twoplan** [comment]
I can also confirm that graphics [driver 31.0.101.2121](https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html) fixes the issue #877 on my Acer Swift 1 SF114 laptop.

Happy Easter!

**Comment by davclark** [comment]
FWIW, still not working on my N6000 in the HP Stream 11 tablet. I see ` xserver crashing too fast: 134` in the weston.log. I gave up on WSL so long ago that I don't remember how to get the dumps file out to share it.

**Comment by davclark** [comment]
Another update for others who may get bit by the same issue. Like the previous driver that DID work with wslg, driver 31.0.1.1.2121 not only doesn't enable wslg, but it also breaks sleep - you need to hard power-off the HP Stream 11 if you leave it sleeping for too long by long-pressing the power button. Given the lag on this machine responding to the power button, it's pretty annoying. I'd recommend against using the above driver and generally be on the lookout for the display server crashing while sleeping.
