### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by Mr-Odd** [microsoft/wslg#897]
### Windows build number:

10.0.22621.0

### Your Distribution version:

22.04

### Your WSL versions:

WSL 版本： 1.0.0.0
内核版本： 5.15.74.2
WSLg 版本： 1.0.47
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.819

### Steps to reproduce:

when I was using matplotlib in anaconda environment, an error has occurred:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.
[1]    972 IOT instruction  /home/odd/miniconda3/envs/pm/bin/python

### Expected behavior:

display a GUI window showing the graph

### Actual behavior:

report an error:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

[1]    972 IOT instruction  /home/odd/miniconda3/envs/pm/bin/python

**Comment by fMagVen** [comment]
> export QT_DEBUG_PLUGINS=1 Then follow the debug info, install all the required libs, the window sucessfully shows the graph

does this generate a text file? where can i find it?

**Comment by odd256** [comment]
In my case, add `export QT_DEBUG_PLUGINS=1` to your environment variables, run the program, and install the required tools based on the debug information to fix this issue

**Comment by odd256** [comment]
> > export QT_DEBUG_PLUGINS=1 Then follow the debug info, install all the required libs, the window sucessfully shows the graph
> 
> does this generate a text file? where can i find it?

In my case, add `export QT_DEBUG_PLUGINS=1` to your environment variables, run the program, and install the required tools based on the debug information to fix this issue
