### ISSUE TITLE
Applications run but don't create window

### ISSUE THREAD

**Issue by Thepenguin9** [microsoft/wslg#90]
# Environment

```none
Windows build number:  Win32NT             10.0.21364.0 Microsoft Windows NT 10.0.21364.0
Your Distribution version: Release:        20.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

1. Launch a wsl instance in Windows Terminal
2. Launch a graphical application (gedit in this example)

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* [pulseaudio.log](https://github.com/microsoft/wslg/files/6370407/pulseaudio.log)
* [weston.log](https://github.com/microsoft/wslg/files/6370408/weston.log)
* [versions.txt](https://github.com/microsoft/wslg/files/6370409/versions.txt)

#  Expected behavior

gedit will open and present a blank file with all UI elements

# Actual behavior

The application runs, does not create a window, and prints these errors
```
pengu@ARCTICA:~$ gedit

(gedit:22): Gdk-CRITICAL **: 19:34:15.273: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.364: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.364: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.539: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.540: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.541: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.616: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_seat_get_pointer: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_device_get_window_at_position_double: assertion 'GDK_IS_DEVICE (device)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed

(gedit:22): Gdk-CRITICAL **: 19:34:15.681: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed
```

**Comment by Thepenguin9** [comment]
https://aka.ms/AAc1v26

**Comment by hideyukn88** [comment]
@Thepenguin9 , would you please provide output of dmesg ? 

It looks WSLg failed to start RDP client software (mstsc.exe) in Windows side, the provided weston.log does not show the connection to Windows.

[19:34:15.666] CreateWndow(): rdp_peer is not initalized

And virtiofs is also not properly configured in your system, this could be separate issue, but can be same root case.

[19:34:09.983] WSL2_SHARED_MEMORY_MOUNT_POINT is not set.

**Comment by Thepenguin9** [comment]
> @Thepenguin9 , would you please provide output of dmesg ?
Interestingly that [dmesgoutput.txt](https://github.com/microsoft/wslg/files/6370458/dmesgoutput.txt) of the puzzle. I've been having mount errors for an unrelated experiment on a hard drive, so I didn't think to check it now.

**Comment by Thepenguin9** [comment]
I followed the guide in the root readme; updating wsl via powershell; restarting the instance; restarting my computer for good measure.

I can't recall any other actions I could've taken to affect WSLg

**Comment by Thepenguin9** [comment]
> It looks WSLg failed to start RDP client software (mstsc.exe) in Windows side, the provided weston.log does not show the connection to Windows.

mstsc.exe works fine launching from start, not sure what I can do there

> And virtiofs is also not properly configured in your system, this could be separate issue, but can be same root case.

And this I have to admit I have no knowledge of, nor encountered this when setting up wsl

**Comment by onomatopellan** [comment]
It seems you are not runnnig WSL2. What's the output of `wsl.exe -l -v` ?

**Comment by Thepenguin9** [comment]
> Are you running a custom kernel? Make sure you are running latest kernel from Windows Update with `wsl.exe --update` and comment out the kernel entry in [.wslconfig](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig).

I was running a self-build of Microsoft's own kernel. No edits, just locally compiled. 
Commenting out the self-built kernel and restarting wsl has fixed the issue I had.

I will try and rebuild the kernel and see if it still works, though for now this issue can be considered solved!

**Comment by c4artisan** [comment]
this seems to be happening to me as well (no i don't have a custom kernel nor any self-built thingy like thepenguin9 so yeah help please)

**Comment by hideyukn88** [comment]
@c4artisan, would you please share /mnt/wslg/weston.log? thanks!

**Comment by c4artisan** [comment]
[weston.log](https://github.com/microsoft/wslg/files/10144762/weston.log)

**Comment by hideyukn88** [comment]
@c4artisan, it looks msrdc.exe on Windows side is not connecting to Linux side, I wonder you might be hitting the issue reported at  https://github.com/microsoft/wslg/issues/841, would you please share output from `reg QUERY "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /S` on Windows's command prompt?

**Comment by c4artisan** [comment]
> reg QUERY "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /S

`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client
    fEnableUsbBlockDeviceBySetupClass    REG_DWORD    0x1
    fEnableUsbNoAckIsochWriteToDevice    REG_DWORD    0x50
    fEnableUsbSelectDeviceByInterface    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client\UsbBlockDeviceBySetupClasses
    1000    REG_SZ    {3376f4ce-ff8d-40a2-a80f-bb4359d1415c}

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client\UsbSelectDeviceByInterfaces
    1000    REG_SZ    {6bdd1fc6-810f-11d0-bec7-08002be2092f}`

**Comment by OfekShilon** [comment]
@hideyukn88  
The same started happening to me today, **immediately after enabling systemd** per the instructions [here](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/). After disabling systemd (just removed wsl.conf) I'm able to see windows again.

I also updated wsl today, so it might be an issue in the latest version.
```
PS> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.1020
```
Here's my own /mnt/wslg/weston.log, seems similar to the one above:
[weston.log](https://github.com/microsoft/wslg/files/10147023/weston.log)

Unfortunately disabling systemd is not an acceptable workaround for me, as I'm running apps that depend on it.

**Comment by c4artisan** [comment]
anything new on my end?

**Comment by c4artisan** [comment]
@hideyukn88

**Comment by OneBlue** [comment]
@OfekShilon: I wonder if you have a sysyemd unit that kills the X11 socket.

Can you share the output of `sudo systemctl -t service`  and `dmesg` ?

**Comment by OfekShilon** [comment]
```
~$ sudo systemctl -t service
  UNIT                                 LOAD   ACTIVE SUB     DESCRIPTION
  accounts-daemon.service              loaded active running Accounts Service
  apport.service                       loaded active exited  LSB: automatic crash report generation
● atd.service                          loaded failed failed  Deferred execution scheduler
  avahi-daemon.service                 loaded active running Avahi mDNS/DNS-SD Stack
  blk-availability.service             loaded active exited  Availability of block devices
  console-getty.service                loaded active running Console Getty
  console-setup.service                loaded active exited  Set console font and keymap
  cron.service                         loaded active running Regular background program processing daemon
  dbus.service                         loaded active running D-Bus System Message Bus
  finalrd.service                      loaded active exited  Create final runtime dir for shutdown pivot root
  gdm.service                          loaded active running GNOME Display Manager
  keyboard-setup.service               loaded active exited  Set the console keyboard layout
  ModemManager.service                 loaded active running Modem Manager
  networkd-dispatcher.service          loaded active running Dispatcher daemon for systemd-networkd
  NetworkManager-wait-online.service   loaded active exited  Network Manager Wait Online
  NetworkManager.service               loaded active running Network Manager
  polkit.service                       loaded active running Authorization Manager
  rsyslog.service                      loaded active running System Logging Service
  rtkit-daemon.service                 loaded active running RealtimeKit Scheduling Policy Service
  setvtrgb.service                     loaded active exited  Set console scheme
  snapd.seeded.service                 loaded active exited  Wait until snapd is fully seeded
  snapd.service                        loaded active running Snap Daemon
● ssh.service                          loaded failed failed  OpenBSD Secure Shell server
  switcheroo-control.service           loaded active running Switcheroo Control Proxy service
  systemd-binfmt.service               loaded active exited  Set Up Additional Binary Formats
  systemd-hostnamed.service            loaded active running Hostname Service
  systemd-journal-flush.service        loaded active exited  Flush Journal to Persistent Storage
  systemd-journald.service             loaded active running Journal Service
  systemd-logind.service               loaded active running Login Service
  systemd-networkd-wait-online.service loaded active exited  Wait for Network to be Configured
  systemd-networkd.service             loaded active running Network Service
● systemd-remount-fs.service           loaded failed failed  Remount Root and Kernel File Systems
  systemd-resolved.service             loaded active running Network Name Resolution
  systemd-sysctl.service               loaded active exited  Apply Kernel Variables
  systemd-sysusers.service             loaded active exited  Create System Users
  systemd-timedated.service            loaded active running Time & Date Service
  systemd-tmpfiles-setup-dev.service   loaded active exited  Create Static Device Nodes in /dev
  systemd-tmpfiles-setup.service       loaded active exited  Create Volatile Files and Directories
  systemd-udev-settle.service          loaded active exited  udev Wait for Complete Device Initialization
  systemd-udev-trigger.service         loaded active exited  udev Coldplug all Devices
  systemd-udevd.service                loaded active running udev Kernel Device Manager
  systemd-update-utmp.service          loaded active exited  Update UTMP about System Boot/Shutdown
  systemd-user-sessions.service        loaded active exited  Permit User Sessions
  udisks2.service                      loaded active running Disk Manager
  ufw.service                          loaded active exited  Uncomplicated firewall
  unattended-upgrades.service          loaded active running Unattended Upgrades Shutdown
  user-runtime-dir@1000.service        loaded active exited  User Runtime Directory /run/user/1000
  user-runtime-dir@122.service         loaded active exited  User Runtime Directory /run/user/122
  user@1000.service                    loaded active running User Manager for UID 1000
  user@122.service                     loaded active running User Manager for UID 122
  wpa_supplicant.service               loaded active running WPA supplicant
```

dmesg output:
[dmesg.txt](https://github.com/microsoft/wslg/files/10183089/dmesg.txt)

Thanks.

**Comment by OneBlue** [comment]
Thank you @OfekShilon.

I don't see anything that jumps out, but let's gather some debugging information to see if we can root cause this. Can you share:


- Which distribution you're using
- The output of `ls -la /tmp/.X11-unix/` 
- The output of `sudo mount`
- The output of `sudo systemctl -u wslg-mount.service` 
- If running `sudo systemctl restart wslg-mount.service` solves the issue 
- If running `systemctl disable gdm.service`, and `wsl.exe --shutdown` solves the issue ? (after restarting the distro)

**Comment by OneBlue** [comment]
Thank you @OfekShilon. 

Sorry about the typo on `wslg-mount.service` (what I meant was `systemctl status wslg-mount.service`), but I can see that `/tmp/.X11-unix/X0` exists on your machine, so this is not the same as [this issue](https://github.com/microsoft/WSL/issues/9126) as I suspected.

Let's keep digging on #917

**Comment by lockieluke** [comment]
i'm using a self-compiled kernel and getting the same error

**Comment by Thepenguin9** [comment]
> i'm using a self-compiled kernel and getting the same error

Firstly it's within the penultimate hour of the year, so Happy New Year!

Secondly, there is likely some secret sauce being applied to the kernel so audio and windows (the actual window of the program) and input etc actually works.

It would be best you spin this off into it's own issue and instead reference this one via it's issue number! I consider this issue fully resolved so it would be the more appropriate place.

**Comment by lockieluke** [comment]
happy new year!
