### ISSUE TITLE
WSL GUI windows can not be pinned to any desktop side

### ISSUE THREAD

**Issue by nE0sIghT** [microsoft/wslg#905]
### Windows build number:

22621.819

### Your Distribution version:

20.04, 22.04

### Your WSL versions:

WSL: 1.0.0.0
Kernel: 5.15.74.2
WSLg: 1.0.47
MSRDC: 1.2.3575
Direct3D: 1.606.4
DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp

### Steps to reproduce:

1. Start any GUI app. In my case this is `gnome-terminal`: `dbus-launch gnome-terminal`
2. Try to pin window to left or right side with mouse or using Win key + left/rigth arrows

### Expected behavior:

WSLg window can be pinned to any Desktop side

### Actual behavior:

WSLg window can not be pinned to any Desktop side.
Also this works fine with normal X server like vcxsrv.

**Comment by NotTheDr01ds** [comment]
Looks like a duplicate of #22.  This was actually even mentioned in the [architecture overview blog post](https://devblogs.microsoft.com/commandline/wslg-architecture/) last year as well:

> [WSLg] still uses server-side window movement and resizing, resulting in ... the inability to snap Linux windows on the edges of the monitors or to custom snap region. These annoy us too 😊.

Also refer to [this Super User answer](https://superuser.com/a/1731539/1210833) where I provided some more color commentary on the topic.

**Comment by nE0sIghT** [comment]
You are right, thanks! Closing then
