### ISSUE TITLE
No sound due to missing Alsa config

### ISSUE THREAD

**Issue by jonaskuske** [microsoft/wslg#906]
### Windows build number:

19045.2311 (same on Windows 11 22H2 though)

### Your Distribution version:

Release:        22.04

### Your WSL versions:

WSL-Version: 1.0.0.0
Kernelversion: 5.15.74.2
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.19045.2311

### Steps to reproduce:

```zsh
sudo apt install epiphany-browser gstreamer1.0-plugins-bad
epiphany
# (visit youtube.com, no sound)
```

↓

```zsh
echo "pcm.default pulse\nctl.default pulse" > ~\.asoundrc
export PULSE_SERVER=unix:$(sed 's/unix://g' <<< "$PULSE_SERVER")

epiphany
# (visit youtube, now there's sound!)
```

### Expected behavior:

There is sound.

### Actual behavior:

No sound.

**Comment by hideyukn88** [comment]
@jonaskuske, thank you very much for reporting the issue, and the solution! As I tried and verified locally at my end, the only change required is to modify PULSE_SERVER env, then audio with epiphany works. It seems ~\.asoundrc is not required, at least, for epiphany, or am I missing something? thanks!
