### ISSUE TITLE
running 'wsl --version' on Windows command prompt doesn't work on windows

### ISSUE THREAD

**Issue by AtP-Wooji** [microsoft/wslg#912]
### Windows build number:

 10.0.22000.0

### Your Distribution version:

22.04

### Your WSL versions:

running 'wsl --version' on Windows command prompt doesn't work on windows

### Steps to reproduce:

running 'wsl --version' on Windows command prompt doesn't work on windows

### Actual behavior:

running 'wsl --version' on Windows command prompt doesn't work on windows

**Comment by Biswa96** [comment]
You need to install WSL from Windows Store. Here is the link https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R?hl=en-us&gl=us
