### ISSUE TITLE
Unexpected RemoteApp warning

### ISSUE THREAD

**Issue by zbalkan** [microsoft/wslg#925]
### Version

10.0.19044.2311

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04

### Other Software

WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2311

### Repro Steps

1. Start WSL2 instance, Ubuntu or Oracle Linux.
2. A RemoteApp like the one below window appears.

![image](https://user-images.githubusercontent.com/39981909/207066591-c6b6b87e-1a47-457e-8369-af1374913f6d.png)

### Expected Behavior

No RemtoeApp window.

### Actual Behavior

Unexpected RemoteApp warning appears.
![image](https://user-images.githubusercontent.com/39981909/207066591-c6b6b87e-1a47-457e-8369-af1374913f6d.png)

**Comment by benhillis** [comment]
@hideyukn88 - can you forward this along to the remote desktop folks please? I'm not sure why these are appearing for some users.

**Comment by hideyukn88** [comment]
@zbalkan, this sounds dup of https://github.com/microsoft/wslg/issues/841, to confirm, would you please share output from `reg QUERY "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /S` on Windows's command prompt? and is your computer managed by your organization? thanks!

**Comment by zbalkan** [comment]
Hi,

Yes, it is managed by the organization and that's the issue. So, WSL runs a Linux distro as a virtual machine, then the console access to console within is exposed as a RemoteApp. That's brilliant! It's been a discovery for me.

I'm closing the ticket as it is a non-issue.
