### ISSUE TITLE
Q: How to access Pulseaudio server configuration

### ISSUE THREAD

**Issue by tiborkiss** [microsoft/wslg#93]
I have a multi-channel audio interface and for audio research I would like to bridge WSL2 with WSLg with the ability to have control to multiple audio inputs and outputs.
The `pacmd` command is not accessible from user space. Is there a way to configure pulse audio server?

I was able to select only one input and one output channel by manually changing the default playback and recording device using the Sound device manager from Control Panel. For a basic thing is OK, but I do really need more flexibility and if possible independent of this default playback and recording device selection.

Someone can point to some documentation, source code, or just write some hints?

**Comment by cerebrate** [comment]
Experimenting earlier, I found that I could access `pacmd` by entering the WSLg system distro with `wsl --system -u wslg`. Might be a workaround you could use?

(Although as far as I understand it, any changes you make this way will be automatically discarded when your distro terminates, so if you need your reconfiguration to stick, that would be an issue.)

**Comment by tiborkiss** [comment]
Thank you, that was what I am looking for. For me it's enough to be able to login in system distro.
