### ISSUE TITLE
Custom Keyboard Layouts

### ISSUE THREAD

**Issue by CarlOlson** [microsoft/wslg#931]
### Windows build number:

22621.963

### Your Distribution version:

20.04.5

### Your WSL versions:

WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.963

### Steps to reproduce:

1. Use a custom keyboard layout (either KLC, kbdedit, or registry tweaks)
2. Unable to use custom layout inside WSLg apps

For reference I use Japanese IME w/ a dvorak layout. Switch between Dvorak and Japanese IME is untenable due to other bugs with East Asian support Windows introduced in the past months.

### Expected behavior:

I expect to be able to type with Dvorak (or any custom layout) inside of WSLg windows, even if using an IME.

We should be allowed to manually set the WSLg keyboard layout. I want to just set my layout to US-Dvorak w/ ctrl+alt remapping and forget about it. Guessing what the user wants makes no sense, for example Korean IME isn't based on romanization and it makes no sense to default to Qwerty. A user (like myself) could easily learn Korean on a Qwerty, but use Dvorak for romanized IME input.

This is particularly important for developers (possibly the main users of WSL?). Not having a comfortable typing experience seriously ruins my nearly $3k Surface and large time investment this past year.

### Actual behavior:

It is defaulting to US QWERTY: 

```
convert_rdp_keyboard_to_xkb_rule_names: matching model=pc105 layout=jp variant=(null) options=(null)
```

**Comment by hideyukn88** [comment]
@CarlOlson, this issue is reported at https://github.com/microsoft/wslg/issues/173, thanks!
