### ISSUE TITLE
WSLg does not use the root setting in wsl.conf

### ISSUE THREAD

**Issue by kurumushi** [microsoft/wslg#950]
### Windows build number:

22621.963

### Your Distribution version:

opensuse Tumbleweed 20230102

### Your WSL versions:

WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.963

### Steps to reproduce:

1. Change the root option under [automount] in /etc/wsl.conf to something other than /mnt
2. wlsg will be mounted at the new location

### WSL logs:

[pulseaudio.log](https://github.com/microsoft/wslg/files/10356994/pulseaudio.log)
[weston.log](https://github.com/microsoft/wslg/files/10356996/weston.log)
[stderr.log](https://github.com/microsoft/wslg/files/10356997/stderr.log)

### Expected behavior:

wslg will update its settings to match the new mount location.

### Actual behavior:

All of the services are looking for files in /mnt/wslg, which does not exist.

**Comment by hideyukn88** [comment]
@kurumushi, thanks for reporting the issue, would you please clarify what services are looking for /mnt/wslg? below shows mount point is changed to /foo/ and xclock can be started, thanks! 

![image](https://user-images.githubusercontent.com/13857962/217380776-f06fbd0e-00b7-4b32-8269-ad6651f27f94.png)

**Comment by kurumushi** [comment]
The logs attached show both weston looking for fonts in /mnt/wslg, and pulseaudio looking for its socket in /mnt/wslg

**Comment by hideyukn88** [comment]
@kurumushi, that should be fine because weston is running inside system distro where its mount space remains /mnt, do you encounter any issues? thanks!

**Comment by kurumushi** [comment]
I don't actually remember what the main issue I was having at the time. I've completely given up on using wslg because of different issues which are not resolved, so I can't really say anymore what the broken app was. Your explanation of it using the system distro probably resolves this issue at least.
