### ISSUE TITLE
How to use WSLg with Windows input-method

### ISSUE THREAD

**Issue by HengyueLi** [microsoft/wslg#955]
Recently I updated my WSL and now I can use Linux app with GUI in **Windows** directly, that is good. But with a small problem. Please assume a case;
 installed a browser inside WSL. Now I run this browser, the GUI window is opened in **Windows**. Now I need to input some Chinese characters. I change the input-method of **Windows**. But I cannot type the characters into the browser. I noticed that I can past and copy characters into browser. So I guess there must be a method let me to use input-method of **Windows** directly. Installing another input-method inside WSL is not a workaround for me.

**Comment by hideyukn88** [comment]
@HengyueLi, currently Windows's IME can not be used with WSLg, which is reported at https://github.com/microsoft/wslg/issues/9, thus you will need to install Linux version of IME and configure it along with ibus, which can be vary by the distro you are using, and the step mentioned at https://github.com/microsoft/wslg/issues/8 might help, thanks!

**Comment by donglixp** [comment]
any update?
