### ISSUE TITLE
high rate of error messages to /var/log/Xorg.pid-####.log

### ISSUE THREAD

**Issue by rye2020** [microsoft/wslg#960]
### Windows build number:

25281

### Your Distribution version:

20.04

### Your WSL versions:

WSL version: 1.1.0.0
Kernel version: 5.15.83.1
WSLg version: 1.0.48
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25281.1000

### Steps to reproduce:

unknown

### WSL logs:

[weston.log](https://github.com/microsoft/wslg/files/10470043/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/10470046/pulseaudio.log)
[stderr.log](https://github.com/microsoft/wslg/files/10470047/stderr.log)
[Xorg.pid-1845.log](https://github.com/microsoft/wslg/files/10470066/Xorg.pid-1845.log)

### Actual behavior:

rapid increase in size of ext4.vhdx; each Xorg.pid file is 18M and they are created quite rapidly; files appear to be empty

**Comment by rye2020** [comment]
CORRECTION -- files filled with the following:
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransSocketCreateListener: failed to bind listener
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransSocketCreateListener: failed to bind listener
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 20 12:12:05 JRM-S4 /usr/lib/gdm3/gdm-x-session[733]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777

**Comment by rye2020** [comment]
syslog is also being filled with the following messages:
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketCreateListener: failed to bind listener
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketCreateListener: failed to bind listener
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketCreateListener: failed to bind listener
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketCreateListener: failed to bind listener
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
Jan 21 10:03:33 OPX3050 /usr/lib/gdm3/gdm-x-session[3389]: _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777

**Comment by hideyukn88** [comment]
@rye2020, thanks for reporting the issue, I believe you should be able to stop logging those loggings by disabling gdm.service unit in systemd, please try it, thanks!

**Comment by sg3-141-592** [comment]
I'm seeing this same issue where there is a build up for these logs files, some months old

![Image](https://github.com/user-attachments/assets/89fd0131-686e-4402-97f1-922a95ec7fb5)
