### ISSUE TITLE
Having issues rendering images with WSL. Just get blank GUI windows.

### ISSUE THREAD

**Issue by daniel-a-diaz** [microsoft/wslg#963]
### Version

Microsoft Windows 11 [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Ubuntu 22.04

### Other Software

Visual Studio Code 1.74.3 with Remote Development Extension 0.23.0 (WSL 0.72.0)

### Repro Steps

I had to do a clean install of Ubuntu on WSL2 and have since had issues getting graphics to render with libraries I use, specifically vedo (https://github.com/marcomusy/vedo). I use Miniconda to install everything. It has worked fine in the past on the same computer (HP Spectre x360 Convertible 14t-ea100 with Intel Iris Xe graphics). My new Ubuntu didn't have libGL.so.1 installed so I did `sudo apt-get install libgl1-mesa-glx libgl1-mesa-dri`. I have the same issue with PyVista (https://github.com/pyvista/pyvista) not rendering, but Matplotlib works fine, so I'm guessing it has something to do with VTK. I have tried completely uninstalling WSL and starting from scratch, as well as tried with Ubuntu 20.04.5 LTS. While I didn't have libGL.so.1 issues with 20.04.5, I still had the rendering issues. I also tried turning Windows Hypervisor Platform on.

### Expected Behavior

From https://vedo.embl.es/autodocs/content/vedo/index.html
![image](https://user-images.githubusercontent.com/107445915/213601222-d1e0dd5c-5b47-4705-bf3a-a8e3149cd153.png)

From https://docs.pyvista.org/api/examples/_autosummary/pyvista.examples.downloads.download_bolt_nut.html
![image](https://user-images.githubusercontent.com/107445915/213602120-e60989fe-3fdb-4c20-a699-5322b4e64f65.png)

### Actual Behavior

I just get a blank GUI window like this for the vedo example
![image](https://user-images.githubusercontent.com/107445915/213601398-5394010a-c34d-4eeb-ae11-bf7c5c15c6ce.png)

And for the PyVista example I get this
![image](https://user-images.githubusercontent.com/107445915/213602281-e1f807e7-4581-4db5-8074-ebaa5250e362.png)
Followed by this directly after I exit out of the previous window.
![image](https://user-images.githubusercontent.com/107445915/213603153-e5d19def-2836-44e7-91f8-80e5a63db47d.png)

**Comment by hideyukn88** [comment]
@daniel-a-diaz., @afilp, have you tried disabling display driver and force software rendering? I just would like to if this is display driver issue. If it does solve, please let us know what version of driver you are using, thanks!

**Comment by daniel-a-diaz** [comment]
Just circling back to this, sorry. It ended up being a display driver issue. Intel had a new driver update that fixed the issue for me. Thanks for all the help.

**Comment by afilp** [comment]
@hideyukn88 @daniel-a-diaz I have a DELL ALIENWARE, that has 2 display drivers, not sure which one should I display and how to use a "software rendering"? Can you please advice, if possible?

![image](https://user-images.githubusercontent.com/7850073/220854918-d26b99ae-7feb-4b52-897c-e6ce648299ab.png)

**Comment by aki-k** [comment]
If Windows decides to install the older Intel graphics driver, try to use these steps to stop it downgrading the driver:

https://github.com/microsoft/wslg/issues/967#issuecomment-1460093451

**Comment by CESI2Jaafar** [comment]
Hi guys, I have same issue . How did you solved? Please let me. Thank you so much for your support in advance!

**Comment by aki-k** [comment]
@CESI2Jaafar I actually found the proper solution for the automatic driver installation problem in Windows 11 two days ago.

Open gpedit.msc and go to

Computer Configuration 
Administrative Templates 
Windows Components 
Windows Update 
Manage updates offered from Windows Update 
Do not include drivers with Windows Updates

**Comment by CESI2Jaafar** [comment]
@aki-k
Thank you so much. I am trying lets see
