### ISSUE TITLE
doesn't work on win10

### ISSUE THREAD

**Issue by lingsamuel** [microsoft/wslg#988]
### Windows build number:

10.0.19045.0

KB5020030 installed.

### Your Distribution version:

22.04

### Your WSL versions:

I used the latest version (wsl 1.0.3 with wslg 1.0.47), but it failed. So I tried the pre-release version.

```
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2604
```

### Steps to reproduce:

```bash
> wsl --update --pre-release
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
> wsl --version
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2604
> wsl --install
```

Inside the Ubuntu:

```bash
> sudo apt-get update
> sudo apt update
> gedit

(gedit:3414): Gtk-WARNING **: 18:09:25.416: cannot open display:
> echo $DISPLAY

> export DISPLAY=:0
> gedit

(gedit:3419): Gtk-WARNING **: 18:13:13.791: cannot open display: :0
> ls -la /tmp/.X11-unix
ls: cannot access '/tmp/.X11-unix': No such file or directory
> ls /mnt/wslg
ls: cannot access '/mnt/wslg': No such file or directory
```

I noticed that the kernel version doesn't match the release log:
```bash
> uname -r
5.10.74.3-microsoft-standard-WSL2+
```

I have two distro, Arch (with systemd) and Ubuntu (newly installed). In Arch, all commands above have same output.

### Expected behavior:

WSLg should work. Kernel version should be updated.

### Actual behavior:

WSLg doesn't work.

**Comment by scbfvyqx36** [comment]
I met the same problems bro, did you find some solutions？

**Comment by lingsamuel** [comment]
> I met the same problems bro, did you find some solutions？

Yes 😅 It's because I have set `guiApplications=false` in `.wslconfig` due to an issue before: https://github.com/microsoft/wslg/issues/33
