### ISSUE TITLE
Stick a wsl window on top of others

### ISSUE THREAD

**Issue by castorfou** [microsoft/wslg#994]
### Is your feature request related to a problem:

It is not really a problem.
Is just that I use a lot this option in linux.

And would love to have it in WSL as well.

### Describe the solution you'd like:

Just an toggle option to keep a given window on top of other windows (always visible even when it doesn't have the focus)

### Describe alternatives you've considered:

I don't know what could be alternative solutions

### Additional context:

![image](https://user-images.githubusercontent.com/2387408/222478049-9b082241-d1a4-401e-996c-13277b55370c.png)

**Comment by jackmawer** [comment]
[Microsoft Powertoys](https://learn.microsoft.com/en-us/windows/powertoys/) has a feature to keep a window always on top of others, perhaps this could work as a solution for you?

**Comment by castorfou** [comment]
yes this is a perfect solution, thank you.
